.github/CODEOWNERS
See item 1 in #12 
This reproduces what's in the prow `OWNERS` files
=> Initial CODEOWNERS file

.github/workflows/sync-readme.yaml
See https://github.com/prometheus-community/helm-charts/pull/39#issuecomment-687616250
Closes #39
=> Auto-sync README from main to gh-pages

charts/prometheus/Chart.yaml, charts/prometheus/templates/deployments/alertmanager.yaml, charts/prometheus/templates/deployments/pushgateway.yaml, charts/prometheus/templates/deployments/server.yaml, charts/prometheus/templates/statefulsets/alertmanager.yaml, charts/prometheus/templates/statefulsets/server.yaml, charts/prometheus/values.yaml
This PR unify labels and annotations across all deploymets and statefulsets in stable/prometheus Helm chart
=> [prometheus] Unify labels and annotations

charts/prometheus-redis-exporter/Chart.yaml
Signed-off-by: zanhsieh <zanhsieh@gmail.com>
I would like to volunteer as co-maintainer of prometheus-redis-exporter as:
https://github.com/prometheus-community/helm-charts/issues/21
I currently am one of the maintainer of prometheus chart:
https://github.com/prometheus-community/helm-charts/blob/ed52a9d095291eb825010e0af89fb9bc365f054f/charts/prometheus/Chart.yaml#L17
=> [prometheus-redis-exporter] Add zanhsieh as maintainer

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
- It adds semantic line breaks to our issue templates.
- I removed the question "Is this a new chart" - I think it will not apply to 95% of PRs anyhow and CODEOWNERS enforce that one of the repository admins review it. So it will be hard to miss.
- Added instruction how to get helm and kubernetes versions
- Added example for how to reproduce an issue. Not sure if people will follow it, but it would definitely help.
=> formatted GitHub templates and made minor adjustments

.github/CODEOWNERS, charts/prometheus-blackbox-exporter/Chart.yaml
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>
no
* added monotek to maintainers
* also adds rsotnychenko to ownes file as he is also maintainer in the chart.yaml
- fixes #
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
=> [blackbox-exporter] added monotek to maintainers

.github/CODEOWNERS, charts/prometheus/Chart.yaml
👋 
I've made a few contributions overtime and we have been using this chart extensively in production at Transit for over 2 years.
I'd like to look into eventually simplifying/cleaning up the chart and modularizing it by using node-exporter, pushgateway and potentially alertmanager subcharts.
=> [prometheus] Add naseemkullah as maintainer

.github/CODEOWNERS, charts/prometheus-postgres-exporter/Chart.yaml
Signed-off-by: zanhsieh <zanhsieh@gmail.com>
As per https://github.com/prometheus-community/helm-charts/pull/47
=> [prometheus-postgres-exporter] Add zanhsieh as maintainer

artifacthub-repo.yaml
In Artifact Hub, a new filter for Verified publishers has been added to the packages search page. This adds the flag.
See:
- https://github.com/artifacthub/hub/issues/550
- https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml
~- [ ] Chart Version bumped~
=> [gh-pages] Add Artifact Hub repo metadata file to verify repo

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/templates/deployment.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
Signed-off-by: Ernesto Cruz <ernesto.cruz@alayacare.com>
=> [prometheus-cloudwatch-exporter] Add priorityClassName to cloudwatch-exporter

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/values.yaml
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
Upgrades to the latest prometheus-redis-exporter - 1.11.1
See - https://github.com/oliver006/redis_exporter/releases
See - https://hub.docker.com/r/oliver006/redis_exporter/tags
https://github.com/oliver006/redis_exporter/pulls?q=is%3Apr+is%3Aclosed
- [X ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X ] Chart Version bumped
- [X ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
=> [prometheus-redis-exporter] Upgrade exporter image to version 1.11.1

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml
Remove colons from the `ClusterRoleBinding` resource name to make the `helm lint` command pass for Helm 3.3+
Fixes #88
=> [prometheus-adapter] Remove colons from the ClusterRoleBinding resource name

charts/kube-prometheus-stack/Chart.yaml
Adds newly supported Artifact Hub annotations for named links and operator search facet.
See: https://github.com/artifacthub/hub/issues/634
I also removed `https://github.com/prometheus-operator/prometheus-operator` as a source, since this is only one component of https://github.com/prometheus-operator/kube-prometheus and explained well there.
**Chart maintainers:** The link annotation could also be added to any of the other charts – in separate PRs – in order to enrich display in Artifact Hub. If anyone wants to take that on for the other charts 😉
=> [kube-prometheus-stack] Add Artifact Hub annotations for named links and operator search facet

.github/CODEOWNERS, PROCESSES.md
=> document repository settings

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
=> [prometheus ]update prometheus image to 2.21.0

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/statefulset.yaml, charts/alertmanager/values.yaml
* fixes persistence
* enables persistence by default (empty dir could fill node)
* set default storage to 50MB
- fixes # https://github.com/prometheus-community/helm-charts/issues/172
=> [alertmanager ]fix persistence

charts/prometheus-consul-exporter/Chart.yaml, charts/prometheus-consul-exporter/templates/deployment.yaml, charts/prometheus-consul-exporter/values.yaml
Allows users to mount sidecar containers and volumes. This allows, for example, mounting a volume for Consul CA certificate.
=> [prometheus-consul-exporter] Support extra containers, environment variables and volumes

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml
- fixes #154 
Signed-off-by: Jai Govindani <jai@honestbank.com>
=> [kube-prometheus-stack] style(grafana): fix typo

charts/prometheus/Chart.yaml, charts/prometheus/templates/alertmanager/sts.yaml, charts/prometheus/values.yaml
Signed-off-by: Ryan Probus <ryan.probus@appian.com>
* fixes alertmanager meshpeering
* N/A
=> [prometheus] fix alertmanager meshpeer

.github/CODEOWNERS, charts/prometheus-druid-exporter/.helmignore, charts/prometheus-druid-exporter/Chart.yaml, charts/prometheus-druid-exporter/README.md, charts/prometheus-druid-exporter/templates/_helpers.tpl, charts/prometheus-druid-exporter/templates/deployment.yaml, charts/prometheus-druid-exporter/templates/service.yaml, charts/prometheus-druid-exporter/templates/serviceaccount.yaml, charts/prometheus-druid-exporter/templates/servicemonitor.yaml, charts/prometheus-druid-exporter/templates/tests/connection-test.yaml, charts/prometheus-druid-exporter/values.yaml
Signed-off-by: iamabhishek-dubey <abhishekbhardwaj510@gmail.com>
Adding a new chart `prometheus-druid-exporter` to `prometheus-community`
NA
NA
=> [prometheus-druid-exporter] Added druid exporter

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/values.yaml
Bump blackbox exporter to [v0.18.0](https://github.com/prometheus/blackbox_exporter/releases/tag/v0.18.0).
Nope
Nope
=> [prometheus-blackbox-exporter] Bump blackbox exporter to v0.18.0.

.github/CODEOWNERS, charts/prometheus-kafka-exporter/Chart.yaml, charts/prometheus-kafka-exporter/README.md, charts/prometheus-kafka-exporter/templates/NOTES.txt, charts/prometheus-kafka-exporter/templates/_helpers.tpl, charts/prometheus-kafka-exporter/templates/deployment.yaml, charts/prometheus-kafka-exporter/templates/podsecuritypolicy.yaml, charts/prometheus-kafka-exporter/templates/role.yaml, charts/prometheus-kafka-exporter/templates/rolebinding.yaml, charts/prometheus-kafka-exporter/templates/service.yaml, charts/prometheus-kafka-exporter/templates/serviceaccount.yaml, charts/prometheus-kafka-exporter/templates/servicemonitor.yaml, charts/prometheus-kafka-exporter/templates/tests/ci-kafka-zoo-pod.yaml, charts/prometheus-kafka-exporter/templates/tests/ci-zoo-kafka-svc.yaml, charts/prometheus-kafka-exporter/values.yaml
A new chart donation to prometheus-community
@prometheus-community/helm-charts-admins Please invite @golgoth31 to `prometheus-community/helm-charts-maintainers`
/cc @scottrigby I have created a fresh PR incorporating all the changes requested in the review.
=> [prometheus-kafka-exporter] new chart donation

charts/prometheus-druid-exporter/Chart.yaml, charts/prometheus-druid-exporter/README.md, charts/prometheus-druid-exporter/templates/deployment.yaml
Signed-off-by: awatercolorpen <hellis@foxmail.com>
if not enable serviceMonitor, it will enable pod annotations by default.
=> [prometheus-druid-exporter] if not enable serviceMonitor, it should auto enable pod annotations.

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
Signed-off-by: chienfuchen32 <chienfuchen32@gmail.com>
- Fixing comment for prometheus base url
=> [prometheus] comment for prometheus base url fixing

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/requirements.yaml
Bump upstream Grafana to include fix for broken PSP (https://github.com/grafana/helm-charts/issues/59)
=> [kube-prometheus-stack] Bump grafana to include PSP fix

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/requirements.yaml
Updating repository for kube-state-metrics to use new stable repository URL
- fixes #
=> [kube-prometheus-stack] Fix requirements.yaml

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/values.yaml
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
Upgrades to the latest pushgateway - 1.3.0
See - https://github.com/prometheus/pushgateway/releases
See - https://hub.docker.com/r/prom/pushgateway/tags
bumped the minor version of the chart to match the minor version bump in the application
- [X ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X ] Chart Version bumped
- [X ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
=> [prometheus-pushgateway] Upgrade pushgateway image to version 1.3.0

charts/prometheus-couchdb-exporter/Chart.yaml, charts/prometheus-couchdb-exporter/values.yaml
=> charts/prometheus-couchdb-exporter: fix typos

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
This field is no longer required since the file that used it (`templates/prometheus-operator/cleanup-crds.yaml`) has since been deleted.
Original Commit: https://github.com/prometheus-community/helm-charts/commit/89b13385c753bbf21d9d77b1a95814e6e8bc1311#diff-fc1a56fd7f1f12a544f40c63eea5899e19606cea9f3b5d3d3c976ab65b635a73
- fixes #
=> [kube-prometheus-stack] Drop kubectl image field

charts/prometheus-pingdom-exporter/Chart.yaml, charts/prometheus-pingdom-exporter/templates/NOTES.txt
=> charts/prometheus-pingdom-exporter: fix typo

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
=> charts/prometheus-cloudwatch-exporter: fix typo

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/values.yaml
=> charts/kube-prometheus-stack: fix typos

.github/ISSUE_TEMPLATE/bug_report.md, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: fktkrt <fktkrt@gmail.com>
This PR extends the bug-temaplate currently in use with useful context informations. The goal of this PR to acquire more details for each bug reports, hence fixing the issue faster.
=> [.github meta resource] Refactor current bug template to request more information

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/templates/_helpers.tpl, charts/prometheus-redis-exporter/templates/role.yaml, charts/prometheus-redis-exporter/templates/rolebinding.yaml
Signed-off-by: Gabriel Melillo <gabriel@melillo.me>
To successfully lint the helm chart with the latest version of Helm the rbac `apiVersion` needs to be returned as `rbac.authorization.k8s.io/v1`, since `rbac.authorization.k8s.io/v1beta1` is marked for deprecation.
- fixes #352
=> [prometheus-redis-exporter] add configurable apiVersion

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/_helpers.tpl, charts/prometheus-postgres-exporter/templates/role.yaml, charts/prometheus-postgres-exporter/templates/rolebinding.yaml
Hi, this PR is to fix the same issue reported in #352 but for the postgres-exporter
/
=> [prometheus-postgres-exporter]: add configurable apiVersion

charts/prometheus-kafka-exporter/Chart.yaml, charts/prometheus-kafka-exporter/templates/_helpers.tpl, charts/prometheus-kafka-exporter/templates/role.yaml, charts/prometheus-kafka-exporter/templates/rolebinding.yaml
Signed-off-by: Gabriel Melillo <gabriel@melillo.me>
To successfully lint the helm chart with the latest version of Helm the RBAC apiVersion needs to be returned as `rbac.authorization.k8s.io/v1` since `rbac.authorization.k8s.io/v1beta1` is marked for deprecation.
- fixes #381
=> [prometheus-kafka-exporter] add configurable apiVersion

charts/prometheus-druid-exporter/Chart.yaml, charts/prometheus-druid-exporter/templates/deployment.yaml, charts/prometheus-druid-exporter/values.yaml
Signed-off-by: awatercolorpen <hellis@foxmail.com>
support podAnnotations
- fixes #
=> [prometheus-druid-exporter] support podAnnotations

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/templates/deployment.yaml, charts/prometheus-snmp-exporter/values.yaml
=> [prometheus-snmp-exporter] Add support mount extra secret and configmap 

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/service.yaml
kube-prometheus-stack: fix ports alignment (indent 2 instead of 4)
- fixes #
=> kube-prometheus-stack: fix ports alignment in service

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/statefulset.yaml, charts/alertmanager/values.yaml
This change allows setting arbitrary annotations to statefulset template. Use case: monitoring of deployment status from GitlabCI:
None known.
=> [alertmanager] add statefulSet annotations

.github/workflows/codespell.yaml
To avoid further common typos being added to the codebase.
- Closes #320
Right now it is expected that this pipeline will fail until PRs #315 #316 #317 #318 #319 are merged and this PR is rebased.
=> .github/workflows: add codespell workflow

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/deployment.yaml, charts/prometheus-adapter/values.yaml
In this PR, I support arguments for the prometheus-adapter deployment.
prometheus-adapter Deployment already supports extraVolumes and extraVolumeMounts, so we can mount the certifications. However, the Deployment does not allow to specify the extra-arguments of the container, so we cannot specify the certification flag.
- fixes #327
=> [prometheus-adapter] support extra arguments for the prometheus-adapter deployment

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
fixes typos
- fixes #
follow up to: https://github.com/prometheus-community/helm-charts/pull/279
=> [kube prometheus stack] fixed typos

charts/prometheus/Chart.yaml, charts/prometheus/templates/node-exporter/psp.yaml
Signed-off-by: Pavel Bakulev <p.bakulev@bilderlings.eu>
PR fixes error in using podSecurityPolicy of node-exporter
```
Type     Reason        Age                  From                  Message
----     ------        ----                 ----                  -------
Warning  FailedCreate  19s (x15 over 101s)  daemonset-controller  Error creating: pods "prometheus-node-exporter-" is forbidden: unable to validate against any pod security policy: [spec.volumes[2].hostPath.pathPrefix: Invalid value: "/": is not allowed to be used]
```
- addition to PR https://github.com/prometheus-community/helm-charts/pull/80
=> [prometheus] added absent allowedHostPath to psp of node-exporter

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml, charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml, charts/kube-prometheus-stack/templates/prometheus/ingress.yaml, charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml, charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
Remove the resource name from the Capabilites.APIVersion.Has so
that it returns an accurate result
Signed-off-by: Will Thames <wthames@skedulo.com>
=> [kube-prometheus-stack] Fix Capabilities check for IngressClass

.github/workflows/check-codeowners.yaml, scripts/check-codeowners.sh
@bismarck pointed out that the worflow does not work: https://github.com/prometheus-community/helm-charts/pull/403#issuecomment-754145107
https://github.com/prometheus-community/helm-charts/actions/runs/461677874
- fixes #
=> fix check CODEOWNERS worflow

charts/prometheus-stackdriver-exporter/Chart.yaml, charts/prometheus-stackdriver-exporter/values.yaml
=> [stackdriver-exporter] fix: scrapeTimeout value

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
Signed-off-by: Daniel Wegener <danielwegener@users.noreply.github.com>
The kubernetes annotation prometheus.io/scheme is currently only supported for services, not for pods. This PR adds support for prometheus.io/scheme for 'kubernetes-pods' and  'kubernetes-pods-slow'.
- fixes #533
=> [prometheus] Support scheme annotation for pod scrapers.

charts/prometheus/.gitignore, charts/prometheus/Chart.yaml, charts/prometheus/values.yaml, ct.yaml
* update prometheus to 2.24.0
* updates pushgateway to 1.3.1
* uses bitnamis kube-state-metrics chart as dependency as the official one has still a broken build pipline. see: https://github.com/kubernetes/kube-state-metrics/issues/1342
- fixes https://github.com/prometheus-community/helm-charts/issues/532
=> [prometheus] image & dependency updates

.github/CODEOWNERS, charts/prometheus-rabbitmq-exporter/Chart.yaml
Signed-off-by: iamabhishek-dubey <abhishekbhardwaj510@gmail.com>
This PR is for adding @iamabhishek-dubey as maintainer for RabbitMQ exporter
=> [prometheus-rabbitmq-exporter] Updated rabbitmq exporter maintainer list

.github/CODEOWNERS, charts/prometheus-rabbitmq-exporter/Chart.yaml
In order to solve https://github.com/prometheus-community/helm-charts/pull/416, I volunteer to maintain this chart as well.
@monotek, are you still interested as well?
- fixes #
=> [prometheus-rabbitmq-exporter] Add desaintmartin & monotek as maintainers

charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
To fix the chart tag issue that raised in https://github.com/prometheus-community/helm-charts/runs/1722435381?check_suite_focus=true
-na-
@scottrigby @bismarck this is to fix the chart version with the bump. {weird that it didn't show as a conflict or obsolete}
=> [kube-prometheus-stack] URGENT fix for chart version

charts/prometheus-pingdom-exporter/Chart.yaml
* try to fix chart release 
There is at least a release for version 2.3.0 of the chart: https://github.com/prometheus-community/helm-charts/releases/tag/prometheus-pingdom-exporter-2.3.0
But that release can't be found in the index.yaml: https://prometheus-community.github.io/helm-charts/index.yaml
The release for version 2.3.1 was not created: https://github.com/prometheus-community/helm-charts/runs/1364220774?check_suite_focus=true
- fixes # https://github.com/prometheus-community/helm-charts/issues/558
=> [pingdom-exporter] update version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md
This pr add the missing upgrade note from #582 
- fixes #595
=> [kube-prometheus-stack]: Add upgrade notes for v13

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
Signed-off-by: Allan Hung <hung.allan@gmail.com>
Use new API version for ingressThanosSidecar
reference: [#22106](https://github.com/prometheus-community/helm-charts/commit/e1f816be553cc75ea9e68798502f4937ad73181f)
=> [kube-prometheus-stack] Use new API version for ingressThanosSidecar

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/README.md
=> [prometheus-blackbox-exporter] Fix chart name in readme

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
Signed-off-by: Sushma Pranathi Reddem <sushmapranathi.reddem@resideo.com>
adding tpl upstream for external labels and url. 
- fixes #
=> [Kube-prometheus-stack]adding upstream for external label and url

.github/CODEOWNERS, charts/prometheus-node-exporter/Chart.yaml
Add bismarck as maintainer
- fixes #
=> [prometheus-node-exporter] Add bismarck as maintainer

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/values.yaml
Signed-off-by: Hector Fernandez <hectorj@gmail.com>
Bump prometheus-adapter to latest version v0.8.3 that includes certain bug fixes.
- fixes #
=> prometheus-adapter: upgrade appversion to v0.8.3

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/daemonset.yaml, charts/prometheus-node-exporter/values.yaml
Add parameter containerSecurityContext to add a securityContext to a container. To allow e.g. to set the capabilities "SYS_TIME" for the node_timex_sync_status metric.
=> [prometheus-node-exporter] add containerSecurityContext

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/servicemonitor.yaml, charts/prometheus-pushgateway/values.yaml
Adds the ability to add `metricRelabelings` and `relabelings` to ServiceMonitor
- fixes #
=> [prometheus-pushgateway] Adds ability to specify metricRelabelings and relabelings

charts/alertmanager/Chart.yaml, charts/alertmanager/values.yaml
Signed-off-by: Hector Fernandez <hectorj@gmail.com>
Upgrade the configmap-reload to tackle certain CVEs.
- fixes #
=> [alertmanager]: bump configmap reloader

charts/prometheus-mysql-exporter/Chart.yaml, charts/prometheus-mysql-exporter/README.md
Just fixing a broken link.
N/A
=> [prometheus-mysql-exporter] fixed link to Prometheus MySQL Exporter repo

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/values.yaml
Signed-off-by: Hector Fernandez <hectorj@gmail.com>
Upgrade the configmap-reload to tackle certain CVEs.
- fixes #
=> [prometheus-snmp-exporter]: bump configmap reloader

charts/prometheus/Chart.yaml
Upgrade the configmap-reload to tackle certain CVEs.
- fixes #
=> [prometheus]: Upgrade configmap reload version

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/deployment.yaml, charts/prometheus-adapter/values.yaml
=> [prometheus-adapter] Ability for custom dnsConfig

charts/prometheus-statsd-exporter/Chart.yaml, charts/prometheus-statsd-exporter/values.yaml
Signed-off-by: Dmitrii Limonov <disordervlz@gmail.com>
- fixes #
=> [prometheus-statsd-exporter] update version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
Signed-off-by: Jan Ludvik <ludvik.honza@gmail.com>
Fixes issue with indentation from my previous PR https://github.com/prometheus-community/helm-charts/pull/303. I tested with one label and when I tried to use it with 2 after first PR being merged, I saw what I did wrong and should have tested. The second line renders as being on top level of the yaml which makes it invalid k8s/prometheus manifest.
- fixes issue from PR https://github.com/prometheus-community/helm-charts/pull/303
I changed the code to similar way like in other places, should have done that in the first place.
=> [kube-prometheus-stack]

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
Signed-off-by: Hector Fernandez <hectorj@gmail.com>
Fix a wrong chart bump where the versions were not bumped.
- fixes #
=> [prometheus]: fix and bump the configmap reloader for real

charts/prometheus-cloudwatch-exporter/CHANGELOG.md, charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
Signed-off-by: Asher Foa <asher@asherfoa.com>
- fixes #
=> [prometheus-cloudwatch-exporter] Update to cloudwatch exporter v0.10.0

charts/prometheus-nats-exporter/Chart.yaml, charts/prometheus-nats-exporter/values.yaml
Update to the latest nats-exporter version
- fixes #
=> [prometheus-nats-exporter] Bump prometheus-nats-expoter app version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Yann David <davidyann88@gmail.com>
CRDs taken from `prometheus-operator` repo
=> [kube-prometheus-stack] 0.46.0 operator and crds

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/serviceThanosSIdecar.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Esther Kim <jabbukka@naver.com>
Supports `NodePort` type to thanos-discovery service.
- fixes #768
=> [kube-prometheus-stack] Added nodePort to thanosService

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
LoadBalancer service type is a case sensitive.
Fix a typo in documentation. loadbalancer -> LoadBalancer
=> [kube-prometheus-stack] Fix LoadBalancer typo in service type

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/services.yaml, charts/alertmanager/values.yaml
added option to support NodePort
- fixes #
- [ X] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ X] Chart Version bumped
- [X ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
=> [alertmanager] add NodePort support

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/README.md
* readme refers to rabbitmq instead of redis
- fixes https://github.com/prometheus-community/helm-charts/issues/813
=> [prometehus-redis-exporter] fix readme

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/hack/requirements.txt
Bump PyYAML to 5.4 (just used in hack scripts) to mitigate CVE-2020-14343 https://github.com/advisories/GHSA-8q59-q68h-6hv4
- fixes #
=> [kube-prometheus-stack] Bump PyYAML to 5.4

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: aisuko <urakiny@gmail.com>
- fixes #841
=> Bump prometheus image version to fix the target's issue

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack] Add support for Alertmanager CR annotations

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
This PR upgrades node-exporter to v1.1.2. The current v1.0.1 is quite outdated.
=> [prometheus] Upgraded node-exporter to v1.1.2

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/templates/servicemonitor.yaml, charts/prometheus-redis-exporter/values.yaml
Signed-off-by: Dhruva <dhruva.chandra@invoice2go.com>
- enables adding [relabel_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) to serviceMonitor resource
=> prometheus-redis-exporter : add relabeling configs for redis exporter

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml, charts/kube-prometheus-stack/values.yaml
Supports enableFeatures API of Prometheus Operator
- fixes #823
n/a
=> [kube-prometheus-stack] support enableFeatures API

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml, charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml, charts/kube-prometheus-stack/templates/prometheus/ingress.yaml, charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml, charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
Adds ingress for v1. One less chart with those pesky deprecation notices
n/a
=> [kube-prometheus-stack] update ingress for v1

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/statefulset.yaml
Signed-off-by: Pavol Stanka <stanka@ehs.sk>
- fixes #
=> [alertmanager]fix cluster-peer names within cluster

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml
Ensure proper configuration of telemetry port and ensure port is exposed from the container.
- fixes #
@tariq1890 @mrueg
=> [kube-state-metrics] Ensure consistent telemetry configuration

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml, charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
This fixes issue with ingressperreplica not working.
- fixes #929
=> [kube-prometheus-stack] Fix ingressperreplica not working

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml, charts/kube-prometheus-stack/templates/exporters/node-exporter/servicemonitor.yaml
- fix serviceMonitor proxyUrl typo of `kube-prometheus-stack` chart.
=> [kube-prometheus-stack] Fix serviceMonitor proxyUrl error

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md
* fixes kube-state-metrics url
- fixes #
followup to https://github.com/prometheus-community/helm-charts/pull/988
=> [kube-prometheus-stack] fix kube-state-metrics url

charts/prometheus-stackdriver-exporter/Chart.yaml, charts/prometheus-stackdriver-exporter/values.yaml
Signed-off-by: Maksim Noskov <RinckFox@yandex.ru>
Considering that the indicators in Stackdriver have some delay (problem described in the [ticket](https://github.com/prometheus-community/stackdriver_exporter/issues/7)), I had a need to create two exporters with different scrape interval in the same namespace. However, this is impossible without changing the nameOverride variable, because otherwise both charts try to create a ServiceMonitor with the same name.
@apenney @rpahli i learned about variable nameOverride variable from the code. It would be nice to tell about her.
Closed previous PR (1008) and open a new one.
=> [prometheus-stackdriver-exporter] add nameOverride and fullnameOverride to values.yaml

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/values.yaml
Signed-off-by: Mariia Kerimova <mashun4ek@gmail.com>
This PR renames the metric specified in `values.yaml` file, which queries `pg_stat_activity` table for idle processes, to avoid overwriting of [built-in pg_stat_activity metrics](https://github.com/prometheus-community/postgres_exporter/blob/21f27a8e03479afc20f7fa3dde2ec94f8508a800/cmd/postgres_exporter/postgres_exporter.go#L359), and clarify that this query includes only processes with idle state. 
- fixes #
Let me know if I need to open the issue related to overwriting the metric.
@gianrubio @zanhsieh
=> [prometheus-postgres-exporter]Rename pg_stat_activity query to pg_stat_activity_idle

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/README.md
Updates the documentation regarding `helm show values` with the most updated repo location on helm repo.
- fixes #1024
cc: @tariq1890 @mrueg
=> [kube-state-metrics] fix documentation for helm show values

charts/alertmanager/Chart.yaml
Upgrade default version to the latest release 0.22.1. https://github.com/prometheus/alertmanager/releases
=> [alertmanager] Upgrade version to 0.22.1

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/exporters/node-exporter/servicemonitor.yaml
Signed-off-by: jmshin92 <shinjm092@gmail.com>
This PR adds an namespaceSelector to the nodeExporter serviceMonitor. With this PR, nodeExporter serviceMonitor can look for the correct namespace (chart's namespace or `prometheus-node-exporter.namespaceOverride`)
- fixes #984
=> [kube-prometheus-stack] fix nodeExporter serviceMonitor's namespaceSelector

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml, charts/kube-state-metrics/values.yaml
Signed-off-by: Biava, Lorenzo <lorenzo.biava@nuance.com>
Add parameter containerSecurityContext to add a securityContext to a container. To allow setting options not available at the Pod level securityContext.
See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#securitycontext-v1-core
=> [kube-state-metrics] Add containerSecurityContext

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/serviceaccount.yaml, charts/prometheus-adapter/values.yaml
Allow specifying annotations in the K8s service account for e.g. to use AWS EKS IAM roles for service accounts
- NA
Nil
=> [prometheus-adapter] Allow specifying service account annotations

charts/prometheus-stackdriver-exporter/Chart.yaml, charts/prometheus-stackdriver-exporter/templates/deployment.yaml, charts/prometheus-stackdriver-exporter/values.yaml
To be able to pass extra args to the exporter. This is helpful to set the log level and log format of the exporter.
- fixes #
=> [prometheus-stackdriver-exporter] Add possiblity to pass extra args to the exporter

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Oleksii Kravchenko <oleksii.kravchenko@aspira.global>
Bump minor version of prometheus-operator to v0.48.1. This version contains only bug fixes.
=> [kube-prometheus-stack] update prometheus-operator to v0.48.1

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
Signed-off-by: birca <birca@adobe.com>
This updates the named port in the kube-state-metrics ServiceMonitor in order to match the service port exposed for metrics: [service port](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/service.yaml#L32)
=> [kube-prometheus-stack] Update kube-state-metrics ServiceMonitor port

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
This reverts #1065
- fixes #1068
=> [kube-prometheus-stack] Revert c4a7d10fdc6a0f694d9b97e9446207ba67d997dd

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/pdb.yaml, charts/alertmanager/values.yaml
Signed-off-by: Chris Sng <chrissng@users.noreply.github.com>
Option to deploy pod disruption budget for Alertmanager
- NA
=> [alertmanager] Add PDB to Alertmanager chart

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/deployment.yaml, charts/prometheus-pushgateway/values.yaml
Signed-off-by: Matteo Maponi <matteo.maponi@gmail.com>
This adds the priorityClassName argument for prometheus-pushgateway.
- fixes #947
=> [prometheus-pushgateway] PriorityClassName for prom-pushgateway

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
This PR updates Grafana helm chart dependency with fixes released in [Grafana 8.0.3](https://github.com/grafana/grafana/releases/tag/v8.0.3)
- fixes #
=> [kube-prometheus-stack] Update Grafana helm chart

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml
Signed-off-by: birca <birca@adobe.com>
https://github.com/prometheus-community/helm-charts/pull/904 broke https://github.com/prometheus-community/helm-charts/commit/f43e17aa14ab4aea40198c296cfeb8e6ea3db314 as you can no longer pass namespaces as a list:
`helm.go:81: [debug] template: kube-state-metrics/templates/deployment.yaml:156:37: executing "kube-state-metrics/templates/deployment.yaml" at <.Values.namespaces>: wrong type for value; expected string; got []interface {}`
=> [kube-state-metrics] allow for namespaces flag to be passed as a list

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml, charts/kube-state-metrics/templates/role.yaml, charts/kube-state-metrics/templates/service.yaml, charts/kube-state-metrics/values.yaml
Signed-off-by: Daniel Carmel <danielcarmel6@gmail.com>
What this PR does / why we need it:
* Fix templates bugs
* Improve templates
* Now its possible change ports from values
* New features: metric-labels-allowlist, metric-allowlist, metric-denylist
=> [kube-state-metrics] Fix and improve template and include new features

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
Updates charts and syncs rules and DB with kube-prometheus
=> [kube-prometheus-stack] Sync rules, dbs and subcharts

.github/workflows/lint-test.yaml
* updates helm to 3.6.2
* update kind action
* updates chart testing action
- fixes 
this fixes all github actions runs which are failing with "node not ready" errors like in:
* https://github.com/prometheus-community/helm-charts/pull/1139/checks?check_run_id=2996921711
* https://github.com/prometheus-community/helm-charts/runs/2976102825
* https://github.com/prometheus-community/helm-charts/runs/2998259878
=> [github actions] fix ci

.github/workflows/release.yaml
Updates helm version to 3.6.2 in releass workflow, to use same version as in lint / install (https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/lint-test.yaml#L16)
- fixes #
=> Update helm version in release workflow

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-burnrate.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-histogram.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
`prometheus-operator/kube-prometheus` was updated with the latest kubernetes-mixin.
- related to https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/643
=> [kube-prometheus-stack] Sync rules

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/README.md, charts/prometheus-blackbox-exporter/templates/NOTES.txt, charts/prometheus-blackbox-exporter/templates/_helpers.tpl, charts/prometheus-blackbox-exporter/templates/configmap.yaml, charts/prometheus-blackbox-exporter/templates/daemonset.yaml, charts/prometheus-blackbox-exporter/templates/deployment.yaml, charts/prometheus-blackbox-exporter/templates/ingress.yaml, charts/prometheus-blackbox-exporter/templates/networkpolicy.yaml, charts/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml, charts/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml, charts/prometheus-blackbox-exporter/templates/prometheusrule.yaml, charts/prometheus-blackbox-exporter/templates/role.yaml, charts/prometheus-blackbox-exporter/templates/rolebinding.yaml, charts/prometheus-blackbox-exporter/templates/service.yaml, charts/prometheus-blackbox-exporter/templates/serviceaccount.yaml, charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml, charts/prometheus-blackbox-exporter/values.yaml
* remove helm 2 support
* ingress update (adds ingressClassName & pathType)
* fix docs (extraArgs)
* use label template
- fixes #
https://github.com/prometheus-community/helm-charts/issues/1111
* updates github actions for chart testing & kind 
* updates helm version to 3.6.2
=> [prometheus-blackbox-exporter] remove helm2 support, ingress update, fix docs & use label template

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/templates/_helpers.tpl, charts/prometheus-snmp-exporter/templates/configmap.yaml, charts/prometheus-snmp-exporter/templates/deployment.yaml, charts/prometheus-snmp-exporter/templates/ingress.yaml, charts/prometheus-snmp-exporter/templates/role.yaml, charts/prometheus-snmp-exporter/templates/rolebinding.yaml, charts/prometheus-snmp-exporter/templates/service.yaml, charts/prometheus-snmp-exporter/templates/serviceaccount.yaml, charts/prometheus-snmp-exporter/templates/servicemonitor.yaml, charts/prometheus-snmp-exporter/values.yaml
=> [prometheus-snmp-exporter] Kubernetes recommanded labels and custom labels

charts/prometheus-elasticsearch-exporter/Chart.yaml, charts/prometheus-elasticsearch-exporter/README.md, charts/prometheus-elasticsearch-exporter/values.yaml
Update version and repository for elasticsearch-exporter image.
See updates in https://github.com/prometheus-community/elasticsearch_exporter
=> [prometheus-elasticsearch-exporter] update image version

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml, charts/kube-prometheus-stack/values.yaml
Updates grafana, node-exporter dependencies as well as syncs dashboards
=> [kube-prometheus-stack] Update dependencies and dashboard

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
*  fix servicemonitor labels
- fixes #
https://github.com/prometheus-community/helm-charts/pull/1121#issuecomment-882719457
=> [prometheus-blackbox-exporter] fix servicemonitor labels

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
* fixes usage of several servicemonitor targets
- fixes #
https://github.com/prometheus-community/helm-charts/issues/1191
=> [prometheus-blackbox-exporter] fix servicemonitor range

charts/prometheus-adapter/Chart.yaml
- fixes # https://github.com/prometheus-community/helm-charts/pull/1136#issuecomment-884350461
=> [prometheus-adapter] create new version to get release work

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/hack/sync_prometheus_rules.py, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
- fixes #122 again after a regression caused by not adding the condition to the prometheus rules sync script.
- See https://github.com/prometheus-community/helm-charts/issues/122#issuecomment-840788371 for the specific issue
Let me know if I have not updated the syncing script correctly!
=> [kube-prometheus-stack] Restore the semver check to AggregatedAPIDown and add it to the sync script

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/templates/servicemonitor.yaml
error validating data: [ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/instance"
To Reproduce
Steps to reproduce the behavior:
enable serviceMonitor and deploy the prometheus-snmp-exporter chart.
getting the error "error validating data: [ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/instance"
- fixes #
prometheus-snmp-exporter:
=> prometheus-snmp-exporter:getting error in  servicemonitor.yaml after enabling  serviceMonitor 

charts/prometheus-mysql-exporter/Chart.yaml, charts/prometheus-mysql-exporter/templates/deployment.yaml
Added checksum of the password to the deployment config.
- fixes #
=> [prometheus-mysql-exporter] Restart pod on password change

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
=> [kube-prometheus-stack] Bump to Grafana chart 6.15.* to use grafana 8

charts/prometheus-kafka-exporter/Chart.yaml, charts/prometheus-kafka-exporter/templates/service.yaml, charts/prometheus-kafka-exporter/templates/servicemonitor.yaml, charts/prometheus-kafka-exporter/values.yaml
Signed-off-by: Edwin Hobor <edwinhobor@gmail.com>
Added the possibility to create custom `service` labels and `serviceMonitor` targetLabels.
- fixes #1222 
@gkarthiks, @golgoth31, @isac-seven would you please take a look? Thanks!
=> [prometheus-kafka-exporter] Kafka exporter chart not propagating service labels

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Ishan Khare <ishankhare07@gmail.com>
This PR exposes the `sidecar.dashboards.provider.allowUiUpdates` override from the [grafana/grafana](https://github.com/grafana/helm-charts/tree/main/charts/grafana) chart, that allows users to "update provisioned dashboards from the UI". More details can be found here - 
- fixes #
=> `[kube-prometheus-stack]` add option to override the allowUiUpdates for grafana dashboards

charts/prometheus-stackdriver-exporter/Chart.yaml, charts/prometheus-stackdriver-exporter/templates/servicemonitor.yaml, charts/prometheus-stackdriver-exporter/values.yaml
Signed-off-by: Felix Kaiser <67369033+fkaiser-mms@users.noreply.github.com>
Add honorTimestamps config to stackdriver-exporter serviceMonitor.
=> [prometheus-stackdriver-exporter] Add honorTimestamps config to stackdriver-exporter serviceMonitor

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/templates/deployment.yaml
Signed-off-by: Stanislav Chesnovskiy <s.chesnovskiy@semrush.com>
This PR allows using annotations in deployment.
=> allow using annotations in deployment

charts/prometheus-pingdom-exporter/Chart.yaml, charts/prometheus-pingdom-exporter/README.md
@monotek
I don't think the version for this chart needs to be bumped for these changes.
=> [prometheus-pingdom-exporter] Minor tweaks to README

charts/prometheus-kafka-exporter/Chart.yaml, charts/prometheus-kafka-exporter/templates/deployment.yaml, charts/prometheus-kafka-exporter/values.yaml
Signed-off-by: Bogdan Matei <bogdan0796@gmail.com>
- fixes #
=> [prometheus-kafka-exporter] Add: securitycontext to deployment.yaml

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/daemonset.yaml, charts/prometheus-node-exporter/values.yaml
=> [prometheus-node-exporter] Allow for specifying automountServiceAccountToken

charts/prometheus-kafka-exporter/Chart.yaml, charts/prometheus-kafka-exporter/templates/_helpers.tpl, charts/prometheus-kafka-exporter/templates/deployment.yaml, charts/prometheus-kafka-exporter/templates/secret.yaml, charts/prometheus-kafka-exporter/values.yaml
Signed-off-by: Max Pschonder <max.pschonder@hivemindtechnologies.com>
I added support for SASL configuration options and fixed errors caused by unsupported `—log.level` param.
- SASL support
- `--verbosity` replaced `--log-level` [README Update](https://github.com/danielqsj/kafka_exporter/commit/b6cb6afe3bc77ff0a7ce556f33f9397e57f9b63b)
=> [prometheus-kafka-exporter] - added SASL support and upgrade to latest version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
It was using the wrong label expression, so wasn't having any effect.
- fixes #
=> [kube-prometheus-stack] Fix alert manager soft anti-affinity configuration

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/values.yaml
When there are multiple results for pg_stat_statements with empty queryId,
it causes the exporter to fail with "collected metric "pg_stat_statements_blk_write_time_seconds" { label:<name:"datname" value:"yyyy" > label:<name:"queryid" value:"" > label:<name:"rolname" value:"rdsadmin" > label:<name:"server" value:"xxxxxx:5432" > counter:<value:0 > } was collected before with the same name and label values".
Some more info at https://github.com/prometheus-community/postgres_exporter/issues/451#issuecomment-751348782
- fixes #
=> [prometheus-postgres-exporter] ignore pg_stat_statememts with empty queryId

charts/prometheus/Chart.yaml
- fixes https://github.com/prometheus-community/helm-charts/issues/1344
=> [prometheus] bump kube-state-metrics version to "3.5.*"

charts/prometheus/Chart.yaml, charts/prometheus/templates/pushgateway/vpa.yaml, charts/prometheus/values.yaml
Signed-off-by: Tuan Anh Nguyen <tuananh.nguyen-ext@commercetools.de>
This will add support for enabling/configuring vertical pod autoscaler for pushgateway component in prometheus chart.
=> [prometheus] Add VPA support for pushgateway

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/deploy.yaml, charts/prometheus/templates/server/sts.yaml, charts/prometheus/values.yaml
Signed-off-by: Tan Luu <luuhoangtanbis@gmail.com>
Support readiness and liveness HTTPS probe scheme
- fixes #
=> [prometheus] add probeScheme for prometheus server

charts/prometheus-statsd-exporter/Chart.yaml, charts/prometheus-statsd-exporter/templates/_helpers.tpl, charts/prometheus-statsd-exporter/templates/ingress.yaml, charts/prometheus-statsd-exporter/values.yaml
* fixes ingress for k8s >= 1.19
* fixes mappingConfigMapName linebreak
- fixes https://github.com/prometheus-community/helm-charts/issues/1295
* changes from https://github.com/prometheus-community/helm-charts/pull/1037 + classname (could not push to other branch)
=> [prometheus-stats-exporter] fix ingress for k8s >= 1.19

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/service.yaml, charts/prometheus-mysql-exporter/Chart.yaml
Signed-off-by: Arnaldo Garat <arnaldo.garat@buda.com>
This PR adds the option to set a secret name containing the proxysql credentials, this is helpful when you manage your secrets externally and don't want them in the values.yaml.
=> [prometheus-mysql-exporter] Add proxysql credentials as secret

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/ingress.yaml, charts/prometheus-pushgateway/values.yaml
Signed-off-by: Tim Collins <tim@thecollins.team>
- fixes #1441
=> [prometheus-pushgateway] Support networking.k8s.io/v1

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/templates/deployment.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
Signed-off-by: Chelo Montilla <chelo.montilla@lansweeper.com>
This PR allows to configure pod annotations in prometheus cloudwatch exporter chart.
- fixes #
=> [prometheus-cloudwatch-exporter] configurable pod annotations

charts/prometheus-consul-exporter/Chart.yaml, charts/prometheus-consul-exporter/templates/deployment.yaml, charts/prometheus-consul-exporter/values.yaml
Add support for annotations to pods. Useful for some pod mutators like Consul Connect Inject etc.
- fixes #
=> [prometheus-consul-exporter] Add Pod Annotations Value

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/values.yaml
Upgrading Prometheus Operator version (and CRD changes) to version v0.52.0. This adds additional features one in question the sigv4 setting to allow remote writing to Amazon Managed Prometheus
- fixes #
The new version v0.52.0 was only released by the operator team today, 4th November 2021
I have a project that is dependent on this change, though I have tested it as a local chart and it has successfully worked, but having it pushed to the main chart is important.
Thank you
@torstenwalter - added you here but cant add you as a reviewer. Noticed you have approved a PR recently. I am looking for this change to get pushed through as quickly as possible :) thanks
=> [kube-prometheus-stack] Prometheus operator version upgrade v0.52.0

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
There is no whitespace between directive and closing braces.
As per formatting-template rules [1]:
"Template directives should have whitespace after the opening 
braces and before the closing braces"
1: https://helm.sh/docs/chart_best_practices/templates/#formatting-templates
Signed-off-by: Nicolas Nosenzo <nicolas@timescale.com>
- fixes #
=> prometheus-cloudwatch-exporter - Add missing whitespace

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
Signed-off-by: Vitaliy Fuks <vitaliyf@users.noreply.github.com>
- fixes #1403
Versions match what is proposed in https://github.com/prometheus-community/helm-charts/pull/1397
=> [prometheus] Bump Prometheus to 2.31.1 and Alertmanager to 0.23.0

charts/prometheus/Chart.yaml, charts/prometheus/README.md
fix prometheus update readme
- fixes #
https://github.com/prometheus-community/helm-charts/issues/1538
=> [prometheus] fix prometheus update readme

charts/prometheus-elasticsearch-exporter/Chart.yaml, charts/prometheus-elasticsearch-exporter/values.yaml
Bump default version of the exporter to 1.3.0.
No breaking change from the [changelog](https://github.com/prometheus-community/elasticsearch_exporter/blob/master/CHANGELOG.md#130--2021-10-21).
None
=> [prometheus-elasticsearch-exporter] Bump exporter to 1.3.0

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
prometheus.yaml is guarded by `{{- if .Values.prometheus.enabled }}` but the if/end does not enclose the whole file.
=> [kube-prometheus-stack] missplaced end tag

.github/CODEOWNERS, charts/kube-prometheus-stack/Chart.yaml
=> [kube-prometheus-stack] Removing me as maintainer

.github/CODEOWNERS, charts/prometheus-node-exporter/Chart.yaml
=> [prometheus-node-exporter] Remove me as maintainer

charts/prometheus-stackdriver-exporter/Chart.yaml
Signed-off-by: Shimon Ohayon  <shimon.ohayon@gmail.com>
Fix small typo of source url for `prometheus-stackdriver-exporter` chart.
FYI:
@apenney
@rpahli
=> [prometheus-stackdriver-exporter] fix chart name in source url.

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/role.yaml
=> [kube-state-metrics] add indentation for customLabels in role template

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
=> [kube-prometheus-stack] update kube-state-metrics dependency to 4.1.1

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
fixed double annotation
- fixes # https://github.com/prometheus-community/helm-charts/issues/1493
=> [kube-prometheus-stack] fix double annotation

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
=> [kube-prometheus-stack] bump grafana dependency to 6.19.0

charts/prometheus-elasticsearch-exporter/Chart.yaml, charts/prometheus-elasticsearch-exporter/templates/deployment.yaml, charts/prometheus-elasticsearch-exporter/values.yaml
=> [prometheus-elasticsearch-exporter] Add support for indices mappings

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/values.yaml
Signed-off-by: MxNxPx <MxNxPx@gmail.com>
Updates prom pushgateway to latest version - [(1.4.2)](https://github.com/prometheus/pushgateway/releases/tag/v1.4.2).
- fixes #https://github.com/prometheus-community/helm-charts/issues/1588
=> [prometheus-pushgateway] - bump prom pushgateway to latest version - 1.4.2

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/service.yaml, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack] Add publishNotReadyAddresses prometheus service value.

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack] fix kubeApiserver rule

charts/prometheus-nats-exporter/Chart.yaml, charts/prometheus-nats-exporter/templates/deployment.yaml, charts/prometheus-nats-exporter/values.yaml
prometheus-nats-exporter version 0.9.0
add `leafz` metrics
Use latest version of the exporter
- fixes #
=> [prometheus-nats-exporter] feature: bump prometheus-nats-exporter version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
* update thanos to 0.24.0
- fixes #
=> [kube-prometheus-stack] update thanos to 0.24.0

charts/prometheus-elasticsearch-exporter/Chart.yaml, charts/prometheus-elasticsearch-exporter/templates/deployment.yaml, charts/prometheus-elasticsearch-exporter/values.yaml
Developer Certificate of Origin
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to …
=> [prometheus-elasticsearch-exporter] Support extra arguments to the pod's container

.github/CODEOWNERS, charts/kube-prometheus-stack/Chart.yaml
Adding andrewgkew as new maintainer
- fixes #
=> [kube-prometheus-stack] Adding andrewgkew as new maintainer

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/role.yaml, charts/kube-state-metrics/templates/rolebinding.yaml
Signed-off-by: Stanislav Khalash <stanislav.khalash@sap.com>
- Unifies the clusterrole labels with the rest of the chart resources by using the `kube-state-metrics.labels` template
=> [kube-state-metrics] Fix code duplication

.github/CODEOWNERS, charts/kube-prometheus-stack/Chart.yaml
Related to https://github.com/prometheus-community/helm-charts/issues/1656#issuecomment-1004134615
=> [kube-prometheus-stack] Add desaintmartin as maintainer.

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
* Update helm version
* Update chart-testing-action to v2.2.0
* Update helm unittest plugin
=> .github: Update workflows

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/_helpers.tpl, charts/kube-state-metrics/values.yaml
* added optional release label to make kube-prometheus-stack servicemonitor work out of the box
* also removes executable bit from Chart.yaml file
- fixes # https://github.com/prometheus-community/helm-charts/issues/1631
=> [kube-state-metrics] added release label option

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md
Just a small typo correction.
Signed-off-by: peterfromthehill <peter@1qay.net>
=> [kube-prometheus-stack] typo fix

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/values.yaml
* use kube-state-metrics release label option which makes scraping of kube-state-metrics working out of the box again.
- fixes # https://github.com/prometheus-community/helm-charts/issues/1631
=> [kube-prometheus-stack] use kube-state-metrics release label option

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/external-metrics-cluster-role-binding-hpa.yaml
Please enter the commit message for your changes. Lines starting
with '#' will be ignored, and an empty message aborts the commit.
On branch fix-external-metrics-role-binding-for-adapter
Changes to be committed:
modified:   charts/prometheus-adapter/templates/external-metrics-cluster-role-binding-hpa.yaml
fix external-metric role binding service account
- fixes #
=> [prometheus-adapter] fix external-metric role binding service account

charts/prometheus-mongodb-exporter/Chart.yaml, charts/prometheus-mongodb-exporter/templates/deployment.yaml, charts/prometheus-mongodb-exporter/values.yaml
PR gives option to attach volumes from various sources (configMap, secret, etc) to the running container. It can also reduce complexity for consumers in many use cases.
In my case it's a secret that contains a certificate. This certificate then used in the URI `?option` part to secure communication.
Without this, I need to use this chart as dependency and overwrite the deployment simply to support volumes management.
=> [prometheus-mongodb-exporter] Add volumes support

charts/prometheus-nats-exporter/Chart.yaml, charts/prometheus-nats-exporter/values.yaml
Use latest version of the exporter
- fixes #
=> [prometheus-nats-exporter] feature: prometheus-nats-exporter version 0.9.1

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
=> [kube-prometheus-stack] Grafana: upgrade to 6.21.0, kube-state-metrics: upgrade to 4.4.1

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/deploy.yaml
Fixes the order of the --web.route-prefix cli arg in the prometheus-server chart.
- fixes #1594
=> [prometheus] Fix issue with --web.route-prefix order (#1594)

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/deployment.yaml, charts/prometheus-pushgateway/values.yaml
=> [prometheus-pushgateway] Add support for containerSecurityContext to fix #1741

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/templates/deployment.yaml, charts/prometheus-snmp-exporter/values.yaml
…elm chart
Signed-off-by: Franco Mariotti <fmariotti@whitestack.com>
- fixes  #1254
=> [prometheus-snmp-exporter] Added missing imagePullSecrets property

charts/prometheus/Chart.yaml, charts/prometheus/templates/alertmanager/deploy.yaml
=> [prometheus] Add support for extraconfigmap mounts on alertmanager

charts/prometheus/Chart.yaml, charts/prometheus/templates/alertmanager/deploy.yaml, charts/prometheus/values.yaml
- [*] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [*] Chart Version bumped
- [*] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
=> [prometheus] Add alertmanager.extraConfigmapMounts

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/grafana-overview.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml, charts/kube-prometheus-stack/values.yaml
* Bump prometheus-operator to 0.54.0
* Sync grafana dashboards
* Sync prometheus rules
* Sync dependencies
* Change default for `grafana.serviceMonitor.enabled` to `true`
- fixes #
=> [kube-prometheus-stack] Prometheus-Operator v0.54.0

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
This dashboard depends on nodeExporter metrics
so make this dashboard depend on that being enabled
=> [kube-prometheus-stack] Import Node Exporter / Nodes grafana dashboard conditionally

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/statefulset.yaml, charts/alertmanager/values.yaml
Signed-off-by: heriet <heriet@heriet.info>
livenessProbe/readinessProbe may require detailed configuration by chart users. (e.g. Basic Authentication #1772)
Currently, livenessProbe/readinessProbe are fixed value on alertmanager chart. This PR enables to configure livenessProbe/readinessProbe.
=> [alertmanager] configurable livenessProbe/readinessProbe

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml, charts/kube-state-metrics/values.yaml
Signed-off-by: Chris <chris@weiss.is>
Details: https://github.com/kubernetes/kube-state-metrics/issues/1593
- fixes #
=> [kube-state-metrics] Add namespacesDenylist

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/ingress.yaml, charts/prometheus-blackbox-exporter/values.yaml
Signed-off-by: ANGkeith <angkeith@hotmail.sg>
We want to be able to add labels only for the blackbox exporter ingress
=> [prometheus-blackbox-exporter] Expose ingress labels

.github/CODEOWNERS, charts/prometheus-json-exporter/Chart.yaml
Related to https://github.com/prometheus-community/helm-charts/issues/1656#issuecomment-1005306520
=> [prometheus-json-exporter] Add zanhsieh as one of maintainers

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
- Bump grafana to 6.22.0
- Bump kube-state-metrics to 4.5.0
- 
- fixes #
=> [kube-prometheus-stack] Bump grafana and kube-state-metrics subcharts

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/values.yaml
Updates the image to 2.4.1
@tariq1890 @dotdc PTAL
- fixes #
=> [kube-state-metrics] Version bump to 2.4.1

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/cm.yaml
Signed-off-by: Ranjith KA <ranjithkumar.359@gmail.com>
- fixes #
=> [prometheus] Move tpl to ToYaml for extraScrapeConfigs

charts/prometheus/Chart.yaml
Commit `90930fcb26e41156892a4457133b38a238469ee8` was merged with conflicting version.
The build has failed since the version already exists.
https://github.com/prometheus-community/helm-charts/commit/90930fcb26e41156892a4457133b38a238469ee8
https://github.com/prometheus-community/helm-charts/pull/1836
- fixes #
=> [prometheus] Bump chart version to release previous commit.

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/external-metrics-cluster-role-binding-hpa.yaml
Fixes #1739
Signed-off-by: Hank Yan <yiyan@wish.com>
- fixes #1739
=> [prometheus-adapter] Correct prometheus-adapter external metrics rbac

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack] fix alertmanagerConfiguration typo

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
Updates all default Prometheus versions to the latest.
=> [prometheus] Update version to v2.34.0

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack] update prometheus images

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/aggregate-clusterroles.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Philip Sieder <philip.sieder@tallence.com>
The PR adds a new option to create aggregate Roles which allow RBAC based on the built in ClusterRoles `view` `edit` and `admin` as described for the prometheus-operator [here](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/rbac-crd.md).
- fixes #
=> [kube-prometheus-stack] Add option to create aggregate ClusterRoles

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/daemonset.yaml, charts/prometheus-node-exporter/values.yaml
Signed-off-by: Tomas Kohout <tomas.kohout1995@gmail.com>
=> [prometheus-node-exporter] be able to set environment variables

.github/CODEOWNERS, charts/prometheus/Chart.yaml
* remove monotek as maintainer from prometheus chart 
* i don't use it as i switched to kube-prometheus-stack a long time ago and i can't really give support here anymore
- fixes #
=> [prometheus] remove monotek from prometheus chart

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: Tomas Kohout <tomas.kohout1995@gmail.com>
Upgrades dependency for prometheus-node-exporter to previously released 3.1.0 version.
=> [kube-prometheus-stack] - upgrade node-exporter version

.github/workflows/check-codeowners.yaml, .github/workflows/codespell.yaml, .github/workflows/lint-test.yaml, .github/workflows/linter.yml, .github/workflows/release.yaml, .github/workflows/sync-readme.yaml, charts/prometheus/Chart.yaml
* updates prometheus 
* update ci components
- fixes #
=> [prometheus] update kube-state-metrics & ci components

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/README.md
This PR fixes README.md for prometheus-snmp-exporter chart.
- Fixes wrong example configs in README.md
- FIxes a typo in README.md
- fixes #
=> [prometheus-snmp-exporter] Fix README.md

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/_helpers.tpl, charts/prometheus-adapter/templates/certmanager.yaml, charts/prometheus-adapter/templates/cluster-role-binding-auth-delegator.yaml, charts/prometheus-adapter/templates/cluster-role-binding-resource-reader.yaml, charts/prometheus-adapter/templates/configmap.yaml, charts/prometheus-adapter/templates/custom-metrics-apiservice.yaml, charts/prometheus-adapter/templates/custom-metrics-cluster-role-binding-hpa.yaml, charts/prometheus-adapter/templates/deployment.yaml, charts/prometheus-adapter/templates/external-metrics-apiservice.yaml, charts/prometheus-adapter/templates/pdb.yaml, charts/prometheus-adapter/templates/psp.yaml, charts/prometheus-adapter/templates/resource-metrics-apiservice.yaml, charts/prometheus-adapter/templates/resource-metrics-cluster-role-binding.yaml, charts/prometheus-adapter/templates/role-binding-auth-reader.yaml, charts/prometheus-adapter/templates/secret.yaml, charts/prometheus-adapter/templates/service.yaml, charts/prometheus-adapter/templates/serviceaccount.yaml, charts/prometheus-adapter/values.yaml
Allow the release namespace to be overridden for multi-namespace deployments in combined charts
- fixes #1931
Thanks!
=> [prometheus-adapter] Allow namespace override

charts/prometheus-rabbitmq-exporter/Chart.yaml, charts/prometheus-rabbitmq-exporter/templates/_helpers.tpl, charts/prometheus-rabbitmq-exporter/templates/deployment.yaml, charts/prometheus-rabbitmq-exporter/templates/serviceaccount.yaml, charts/prometheus-rabbitmq-exporter/values.yaml
Signed-off-by: Daniel Cristian Aragão Paula <danielcrisap@gmail.com>
Enable creation of a service account for `prometheus-rabbitmq-exporter`
- feat #1948
=> [prometheus-rabbitmq-exporter] Added Service Account

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/daemonset.yaml, charts/prometheus-node-exporter/values.yaml
Signed-off-by: Prateek Mishra <pr0pm@pm.me>
- fixes #1981
=> [prometheus-node-exporter] add config to enable imagePullSecrets

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/deploy.yaml
This PR will allow set securityContext on containers level on Prometheus server, rather than just pod level that is currently implemented
- fixes #1990 
[@gianrubio](https://github.com/gianrubio) [@zanhsieh](https://github.com/zanhsieh) [@Xtigyro](https://github.com/Xtigyro) [@naseemkullah](https://github.com/naseemkullah) - Please review this PR and let me know if any change is required.
=> [prometheus] adding securityContext for prometheus server containers

charts/prometheus/Chart.yaml, charts/prometheus/templates/alertmanager/sts.yaml
Signed-off-by: Alexis Guerville <alexis.guerville@messagebird.com>
Add missing extraArgs for alertmanager configmapReloader on the statefulset.
=> [prometheus] Add missing extraArgs for alertmanager configmapreloader

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/deploy.yaml
PR fixes indentation on securityConext on container level for prometheus
- fixes #1990 
[@gianrubio](https://github.com/gianrubio) [@zanhsieh](https://github.com/zanhsieh) [@Xtigyro](https://github.com/Xtigyro) [@naseemkullah](https://github.com/naseemkullah) - Please review this PR and let me know if any change is required.
=> [prometheus] fixing indentation securityContext for prometheus server containers 

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-burnrate.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-histogram.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml, charts/kube-prometheus-stack/values.yaml
* Sync dashboards
* Sync charts
* Sync crds
* Sync prometheus rules
* Bump prometheus to 2.35.0
=> [kube-prometheus-stack] Bump to prometheus-operator 0.56.0

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/serviceaccount.yaml
fixes #2011
Signed-off-by: Jason Tarasovic <jason@tarasovic.com>
- fixes #2011
=> [prometheus-adapter] fix serviceaccount annotations

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml
Signed-off-by: rmartinez3 <rmarti619@gmail.com>
This adds to chart rbac role that prometheus operator needs to update  prometheuses/status
- fixes #2010
=> kube-prometheus-stack adding cluster role for  prometheus-operator  prometheuses/status

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/values.yaml
Signed-off-by: secustor <sebastian@poxhofer.at>
This PR updates the default image to 0.10.1 which fixes broken log levels
- fixes #
=> [prometheus-postgres-exporter] update image to 0.10.1

charts/alertmanager/Chart.yaml
- fixes # https://github.com/prometheus-community/helm-charts/issues/2027
=> [allertmanager] trigger alertmanager build

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml, charts/prometheus-blackbox-exporter/values.yaml
Adds `additionalRelabeling` to ServiceMonitor so that custom relabeling
can be done. I wanted this because I wanted to be able to add the module
as a label but I think there are other good reasons to have it.
While I was here I added `quote` for `additionalMetricsRelabels` so that
values wouldn't be converted.
Please make note of the fact I did a concat instead of replacing default values. I think this is more productive but it works differently than `additionalMetricsRelabels`. Let me know if you want me to change one or the other so they work the same. Wanted to avoid a major bump if I could.
@desaintmartin 
Signed-off-by: Evan Pitstick <epitstick@paloaltonetworks.com>
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets …
=> [prometheus-blackbox-exporter] Add custom relabeling and quote values

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: Cristian Chiru <cristian.chiru@revomatico.com>
Bump Grafana chart that fixes (among other bugs) hardcoded path for dashboardownloader (https://github.com/grafana/helm-charts/pull/1291)
=> [kube-prometheus-stack] Upgrade Grafana chart to 6.29

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/extra-manifests.yaml, charts/prometheus/values.yaml
Signed-off-by: Kent Iso <kentaiso@google.com>
When we want to deploy current chart with custom resources(e.g. [ManagedCertificate](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs), [SecretProviderClass](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage.html)), we don't have any ways to deploy these with this chart.
By this PR, we can offer the way to deploy the extra manifests.
- fixes #2009
=> [prometheus] Add extra manifest template

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/services.yaml, charts/alertmanager/templates/statefulset.yaml, charts/alertmanager/values.yaml
Signed-off-by: Nolwenn Cauchois <nolwenn.cauchois@orange.com>
=> [alertmanager] Add support change cluster port

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
```
Error: INSTALLATION FAILED: Service "prometheus-node-exporter" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for LoadBalancer services
```
- fixes #
=> [prometheus] Fix clusterType for service node-exporter of prometheus

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/statefulset.yaml
Signed-off-by: Joseph Ziegler <joseph@josephziegler.com>
We need this to support IPv6 for AlertManager. This was added to the prometheus chart: https://github.com/prometheus-community/helm-charts/pull/528/files but not the AlertManager chart to support this functionality.
- fixes #
=> [AlertManager] Allow IPv6 support for main AlertManager StatefulSet

charts/prometheus-nats-exporter/Chart.yaml
New version of prometheus-nats-exporter was released
- fixes #
=> [prometheus-nats-exporter] feat: prometheus-nats-exporter version 0.9.3

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
This updates the default tag for the Cloudwatch exporter from v0.12.2 to v0.14.0. This is particularly important because v0.13.3 fixed CVE-2022-21449, the "psychic signatures" vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-21449
- Tag diff: https://github.com/prometheus/cloudwatch_exporter/compare/v0.12.2...v0.14.0
- Fix for psychic signatures vulnerability: https://github.com/prometheus/cloudwatch_exporter/issues/415
n/a
=> [prometheus-cloudwatch-exporter] Update default image tag for Cloudwatch exporter chart

charts/prometheus-mysql-exporter/Chart.yaml, charts/prometheus-mysql-exporter/README.md, charts/prometheus-mysql-exporter/templates/deployment.yaml, charts/prometheus-mysql-exporter/values.yaml
- feat(mysql_exporter): add logLevel and logFormat options
- feat(mysql_exporter): bump chart to 1.8.0
Hey :wave:
Here is a small contribution that will allow to override the logs options of the mysql exporter especally
to change the logs level (info, warn, err) and the logs format (json).
Thanks for the review :wink:
- fixes #
=> [prometheus-mysql-exporter] add logLevel and logFormat options

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: sunlintong <sunlintongshuai@gmail.com>
The comment under `alertmanagerConfiguration`, `name: global-alertmanager-Configuration` should not be a map.
ref. https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#alertmanagerconfiguration
=> [kube-prometheus-stack] Fix alertmanagerConfiguration comment

charts/prometheus-mongodb-exporter/Chart.yaml, charts/prometheus-mongodb-exporter/README.md, charts/prometheus-mongodb-exporter/templates/deployment.yaml, charts/prometheus-mongodb-exporter/values.yaml
Signed-off-by: Bilovus, Ihor <ihor.bilovus@outlook.com>
In order to add additional labels to pod one can provide podLabels
=> [prometheus-mongodb-exporter] - Added podLabels

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/values.yaml
Bumps to kube-state-metrics v2.5.0 and uses different registry domain as k8s.gcr.io will be deprecated.
- fixes #
=> [kube-stat-metrics] Version bump to 2.5.0

charts/prometheus-json-exporter/Chart.yaml, charts/prometheus-json-exporter/templates/deployment.yaml, charts/prometheus-json-exporter/values.yaml
Signed-off-by: Gennadiy Nerubayev <gennadiy.nerubayev@schrodinger.com>
Adds functionality to be able to add custom labels to the pod via values.yaml, similar to how kube-prometheus-stack does it.
N/A
Mentions: @schmiddim @zanhsieh
=> [prometheus-json-exporter] Allow specifying additional pod labels

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml, charts/kube-state-metrics/values.yaml
Signed-off-by: kostas <kostavro@gmail.com>
This PRs allows full configuration of the kube-state-metrics, whereas up until now one could only set `runAsGroup`, `runAsUser`, and `fsGroup` properties.
- fixes #
=> [kube-state-metrics] Allow complete pod securityContext to kube-state-metrics deploy chart

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: TheRealNoob <TheRealNoob@users.noreply.github.com>
Fix indentation
[Relevant CRD line](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml#L4207)
- none
Only changing a commented line so not bumping chart version
=> [kube-prometheus-stack] fix typo

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml, charts/kube-prometheus-stack/values.yaml
- fixes #2101
Currently, I don't know how the crd's get upgraded/changed.
=> [kube-prometheus-stack] Version bump to 0.57.0

charts/prometheus/Chart.yaml, charts/prometheus/templates/alertmanager/cm.yaml, charts/prometheus/templates/server/cm.yaml
=> [prometheus] fix cve-2021-25742

charts/prometheus-json-exporter/Chart.yaml, charts/prometheus-json-exporter/templates/configmap.yaml
=> [prometheus-json-exporter] fix cve-2021-25742

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/configmap.yaml
=> [prometheus-postgres-exporter] fix cve-2021-25742

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md
Signed-off-by: Roberto Giovanardi <rob.giovanardi@gmail.com>
Fixes a broken link (404) on the dock
- fixes #
=> kube-prometheus-stack fix: fixed remote link to prometheus-operator doc

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml, charts/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml
Signed-off-by: Baptiste Roux <baptiste.roux@skale-5.com>
Use policy/v1 API version when available, fallback on policy/v1beta1
- fixes #2200
=> [prometheus-blackbox-exporter] Use pdb/psp apiVersion policy/v1 if available

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/README.md, charts/prometheus-redis-exporter/templates/_helpers.tpl, charts/prometheus-redis-exporter/templates/deployment.yaml, charts/prometheus-redis-exporter/templates/service.yaml, charts/prometheus-redis-exporter/templates/servicemonitor.yaml, charts/prometheus-redis-exporter/values.yaml
=> [prometheus-redis-exporter] support multiple targets

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/servicemonitorThanosSidecar.yaml
Signed-off-by: Zadkiel Aharonian <zadkiel_aharonian@carrefour.com>
Renames the sidecar thanos ServiceMonitor from `{fullname}-thanos-discovery` to `{fullname}-thanos-sidecar`.
This would make the official Thanos Sidecar grafana dashboard work out of the box with this implementation. See https://github.com/thanos-io/thanos/blob/v0.25.2/examples/dashboards/sidecar.json#L1462. 
- fixes #
=> [kube-prometheus-stack] fix: rename thanos sidecar servicemonitor

charts/prometheus/Chart.yaml, charts/prometheus/templates/alertmanager/deploy.yaml, charts/prometheus/templates/alertmanager/sts.yaml, charts/prometheus/templates/server/deploy.yaml, charts/prometheus/templates/server/sts.yaml
Signed-off-by: Suleyman Kutlu <suleyman.kutlu@actian.com>
Helm Chart processes `probeHeaders` values properly for liveness and readiness probes for Server and AlertManager deployments.. 
If statefulSet is enabled, same values are not handled at all.
- fixes #2205 
- [ x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
=> [prometheus] add http headers for probes in statefulset

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/servicemonitorThanosSidecar.yaml
Signed-off-by: Zadkiel Aharonian <hello@zadkiel.fr>
Fix a bug I introduced with #2216 which prevents the Thanos Sidecar ServiceMonitor from reaching the Thanos Sidecar service.
- fixes https://github.com/prometheus-community/helm-charts/pull/2216#issuecomment-1176262339
=> [kube-prometheus-stack] fix the thanos discovery servicemonitor selector

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
@andrewgkew 
@bismarck
@desaintmartin 
- fixes #2254
=> [kube-prometheus-stack] fixes #2254 

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack-operator] adds deployment annotations for prometheus operator

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
After PR #2237 there are similar issue to #2254
=> [kube-prometheus-stack] Fix field evolution error

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
PR updates the following dependencies so we can use the latest features without needing to override the image versions in the chart values:
- Prometheus: `v2.34.0` to `v2.36.2`
- AlertManager: `v0.23.0` to `v0.24.0`
- NodeExporter: `v1.3.0` to `v1.3.1`
- PushGateway: `v1.4.2` to `v1.4.3`
The subchart for KubeStateMetrics has also been upgraded from `v4.7.*` to `v4.13.*` which is an upgrade from app version `v2.4.1` to `v2.5.0`.
There are no major version changes or known breaking changes across the applications and I've deployed this into my test environments with no issues.
Chart version has been patch upgraded to `v15.10.4` due to no configuration changes in the chart and no known changes required.
Mentioning code maintainers:
@gianrubio @zanhsieh @Xtigyro @naseemkullah
Thanks!
=> [prometheus] Update applications to latest versions

.github/CODEOWNERS, charts/prom-label-proxy/.helmignore, charts/prom-label-proxy/Chart.yaml, charts/prom-label-proxy/README.md, charts/prom-label-proxy/templates/_helpers.tpl, charts/prom-label-proxy/templates/deployment.yaml, charts/prom-label-proxy/templates/ingress.yaml, charts/prom-label-proxy/templates/service.yaml, charts/prom-label-proxy/templates/serviceaccount.yaml, charts/prom-label-proxy/values.yaml
Helm chart for https://github.com/prometheus-community/prom-label-proxy
None
If chart needs a maintainer, I can take ownership of this.
I tried to follow https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md, but there is no process for new charts.
=> [prom-label-proxy] setup chart

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml, charts/kube-prometheus-stack/values.yaml
This PR adds support for `labels` on spec for thanos-ruler template
N/A
=> [kube-prometheus-stack]: add labels spec for thanos-ruler

.github/CODEOWNERS, charts/prometheus-node-exporter/Chart.yaml
=> [prometheus-node-exporter] Removing me as maintainer

charts/prometheus-stackdriver-exporter/Chart.yaml, charts/prometheus-stackdriver-exporter/templates/deployment.yaml, charts/prometheus-stackdriver-exporter/values.yaml
Signed-off-by: Nam Hai Nguyen <namhai.nguyen-ext@commercetools.com>
Add Monitoring filters to the Helm chart after this feature is supported in https://github.com/prometheus-community/stackdriver_exporter/pull/133
- fixes #
=> [prometheus-stackdriver-exporter] Add monitoring filters

charts/prometheus/Chart.yaml, charts/prometheus/templates/alertmanager/pvc.yaml, charts/prometheus/templates/pushgateway/pvc.yaml, charts/prometheus/templates/server/pvc.yaml, charts/prometheus/values.yaml
Signed-off-by: Joffrey JANIEC <16088893+jjaniec@users.noreply.github.com>
Allow specifying volumeName to PVCs deployed by the prometheus chart
- fixes #
=> [prometheus] Add support for pvc.spec.volumeName

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: Stevo Slavić <stevo.slavic@form3.tech>
Updates grafana chart dependency for security vulnerability fixes, see https://grafana.com/blog/2022/07/14/grafana-v9-0-3-8-5-9-8-4-10-and-8-3-10-released-with-high-severity-security-fix/ and https://github.com/grafana/helm-charts/pull/1606
- fixes #
=> [kube-prometheus-stack]: bump grafana version

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/alertmanager-overview.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes-darwin.yaml, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.rules.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml, charts/kube-prometheus-stack/values.yaml
* update prometheus operator to v0.58.0
* update all docker images
* update all dependency charts
- fixes https://github.com/prometheus-community/helm-charts/pull/2154/
=> [kube-prometheus-stack] update prometheus operator to v0.58.0

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/_helpers.tpl
I faced this issue
`Error: parse error at (kube-prometheus-stack/templates/_helpers.tpl:86): unclosed action`
Signed-off-by: Letfdsada <Letfdsada@users.noreply.github.com>
=> [kube-prometheus-stack] fix new lines in _helpers

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: gadisn <gadisn@gmail.com>
Bump dependency version of kube-prometheus-stack chart.
kube-state-metrics: 4.15.0
- fixes #
This PR allows to use new features provided by KSM.
=> [kube-prometheus-stack]: Bump KSM version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Fausto David Suarez Rosario <faustodavid@hotmail.com>
Add exemplars related settings. This PR enables the following feature released on **prometheus-operator** version **0.58.0**.
https://github.com/prometheus-operator/prometheus-operator/pull/4834
=> [kube-prometheus-stack] Add exemplars related settings

charts/prometheus-conntrack-stats-exporter/Chart.yaml
* update docker image
- fixes #
=> [prometheus-conntrack-stats-exporter] update docker image

charts/prometheus-conntrack-stats-exporter/Chart.yaml, charts/prometheus-conntrack-stats-exporter/values.yaml
* fix conntrack stats exporter image
- fixes #
=> [proemtehusd-conntrack-stats-exporter] fix conntrack stats exporter image

charts/prometheus-mysql-exporter/Chart.yaml, charts/prometheus-mysql-exporter/templates/deployment.yaml, charts/prometheus-mysql-exporter/values.yaml
This PR adds the option to add the parameter `-ip-address-types` for the cloudsqlproxy deployment. The default value of this parameter is `PUBLIC,PRIVATE`. With this option you can change it to what you prefer, in our case we would prefer to use `PRIVATE,PUBLIC`.
No issue
=> [prometheus-mysql-exporter] Add option for ipAddressTypes

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/sts.yaml, charts/prometheus/values.yaml
Signed-off-by: Canh Ngo <canhnt@gmail.com>
In our multi-tenant K8s clusters , the in-house admission controllers require custom labels must be added to PVCs.
No
=> [prometheus] Allowed to add custom labels to Statefulset volume template

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/hack/README.md, charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py, charts/kube-prometheus-stack/hack/sync_prometheus_rules.py, charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml, charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml
This is needed as the source of truth fro etcd alerts and dashboards
is no longer maintained in https://github.com/etcd-io/website. See
https://github.com/etcd-io/etcd/blob/main/contrib/mixin/mixin.libsonnet
Signed-off-by: Sergei Kuzmin <sergeikuzmin@gmail.com>
- fixes #
=> [kube-prometheus-stack] Support for import from jsonnet mixin for etcd

charts/prometheus-json-exporter/Chart.yaml, charts/prometheus-json-exporter/templates/deployment.yaml, charts/prometheus-json-exporter/values.yaml
Signed-off-by: Felix <mail@freichert.de>
This allows to mount arbitrary volumes. 
This is needed for including password files for basic auth, that are deployed with e.g. sealed-secrets.
The `additionalVolume` and `additionalVolumeMounts` Values were added.
_none_
_none_
=> [prometheus-json-exporter] feat: Implement mounting of additional volumes.

.github/CODEOWNERS, charts/prometheus-fastly-exporter/.helmignore, charts/prometheus-fastly-exporter/Chart.yaml, charts/prometheus-fastly-exporter/README.md, charts/prometheus-fastly-exporter/templates/NOTES.txt, charts/prometheus-fastly-exporter/templates/_helpers.tpl, charts/prometheus-fastly-exporter/templates/deployment.yaml, charts/prometheus-fastly-exporter/templates/podsecuritypolicy.yaml, charts/prometheus-fastly-exporter/templates/role.yaml, charts/prometheus-fastly-exporter/templates/rolebinding.yaml, charts/prometheus-fastly-exporter/templates/secret.yaml, charts/prometheus-fastly-exporter/templates/service.yaml, charts/prometheus-fastly-exporter/templates/serviceaccount.yaml, charts/prometheus-fastly-exporter/templates/servicemonitor.yaml, charts/prometheus-fastly-exporter/values.yaml
Added new exporter for https://fastly.com service
https://github.com/fastly/fastly-exporter
=> [prometheus-fastly-exporter] Add fastly exporter

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Stevo Slavić <stevo.slavic@form3.tech>
To support configuring in kube-prometheus-stack Helm chart a prometheus-operator feature flag added via https://github.com/prometheus-operator/prometheus-operator/pull/4455
- fixes #
=> [kube-prometheus-stack]: add alertmanager-config-namespaces for prometheus-operator support

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/README.md, charts/prometheus-blackbox-exporter/ci/icmp-values.yaml, charts/prometheus-blackbox-exporter/templates/deployment.yaml, charts/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml, charts/prometheus-blackbox-exporter/values.yaml
Signed-off-by: Daniel Maganto <daniel.maganto@allianzdirect.es>
Drop all capabilities in case it is not needed to reduce the surface attack 
N/A
- fixes #
=> [prometheus-blackbox-exporter] Drop all capabilities in case that it is not needed

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/values.yaml
Signed-off-by: Dan Peric <dperic@axon.com>
This PR will bump the prometheus adapter helm chart to the latest version of the prometheus adapter [v0.10.0](https://github.com/kubernetes-sigs/prometheus-adapter/releases/tag/v0.10.0)
- fixes #
=> [prometheus-adapter] Update To v0.10.0

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Zadkiel Aharonian <hello@zadkiel.fr>
Add the `thanosRuler.thanosRulerSpec.alertmanagersConfig` field to the templates
Add `thanosRuler.thanosRulerSpec.alertmanagersUrl` and `thanosRuler.thanosRulerSpec.alertmanagersConfig` to the values file.
- fixes #2243
=> [kube-prometheus-stack] add thanosRulerSpec.alertmanagersConfig config

charts/kube-prometheus-stack/Chart.yaml
=> [kube-prometheus-stack] fix release

charts/prometheus-smartctl-exporter/Chart.yaml, charts/prometheus-smartctl-exporter/templates/servicemonitor.yaml, charts/prometheus-smartctl-exporter/values.yaml
The official image isn't released yet. Point at a usable image in the mean time.
=> [prometheus-smartctl-exporter] Fix smartctl image

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml, charts/kube-prometheus-stack/values.yaml
Add `.thanosRuler.thanosRulerSpec.evaluationInterval ` to thanos ruler templates.
- fixes #
=> [kube-prometheus-stack] Add evaluationInterval to Thanos Ruler

charts/prometheus-nats-exporter/Chart.yaml
New version of prometheus-nats-exporter was released
- fixes #
=> [prometheus-nats-exporter] feat: bump nats-exporter version

charts/prometheus-json-exporter/Chart.yaml, charts/prometheus-json-exporter/templates/service.yaml, charts/prometheus-json-exporter/values.yaml
Signed-off-by: gaoxiang <gao_xiang@126.com>
open service configuration
=> [prometheus-json-exporter] open service configuration

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/deployment.yaml, charts/prometheus-postgres-exporter/templates/secrets.yaml, charts/prometheus-postgres-exporter/values.yaml
Signed-off-by: Anthony TREUILLIER <anthony.treuillier@gmail.com>
- fixes #
=> [prometheus-postgres-exporter] DATA_SOURCE_PASS_FILE support

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
Support for sensible defaults in downstream charts.
=> [kube-prometheus-stack]  Add support for templating in excludedFromEnforcement parameter

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/statefulset.yaml
Signed-off-by: Till Wiese <1872304+m3adow@users.noreply.github.com>
This PR fixes the implementation of Pod affinity rules for alertmanager which was broken with Commit 61812c8.
=> [alertmanager] Fix wrong values being dumped for affinity rules

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
[prometheus-cloudwatch-exporter] Update image tag v0.14.3 to v0.15.0
Signed-off-by: Matt Sladen <matt5188@gmail.com>
Updates Cloudwatch Exporter from 0.14.3 to 0.15.0. See [change log](https://github.com/prometheus/cloudwatch_exporter/releases/tag/v0.15.0)
N/A
=> [prometheus-cloudwatch-exporter] Update image tag v0.14.3 to v0.15.0

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Fix port for metric etcd
https://github.com/kubernetes/kubernetes/blob/dafa55be106730eaacb740e20b999b84848c6ac5/cmd/kubeadm/app/constants/constants.go#L95-L96
=> [kube-prometheus-stack] Update port for metric of etcd

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
Signed-off-by: Nick Hudson <nick.hudson@gmail.com>
Adds the `tpl` function around the `storageSpec` configuration in prometheus templates and `storage` configuration in the alertmanager templates.
=> [kube-prometheus-stack] Add template to storage configurations

charts/prometheus-conntrack-stats-exporter/Chart.yaml
* update image to v0.4.4
- fixes #
=> [conntrack-stats-exporter] update image to v0.4.4

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml, charts/kube-state-metrics/values.yaml
…itional namespaces
Signed-off-by: birca <Allex21ro@yahoo.com>
Add option to merge .Release.Namespace and add additional namespaces
=> [kube-state-metrics] - Add option to merge namespaces

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/README.md, charts/prometheus-blackbox-exporter/templates/prometheusrule.yaml
=> [prometheus-blackbox-exporter] Fix rule rendering, #2450

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/sts.yaml, charts/prometheus/values.yaml
Signed-off-by: Wojciech <duxetlg@gmail.com>
Startup probe has been added to prometheus server Helm chart in PR #1404, but it only works for Deployment. This PR will enable it for StatefulSet too.
=> [prometheus] Add a startup probe to StatefulSet too

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
Add template option to namespaces flag
=> [kube-prometheus-stack] - Add template option to namespaces flag

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: Julien Francoz <julien@les-tilleuls.coop>
Update grafana dependency
=> [kube-prometheus-stack] helm dependency update

charts/prometheus-stackdriver-exporter/Chart.yaml, charts/prometheus-stackdriver-exporter/templates/deployment.yaml, charts/prometheus-stackdriver-exporter/values.yaml
Signed-off-by: Mitch McKenzie <mitch.mckenzie@outlook.com>
Currently, the chart only allows setting pod-level security context settings. This PR adds support for container-level security context settings.   Some organizations require certain security settings to be applied at both the pod and container levels in order to be compliant(e.g. Open Policy Agent / Gatekeeper).  
N/A
=> [prometheus-stackdriver-exporter] Adding support for container-level security context settings.

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/templates/deployment.yaml, charts/prometheus-redis-exporter/templates/podsecuritypolicy.yaml, charts/prometheus-redis-exporter/values.yaml
* update exporter to v1.44.0
* use appVersion in chart.yaml as image tag
- fixes https://github.com/prometheus-community/helm-charts/issues/2488
=> [prometehus-redis-exporter] update exporter to 1.44 & use appVersion as image tag

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/deployment.yaml
Ensure the namespaces list is unique
=> [kube-state-metrics] - Ensure namespaces uniqueness

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/_helpers.tpl
Fix typo for newly added topology spread constraints.
=> [prometheus-pushgateway] Fix topologySpreadConstraints

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Mohamed Chiheb <mohamed@giantswarm.io>
This PR:
- Add support to set custom labels in operator Deployment. (We need this in order to enable some alerting.)
- TBD
- fixes #
=> [kube-prometheus-stack] Add ability to add custom labels in the operator deployment

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/values.yaml
Fixes Helm warnings. Otherwise, one will see warnings like:
```
coalesce.go:220: warning: cannot overwrite table with non table for prometheus-pushgateway.extraVolumes (map[])
coalesce.go:220: warning: cannot overwrite table with non table for prometheus-pushgateway.extraVolumeMounts (map[])
```
- fixes #
=> [prometheus-pushgateway] extraVolumes and extraVolumeMounts should be empty arrays

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: birca <Allex21ro@yahoo.com>
BUMP kube-state-metrics helm version
=> [kube-prometheus-stack] BUMP ksm helm dep

charts/prometheus-statsd-exporter/Chart.yaml, charts/prometheus-statsd-exporter/templates/configmap.yaml, charts/prometheus-statsd-exporter/templates/deployment.yaml, charts/prometheus-statsd-exporter/values.yaml
Adds the ability to override the name of the key inside Statsd Mapping ConfigMap. It's quite useful when this ConfigMap has generated already with a different key name (i.e., with `.yaml` extension).
None
None
Signed-off-by: Dmytro Horkhover <gd.mail.89@gmail.com>
=> [prometheus-statsd-exporter] override key in mapping ConfigMap

charts/prometheus-conntrack-stats-exporter/Chart.yaml, charts/prometheus-conntrack-stats-exporter/templates/_helpers.tpl, charts/prometheus-conntrack-stats-exporter/values.yaml
=> [conntrack-stats-exporter] add commonlabels

charts/prometheus-conntrack-stats-exporter/Chart.yaml, charts/prometheus-conntrack-stats-exporter/templates/daemonset.yaml, charts/prometheus-conntrack-stats-exporter/values.yaml
=> [conntrack-stats-exporter] add podlabels

charts/prometheus-conntrack-stats-exporter/Chart.yaml, charts/prometheus-conntrack-stats-exporter/templates/daemonset.yaml
- fix livenessprobe (was same as readiness)
- fixes
=> [conntrack-stats-exporter] fix livenessprobe

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
- fixes # https://github.com/prometheus-community/helm-charts/issues/2545
=> [kube-prometheus-stack] fix versions

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
- fix sm (https://github.com/prometheus-community/helm-charts/pull/2540)
- fixes # https://github.com/prometheus-community/helm-charts/commit/bd46559a54b765b6489f8205b87db913ef3e51d5#commitcomment-86546702
=> [kube-pronetheus-stack] fix servicemonitor

charts/prometheus-conntrack-stats-exporter/Chart.yaml
=> [conntrack-stats-exporter] raise version to v0.4.6

charts/prometheus-mongodb-exporter/Chart.yaml, charts/prometheus-mongodb-exporter/README.md
Signed-off-by: OktarianTB <oktotb@gmail.com>
`ServiceMonitor` is disabled by default for `prometheus-mongodb-exporter` https://github.com/prometheus-community/helm-charts/blob/1a0c21e0be9e0d3d046a1a77293241371ada03e6/charts/prometheus-mongodb-exporter/values.yaml#L95
The README's configuration section hadn't been updated accordingly, so this PR aims to fix that. :)
N.A.
=> [prometheus-mongodb-exporter] Update ServiceMonitor documentation

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
Signed-off-by: Jörg Reinhold <joerg.reinhold@f-i-ts.de>
fixes issue #2498; avoids empty `relabelings:` value in serviceMonitor.yaml
- fixes #2498
=> [prometheus-blackbox-exporter]: fix invalid serviceMonitoring relabelings, see issue #2498

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/_helpers.tpl, charts/kube-prometheus-stack/templates/prometheus-operator/networkpolicy.yaml
https://github.com/prometheus-community/helm-charts/pull/2580/files#diff-85a3dc19698b0354069cf3f9c89eb4a790506d3dd6d9e1e1c38b9c4aa9795d1dR2 which adds `NetworkPolicy` references a missing template
- fixes #
=> kube-prometheus-stack: fix network policy api missing template

charts/prometheus-mysql-exporter/Chart.yaml, charts/prometheus-mysql-exporter/README.md
=> [prometheus-mysql-exporter] Fix typo in README.md

.github/CODEOWNERS, charts/kube-prometheus-stack/Chart.yaml
Remove desaintmartin from maintainers.
I though I would have more time contributing to the maintenance of this chart, unfortunately I am just ending up hiding the github notifications coming from this chart.
Still a heavy user of the chart so I'll continue to contribute, of course. And maybe I can come back (if) I have more time.
- fixes #
=> [kube-prometheus-stack] Remove desaintmartin from maintainers.

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml
Signed-off-by: Pavel Storozhenko <storozhenkopf@gmail.com>
1. Implement the same change as in #2581  for selfmonitor
2. Cleanup code from unneeded functions
=> [prometheus-blackbox-exporter] selfmonitor template refactor

charts/prometheus-kafka-exporter/Chart.yaml, charts/prometheus-kafka-exporter/templates/deployment.yaml, charts/prometheus-kafka-exporter/values.yaml
Signed-off-by: Zied ABID <zied.abid@jobteaser.com>
- Bump kafka-exporter to 1.6.0 acording to https://github.com/danielqsj/kafka_exporter/releases/tag/v1.6.0 along with new features
- extend container image `tag` to get either `values.yaml` `image.tag` value or `Chart.yaml` `appVersion` value as recommended by @monotek.
=> [prometheus-kafka-exporter] Bump kafka-exporter to 1.6.0

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: João Estrela <jestrela@barracuda.com>
Bump prometheus-node-exporter subchart version as it is now 4.4.*
Changes tested by diffing results with default values
=> [kube-prometheus-stack] Bump prometheus-node-exporter subchart version

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/servicemonitor.yaml
Signed-off-by: João Estrela <jestrela@barracuda.com>
This PR fixes not being able to use values such as:
```yaml
prometheus:
monitor:
enabled: true
selectorOverride:
myNewLabel: myNewLabelValue
myNewLabelTwo: myNewLabelValueTwo
```
=> [kube-state-metrics] ServiceMonitor selectorOverride fix

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/servicemonitor.yaml
Signed-off-by: David <davidcalvertfr@gmail.com>
removed unnecessary line introduced in #2610
=> [kube-state-metrics] removed unnecessary line introduced in #2610

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: João Estrela <jestrela@barracuda.com>
Bump version of kube-state-metrics as it was bumped recently
Changes tested by diffing results with default values
=> [kube-prometheus-stack] Bump kube-state-metrics subchart version

charts/prometheus-to-sd/Chart.yaml, charts/prometheus-to-sd/README.md
- Update Git repo README with instructions for both OCI registries and HTTP repos
- Deduplicate release charts status and link badge to the GH Action
- [prometheus-to-sd] Remove Helm 2 info from README
Simple readme update to check CI perms
=> [prometheus-to-sd] Remove Helm 2 info from README

charts/alertmanager/Chart.yaml, charts/alertmanager/values.yaml
It updates the alertmanager appVersion to the current release.
N/A
=> [alertmanager] update to current release

charts/prometheus/Chart.yaml
Signed-off-by: David <davidcalvertfr@gmail.com>
Updated kube-state-metrics dependency to 4.22.* because it hasn't been updated in a while.
This also may help with https://github.com/prometheus-community/helm-charts/issues/2517
- fixes #
=> [prometheus] uptaded kube-state-metrics dependency to 4.22.*

charts/prometheus-conntrack-stats-exporter/Chart.yaml
* update image to v0.4.7
- fixes #
=> update image to v0.4.7

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/service.yaml
Signed-off-by: Dominic Paul <dominic.paul.92+github@gmail.com>
When auto sharding is enabled for Kube stae metrics, the service is not created as headless. This change will take care of creating a headless service if auto sharding flag is true.
- fixes #2642
=> [kube-state-metrics] Make headless service for auto sharding

charts/kube-state-metrics/Chart.yaml
Signed-off-by: David Calvert <david@0xdc.me>
Just updating kube-state-metrics with my new default GitHub email address. 
This could also be a good way to check the issue with the GitHub workflow described in #2658.
- fixes #2658
=> [kube-state-metrics] updated maintainer email and check github workflow

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/custom-metrics-apiservice.yaml, charts/prometheus-adapter/templates/external-metrics-apiservice.yaml, charts/prometheus-adapter/templates/resource-metrics-apiservice.yaml
Prevent helm diff on apply of the chart when certManager or TLS is enabled
The default value for insecureSkipTLSVerify attribute is false.
This is an issue when using tools like [ArgoCD](https://argo-cd.readthedocs.io/en/stable/)
=> [prometheus-adapter] Prevent helm diff on insecureSkipTLSVerify 

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/templates/deployment.yaml, charts/prometheus-redis-exporter/values.yaml
This PR enables exporter tls config using secrets to mount certs and keys on the filesystem.
No issue
=> [prometheus-redis-exporter] Support tls config

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/service.yaml, charts/kube-state-metrics/values.yaml
Add `loadBalancerSourceRanges` to `kube-state-metrics` Helm chart. Inspired by [pull/2502](https://github.com/prometheus-community/helm-charts/pull/2502).
- fixes #
=> [kube-state-metrics] add service load balancer IP ranges

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/_helpers.tpl, charts/prometheus-node-exporter/templates/daemonset.yaml, charts/prometheus-node-exporter/templates/endpoints.yaml, charts/prometheus-node-exporter/templates/psp-clusterrole.yaml, charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml, charts/prometheus-node-exporter/templates/psp.yaml, charts/prometheus-node-exporter/templates/service.yaml, charts/prometheus-node-exporter/templates/serviceaccount.yaml, charts/prometheus-node-exporter/templates/servicemonitor.yaml, charts/prometheus-node-exporter/templates/verticalpodautoscaler.yaml
Refactor 
- From `{{- if .Values.foo }}` to `{{- with }}` and using the context under it
- Get rid of `{{- if .Values.foo }}` when it combines with `{{ range $key, $value := .Value.foo }}`
- Proper indention
=> [prometheus-node-exporter] Refactor

.github/workflows/release.yaml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Based on the comment in [here](https://github.com/prometheus-community/helm-charts/pull/2631). 
it'd be better to sign images with its digests 
- fixes #
=> [ALL CHARTS] signing an image with digest instead of tag

charts/prometheus-to-sd/Chart.yaml
Test #2664 by bumping the least recently updated chart again.
=> Bump chart to test CI

.github/workflows/release.yaml
* update chart releaser dependencies (adds bitnami repo)
- fixes # https://github.com/prometheus-community/helm-charts/actions/runs/3472208448/jobs/5802727827
=> update chart releaser dependencies

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml, charts/kube-prometheus-stack/values.yaml
Enable "hostNetwork" support for "Prometheus" CR Object
Released in [v0.60.0](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.60.0)
Added at [feat : enable support for "hostNetwork" in Prometheus CRD](https://github.com/prometheus-operator/prometheus-operator/pull/5010)
- fixes #2689 
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
=> [kube-prometheus-stack] : enable "hostNetwork" support for "Prometheus" CR Object

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml, charts/kube-prometheus-stack/values.yaml
This PR add support for placing additional custom labels on the ServiceMonitor resource created for the Prometheus operator deployment.
=> [kube-prometheus-stack] add support for additional labels on operator's ServiceMonitor

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/daemonset.yaml, charts/prometheus-node-exporter/values.yaml
This PR adds a possibility of setting annotations on the node exporter daemonset via value `daemonsetAnnotations`.
- fixes #2632
=> [prometheus-node-exporter] Add daemonset annotations

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
Signed-off-by: QuentinBisson <quentin@giantswarm.io>
This PR fixes PSP deprecation after k8s 1.25+ added for the prometheus operator patch jobs.
=> [kube-prometheus-stack] Fix PSP deprecation after k8s 1.25+

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/ingress.yaml, charts/prometheus-pushgateway/values.yaml
Align with PR#17979
See:
https://github.com/prometheus-community/helm-charts/commit/6bbf14b54bde1217a8e47c32b4ba1afdd17b1ed7
=> [prometheus-pushgateway] Support ingress.extraPaths

charts/prometheus/Chart.yaml, charts/prometheus/README.md
When the Prometheus Pushgateway was moved to a subchart in #2714, the list of subcharts in the README wasn't updated to include it.
Signed-off-by: Tom Walker <walker.thomas.p@gmail.com>
Updates the documentation for the prometheus Chart to mention the Pushgateway being installed as a subchart.
Thanks!
=> [prometheus] Update 'prometheus' README to mention prometheus-pushgateway

charts/prometheus/Chart.yaml, charts/prometheus/README.md
Signed-off-by: Tom Walker <walker.thomas.p@gmail.com>
Fixes incorrect URL used for Node Exporter in list of dependencies. Also fixes bad formatting from my previous PR #2725 (apologies).
- fixes #
=> [prometheus] Fix Node Exporter URL in README

.github/CODEOWNERS, charts/kube-prometheus-stack/Chart.yaml
As I have been contributing to the chart more lately, I would like to be able to be a maintainer to help the chart forward :)
- fixes #
- [x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
=> [kube-prometheus-stack] Add myself as kube-prometheus-stack maintainer

charts/jiralert/Chart.yaml, charts/jiralert/templates/servicemonitor.yaml, charts/jiralert/values.yaml
Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>
Add serviceMonitor to jiralert to scrape metrics
=> [jiralert] Add ServiceMonitor

charts/prometheus-mysql-exporter/Chart.yaml, charts/prometheus-mysql-exporter/templates/deployment.yaml, charts/prometheus-mysql-exporter/values.yaml
Allow additional volumes to be added, can be used with any CSI Secret Store to populate the secrets in the pod's environment, for example [Vault CSI Provider](https://developer.hashicorp.com/vault/docs/platform/k8s/csi/examples#environment-variable-dynamic-database-credentials) which requires to specify additional volumes to make it work.
- fixes #
=> [prometheus-mysql-exporter] add extraVolumes and extraVolumeMounts to chart

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/cm.yaml
After last refactoring. I notice that prometheus cannot find the alertmanager.
Chart version: prometheus-18.2.0
- fixes #
=> [prometheus] fix alertmanager discovery

charts/prometheus/Chart.yaml, charts/prometheus/templates/server/cm.yaml
Signed-off-by: Jose M. Palomar <jmpalomar@gmail.com>
Will fix prometheus discovery of alertmanager if someone overrides prometheus name or alertmanager name.
- fixes #2745
=> [prometheus] fix alertmanager discovery when overriding names

charts/prometheus-mysql-exporter/Chart.yaml, charts/prometheus-mysql-exporter/templates/deployment.yaml
Signed-off-by: Vadim Grek <vadimprog@gmail.com>
Fixes a following error: 
```
Error: template: prometheus-mysql-exporter/templates/deployment.yaml:138:17: executing "prometheus-mysql-exporter/templates/deployment.yaml" at <.Values.extraVolumes>: can't evaluate field Values in type []interface {}
```
when  `extraVolumes` is set
- fixes #
=> [prometheus-mysql-exporter] fix error in extraVolumes

charts/jiralert/Chart.yaml, charts/jiralert/templates/deployment.yaml, charts/jiralert/values.yaml
Annotations on deployment level should be configurable. 
- fixes #
=> [jiralert] Add annotations for deployment and remove annotation config hash if existingSecret

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/_helpers.tpl, charts/prometheus-pushgateway/templates/ingress.yaml
This PR supersedes PR #2777 since it fixes ingress, netpol, and pdb at once.
=> [prometheus-pushgateway] Hotfix new line problem

charts/prometheus/Chart.yaml
- Update Chart.yaml
-  kubeVersion
- keywords
- annotations: "artifacthub.io/links"
None.
- see
- https://helm.sh/docs/topics/charts/#the-chartyaml-file
- https://artifacthub.io/docs/topics/annotations/helm/
=> [prometheus] Update Chart.yaml - add kubeVersion, keywords, annotation-links

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
Signed-off-by: Christof Huber <christof-huber@gmx.de>
Bumps the Grafana helm chart version to enable better dahsboard provisioning/reloading of provisioning (https://github.com/grafana/helm-charts/pull/2062)
=> [kube-prometheus-stack] Update grafana chart version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>
Prometheus in agent mode does not allow rule_files inside the config. The Prometheus Operator omits rule_files, if the value is nil inside the CR. https://github.com/prometheus-operator/prometheus-operator/pull/4417
- rel #2506
=> [kube-prometheus-stack] Remove ruleNamespaceSelector and ruleSelector from CRD, if enableFeatures contains agent

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/configmap.yaml, charts/prometheus-postgres-exporter/templates/deployment.yaml, charts/prometheus-postgres-exporter/values.yaml
* Use list instead of map. Allow for valueFrom, other flexibility
* Check type for backwards compatibility
* Fix configmap multi-line
@gianrubio @zanhsieh 
The chart would not pass templating for me without the `configmap.yaml` change
=> [prometheus-postgres-exporter] Refactor extra envs

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/deployment.yaml, charts/prometheus-adapter/values.yaml
This PR adds support for setting environment variables loaded from a secret or a config map.
- fixes #2842
=> [prometheus-adapter] Support environment variables (#2842)

.github/workflows/lint-test.yaml
* disable helm unit test
Installing the oplugin constantly fails:
```
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/tags/v0.2.8
No download_url found only searching for linux
Downloading  to location /tmp/_dist/
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
Error: Process completed with exit code 1.
```
example: https://github.com/prometheus-community/helm-charts/actions/runs/3768106477/jobs/6406304277
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR …
=> disable helm unit test

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/deployment.yaml, charts/prometheus-postgres-exporter/values.yaml
This PR fixes indentation at the container's securityContext. At the same time, it changes the templating of securityContext similar to that of podSecurityContext. 
- fixes #2840
=> [postgres-exporter] Fix indentation at securityContext (#2840)

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/deployment.yaml
This PR corrects wrongly placed container's securityContext applied previously through PR #2850.
- fixes #2840
=> [postgres-exporter] Correct placement of securityContext

charts/alertmanager/Chart.yaml, charts/alertmanager/README.md
* remove helm2 infos
- fixes #
=> [alertmanager] cleanup readme

charts/prometheus-conntrack-stats-exporter/Chart.yaml
* update image to v0.4.10
- fixes #
=> [conntrack-stats-exporter] update image to v0.4.10

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/_helpers.tpl, charts/prometheus-blackbox-exporter/values.yaml
Update blackbox exporter to [0.23.0](https://github.com/prometheus/blackbox_exporter/releases/tag/v0.23.0) and add release label for kube-prometheus-stack out of the box experience.
- fixes #
=> [prometheus-blackbox-exporter] Update blackbox-exporter to 0.23.0

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/README.md, charts/prometheus-node-exporter/templates/_helpers.tpl, charts/prometheus-node-exporter/templates/podmonitor.yaml, charts/prometheus-node-exporter/values.yaml
This PR brings an option do define a podmonitor for Node Exporter pods.
- fixes #2861
=> [prometheus-node-exporter] Add a pod monitor (#2861)

charts/prometheus-rabbitmq-exporter/Chart.yaml, charts/prometheus-rabbitmq-exporter/templates/deployment.yaml, charts/prometheus-rabbitmq-exporter/values.yaml
Signed-off-by: Vitalii Ivanin <contact@vitalyivanin.com>
Add support of - `EXCLUDE_METRICS` https://github.com/kbudde/rabbitmq_exporter#settings, which is currently unsupported.
=> [prometheus-rabbitmq-exporter] Add support of EXCLUDE_METRICS

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: BobDu <i@bobdu.cc>
- fixes https://github.com/prometheus-community/helm-charts/pull/2615#issuecomment-1379866223
=> [kube-prometheus-stack] modify prometheusOperator.serviceMonitor.sampleLimit default value 0 (mean no limit)

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/statefulset.yaml, charts/alertmanager/values.yaml
Allows adding custom initContainers to alertmanager (similar to https://github.com/prometheus-community/helm-charts/pull/1124).
This could (for example) be used to `envsubst` certain values in the alertmanager configuration.
@monotek 
@naseemkullah 
N/A
=> [alertmanager] Allow to configure init containers

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/hack/update_crds.sh, charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml, charts/kube-prometheus-stack/values.yaml
I need this to avoid kube-prometheus-stack being OutOfSync in ArgoCD because of failurePolicy. Also, this could be a security issue, because the webhook is not enforced during upgrades.
NB: The default behavior is preserved
Related issue https://github.com/prometheus-community/helm-charts/issues/1041
None
=> [kube-prometheus-stack] More secure admissionWebhooks failurePolicy

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml, charts/kube-prometheus-stack/values.yaml
This PR adds an option to set host aliases in prometheus through the field `prometheus.prometheusSpec.hostAliases` as supported by [Prometheus operator](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.HostAlias). 
- fixes #2383
=> [kube-prometheus-stack] Add support for hostAliases in prometheus

charts/prometheus-conntrack-stats-exporter/Chart.yaml
=> [prometehus-conntrack-stats-exporter] update image to v0.4.11

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
As mentioned here https://github.com/kubernetes/registry.k8s.io#stability, migration should be done ASAP.
=> [kube-prometheus-stack] Registry change for upstream kube-webhook-certgen

.gitignore, charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/values.yaml
Signed-off-by: BobDu <i@bobdu.cc>
like #2924 
- fixes #
=> [prometheus-adapter] Registry change registry.k8s.io

charts/prometheus-operator-crds/Chart.yaml, charts/prometheus-operator-crds/templates/crd-alertmanagerconfigs.yaml, charts/prometheus-operator-crds/templates/crd-alertmanagers.yaml, charts/prometheus-operator-crds/templates/crd-podmonitors.yaml, charts/prometheus-operator-crds/templates/crd-probes.yaml, charts/prometheus-operator-crds/templates/crd-prometheuses.yaml, charts/prometheus-operator-crds/templates/crd-prometheusrules.yaml, charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml, charts/prometheus-operator-crds/templates/crd-thanosrulers.yaml
This PR updates Prometheus operator CRDs to the operator release 0.62.0.
- fixes #2921
=> [prometheus-operator-crds] Update to 0.62.0

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/deployment.yaml, charts/prometheus-postgres-exporter/values.yaml
Allow setup more parameters/flags for [Prometheus postgres exporter](https://github.com/prometheus-community/postgres_exporter#flags )
=> [prometheus-postgres-exporter] add parameters to helm

charts/prometheus/Chart.yaml, charts/prometheus/README.md
Signed-off-by: Ajay Kumar <akuma5157@gmail.com>
- fixes #
=> [prometheus] Fix typo in promethus in prometheus chart readme

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/deployment.yaml
=> [prometheus-postgres-exporter] fix flag format

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/templates/deployment.yaml
Signed-off-by: Wei Kin Huang <weikin.huang04@gmail.com>
Fixes an issue with using `with` and `customAnnotations` and `deploymentAnnotations`
=> [prometheus-adapter]: fix usage of with for deploymentAnnotations

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/_helpers.tpl, charts/prometheus-pushgateway/templates/deployment.yaml, charts/prometheus-pushgateway/templates/ingress.yaml, charts/prometheus-pushgateway/templates/networkpolicy.yaml, charts/prometheus-pushgateway/templates/pdb.yaml, charts/prometheus-pushgateway/templates/pushgateway-pvc.yaml, charts/prometheus-pushgateway/templates/service.yaml, charts/prometheus-pushgateway/templates/serviceaccount.yaml, charts/prometheus-pushgateway/templates/servicemonitor.yaml, charts/prometheus-pushgateway/templates/statefulset.yaml, charts/prometheus-pushgateway/values.yaml
This PR adds `namespace` on all resources along with a way to override it. By default, it'll return `.Release.Namespace` and keep the `monitoring` default on `ServiceMonitor`.
None
=> [prometheus-pushgateway] Add namespaceOverride to all resources

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
This PR is enabling unused ConfigReloader and Thanos `registry` from `values.yaml`. Otherwise they all are taking `registry` of Prometheus Operator itself in template.
- fixes #2823
=> [kube-prometheus-stack] Fix registry for Config Relaoder and Thanos

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/values.yaml
Correctly updates the blackbox-export App version to 0.23.0
PR https://github.com/prometheus-community/helm-charts/pull/2886 missed bumping the container version
=> [prometheus-blackbox-exporter] update the prom/blackbox-exporter image to version/tag 0.23.0

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/servicemonitor.yaml
Signed-off-by: Jan-Otto Kröpke <joe@cloudeteer.de>
Fix error
```
Error: template: prometheus-pushgateway/templates/servicemonitor.yaml:39:37: executing "prometheus-pushgateway/servicemonitor.yaml" at <.>: wrong type for value; expected chartutil.Values; got []interface {}
```
- fixes #
=> [prometheus-pushgateway] helm template error

charts/prometheus-stackdriver-exporter/Chart.yaml, charts/prometheus-stackdriver-exporter/templates/deployment.yaml, charts/prometheus-stackdriver-exporter/values.yaml
Signed-off-by: mmckenzie <mitch.mckenzie@outlook.com>
Adds support for new features in the v0.13.0 release. 
- Set the default app version to the latest 0.13.0 which was released on 1/25/2023
- Add support for new feature flags: monitoring.aggregate-deltas and monitoring.aggregate-deltas-ttl	
- Applicable stackdriver-exporter release: https://github.com/prometheus-community/stackdriver_exporter/releases/tag/v0.13.0
- Applicable Feature : https://github.com/prometheus-community/stackdriver_exporter/pull/168
N/A
N/A
=> [prometheus-stackdriver-exporter] Adding new params: aggregate-deltas and aggregate-deltas-ttl

charts/prometheus-nats-exporter/Chart.yaml, charts/prometheus-nats-exporter/templates/service.yaml, charts/prometheus-nats-exporter/templates/servicemonitor.yaml, charts/prometheus-nats-exporter/values.yaml
Adds features common in other charts:
- Labels for the Service
- TargetLabel for the ServiceMonitor
These two together allow adding additional labels on metrics.
N/A
=> [prometheus-nats-exporter] service labels and servicemonitor targetLabels

charts/prometheus-consul-exporter/Chart.yaml, charts/prometheus-consul-exporter/README.md
This PR increments Helm Chart `apiVersion` from v1 to v2. In addition, fields `annotations`, `sources` and `type` have been added. README file has been updated with respect to the change.
Although a breaking change, as the chart is currently a development release (aka 0.y.z) and considered thus unstable, the minor version number has been bumped.
- related to #764
=> [prometheus-consul-exporter] Increment Helm apiVersion

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/templates/deployment.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
=> [prometheus-cloudwatch-exporter]: upgrade to v0.15.1

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/README.md, charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml, charts/kube-prometheus-stack/crds/crd-podmonitors.yaml, charts/kube-prometheus-stack/crds/crd-probes.yaml, charts/kube-prometheus-stack/crds/crd-prometheuses.yaml, charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml, charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml, charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack] update to v0.63.0

charts/prometheus-operator-crds/Chart.yaml, charts/prometheus-operator-crds/README.md, charts/prometheus-operator-crds/templates/crd-alertmanagerconfigs.yaml, charts/prometheus-operator-crds/templates/crd-alertmanagers.yaml, charts/prometheus-operator-crds/templates/crd-podmonitors.yaml, charts/prometheus-operator-crds/templates/crd-probes.yaml, charts/prometheus-operator-crds/templates/crd-prometheuses.yaml, charts/prometheus-operator-crds/templates/crd-prometheusrules.yaml, charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml, charts/prometheus-operator-crds/templates/crd-thanosrulers.yaml
This PR updates Prometheus Operator CRDs to release 0.63.0. A README file has also been added.
None
=> [prometheus-operator-crds] Update to v0.63.0

charts/jiralert/Chart.yaml, charts/jiralert/templates/secret.yaml, charts/jiralert/values.yaml
Signed-off-by: Jan-Otto Kröpke <joe@cloudeteer.de>
Add explicit toggle for helm template engine.
Add value as alternative to config for complex templating situations
- fixes #
=> [jiralert] Make tplConfig toggable and introduce a value for complex configurations

charts/prometheus-cloudwatch-exporter/Chart.yaml, charts/prometheus-cloudwatch-exporter/templates/deployment.yaml, charts/prometheus-cloudwatch-exporter/values.yaml
This PR adds support for attaching labels and annotations to the deployment resource.
- fixes #2995
=> [prometheus-cloudwatch-exporter] Add labels to deployment resource

charts/prometheus/Chart.yaml, charts/prometheus/README.md, charts/prometheus/values.schema.json, charts/prometheus/values.yaml
Signed-off-by: Ostosh, Ivy <ivyjin@amazon.com>
This PR adds a json validation step to validate the input of `values.yaml` at helm chart installation. The json validation file is generated by helm plugin [helm-schema-gen](https://github.com/karuppiah7890/helm-schema-gen). A few default values in `values.yaml` are modified to reflect the most accurate type of each field.
- N/A
=> [prometheus] Add values.schema.json file

charts/kube-state-metrics/Chart.yaml
Bumps version to https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.8.0
- fixes #
=> [kube-state-metrics] Version bump to 2.8.0

charts/prometheus-pushgateway/Chart.yaml, charts/prometheus-pushgateway/templates/service.yaml
This PR fixes a spelling mistake in the service template.
- fixes #2998
=> [prometheus-pushgateway] Correct spelling mistake

charts/prometheus/Chart.lock, charts/prometheus/Chart.yaml
The main chart is using an outdated version of the kube-state-metrics dependency
=> [prometheus] update kube-state-metrics deps version

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/secret.yaml, charts/kube-prometheus-stack/values.yaml
Signed-off-by: Jan-Otto Kröpke <joe@cloudeteer.de>
- fixes #2950
=> [kube-prometheus-stack] Add alertmanager.stringConfig

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/templates/deployment.yaml, charts/prometheus-snmp-exporter/templates/servicemonitor.yaml, charts/prometheus-snmp-exporter/values.yaml
This PR fixes relabelings and metrics relabelings in the service monitor template.  Additionally, the values file has been updated with examples and comments in the  serviceMonitor configuration.
- fixes #2811
=> [prometheus-snmp-exporter] Fix service monitor relabelings

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/daemonset.yaml, charts/prometheus-node-exporter/templates/verticalpodautoscaler.yaml
Changes the DaemonSet container name to match the name used by the VerticalPodAutoscaler containerPolicies
=> [prometheus-node-exporter] Update VPA containerPolicies container name to match DaemonSet

charts/kube-prometheus-stack/Chart.lock, charts/kube-prometheus-stack/Chart.yaml
=> [kube-prometheus-stack] Bump kube-state-metrics version

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/templates/ingress.yaml, charts/prometheus-snmp-exporter/values.yaml
This PR updates the ingress template for kubeVersion 1.19 and later by correcting the service backend. At the same time, it adds support for ingress class.
- fixes #3071
=> [prometheus-snmp-exporter] Correct ingress template

charts/prometheus/Chart.yaml, charts/prometheus/templates/clusterrole.yaml
The default scrap configuration used to pass through kubelet/cAdvisor scrape requests by passing them through the API server as a proxy. The standard configuration today uses direct access with a ServiceAccount token. We can now remove `nodes/proxy` from the default `ClusterRole`. Note, this is already the default in the `kube-prometheus-stack` chart.
- fixes #
=> [prometheus] Remove obsolete permissions

charts/prometheus/Chart.yaml, charts/prometheus/templates/clusterrole.yaml
This reverts commit dd013b1ecc651491a778ae75c430345965657c18 / PR #3077 
- fixes #
=> [prometheus] Revert remove obsolete permission

charts/kube-prometheus-stack/Chart.yaml
Bumps the Grafana helm chart version
=> [kube-prometheus-stack] Update grafana chart

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/networkpolicy.yaml, charts/kube-state-metrics/values.yaml
This PR adds support for environment constrained with network policies
- fixes #
=> [kube-state-metrics] Add network policy and bump to 2.8.1

charts/prometheus-rabbitmq-exporter/Chart.yaml, charts/prometheus-rabbitmq-exporter/templates/servicemonitor.yaml, charts/prometheus-rabbitmq-exporter/values.yaml
- adds an option to configure ServiceMonitor relabelings/metricRelabelings attributes
=> [prometheus-rabbitmq-exporter] add relabelings config to ServiceMonitor

charts/prometheus-statsd-exporter/Chart.yaml, charts/prometheus-statsd-exporter/templates/_helpers.tpl, charts/prometheus-statsd-exporter/templates/deployment.yaml, charts/prometheus-statsd-exporter/values.yaml
This PR enables additional labels for statsd-exporter pods
- @scDisorder
=> [prometheus-statsd-exporter] add podLabels to add extra labels to pods

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/servicemonitor.yaml, charts/kube-state-metrics/values.yaml
In this PR I am proposing adding support for bearer token in service monitor by means of `bearerTokenFile` as well as `bearerTokenSecret`
- related to #3143
=> [kube-state-metrics] Update servicemonitor

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/extra-manifests.yaml, charts/prometheus-blackbox-exporter/values.yaml
Taking inspiration from the prometheus Chart, this adds a template through which you can deploy extra manifests alongside your blackbox-exporter ones. The main use case I have for this is for deploying extra resources used/related to the Chart such as an OpenShift Route.
=> [prometheus-blackbox-exporter] Add extra manifests template

charts/prometheus-elasticsearch-exporter/Chart.yaml, charts/prometheus-elasticsearch-exporter/templates/deployment.yaml, charts/prometheus-elasticsearch-exporter/values.yaml
Added possibility to enable exporter for aliases, slm and data streams
- fixes #
=> [prometheus-elasticsearch-exporter] add setters for missed out exporters

charts/prometheus/Chart.yaml, charts/prometheus/templates/cm.yaml, charts/prometheus/values.schema.json, charts/prometheus/values.yaml
With this PR I am proposing to add support for [tsdb](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb) and [exemplars](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#exemplars) configuration in
Prometheus' configuration file.
- fixes #3171
=> [prometheus] Add support for tsdb and exemplars

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/values.yaml
I have spent some time trying to figure out why these variables were not being recognized, so I think a comment was necessary. Especially because in the HELM chart this is not as clear as one would like: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-postgres-exporter/templates/deployment.yaml#L66
- clarifies the usage of `excludeDatabases` and `includeDatabases` variables
=> [prometheus-postgres-exporter] Add comments regarding excludeDatabases and includeDatabases

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/configmap.yaml, charts/alertmanager/values.yaml
I added annotations to configmap to be able to mutate secrets from vault. The config often contains private tokens or links and you don’t want to publish them to git when using, for example, argocd.
An example of use described.
=> [alertmanager] Add annotations for ConfigMap

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/networkpolicy.yaml, charts/prometheus-node-exporter/values.yaml
Fixes: #3211
This provides a simple way to set a network policy on the `node-exporter` for further constraining the container.
- fixes #3211
=> [prometheus-node-exporter] add an optional `NetworkPolicy`

charts/prometheus-redis-exporter/Chart.yaml, charts/prometheus-redis-exporter/templates/servicemonitor.yaml
explicit default for metricRelabelings[].action
if not set it causes permanent difference when using ArgoCd
[argocd diff screenshot](https://paste.pics/4834f8b9a3c0f1f3cd45d5a410a97058)
- fixes #
=> [prometheus-redis-exporter] explicit default for metricRelabelings[].action

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/values.yaml
Revert #3194 until further tests because it breaks the chart.
- fixes #3228
=> [kube-state-metrics] revert #3194

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/servicemonitor.yaml
Fix service monitor annotations templating to avoid `annotations: null`
- fixes https://github.com/prometheus-community/helm-charts/issues/3237
=> [kube-state-metrics] Fix ServiceMonitor annotations templating

charts/prometheus-operator-admission-webhook/Chart.yaml
This PR bumps the admission webhook application to release 0.64.0.
None
=> [prometheus-operator-admission-webhook] Bump application version to 0.64.0

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Addresses: https://github.com/prometheus-community/helm-charts/issues/2928
=> [kube-prometheus-stack] Grafana dashboards in all namespaces by default

charts/prometheus-operator-admission-webhook/Chart.yaml, charts/prometheus-operator-admission-webhook/templates/mutatingWebhookConfiguration.yaml, charts/prometheus-operator-admission-webhook/templates/validatingWebhookConfiguration.yaml
This PR corrects admission webhook configurations for cases where target namespace name gets overriden.
None
=> [prometheus-operator-admission-webhook] Correct webhook configurations

charts/kube-prometheus-stack/Chart.yaml
Update the grafana dependency to the current grafana chart
- fixes #
I wrote the patches that went into the grafana chart updates.
=> [kube-prometheus-stack] update grafana dep

charts/prometheus/Chart.yaml, charts/prometheus/README.md, charts/prometheus/values.yaml
=> [prometheus] Typo and broken link fix

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
Currently, the "secretFieldSelector" option only supports setting constants. But in more cases we want to be able to set variables (eg `metadata.namespace={{ .Release.Namespace }}`). 
- fixes #
=> [kube-prometheus-stack] adding tpl upstream for secretFieldSelector

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/README.md, charts/prometheus-node-exporter/values.yaml
This sets `readOnlyRootFilesystem` for node-exporter.  Since this container has access to some host elements, the additional hardening should help avoid some container escape surfaces.
- fixes #
This deployed ok in `kind`, but may need some additional eyes.
=> [prometheus-node-exporter] set readOnlyRootFilesystem=true

charts/prometheus-adapter/Chart.yaml, charts/prometheus-adapter/README.md, charts/prometheus-adapter/templates/deployment.yaml, charts/prometheus-adapter/values.yaml
Containers' readiness and liveness probes often need tweaking. This PR adds an option to modify container probes' parameters through values `livenessProbe` and `readinessProbe`. The previous parameters' values are being kept as defaults. 
- fixes #3271
=> [prometheus-adapter] Add support for configuring probes

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/templates/ciliumnetworkpolicy.yaml, charts/kube-state-metrics/templates/networkpolicy.yaml, charts/kube-state-metrics/values.yaml
Cilium is getting more and more used and this means KSM users needs to create a standalone ciliumnetworkpolicy for their needs. This PR addresses that
- fixes #
=> [kube-state-metrics] Add cilium networkpolicy support

charts/prometheus-operator-crds/Chart.yaml, charts/prometheus-operator-crds/hack/update_crds.sh, charts/prometheus-operator-crds/templates/crd-alertmanagerconfigs.yaml, charts/prometheus-operator-crds/templates/crd-alertmanagers.yaml, charts/prometheus-operator-crds/templates/crd-podmonitors.yaml, charts/prometheus-operator-crds/templates/crd-probes.yaml, charts/prometheus-operator-crds/templates/crd-prometheusagents.yaml, charts/prometheus-operator-crds/templates/crd-prometheuses.yaml, charts/prometheus-operator-crds/templates/crd-prometheusrules.yaml, charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml, charts/prometheus-operator-crds/templates/crd-thanosrulers.yaml
=> [prometheus-operator-crds] Update to 0.64.1

.github/CODEOWNERS, charts/prometheus-smartctl-exporter/Chart.yaml
This PR adds @zeritti as a maintainer of the chart. I have been contributing to the community's charts through [pull requests](https://github.com/prometheus-community/helm-charts/pulls?q=is%3Apr+author%3Azeritti) as well as through supporting users's [issues](https://github.com/prometheus-community/helm-charts/issues?q=is%3Aissue+commenter%3Azeritti) and will be happy to support the community's work further as a chart maintainer. 
=> [prometheus-smartctl-exporter] Add zeritti as chart maintainer

charts/prometheus/Chart.yaml, charts/prometheus/templates/extra-manifests.yaml
This PR removes the `toYaml` function in the `extraManifests` template. For example, I want to use this config with `extraManifests`:
```
extraManifests:
- apiVersion: v1
kind: ConfigMap
metadata:
name: extra-config
labels:
{{- include "prometheus.server.labels" . | nindent 4 }}
data:
{{ ( tpl (.Files.Glob "rules/**/*.yaml").AsConfig .) | indent 2 }}
```
but it doesn't work, since it is not a valid YAML blocks.
=> [prometheus] Remove toYaml function in extraManifests template

charts/prometheus-smartctl-exporter/Chart.yaml, charts/prometheus-smartctl-exporter/README.md
This PR adds a README file that has so far been missing.
- fixes #3126
=> [prometheus-smartctl-exporter] Add README file

charts/prometheus/Chart.yaml, charts/prometheus/templates/deploy.yaml, charts/prometheus/templates/sts.yaml
=> [prometheus] fix prometheus 3307

.github/CODEOWNERS, charts/prometheus-kafka-exporter/Chart.yaml
=> [prometheus-kafka-exporter] Add zeritti as chart maintainer

.github/CODEOWNERS, charts/prometheus-nginx-exporter/Chart.yaml
=> [prometheus-nginx-exporter] Add zeritti as chart maintainer

.github/CODEOWNERS, charts/prometheus-pgbouncer-exporter/Chart.yaml
=> [prometheus-pgbouncer-exporter] Add zeritti as chart maintainer

.github/CODEOWNERS, charts/prometheus-mongodb-exporter/Chart.yaml
=> [prometheus-mongodb-exporter] Add zeritti as chart maintainer

.github/CODEOWNERS, charts/prometheus-node-exporter/Chart.yaml
=> [prometheus-node-exporter] Add zeritti as chart maintainer

.github/CODEOWNERS, charts/prometheus/Chart.yaml
This PR adds @zeritti as a maintainer of the chart. I have been contributing to the community's charts through [pull requests](https://github.com/prometheus-community/helm-charts/pulls?q=is%3Apr+author%3Azeritti) as well as through supporting users's [issues](https://github.com/prometheus-community/helm-charts/issues?q=is%3Aissue+commenter%3Azeritti) and will be happy to support the community's work further as a chart maintainer. I would like to contribute to active development of this chart in particular.
=> [prometheus] Add zeritti as chart maintainer

.github/CODEOWNERS, charts/prometheus-postgres-exporter/Chart.yaml
=> [prometheus-postgres-exporter] Add zeriti as chart maintainer

charts/prometheus/Chart.yaml, charts/prometheus/templates/sts.yaml
ping: @gianrubio @zanhsieh @Xtigyro @naseemkullah
I inadvertently left a bug in my [last PR.](https://github.com/prometheus-community/helm-charts/pull/3289)
N/A
Looks like I forgot to change the volume mount name, this PR updates the volume mount to rename the mounted volume in-line with the name override.
=> [prometheus]: Fix statefulSet PVC volume mount name

charts/prometheus-node-exporter/Chart.yaml, charts/prometheus-node-exporter/templates/daemonset.yaml
With `kubeRBACProxy` enabled node-exporter port should be protected by TLS and RBAC (via kube-rbac-proxy) so it shouldn't be exposed and available for anybody to scrape. In order to do this change node-exporter listen address to 127.0.0.1.
- fixes https://github.com/prometheus-community/helm-charts/issues/3031
=> [prometheus-node-exporter] fix node-exporter listen address with kubeRBACProxy enabled

charts/prometheus/Chart.yaml, charts/prometheus/README.md
This PR brings Prometheus to release [v2.43.1](https://github.com/prometheus/prometheus/releases/tag/v2.43.1), a bugfix release.
None
=> [prometheus] Bump Prometheus release

charts/prometheus/Chart.yaml, charts/prometheus/values.yaml
Updates the documentation for `extraManifests` value following the removal of `toYaml` in the template in #3287 
- fixes #3328
=> [prometheus] Update extraManifests example to be multiline string instead of YAML

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/_helpers.tpl, charts/prometheus-blackbox-exporter/values.yaml
=> Add commonLabels values to blackbox-exporter

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/service.yaml, charts/kube-prometheus-stack/values.yaml
Adds sessionAffinity support to alertmanager service
=> [kube-prometheus-stack] Add sessionAffinity support to alertmanager

charts/prometheus/Chart.yaml, charts/prometheus/templates/deploy.yaml, charts/prometheus/templates/sts.yaml
This PR fixes the default reload URL for the config-reloader if `prefixURL` is set. The thing is that `prefixURL` always includes a leading slash - doubling it has to be avoided.
- fixes #3390
=> [prometheus] Correct reload URL

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/templates/role.yaml
If PodSecurityPolicy API is not available in a cluster, a `use` permission on resources `podsecuritypolicies` should not be created through the role template.
None
=> [prometheus-postgres-exporter] Correct role

charts/prometheus/Chart.yaml, charts/prometheus/README.md
=> [promtheus] Typo correction

charts/prometheus-json-exporter/Chart.yaml, charts/prometheus-json-exporter/templates/deployment.yaml, charts/prometheus-json-exporter/values.yaml
Adds the ability to define init containers to be added to the deployment
n/a
=> [prometheus-json-exporter] Add extra init containers

charts/prometheus-operator-crds/Chart.yaml, charts/prometheus-operator-crds/hack/update_crds.sh, charts/prometheus-operator-crds/templates/crd-alertmanagerconfigs.yaml, charts/prometheus-operator-crds/templates/crd-alertmanagers.yaml, charts/prometheus-operator-crds/templates/crd-podmonitors.yaml, charts/prometheus-operator-crds/templates/crd-probes.yaml, charts/prometheus-operator-crds/templates/crd-prometheusagents.yaml, charts/prometheus-operator-crds/templates/crd-prometheuses.yaml, charts/prometheus-operator-crds/templates/crd-prometheusrules.yaml, charts/prometheus-operator-crds/templates/crd-scrapeconfigs.yaml, charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml, charts/prometheus-operator-crds/templates/crd-thanosrulers.yaml
This PR brings Prometheus operator CRDs release [0.65.1](https://github.com/prometheus-operator/prometheus-operator/releases).
None
=> [prometheus-operator-crds] Update to 0.65.1

.github/workflows/release.yaml
Re-enable pushing charts as OCI artifact to ghcr.io
- ref #2454
=> Re-enable publish charts on ghcr.io as OCI artifact

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
=> update helm in ci workflows

charts/prometheus-conntrack-stats-exporter/Chart.yaml
=> [prometheus-conntrack-stats-exporter] update image to v0.4.15

charts/jiralert/Chart.yaml, charts/jiralert/templates/deployment.yaml, charts/jiralert/values.yaml
=> [jiralert] fix podSecurityContext and define defaults

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
This PR changes `prometheusOperator.admissionWebhooks.failurePolicy` from nil to an empty string to prevent a compatibility issue when installing the chart with Helm 3 built with compiler below release go1.17 (Helm's build below release 3.8).
- fixes #3436
=> [kube-prometheus-stack] Make failurePolicy a string

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml, charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml, charts/kube-prometheus-stack/values.yaml
=> [kube-prometheus-stack] - add scrapeConfig CR and tpl support for all CR's selectors

charts/kube-state-metrics/Chart.yaml, charts/kube-state-metrics/values.yaml
Updates kube-state-metrics to v2.9.2
- fixes #
=> [kube-state-metrics] Version bump to 2.9.2

.github/CODEOWNERS, charts/prometheus-operator-crds/Chart.yaml
Adding myself as a maintainer. To assist in PRs like #3453
- fixes #
=> [prometheus-operator-crds] Add jkroepke as maintainer

charts/prometheus-operator-crds/Chart.yaml, charts/prometheus-operator-crds/templates/crd-alertmanagerconfigs.yaml, charts/prometheus-operator-crds/templates/crd-alertmanagers.yaml, charts/prometheus-operator-crds/templates/crd-podmonitors.yaml, charts/prometheus-operator-crds/templates/crd-probes.yaml, charts/prometheus-operator-crds/templates/crd-prometheusagents.yaml, charts/prometheus-operator-crds/templates/crd-prometheuses.yaml, charts/prometheus-operator-crds/templates/crd-prometheusrules.yaml, charts/prometheus-operator-crds/templates/crd-scrapeconfigs.yaml, charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml, charts/prometheus-operator-crds/templates/crd-thanosrulers.yaml
* Upgrades CRDs to latest version
=> [prometheus-operator-crds] upgrade crds to 0.65.2

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/deployment.yaml, charts/prometheus-blackbox-exporter/values.yaml
=> [prometheus-blackbox-exporter] update to 0.24.0 and add topologySpreadConstraints

charts/alertmanager/Chart.yaml, charts/alertmanager/values.schema.json
=> [alertmanager] handle special case to group_by all labels

charts/kube-prometheus-stack/Chart.yaml
usual chart bump
tested on my local machine. via `helm install kube-prometheus-stack .`
- fixes #
=> [kube-prometheus-stack] bump chart dependencies

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml, charts/kube-prometheus-stack/values.yaml
By adding the Alertmanager datasource in Grafana, silenced can be created through Grafana. This removes the dependency for having Alertmanager public-facing. 
- fixes #
Tested locally
=> [kube-prometheus-stack] Add Alertmanager as default data source

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/daemonset.yaml, charts/prometheus-blackbox-exporter/templates/deployment.yaml, charts/prometheus-blackbox-exporter/values.yaml
Update to AppVersion 0.24.0 was announced.
But I have noticed that the image-tag was not updated.
So, I have updated the values.yaml to use v0.24.0 as default application version.
=> [prometheus-blackbox-exporter] update values to use default from app-version of chart

charts/alertmanager/Chart.yaml, charts/alertmanager/templates/NOTES.txt, charts/alertmanager/templates/_helpers.tpl, charts/alertmanager/templates/configmap.yaml, charts/alertmanager/templates/ingress.yaml, charts/alertmanager/templates/pdb.yaml, charts/alertmanager/templates/serviceaccount.yaml, charts/alertmanager/templates/services.yaml, charts/alertmanager/templates/statefulset.yaml, charts/alertmanager/templates/tests/test-connection.yaml, charts/alertmanager/values.schema.json, charts/alertmanager/values.yaml
This PR adds support for overriding namespace through the value `namespaceOverride`.
- fixes #3472
=> [alertmanager] Support overriding namespace

.github/CODEOWNERS, charts/prometheus-elasticsearch-exporter/Chart.yaml
This PR adds @zeritti to the chart's maintainers.
=> [prometheus-elasticsearch-exporter] Add a chart maintainer

charts/prometheus-elasticsearch-exporter/Chart.yaml, charts/prometheus-elasticsearch-exporter/templates/deployment.yaml, charts/prometheus-elasticsearch-exporter/values.yaml
Signed-off-by: Antonio Belloso Vicente antonio.belloso.vicente@gmail.com
This PR adds support for custom init containers.
n/a
=> [prometheus-elasticsearch-exporter] Add init containers

charts/prometheus-pingmesh-exporter/Chart.yaml, charts/prometheus-pingmesh-exporter/templates/deployment.yaml, charts/prometheus-pingmesh-exporter/templates/service.yaml, charts/prometheus-pingmesh-exporter/values.yaml
- fixes #
Add `ipv4/ipv6`  `dual-stack`, default setting `SingleStack`
=> [prometheus-pingmesh-exporter] Add ipv4/ipv6 dual stack

charts/prometheus-cloudwatch-exporter/Chart.yaml
* update image version
- fixes #
=> [cloudwatch exporter] update image version

charts/prometheus/Chart.yaml, charts/prometheus/templates/NOTES.txt, charts/prometheus/templates/_helpers.tpl
=> [prometheus] correct NOTES.txt for pod labels selection

.github/workflows/release.yaml
After some investigates, the helm oci push can be considered as stable. Before communicating OCI based repositories, we should increase the awareness, if helm push failed. ref #2454
- fixes #
=> [*] CI: fail pipeline, if helm push is not successful

charts/prometheus-pingmesh-exporter/Chart.yaml, charts/prometheus-pingmesh-exporter/templates/daemonset.yaml
- fixes #
1. update image version to support amd64/arm64. 
2. fix a misspelling
=> [prometheus-pingmesh-exporter] update image version to support amd64/arm64

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml, charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml, charts/prometheus-blackbox-exporter/values.yaml
Allow to configure probe and metric path. This is requires, if the arg `web.route-prefix` is defined.
- fixes #
=> [prometheus-blackbox-exporter] Allow to configure probe and metrics path

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/values.yaml
Update chart dependencies. Upgrade Prometheus should fine, this it got accepted for prometheus chart, too:
- https://github.com/prometheus-community/helm-charts/pull/3519
- fixes #
=> [kube-prometheus-stack] Bump Prometheus and chart dependencies

charts/prometheus/Chart.yaml, charts/prometheus/README.md, charts/prometheus/templates/_helpers.tpl
It allows users of this chart to set their own custom common metadata labels (i.e. for use with label policies)
- fixes #
=> [prometheus] Added custom common meta labels

charts/prometheus-postgres-exporter/Chart.yaml, charts/prometheus-postgres-exporter/values.yaml
Bump default postgres-exporter version. Queries.yaml is deprecated but not removed, so still should be safe to use.
=> [prometheus-postgres-exporter] Upgrade postgres-exporter version

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/README.md, charts/prometheus-blackbox-exporter/templates/_helpers.tpl, charts/prometheus-blackbox-exporter/templates/daemonset.yaml, charts/prometheus-blackbox-exporter/templates/deployment.yaml, charts/prometheus-blackbox-exporter/values.yaml
Replicate the image configuration syntax from kube-prometheus-stack / node-exporter.
Additionally, use the quay.io image by default. (https://github.com/prometheus-community/helm-charts/pull/928, https://github.com/prometheus-community/helm-charts/pull/3562)
- fixes #
=> [prometheus-blackbox-exporter] Refactor image configuration

charts/prometheus-snmp-exporter/Chart.yaml, charts/prometheus-snmp-exporter/templates/_helpers.tpl, charts/prometheus-snmp-exporter/templates/configmap.yaml, charts/prometheus-snmp-exporter/templates/daemonset.yaml, charts/prometheus-snmp-exporter/templates/deployment.yaml, charts/prometheus-snmp-exporter/templates/ingress.yaml, charts/prometheus-snmp-exporter/templates/role.yaml, charts/prometheus-snmp-exporter/templates/rolebinding.yaml, charts/prometheus-snmp-exporter/templates/service.yaml, charts/prometheus-snmp-exporter/templates/serviceaccount.yaml, charts/prometheus-snmp-exporter/values.yaml
=> [prometheus-snmp-exporter] Add a namespace override

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml, charts/kube-prometheus-stack/values.yaml
This PR adds support for Prometheus Tracing Config
- fixes #3557
=> [kube-prometheus-stack] adding prometheus tracing config

charts/prometheus-blackbox-exporter/Chart.yaml, charts/prometheus-blackbox-exporter/templates/verticalpodautoscaler.yaml, charts/prometheus-blackbox-exporter/values.yaml
This PR adds support the the vertical pod autoscaler so users do not have to care about the resource usage of the prometheus blackbox exporter and let the vertical pod autoscaler to do its job.
- fixes #
=> [prometheus-blackbox-exporter] Add Vertical Pod Autoscaler to Prometheus Blackbox Exporter

charts/kube-prometheus-stack/Chart.yaml, charts/kube-prometheus-stack/templates/prometheus-operator/verticalpodautoscaler.yaml, charts/kube-prometheus-stack/values.yaml
Adds optional configuration for custom [recommender](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml#L266) for Vertical Pod Autoscaler.
- fixes #
=> [kube-prometheus-stack] Add recommender option to VPA
