prometheus-community/helm-charts

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/prometheus/Chart.yaml
ct.yaml

Adds Helm GitHub actions for CI (linting and testing any changed charts in a PR), and CD (packaging merged chart changes and uploading to GitHub releases, and updating the repo index in GitHub pages). For more info, see https://github.com/helm/charts-repo-actions-demo
Note about steps:
- Merging this PR should not publish any charts yet, since there was no previous version of them in a GitHub pages helm repo index file.
- In subsequent PRs, we can bump the versions of individual charts that we want to list. When we do, we should update each chart's README to add the new helm repo to installation instructions. See https://github.com/prometheus-community/community/issues/28 for the overall plan to incrementally improve/simplify charts after moving from `stable` to a new helm repo in …

Add Helm GitHub Actions

---

.github/stale.yml

This adds a configuration for https://github.com/apps/stale. If you want to use it then this should be merged and afterwards the GitHub installed to the repository.
Config is taken from https://github.com/helm/charts/blob/92be1ddfc5a242eacae8c34a4401eb1561240d74/.github/stale.yml

Add configuration for Stale GitHub app

---

.github/workflows/linter.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
charts/kube-prometheus/hack/minikube/README.md

The goal of this is to resolve all errors reported by superlinter or to disable the linters which report errors.
That way we would not block contributions. Disabled linters can be enabled one by one in separate PRs if desired together with fixing issues reported by them.

fix errors reported by superlinter

---

.github/workflows/linter.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
charts/prometheus-operator/hack/minikube/README.md

- fixes markdown issues reported by markdownlint
- disabled yamllint as helm templates are never valid
- disabled the other linters as there is a problem with a shell script and some python code
once that is fixed we could enable them again
Note: After cherry-picking this I removed changes for prometheus-operator  as thos are better done in #1 (otherwise I would need to bump the version because of a minikube README change)

disabled failing linters and fixed markdown issues (#32)

---

index.yaml

Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
This PR is to change the URL for the charts to the `prometheus-community` GH Pages.
Fixes: https://github.com/prometheus-community/helm-charts/issues/35
/cc @scottrigby

fix: correcting asset urls

---

README.md

Follow up to #41 
Also see https://github.com/prometheus-community/helm-charts/pull/39#issuecomment-687616250
To be clear, changes to the README in `main` now auto-sync to the `gh-pages` branch, so users will be able to see human-readable help and info about this helm repo if they decide to visit the helm repo URL.
I didn't add an additional link to the source code location, since the CONTRIBUTING file links directly there, with explicit instructions for forking etc.
Thanks to @monotek for getting the ball rolling with this in #39

Improve README for main and gh pages

---

README.md

Added github repo link to readme.md. 
This might look redundant but imho its nice to have a link to the repo from the index.html generated by gh-pages.

added github repo link to readme

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
This PR is to create the Issue Templates (bug-report and feature_request) as in the `helm/charts` repo. 
/cc @torstenwalter @scottrigby

feat: adding issue templates

---

.github/CODEOWNERS
charts/prometheus/Chart.yaml

* adds monotek to prometheus maintainers
- fixes #
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

[prometheus] - adds monotek to prometheus maintainers

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/_helpers.tpl
charts/prometheus-blackbox-exporter/templates/role.yaml
charts/prometheus-blackbox-exporter/templates/rolebinding.yaml

Signed-off-by: Jorrit Salverda <jsalverda@travix.com>
No
To fix `helm lint` from failing on deprecated api versions in `role` and `rolebinding`
- fixes #56
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

[prometheus-blackbox-exporter] fix linting failure due to deprecated api version (see issue #56)

---

charts/kube-prometheus-stack/templates/NOTES.txt

Signed-off-by: Xtigyro <miroslav.hadzhiev@gmail.com>
Fixes the name of the chart and removes whitespaces in `templates/NOTES.txt`.
- [already done in original PR] Chart Version bumped

[kube-prometheus-stack] Fix Chart Name and Rm Whitespaces in "NOTES.txt"

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/daemonset.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: John Stewart <jstewart@rentpath.com>

[prometheus-blackbox-exporter] allow configurable DNS settings

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/rbac/alertmanager-clusterrole.yaml
charts/prometheus/templates/rbac/alertmanager-clusterrolebinding.yaml
charts/prometheus/templates/rbac/alertmanager-role.yaml
charts/prometheus/templates/rbac/alertmanager-rolebinding.yaml
charts/prometheus/templates/rbac/node-exporter-role.yaml
charts/prometheus/templates/rbac/node-exporter-rolebinding.yaml
charts/prometheus/templates/rbac/pushgateway-clusterrole.yaml
charts/prometheus/templates/rbac/pushgateway-clusterrolebinding.yaml
charts/prometheus/templates/rbac/server-clusterrole.yaml
charts/prometheus/templates/rbac/server-clusterrolebinding.yaml
charts/prometheus/templates/rbac/server-rolebinding.yaml

Signed-off-by: Jorrit Salverda <jsalverda@travix.com>
To successfully lint the helm chart with the latest version of Helm the rbac apiVersion needs to be returned as `rbac.authorization.k8s.io/v1`, since `rbac.authorization.k8s.io/v1beta1` is marked for deprecation.
- fixes #65

[prometheus] set rbac api version with template rbac.apiVersion

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
charts/prometheus-blackbox-exporter/values.yaml

Allow passing in additional metrics relabels for blackbox-exporter.
One useful example would be to add an owner label that would help with routing alerts via Alertmanager
N/A

[prometheus-blackbox-exporter] Add additional metrics relabels blackbox and update to 0.17.0

---

.github/CODEOWNERS
.github/workflows/release.yaml
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/requirements.yaml
charts/kube-prometheus-stack/values.yaml
ct.yaml

Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
This PR is to update the Grafana's dependent repository from **`stable`** to **`grafana`**.
👉  Version of Grafana chart has been upgraded from `5.3.*` to `5.6.*`
👉  `values.yaml` file's default value for Grafana has been same even after the bump of grafana chart.
/cc @bismarck @gianrubio @vsliouniaev 
🗒️  I also added myself as an additional maintainer to the chart.

feat: replacing grafana rom stable to its own repo + additional chart maintainer

---

.github/CODEOWNERS
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Xtigyro <miroslav.hadzhiev@gmail.com>
Adds @Xtigyro as a maintainer of the `kube-prometheus-stack` chart.

[kube-prometheus-stack] Add "xtigyro" as Maintainer for "kube-prometheus-stack"

---

artifacthub-repo.yaml

Fixes #75
format was incorrect. repositoryID is a UUID. See https://github.com/artifacthub/hub/blob/master/docs/chart/artifacthub-repo.yml

[gh-pages] Artifact Hub verified fix repositoryID

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/README.md

Looks like the generate command was renamed here https://github.com/prometheus-operator/kube-prometheus/commit/0f6cd6d0a8881ad7e80f2817c597dab8345f8790#diff-b67911656ef5d18c4ae36cb6741b7965
I don't think we need to bump version number here.

[kube-prometheus-stack] Update README.md

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Fix URL to stable/prometheus-node-exporter chart
- [ x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped (is it needed for this change?)

[kube-prometheus-stack] Fix URL to node-exporter

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

adds an extra volume mount so an extra volume can actually be mounted into the pod.
adds an example how to mount a custom ca-certificates files to allow SSL connections to postgres databases
none

[prometheus-postgres-exporter] add extraVolumeMounts and examples

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Add documentation to use additionalPrometheusRulesMap as finding the correct format is not straightforward
Backport of https://github.com/helm/charts/pull/23577

[kube-prometheus-stack] Add documentation on how to configure additionalPrometheusRulesMap

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/daemonset.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Allow custom labels for pods. Also adds label option to service entry in values.yaml that was missed in commit [d696fd4c388fdece1026491248be0b45412c163a](https://github.com/prometheus-community/helm-charts/commit/d696fd4c388fdece1026491248be0b45412c163a)
I created a top-level `pods` entry in `values.yaml` to mimic other top-level resource values such as `service`, `ingress`, etc. However, there is currently a top-level entry named podAnnotations that I feel should fit under it. I however didn't change that key to be under `pods` as it would be a breaking change.

[prometheus-blackbox-exporter] Allow custom labels for pods. Add service labels to values.yaml.

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/custom-metrics-apiserver-auth-reader-role-binding.yaml

Fixes an issue with the auth reader role binding to allow the prometheus adapter to read the extension-apiserver-authentication configmap in kube-system. 
The extension-apiserver-authentication-reader role resides in the kube-system namespace so the rolebinding will also need to reside in the kube-system namespace. 
As an example, in the metrics-server chart, this rolebinding is correctly set up - https://github.com/helm/charts/blob/c5989490cac32d4ca350c5d2f8928dfebff111b3/stable/metrics-server/templates/role-binding.yaml#L6. 
For additional reference, this is step 13 in the docs for setting up an extension api server - https://kubernetes.io/docs/tasks/extend-kubernetes/setup-extension-api-server/. 
Previous PR in helm/stable - https://github.com/helm/charts/pull/23341
*(optional, in …

[prometheus-adapter] Fix auth-reader rolebinding

---

.github/CODEOWNERS
charts/alertmanager/.helmignore
charts/alertmanager/Chart.yaml
charts/alertmanager/README.md
charts/alertmanager/templates/NOTES.txt
charts/alertmanager/templates/_helpers.tpl
charts/alertmanager/templates/configmap.yaml
charts/alertmanager/templates/ingress.yaml
charts/alertmanager/templates/serviceaccount.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/templates/tests/test-connection.yaml
charts/alertmanager/values.yaml

Adds a minimalist alertmanager chart.

[alertmanager] add new chart

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

[kube-prometheus-stack] Add docs on podmonitors

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Philippe Bürgisser <philippe.burgisser@camptocamp.com>

kube-prometheus-stack/alertmanager Added more options for AlertManager ServiceMonitoring

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/cleanup-crds.yaml
charts/kube-prometheus-stack/values.yaml

The hypercube image has been deprecated and will no longer be built. Replacing with the kubectl image from the bitnami repository
- fixes #156

[kube-prometheus-stack] Replacing hyperkube image with kubectl image from bitnami

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Prometheus try to scrape not running pods which cause reporting failures to scrape these ones. 
If it seems legit, I will review the PR to follow the contribution guidelines.
Best,

[prometheus] Proposition to not scrape not running pods

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/ci/extraenv-values.yaml
charts/prometheus-blackbox-exporter/templates/daemonset.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: Oleg Vorobev <olegy2008@ya.ru>
Add additional environment variables for blackbox-exporter container
For instance to add a http_proxy variable

[prometheus-blackbox-exporter] Add additional env variables to blackbox-exporter container

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/requirements.yaml

Allows latest grafana chart to be used.
- fixes #

[kube-prometheus-stack] Update grafana requirement

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

Allow configuring namespaces where prometheus-operator searches for custom resources to deploy. This allows narrowing the scope of permissions for prometheus-operator service account.
N/A
The flags can be consulted here https://github.com/prometheus-operator/prometheus-operator/blob/master/cmd/operator/main.go#L177.
Original [PR](https://github.com/helm/charts/pull/23667).

[kube-prometheus-stack] Add instance namespaces arguments for prometheus-operator deployment

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/templates/service.yaml
charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: Philippe Bürgisser <philippe.burgisser@camptocamp.com>
- Adding support of multiple container in the same pod (side car, like oAuth-proxy)
- Adding support of multiple secret (necessary for oauth)
- Adding support of annotation on service, service account
- Adding support of authenticated Service Monitor

[prometheus-blackbox-exporter] Added support of sidecars and extraVolumes

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml

Following 1d66906e0f792372e0f76e7e058a5dd507778fe4 the chart fails to render with the following error:
```
Error: YAML parse error on prometheus-blackbox-exporter/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context
```
Issue replicate with the following vals:
```yaml
enabled: true
targets:
- name: example
url: https://example.com
```

[prometheus-blackbox-exporter] fix service monitor template

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/psp.yaml
charts/prometheus/templates/node-exporter/psp.yaml
charts/prometheus/templates/pushgateway/psp.yaml
charts/prometheus/templates/server/psp.yaml

Signed-off-by: Qiu Yu <unicell@gmail.com>
Currently once `.Values.podSecurityPolicy.enabled` is set to true, PSPs will be created for all components (server, alertmanager, pushgateway) regardless of their enabling states. This PR fixes that by adding additional checks.
n/a

[prometheus] Create PSP only when corresponding components enabled

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

Signed-off-by: Ryan Bohannon <ryan.bohannon@centurylink.com>
Fixes the statefulset template. It's currently broken if you set persistence.enabled=false
- fixes #
Test by running:
`helm install alertmanager . --dry-run --set persistence.enabled=false`

[alertmanager] template fix

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/configmap.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

Signed-off-by: Rostyslav Sotnychenko <me@sota.sh>
One might want to collect the exact same set of metrics in different environments, with a difference only in tag filter value (`metrics.*.aws_tag_select.tag_selections.someLabel=XXXX`).
Given that definition of what metrics to collect takes most of the configuration file, it's handy to have an ability to change a single variable instead of overwriting the whole config from scratch.

[prometheus-cloudwatch-exporter] Allow Helm variables in config

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Signed-off-by: Raffael Sahli <raffael.sahli@doodle.com>
The current description to migrate from stable/prometheus-operator only covers a migration path with downtime. In most cases people want a zero downtime migration.
This fairly small pr adds a simple hint to cover the fullnameOverride option.

[kube-prometheus-stack] Add hint for zero downtime migration from stable/prometheus-operator

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/configmap.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

Default image prom/alertmanager use configfile called `alertmanager.yml`, but in the chart we use configfile with name `config.yml`.
Configuration from `.Values.config` is rendered correctly but it doesn't matter because we don't use this configfile.
Also, we don't have an option how to say alertmanager to use our configfile.
This PR allows us to:
* use this configuration file (fix)
* configure the name of the configuration file.
* add some extra args if it needed.
We have added `configFileName` as param just in case when someone uses a custom image and default alertmanager.yml contains some kind of reference configurations or examples.

[alertmanager] Add support change default config

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/templates/alertmanager/sts.yaml
charts/prometheus/templates/server/sts.yaml
charts/prometheus/values.yaml

Currently only prometheus server takes `emptyDir.sizeLimit` for
`deployment` but not for `statefulset`. And alertmanager has no notion
about `emptyDir.sizeLimit` at all.
This change fixes that by following existing pattern of prometheus
server deployment spec, to allow `sizeLimit` to be set for both `server`
and `alertmanager`, regardless it is a deployment spec or statefulset.
On the pushgateway side, existing comment string in `values.yaml`
suggests if `persistentVolume.enabled` set to false, `emptyDir` will be
used. But that's actually not the case. Since the existing pushgateway
deployment spec by default has persistent volume turned off and doesn't
specify emptyDir at all (neither in volume nor  volumeMount), this
change fixes the inconsistency by updating the comment string in …

[prometheus] Make emptyDir settings consistent across components

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

Add probe properties in prometheus template and default values.
- fixes #235

[kube-prometheus-stack] Add support for ProbeSelector and ProbeNamespaceSelector

---

.github/workflows/release.yaml
ct.yaml

https://github.com/prometheus-community/helm-charts/pull/183#issuecomment-716725104
Release failed as the URL to stable repository needs to be updated.
kube-prometheus-stack and prometheus also reference the old URL. I think it't best to merge this first and have separate PRs for those charts.

update URL for stable repository

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml

Signed-off-by: Sally Lehman <slehman@ripple.com>
The latest master build of the prometheus-operator chart cannot currently be used with kube-prometheus-stack because the deployment.yaml restricts customization only to release numbers.
This modification allows for releases, as well as the latest [master build of prometheus operator](https://quay.io/repository/prometheus-operator/prometheus-operator?tab=tags
) to be used with the chart.
cc'ing chart maintainers mentioned in Chart.yaml, as recommended in the Pull request guidelines:
@vsliouniaev @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro

[kube-prometheus-stack] Allow use of Prometheus Operator master image tag

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/service.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Allow native TLS supported by prometheus-operator v0.39.0 and later 
This is not tested yet and still WIP. 
To be discussed: Deprecate tlsproxy to simplify chart?

[WIP][kube-prometheus-stack] Support native TLS in prometheus-operator

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml

admissionregistration.k8s.io/v1beta1 -> admissionregistration.k8s.io/v1
W1027 12:53:41.791271 2909521 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration

[kube-prometheus-stack] Upgrade admission-webhook api

---

charts/prometheus/Chart.yaml
charts/prometheus/requirements.yaml
charts/prometheus/templates/server/rolebinding.yaml

Setting `server.useExistingClusterRoleName` and `server.namespaces` results in an error upon deployment:
Error: template: prometheus/templates/_helpers.tpl:199:20: executing "rbac.apiVersion" at <.Capabilities.APIVersions.Has>: can't evaluate field Capabilities in type string

[prometheus] Fix rolebinding apiVersion

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md

Actualize docs
New URL for [stable](https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository) helm chart
Аfter closing https://github.com/prometheus-community/helm-charts/pull/283

[prometheus] Change helm stable repo in docs

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Actualize docs
New URL for [stable](https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository) helm chart
For reference: https://github.com/prometheus-community/helm-charts/pull/286

[kube-prometheus-stack] Change helm stable repo in docs

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/requirements.yaml

Updates chart dependencies to new minor. 
Can't upgrade Grafana chart, which moved to helm-v3 only chart in 6.x

[kube-prometheus-stack] Update chart dependencies

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Bumps prometheus-operator to 0.43.1

[kube-prometheus-stack] Bump prometheus-operator to 0.43.1

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Based on the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/kubelet-resource-metrics-endpoint.md) for the Kubelet Resource Metrics Endpoint, I don't believe we should be scraping this endpoint. In the past, it's caused [issues](https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/458) with some of the metrics reported by cAdvisor. Also, the kube-prometheus project (which this chart is based on) [does not scrape](https://github.com/prometheus-operator/kube-prometheus/blob/master/manifests/prometheus-serviceMonitorKubelet.yaml) this endpoint.
Also, bumping the prometheus to v2.22.1 because it has fixes for a [retention size bug](https://github.com/prometheus/prometheus/pull/8139).
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …

[kube-prometheus-stack] Disable scraping kubelet resource metrics endpoint

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

charts/prometheus: fix typo

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
charts/kube-prometheus-stack/templates/prometheus/ingress.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Christian Niehoff <mail@christian-niehoff.com>
The annotation `kubernetes.io/ingress.class` will be deprecated.
Instead you have to specify the class of your ingress-controller via the new field `ingressClassName`
- fixes #265

[kube-prometheus-stack] add ingressclass support

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Bump prometheus-operator to 0.43.2

[kube-prometheus-stack] Bump prometheus-operator to 0.43.2

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

Adds support for Alertmanager to pick up alertmanagerConfig CRDs released with Prometheus operator v0.43.
- fixes #304 
The ct test was throwing an "unexpected element error" for the tillerVersion key in the Chart.yaml. I removed it so the tests could succeed but feel free to re-add if needed.

[kube-prometheus-stack] Add alertmanagerConfigSelector option

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/prometheusrule.yaml
charts/prometheus-postgres-exporter/values.yaml

Adds support for creation of "prometheusRule" objects that can be used by Prometheus Operator.
see also https://github.com/helm/charts/pull/21096/

[prometheus-postgres-exporter] Add prometheusrule support

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/deployment.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Allow for enabling the ability to drop delegated projects from the scraped data in stackdriver-exporter using the STACKDRIVER_EXPORTER_DROP_DELEGATED_PROJECTS env var.
Adds the ability to drop delegated projects from scraped data using the STACKDRIVER_EXPORTER_DROP_DELEGATED_PROJECTS env var.

[prometheus-stackdriver-exporter] Add dropDelegatedProjects to stackdriver-exporter

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/cm.yaml

Signed-off-by: Anas <anas.oubrahim@commercetools.com>
Avoid sending alerts to Alertmanager Peering port.
- fixes #
In this PR : https://github.com/prometheus-community/helm-charts/pull/179 the mesh peering port was explicitly defined for Alertmanager pods, as a result `kubernetes_sd` will list it as a target for Prometheus to send alerts to.
This leads to the following error on Prometheus spamming the logs:
```json
{"alertmanager":"http://10.35.102.55:6783/api/v1/alerts","caller":"notifier.go:527","component":"notifier","count":2,"err":"Post \"http://10.35.102.55:6783/api/v1/alerts\": EOF","level":"error","msg":"Error sending alert","ts":"2020-11-12T16:45:09.526Z"}
```

[prometheus] Use Alertmanager API port only for kubernetes_sd.

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
charts/prometheus-adapter/templates/custom-metrics-apiserver-service-account.yaml
charts/prometheus-adapter/templates/custom-metrics-apiserver-service.yaml
charts/prometheus-adapter/templates/custom-metrics-configmap.yaml

Fix for deploying the adapter in a custom namespace like monitoring.

[prometheus-adapter] Add missing namespace fields to custom-metric resources to allow install dedicated ns

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

When a comment has not the same indentation as the other items
an IDE like VS Code will collapse only the section above until
the comment that is not correctly indented.
None, only a minor change
CC: @vsliouniaev

[kube-prometheus-stack] Fix indentation to allow IDE collapse of sections

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Marc Troelitzsch <Marc.Troelitzsch@gmail.com>
Allows modifying the `path` in the ServiceMonitor. This can be needed if the `root_url` set in the `grafana.ini` points to a non-root path, e.g. when set to `www.foo.de/grafana`, the ServiceMonitor needs to check `/grafana/metrics` instead of just `/metrics`
@bismarck @vsliouniaev @gianrubio @gkarthiks @scottrigby @Xtigyro

[kube-prometheus-stack] Allow modifying ServiceMonitor path

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-coredns.yaml

Updates the CoreDNS dashboard to support versions after 1.7.0 which changed a number of metrics and broke the existing dashboard.
fixes #207 
This is a slightly tweaked version of this dashboard and seems to work just fine before and after the 1.7.0 upgrade: https://grafana.com/grafana/dashboards/12539
Before new dashboard (you can see where I upgraded coredns and the metrics disappeared):
After new dashboard:

[kube-prometheus-stack] Fix CoreDNS dashboard for v1.7.0+

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Did some digging for how to configure the default emptyDir for the `/prometheus` mount and I found https://github.com/prometheus-community/helm-charts/blob/3ab7f9b04e1ab5abd6c0b35268368422436ae3a6/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml#L4502
Adding comment to storageSpec in case future folks want to use a tmpfs mount for metrics (useful for short-term/ephemeral things, fast queries, or for not ruining a RaspberryPi microSD card).

[kube-prometheus-stack] Show tmpfs option for Prometheus storageSpec

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus/additionalScrapeConfigs.yaml
charts/kube-prometheus-stack/templates/prometheus/ingress.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

Allow additional templating within values.yaml file
Signed-off-by: Ryan Dyer <ryan-dyer-sp@users.noreply.github.com>
- fixes #333 
@bismarck @vsliouniaev @gianrubio @gkarthiks @scottrigby @Xtigyro For review please.

[kube-prometheus-stack] Issue #333

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml

This PR fixes ingress-per-replica labels. 
Currently when attempting to add labels to per-replica ingresses you'll get some variation of this error:
```
Error: YAML parse error on kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml: error converting YAML to JSON: yaml: line 18: did not find expected key
```
This is because the indent is set incorrectly in the template. I imagine it's a very seldom used feature which might explain why it's been like this for a while.
No issue was reported, as it was a small, quick fix.
@bismarck @vsliouniaev @gianrubio @gkarthiks @scottrigby @Xtigyro For review please.

[kube-prometheus-stack] Fix indentation for applying labels to per-replica ingress

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

The parameter `scrapeTimeout` is missing from the [values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml)  and from the [prometheus template](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml). This parameter is present on the CRD [prometheuses.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml).
This value is to customize the number of seconds to wait for target to respond before erroring, and currently the only way to change it is to added after deploy the chart by editing the pometheus object or creating a new one with the parameter and value in the spec. 
*(optional, in …

[kube-prometheus-stack] Add missing parameter scrapetimeout

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/README.md

Was reading through [`charts/kube-prometheus-stack/hack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/hack) and noticed some links were broken or outdated.
This includes pointing to new etcd-io/etcd rules set (after https://github.com/etcd-io/etcd/commit/4160b8396ddf21b0727c189017e5e71b25c3e5c5). I think these changes have been already synced in this repo, as the intermediate artifact (https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/grafana.json) stayed the same. It was just a matter of updating the procedure in the docs.
I don't think the chart version needs to be bumped for documentation nitpicks, but let me know otherwise.

[kube-prometheus-stack] Fix some GitHub broken links on 'hack/README.md'

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/service.yaml
charts/prometheus-kafka-exporter/templates/servicemonitor.yaml
charts/prometheus-kafka-exporter/values.yaml

This PR fix the issue of kafka-exporter endpoints not being displayed in prometheus targets.
After merging this PR serviceMonitor will be able to find the endpoints and endpoints will be shown in prometheus targets.
Kafka-exporter metrics then will be scraped by prometheus.
- fixes #343
@gkarthiks Please review the PR.

[prometheus-kafka-exporter] Servicemonitor is not able to find endpoints for kafka-exporter target (shows 0/0 up) #343

---

charts/prometheus-couchdb-exporter/Chart.yaml
charts/prometheus-couchdb-exporter/templates/_helpers.tpl
charts/prometheus-couchdb-exporter/templates/role.yaml
charts/prometheus-couchdb-exporter/templates/rolebinding.yaml

Signed-off-by: Gabriel Melillo <gabriel@melillo.me>
To successfully lint the helm chart with the latest version of Helm the RBAC apiVersion needs to be returned as `rbac.authorization.k8s.io/v1` since `rbac.authorization.k8s.io/v1beta1` is marked for deprecation.
- fixes #380

[prometheus-couchdb-exporter]: add configurable apiVersion

---

charts/prometheus-consul-exporter/Chart.yaml
charts/prometheus-consul-exporter/templates/_helpers.tpl
charts/prometheus-consul-exporter/templates/role.yaml
charts/prometheus-consul-exporter/templates/rolebinding.yaml

Signed-off-by: Gabriel Melillo <gabriel@melillo.me>
To successfully lint the helm chart with the latest version of Helm the RBAC apiVersion needs to be returned as rbac.authorization.k8s.io/v1 since rbac.authorization.k8s.io/v1beta1 is marked for deprecation.
- fixes #379

[prometheus-consul-exporter] add configurable apiVersion

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

… prometheus-operator
Signed-off-by: xxxbobrxxx <xxxbobrxxx@gmail.com>

[kube-prometheus-stack] Correct provisioning for the --thanos-ruler-instance-namespaces prometheus-operator argument

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

- There are 2 logFormat options for Operator and Alertmanager, which are
`logfmt` and `json`, but the comments now make it look like that the
options are `logfmt` and `json-formatted`

[kube-prometheus-stack] Clarify log format options in kube-prometheus-stack

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/values.yaml

The namespaceSelector applies to labels on a Namespace, not fields on a Namespace.
There is a discussion about this in the kubernetes repository - kubernetes/kubernetes#88253
I described this in more detail in the comment on the option `allowMonitoringNamespace` in `values.yaml`
- fixes #221

[prometheus-blackbox-exporter] add detail comment to the option allowMonitoringNamespace in values.yaml

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

Adds `imagePullSecrets` to prometheus-cloudwatch-exporter.
- fixes https://github.com/prometheus-community/helm-charts/issues/129

prometheus-cloudwatch-exporter - Add imagePullSecrets

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/service.yaml
charts/kube-prometheus-stack/values.yaml

Add optional extra ports to alertmanager
As it is done for prometheus. This allows to add an auth proxy in front
of alertmanager while still using direct access from prometheus.

kube-prometheus-stack: Add optional extra ports to alertmanager

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/README.md

Signed-off-by: zanhsieh <zanhsieh@gmail.com>
Initial attempt to move to chart v2, since helm v2 has been out of support from Nov. 15th, 2020.

[prometheus-redis-exporter] Migrate to chart v2

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

With TLS enabled, by default kubectl (at least versions v1.14.x v1.15.x and v1.16.x) cannot create PrometheusRules because the min TLS version is too high. This allows a deployer to set a lower TLS version.
Error from client: 
```
$ kubectl -n infra create -f rules.yaml 
Error from server (InternalError): error when creating "rules.yaml": Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-kube-p-operator.infra.svc:443/admission-prometheusrules/mutate?timeout=10s: remote error: tls: protocol version not supported
```
Error from prometheus-operator:
```
http: TLS handshake error from 10.244.67.0:42380: tls: client offered only unsupported versions: [303 302 301]
```

[kube-prometheus-stack] Allow custom TLS min version for operator

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

The `volume` and `volumeMounts` fields are currently treated as strings instead of an array of objects.

[kube-prometheus-stack] Fix broken volumes and volumeMounts fields on alertmanager

---

.github/CODEOWNERS

@sandy724 is a maintainer of that chart according to:
https://github.com/prometheus-community/helm-charts/blob/18ce04ce2dd84ea0884251745256e5405ad6b77d/charts/prometheus-druid-exporter/Chart.yaml#L9-L13
This PR reflects that in CODEOWNERS
- fixes #

[prometheus-druid-exporter] update CODEOWNERS to reflect maintainers

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Changes the default configuration so that the liveness and readiness probes have timeouts shorter than the period. This addresses issue #410 which means that the chart does not currently play nicely with GKE HTTP Ingresses when configured in NodePort mode.
It does continue to make sense to me that the timeout for these things should be less than the period (Indeed, this is how Prometheus itself treats scraping). I am not sure that 4 seconds is the correct timeout for us to be using here, but 30 seconds does seem absurd when both the health and liveness endpoints have been designed to respond relatively quickly. I thought opening this PR would at least give us a chance to discuss this, or decide to just improve the documentation around deploying onto GKE rather than changing these default …

[prometheus] Potentially change default liveness and readiness to abide by GKE limitations

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/README.md
charts/prometheus-snmp-exporter/templates/servicemonitor.yaml
charts/prometheus-snmp-exporter/values.yaml

- Fixes ServiceMonitor to crawl the correct pods
- Fixes ServiceMonitor to properly work when multiple instances
of the chart are installed
- Allows specifying relabelings and metricRelabelings configuration
in ServiceMonitor
- fixes #398

[prometheus-snmp-exporter] Fixes #398 and adds some features

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

With the introduction of codespell, the CI is not working anymore due to an error on a readme.

[codespell] fix readme

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

Currently the exporter does not propose init containers parameter, it can be useful for example to have an init job to create credentials

[prometheus-postgres-exporter] add initContainers

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/proxy.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/scheduler.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/statefulset.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-prometheus-node-recording.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-resources.yaml

Predominately added to fix the double CPU bug present in the `Kubernetes / Compute Resources / Pod` dashboard, but I'm sure there's a few other fixes coming in with that change.
I updated the python script to account for a URL change to the runbook which had broken the replacement. I've just adjusted it so no file changes occur to avoid breaking anything.

[kube-prometheus-stack] Sync grafana dashboards and prometheus rules from kube-prometheus

---

charts/prometheus-consul-exporter/Chart.yaml
charts/prometheus-consul-exporter/templates/servicemonitor.yaml
charts/prometheus-consul-exporter/values.yaml

Add service monitor for consul exporter

[prometheus-consul-exporter] Add service monitor for consul exporter

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

In order to install prometheus adapter on EKS that is using custom CNI (e.g. Calico), it needs to use hostNetwork. This setting is available but we also need to set the correct dnsPolicy, same way [it is done here for example](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L127).
- fixes https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/268

[prometheus-adapter] Add missing dnsPolicy for hostNetwork

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/node-exporter/daemonset.yaml
charts/prometheus/values.yaml

Adds in default enabling of flag `path.rootfs` with required mounts and volumes.
As per [docs](https://github.com/prometheus/node_exporter#using-docker) 
```
If you start container for host monitoring, specify path.rootfs argument. This argument must match path in bind-mount of host root. The node_exporter will use path.rootfs as prefix to access host filesystem.
```
Also enables default securityContexts for the pods (to match [prometheus-node-exporter] chart
@naseemkullah @monotek @Xtigyro @zanhsieh @gianrubio 
fixes https://github.com/prometheus-community/helm-charts/issues/447
- [ x] Title of the PR starts with chart name (e.g. …

[prometheus] - Fix/node exporter host bug

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

This fixes a regression from #375. That made the default dnsPolicy Default. This is *not* typically the default dnsPolicy of a cluster. In EKS the default is ClusterFirst.
I got an error message like this after installing the chart:
```
> kubectl top nodes
Error from server: Error while fetching node metrics for selector : unable to fetch node CPU metrics: unable to execute query: Get http://prometheus:9090/api/v1/query?query=...: dial tcp: lookup prometheus on XX.XX.0.2:53: no such host
```
Instead with this fix no dnsPolicy is set by default in the Deployment.

[prometheus-adapter] Default to not dnsPolicy to keep cluster default

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml

Enable the `AggregatedAPIDown` rule only for k8s >= 1.18 as the alert constantly fires on previous versions due to a bug fixed in 1.18
- fixes #122

[kube-prometheus-stack] Enable AggregatedAPIDown for k8s>=1.18 only

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

I went through the api specs of prometheus-operator 0.42.1 and added all the missing fields to the Prometheus and Alertmanager resources that I could find.
See https://github.com/prometheus-operator/prometheus-operator/blob/v0.42.1/Documentation/api.md

[kube-prometheus-stack] Add missing fields to prometheus and alertmanager

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
charts/kube-prometheus-stack/values.yaml

Full description in the issue referenced below
*tl;dr:* it is important to ensure the scrape interval defined in the Grafana data source matches the one configured by the Prometheus operator. Right now, default values do not match ([`15s`](https://grafana.com/docs/grafana/latest/datasources/prometheus/) vs. [`30s`](https://github.com/prometheus-operator/prometheus-operator/blob/release-0.44/pkg/prometheus/promcfg.go#L180-L183)).
Fixes #394
I'm bumping the _minor_ part of the chart's semver because the change does have an effect on the current default.

[kube-prometheus-stack] Align Grafana and Prometheus scrape intervals

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/values.yaml

This upgrades prometheus-adapter to v0.8.2. That's the latest available release at this time.
N/A

[prometheus-adapter] Upgrade to v0.8.2

---

charts/prometheus/Chart.yaml

Set correct appversion in prometheus chart

prometheus: change appversion to 2.22.1 matching prometheus server version

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/values.yaml

From the 1.16 version, they move the cloudsql-proxy image from alpine to distroless.
https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/317#issuecomment-540869722
Its make the lives probe starting to fail for us as well: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mysql-exporter/templates/deployment.yaml#L68
But they include other tags for folks that need a shell in the container: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/371
I did a test, seems good:
```
docker run -ti --rm gcr.io/cloudsql-docker/gce-proxy:1.19.1-alpine /bin/sh
/ $ nc
BusyBox v1.31.1 () multi-call binary.
Usage: nc [OPTIONS] HOST PORT  - connect
nc [OPTIONS] -l -p PORT [HOST] [PORT]  - listen
-e PROG	Run PROG after connect (must be last)
-l	Listen mode, for …
```

[prometheus-mysql-exporter] Use alpine cloudsql-proxy image

---

.github/CODEOWNERS
charts/prometheus-statsd-exporter/.helmignore
charts/prometheus-statsd-exporter/Chart.yaml
charts/prometheus-statsd-exporter/README.md
charts/prometheus-statsd-exporter/templates/NOTES.txt
charts/prometheus-statsd-exporter/templates/_helpers.tpl
charts/prometheus-statsd-exporter/templates/configmap.yaml
charts/prometheus-statsd-exporter/templates/deployment.yaml
charts/prometheus-statsd-exporter/templates/hpa.yaml
charts/prometheus-statsd-exporter/templates/ingress.yaml
charts/prometheus-statsd-exporter/templates/service.yaml
charts/prometheus-statsd-exporter/templates/serviceaccount.yaml
charts/prometheus-statsd-exporter/templates/servicemonitor.yaml
charts/prometheus-statsd-exporter/templates/tests/test-connection.yaml
charts/prometheus-statsd-exporter/values.yaml

Signed-off-by: disorder <disordervlz@gmail.com>
- I needed one, so I made it. Just though to share it will be nice.
- fixes #

[prometheus-statsd-exporter] add first release

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Signed-off-by: OlleLarsson <olle.larsson@elastisys.com>
In the `vaules.yaml` file the toleration entry takes the form of an empty map `tolerations: {}` but it should really be an empty list
```
kubectl explain Deployment.spec.template.spec.tolerations
KIND:     Deployment
VERSION:  apps/v1
RESOURCE: tolerations <[]Object>
```

[prometheus-elasticsearch-exporter] change tolerations from map to list

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/statefulset.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/etcd.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/k8s-cluster-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/k8s-node-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/nodes.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/pods.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards/statefulset.yaml
charts/kube-prometheus-stack/values.yaml

These changes enable to configure Grafana's dashboard to support multi cluster configuration.
Additionally, PR updates dashboards.
- fixes #356

[kube-prometheus-stack] #356 add support for multicluster in grafana dashboards

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/custom-metrics-apiservice.yaml
charts/prometheus-adapter/templates/external-metrics-apiservice.yaml
charts/prometheus-adapter/templates/resource-metrics-apiservice.yaml

* it adds support for `APIService` in version v1.
The version v1beta1 became deprecated in Kubernetes 1.19.
- fixes #461

[prometheus-adapter] Use the supported APIService API version

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

Configuring the fsGroup in the securityContext prevents an authentication issue when running the cloudwatch exporter in EKS
- fixes https://github.com/prometheus/cloudwatch_exporter/issues/303

[prometheus-cloudwatch-exporter] Add the fsGroup:65534 to the security context

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/ingress.yaml
charts/prometheus/templates/server/ingress.yaml

Adds support for ingressClassName for kubernetes >1.18. 
Fixes #507

[prometheus] add .Capabilities.APIVersions for IngressClass fixes #507

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
charts/prometheus-postgres-exporter/values.yaml

Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>
Adds the ServiceMonitor metricRelabelings and targetLabels key as documented in the [Prometheus Operator API](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint).
Used for adding, dropping or renaming labels at ingestion time, or to drop entire metrics that are not useful.
- fixes #
I've made similar changes in the past for other exporter charts:
- https://github.com/helm/charts/pull/23289
- https://github.com/helm/charts/pull/23288
- https://github.com/helm/charts/pull/23290
- https://github.com/helm/charts/pull/23291
- https://github.com/helm/charts/pull/23292
- …

[prometheus-postgres-exporter] Add ServiceMonitor metricRelabeling and targetLabels

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/servicemonitor.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Will be useful to be able to increase scrape timeout like we are doing in other charts that use serviceMonitor.

[stackdriver-exporter] add scrapeTimeout parameter

---

charts/prometheus/Chart.yaml

PR #508 and #470 used same chart version 13.0.1
```
$ git log --oneline charts/prometheus
034bbda1 (origin/main, origin/HEAD) Added absent allowedHostPath to psp for node-exporter (#470)
e4d7a0c7 (tag: prometheus-13.0.1) [prometheus] add .Capabilities.APIVersions for IngressClass fixes #507 (#508)
```
Therefor chart releasing failed for the second time as a chart with that version was already released.
This PR just bumps the version to create a new release with that change.
- fixes #

[prometheus] fix chart version

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/role.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/certmanager.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Adam Graves <adam.graves85@gmail.com>
Adds cert-manager support of generating the certs for the operator webhooks. This negates the need for the patch Job and means certs can be short lived going forward.

[kube-prometheus-stack] cert-manager support for operator webhooks

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml

PR #481 in `12.9.0` added support for using cert manager for operator webhooks. Unfortunately this seems to have broken the `ServiceMonitor` for prometheus-operator itself due to what looks like a typo on the correct `{{ if }}` to decide whether the CA certs are at key `ca.crt` or `ca` within the `Secret`.
The chart will work if `admissionWebhooks.certManager.enabled`, but not otherwise; as in both cases it is looking for the CA cert in the `ca.crt` key.
@velothump @bismarck

[kube-prometheus-stack] Correct path to `ServiceMonitor` ca cert when running with tls enabled

---

.github/workflows/check-codeowners.yaml
scripts/check-codeowners.sh

Script generates CODEOWNERS based on chart maintainers and checks if generated file shows a diff.
- fixes #

CI: Check if CODEOWNERS reflect chart maintainers

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

- Upgrade grafana dependency to 6.1
- ~~bump major version to match grafana breaking change~~ -> No, see below
- update prometheusOperator.configReloaderMemory from 25Mi to 50Mi to follow 0.44.0 change in https://github.com/prometheus-operator/prometheus-operator/pull/3660.
- Add Chart.lock in .gitignore
~~Should we add Chart.lock in .gitignore or add Chart.lock? ;)~~ -> yes

[kube-prometheus-stack] Upgrade grafana dependency to 6.1 & update configReloaderMemory default

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml

When templating with
`version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}`
a stray dash is inserted which causes the following error: 
```
Service \"prom-kubelet- --logtostderr=true\" is invalid: metadata.name: Invalid value: \"prom-kubelet- --logtostderr=true\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start w │
│ ith an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')"
```
This is because `-}}` [removes all trailing whitespace](https://golang.org/pkg/text/template/#hdr-Text_and_spaces), so the args get lumped together.
This PR resolves the error. Tested and verified …

[kube-prometheus-stack] Fix an errant dash in prometheus-operator's args

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml

The current `Deployment` specifies path to the TLS cert/key via relative paths that depend on the image default `WORKDIR`. Since the certs are always mounted from root by the chart; it would be clearer to specify this in the path rather than incidentally relying on `WORKDIR=/`.
This also improves interoperability for those re-using the chart with custom-built images which might change the working dir for various reasons; avoiding coupling with the way the image is built.
For example, we combine use of this chart with [the bitnami images](https://github.com/bitnami/bitnami-docker-prometheus-operator), which are regularly rebuilt for security/patching purposes; but which use an [alternate working dir](https://github.com/bitnami/bitnami-docker-prometheus-operator/blob/master/0/debian-10/Docke …

[kube-prometheus-stack] Avoid relying on working directory when specifying path to prometheus-operator TLS cert/key

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml

[kube-prometheus-stack] Fix accessing root (.Values....) in range block for datasources.timeInterval

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml

There is no way to scrap alertmanagerConfig resources from all namespaces. So I would like to add such a possibility.
As I see there is an issue #478 partially related to the Pull Request.  
I'm not sure, should I add new value like `alertmanager.alertmanagerSpec.alertmanagerConfigSelectorNilUsesHelmValues`, like here:
https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-12.8.0/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L104-L113

[kube-prometheus-stack] allow to select alertmanagerConfig resources from all namespaces

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml

Missing templating for the alertmanager tls field.  The alertmanager hosts field has it as well as prometheus hosts and tls fields.
#333

[kube-prometheus-stack] 333 - need to template the alertmanager tls settings as well

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/values.yaml

Allows setting a value for 'caBundle' for the admission webhook configurations. The feature enables providing a pre-existing certificate without using cert-manager, or the patch mechanism.

[kube-prometheus-stack] Allow setting caBundle value for admission webhook configuration

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/templates/alertmanager/sts.yaml

This PR is to address #241. In this stage, it only aims to allow the deployment to proceed properly.
It may be needed to also modify the `cluster.listen-address` parameter (it's now set to 0.0.0.0).
I've simply added brackets to the $(POD_IP) parameter; the alertmanager code seems to properly handle this, so using brackets around the IP address is supported by alertmanager for the "cluster.advertise-address" command line option for both ipv4 and ipv6 so this should not affect existing IPv4 functionality.
See: https://github.com/prometheus/alertmanager/blob/ce108378d4c8d580804452dcc3a31222067793b2/cluster/cluster.go#L135 - this uses net.SplitHostPort() which handles, as said above, brackets around the host.

Allow alertmanager to be deployed in IPv6 only environments 

---

charts/prometheus-statsd-exporter/Chart.yaml
charts/prometheus-statsd-exporter/templates/servicemonitor.yaml
charts/prometheus-statsd-exporter/values.yaml

Adding the configuration to set the `honorLabels` of the `statsd-exporter` `ServiceMonitor` to `true`

[prometheus-statsd-exporter] Adding `honorLabels` to `statsd-exporter` `ServiceMonitor`

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Sören Jentzsch <me@sjentzsch.de>
Make prometheus sharding configurable, as implemented in latest 0.44 prometheus-operator:
- https://github.com/prometheus-operator/prometheus-operator/pull/3241/files
- https://github.com/prometheus-operator/prometheus-operator/issues/3130

[kube-prometheus-stack] prometheus: add sharding mechanism

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: kamilswiec <kamilswiec@protonmail.com>
Comment in `serviceMonitorNamespaceSelector` in Values file points to `NamespaceSelector` which is invalid and if used causes errors. `serviceMonitorNamespaceSelector` should mention metav1.LabelSelector - reference https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

[kube-prometheus-stack] Values: fix missleading comment

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSIdecar.yaml
charts/kube-prometheus-stack/values.yaml

Add option to add headless svc for Thanos sidecar. Let Thanos Query can use `--store=dnssrv+_grpc._tcp.${kube-prometheus-stack.fullname}-thanos-discovery.infra.svc.cluster.local` to discovery Thanos sidecar.
Reopen for PR #309

Add option to add headless svc for thanos sidecar

---

charts/prometheus-cloudwatch-exporter/CHANGELOG.md
charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

This PR fixes the issue that when using STS to assume a role the global endpoint is used by default. If this is not accessible and a regional endpoint is configured the launched pods/containers will get in a crash loop. By setting the ENV variable `AWS_STS_REGIONAL_ENDPOINTS=regional` this tells the SDK to use the regional endpoint instead of the global endpoint.
- fixes #

[prometheus-cloudwatch-exporter] - Added option to enable sts regional endpoints

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md
charts/prometheus/values.yaml
ct.yaml

1) Updates the version of the `kube-state-metrics` dependency to `"2.9.*"` - this will allow for support of using the latest features of the chart
None.

[prometheus] Update Helm dependency to use new kube-state-metrics chart versions

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

helm/stable is deprecated. This removes the last dependency.

[kube-prometheus-stack] Migrate kube-state-metrics off helm/stable

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/templates/service.yaml
charts/prometheus-blackbox-exporter/values.yaml

Imagine we want to change the service port from 9115 to another value.
Because the `containerPort` in `deployment.yaml` is referring to service port, if we want to change the service port in `Values.yaml`, app will still listen in 9115 and container in the newly specified port and the probes will fail. That's why I think container port meant to listen to the `targetPort` in the `Values.yaml`.
Though I cannot see the reason why someone would like to do that, but the same issue will arise if someone changes the targetPort in `Values.yaml`. We should either change app listening port to be set to the targetPort [(here)](https://github.com/prometheus/blackbox_exporter/blob/57b2925620b3ea2d3bb20899e16a415c2d5dd95b/main.go#L55) or just remove the the line from `Values.yaml`. I didn't change that …

Changing default container port in prometheus-blackbox-exporter

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/certmanager.yaml
charts/prometheus-adapter/templates/custom-metrics-apiservice.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/templates/external-metrics-apiservice.yaml
charts/prometheus-adapter/templates/resource-metrics-apiservice.yaml
charts/prometheus-adapter/values.yaml

Signed-off-by: Adam Graves <adam.graves85@gmail.com>
Adds cert-manager support to the prometheus-adapter apiservice.

[prometheus-adapter] cert-manager support

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

Image Pull secrets option is not available in PostgresSQL chart

[prometheus-postgres-exporter] (feat): add imagePullSecrets

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

The Spotinst autoscaler does not support matchLabels (which is ridiculous IMO, but they are not going to fix it). They only support the newer matchExpressions syntax.  This PR switches to the newer syntax and should be 100% functionally identical to the previous `matchLabels` one. This syntax should work on all supported Kubernetes versions as it is part of the `*v1.Affinity` API.

[kube-prometheus-stack] Use matchExpressions instead of matchLabels in podAntiAffinity rules

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/hack/update_crds.sh
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

Updates prometheus-operator to 0.45.0 
https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.45.0

[kube-prometheus-stack] Version bump prometheus-operator to 0.45.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/service.yaml

This PR adds grpc thanos port to prometheus service. The thanos ingress was pointing to a non-existent port.
- fixes #426

[kube-prometheus-stack] Add grpc thanos port to prometheus service

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml

This PR completes https://github.com/prometheus-community/helm-charts/pull/357
and add multicluster to other dashboard. Some dashboard like CoreDNS,Controller
manager etc does not support cluster variable. I may add them in another PR

[kube-prometheus-stack]: enable multi cluster dashboards

---

charts/prometheus-to-sd/Chart.yaml
charts/prometheus-to-sd/templates/deployment.yaml
charts/prometheus-to-sd/values.yaml

Hi
`prometheus-to-sd` sends to Cloud Monitoring using [`gke_containers` Monitored resource types](https://cloud.google.com/monitoring/api/resources#tag_gke_container)
But, after March 31, 2021, Legacy Logging and Monitoring is no longer supported, and some resource type changed. https://cloud.google.com/stackdriver/docs/solutions/gke/migration#resource-changes
In prometheus-to-sd v0.5.2, [`monitored-resource-types`](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/prom-to-sd-v0.5.2/prometheus-to-sd/main.go#L55) flag exists and when use `monitored-resource-types=k8s`,new type is used.
https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/211#issuecomment-447974372
So, I added this flag as optional values.
I test this chat at my GKE cluster 1.17.14-gke.400 and it seems to …

[prometheus-to-sd]add optional monitoredResourceTypes

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/service.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Joe Rhodes <joe@purestake.com>
The Prometheus service that is created when Thanos sidecar is enabled _and_ the service is of type NodePort fails to validate/install.  It attempts to create a NodePort that is not in the valid NodePort range:  `Invalid value: 10901: provided port is not in the valid range. The range of valid ports is 30000-32767`
- [x ] Chart Version bumped
- [x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

[kube-prometheus-stack] Fix thanos grpc port when using service type NodePort

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

Signed-off-by: Petr Kohut <me@petrkohut.cz>
The Helm Chart doesn't support configuration for the `--constantLabels` flag which is available in https://github.com/wrouesnel/postgres_exporter .
The flag allow adding additional custom labels to all metrics provided by postgres-exporter.
I found the missing feature as a blocker for what I need to do on my project hence I made the PR :-)
*none
I decided to make the configuration of `constantLabels` a bit nicer by allowing a user to set it up as object (dictionary).
So instead having this in values.yaml:
```yaml
constantLabels: "customLabel1=x,customLabel2=y"
```
there can be:
```yaml
constantLabels: 
customLabel1: x
customLabel2: y
```
CC: @gianrubio @zanhsieh

[prometheus-postgres-exporter]add optional constantLabels

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

Signed-off-by: Arvid Widerberg <arvid.viderberg@gloot.com>
Adds functionality to add environment variables in the deployment of `prometheus-kafka-exporter`. This will allow me and others to use ConfigMap and Secret values as connection strings to the `kafka-server`. Example:
```yaml
env:
- name: KAFKA_URL
valueFrom:
secretKeyRef:
name: my-secret
key: url
kafka-server:
- $(KAFKA_URL)
```
- fixes #599
@gkarthiks @golgoth31

[prometheus-kafka-exporter] Add environment variables

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Add instructions on how to enable admission webhook TLS certificate provisioning via cert-manager to the readme.

[kube-prometheus-stack]: Document cert-manager usage

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Without config.templates defined any templates defined in templateFiles
will not be loaded. The default location and suffix are in line with the
examples in the alertmanager and kube-prometheus-stack docs.
Signed-off-by: Kevin Maris <kevin@kmaris.net>
Without config.templates set templateFiles will not be loaded in alertmanager.
- fixes #492
I was unsure of wording for the templateFiles doc section. Happy to update if you prefer something else.

[kube-prometheus-stack] Add config.templates

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/values.yaml

Allow adding labels to the pods so we can contact rabbitmq pods when a networkpolicy is enabled.

[prometheus-rabbitmq-exporter] Make it possible to add labels to the pods 

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

- Reduces extraneous metrics related to filesystems that are not particularly interesting
- Increases consistency with upstream node-exporter's default configuration

[kube-prometheus-stack] Update list of excluded fs types and mountpoints in node exporter collector

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/psp.yaml
charts/kube-prometheus-stack/values.yaml

This PR allowes end users to configure extra volumes and allowedHostPaths. This is often used when a TLS certificate is required in order to auth agains ETCD databases.
In our usecase we run an init container that fetches ETCD TLS keys from the host (by mounting a hostpath as read only) and later copies it to an emtydir stored in memory.
- fixes # N/A

[kube-prometheus-stack] Allow users to add extra psp volume and configure allowedHostPaths

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Add the option to add additional labels to pods.
One need that we have is to add the label `app.kubernetes.io/part-of: elasticsearch-exporter` to forward it to the right index pattern for our ELK log stack, but we could have wanted other labels as well for other needs.

[prometheus-elasticsearch-exporter] Add additional pod labels support

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/deployment.yaml
charts/prometheus-stackdriver-exporter/templates/service.yaml
charts/prometheus-stackdriver-exporter/templates/serviceaccount.yaml
charts/prometheus-stackdriver-exporter/templates/servicemonitor.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Adding relabeling configs to its serviceMonitor. Will be useful to improve Prometheus cardinality.

[stackdriver-exporter] feat: Adding relabeling config to serviceMonitor

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

Signed-off-by: Pavol Stanka <stanka@ehs.sk>
This allows alertmanager to be used in HA mode, either in one cluster or between clusters.
fixes #598 
@monotek , @naseemkullah

[alertmanager] allow possibility to use alertmanager in HA

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

@gianrubio @zanhsieh 
In some casses initial query to the database, for some complex queries, takse more time than the succeding. This time might be so long it exceeds the time for liveness and readiness probe. This fails and restarts the container even before the initialisation can be succesfully done.
This MR adds initialDelaySeconds configuration option to allow setting it when needed.

[prometheus-postgres-exporter] add initialDelaySeconds configuration

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

… 
This PR adds overridability of the prometheus and alertmanager base image which we are in need of as we are retagging images so they can be deployed in China (customer registry) and having to specify the image to use in every CR should be unnecessary if we can define the default image to use

[kube-prometheus-stack] Allow override of prometheus and alertmanager default base images

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Signed-off-by: Aaron Webre <aaron.webre@g5platform.com>
The `frodenas/stackdriver-exporter` docker image's latest tag is `v0.6.0`, and it looks like `v0.7.0` and up are getting pushed to `prometheuscommunity/stackdriver-exporter`. Changing image repository accordingly and using most recent tag. Also bumping chart and app versions.

[prometheus-stackdriver-exporter] Using prometheus community docker image instead of deprecated version

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/templates/monitor.yaml
charts/prometheus-node-exporter/templates/serviceaccount.yaml
charts/prometheus-node-exporter/values.yaml

Signed-off-by: Philippe Bürgisser <philippe.burgisser@camptocamp.com>
- Adding secrets mount used to expose for eg tls certificate used by oauth proxy
- Changed port variable in daemonset so we can keep node-exporter on the same port but targetPort points to the sidecar container

[prometheus-node-exporter] Adding secret support for oauth psidecar

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml

Fixes port mismatch introduced in 13.4.0 by https://github.com/prometheus-community/helm-charts/pull/400
- `containerPort` doesn't match the port specified in the container args with `web.listen-address`
- operator target is therefore unreachable using the address provided by the `ServiceMonitor`
@gkarthiks as you were the maintainer involved in the previous change
I've confirmed that this fixes the issue by manually editing the `Deployment` on our cluster so that the `arg` matches the `containerPort`.

[kube-prometheus-stack] fix: match containerPort and listen-address in operator

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/servicemonitors.yaml
charts/kube-prometheus-stack/values.yaml

- This PR adds `podTargetLabels` fields to `additionalServiceMonitors` of Prometheus deployment in the `kube-prometheus-stack` chart.
- The field is described in [the API documentation](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec) but missing in the `values.yaml` file.

[kube-prometheus-stack] podTargetLabels in additional ServiceMonitors

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/deployment.yaml
charts/prometheus-pushgateway/values.yaml

Signed-off-by: Nick Abt <nicholas-abt@pluralsight.com>
It adds `imagePullSecrets` handling for the deployment of the `prometheus-pushgateway` chart to allow injection of `imagePullSecrets` for custom image registries.  This brings the chart in line with other prometheus charts and common practices.  Such registries are commonly in use in airgapped Kubernetes instances.

[prometheus-pushgateway] Adds imagePullSecrets value for deployment

---

charts/prometheus-pushgateway/Chart.yaml

Last release failed
https://github.com/prometheus-community/helm-charts/runs/1834138576?check_suite_focus=true
PRs #608 and #453 used same chart version
- fixes #

[prometheus-pushgateway] fix failed release

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Syncs with latest kube-state-metrics chart

[kube-prometheus-stack] Sync kube-state-metrics

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/templates/node-exporter/daemonset.yaml
charts/prometheus/templates/pushgateway/deploy.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/values.yaml

[prometheus] Ability for custom dnsConfig

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

What this PR does / why we need it:
Split of #554
Which issue this PR fixes
Part of #634

[alertmanager] Ability for custom dnsConfig 

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

[prometheus-elasticsearch-exporter] Ability for custom dnsConfig

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
charts/kube-prometheus-stack/values.yaml

Optional parameter.
Allow to decorelate prometheus.prometheusSpec.scrapeInterval from the one in grafana default datasource.
Sometimes, you have some ServiceMonitors with high frequency (let's say 10 seconds) but grafana is still limited to 30s or whatever value you set for the default Prometheus `scrapeInterval`.
- fixes #

[kube-prometheus-stack] introduce grafana.sidecar.datasources.defaultDatasourceScrapeInterval

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

Split of #554
Part of #634
Last part of #634.
Fixes #634

[prometheus-node-exporter] Ability for custom dnsConfig

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
- Add opportunity to specify log.level argument for exporter container in deployment manifest

[prometheus-postgres-exporter] add opportunity to specify log.level in container args

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/configmap.yaml
charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
charts/prometheus-cloudwatch-exporter/templates/ingress.yaml
charts/prometheus-cloudwatch-exporter/templates/secrets.yaml
charts/prometheus-cloudwatch-exporter/templates/service.yaml
charts/prometheus-cloudwatch-exporter/templates/serviceaccount.yaml

Set namespace on objects where it is not set, to `.Release.namespace`

[prometheus-cloudwatch-exporter] Set namespace

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/deployment.yaml
charts/prometheus-mysql-exporter/values.yaml

Adds securityContext and podSecurityContext to be able to run the image as a `nobody` user

[prometheus-mysql-exporter] Add securityContext and podSecurityContext

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Update node exporter chart to current version

[kube-prometheus-stack] update node exporter chart to 1.14.*

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

* Upgrade grafana dependency to 6.4 (includes Grafana 7.4.1)
None

[kube-prometheus-stack] Upgrade grafana dependency to 6.4

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/templates/alertmanager/sts.yaml
charts/prometheus/templates/node-exporter/daemonset.yaml
charts/prometheus/templates/pushgateway/deploy.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml

The `imagePullSecrets` list is not indented enough; and applying charts with `imagePullSecrets` set fails with errors like `Error: YAML parse error on prometheus/templates/alertmanager/deploy.yaml: error converting YAML to JSON: yaml: line 74: did not find expected key`.
It seems hard to imagine this bug went unnoticed for >2 years, so I'm guessing newer versions of helm are more strict about indentation.

[prometheus] fix imagePullSecrets indentation

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/serviceaccount.yaml
charts/prometheus-postgres-exporter/values.yaml

Allow setting annotations on the ServiceAccount used by the
postgres-exporter Deployment. If we are running a sidecar container such
as the Google Cloud SQL Proxy we can annotate the service account to
enable Workload Identity. The approach is the same in EKS clusters
also.
I notice in the `values.yaml` there is already a reference to running the
cloud SQL proxy as a sidecar container.

[prometheus-postgres-exporter]: Add annotations to postgres-exporter ServiceAccount

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/custom-metrics-apiservice.yaml
charts/prometheus-adapter/templates/external-metrics-apiservice.yaml
charts/prometheus-adapter/templates/resource-metrics-apiservice.yaml

The APIService templates will error in their current state due to fields being unintentionally merged into one line.
Signed-off-by: Joe Hohertz <joe@viafoura.com>
Corrects whitespace errors in the template rendering.
Didn't see existing issue on this.
Needs to have the API service records enabled to see the error.
- [*] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [*] Chart Version bumped
- [*] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

[prometheus-adapter] Fix overzealous whitespace trimming.

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
charts/kube-prometheus-stack/templates/prometheus/ingress.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
charts/kube-prometheus-stack/values.yaml

Kubernetes 1.18 brought a few changes in API for ingress, one of which is the `pathType` field that can specify how Ingress paths should be matched.
`pathType` could be one of the following: `ImplementationSpecific`, `Exact`, `Prefix` (defaults to `ImplementationSpecific`).
API gives controllers freedom to decide what `ImplementationSpecific` means to them. - They could treat it as a separate `PathType` or identically to `Prefix` or `Exact` path types.
To give some examples, for nginx `ImplementationSpecific` = `Prefix`, for `Istio` - `Exact` (meaning, you can't access subpaths in URI, by default). That's why it's important to support this feature in the chart.

[kube-prometheus-stack] Added pathType

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Nozomu Ohki <nozomunoise@gmail.com>
This allows users to configure topologySpreadConstraints.

[kube-prometheus-stack] add Prometheus and Alertmanager topologySpreadConstraints

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Upgrades to latest kube-state-metrics v1.9 version
- fixes #373

[kube-prometheus-stack] Upgrade to latest kube-state-metrics chart

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
introduces extraVolume + Mounts if the volume you want to mount is not a secret (ex: csi volumes) for secrets-store implementation.
n/a
n/a
- [ x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

[prometheus-elasticsearch-exporter] Introduce extraVolume/Mounts

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Signed-off-by: David Calvert <davidcalvertfr@gmail.com>
Adds a missing upgrade command for alertmanager to do before upgrading to 13.x
This PR fix a migration of a previous deployment to 13.x
If you do not update alermanager's CRD, you  will have the following error during a helm upgrade: 
`Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]`
Let me know if there's anything missing in this PR.
@vsliouniaev @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro

[kube-prometheus-stack] Added missing upgrade command for alertmanager to do before upgrading to 13.x

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/deployment.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Signed-off-by: Whyeasy <Whyeasy@users.noreply.github.com>
Add the capability to provide a custom key to load the credentials from in a secret.

[prometheus-stackdriver-exporter] Add feature for custom key.

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Signed-off-by: Whyeasy <Whyeasy@users.noreply.github.com>
scrapeTimeout was on the wrong location and when applied gave an error at the creation of the ServiceMonitor.

[prometheus-stackdriver-exporter] Moving scrapeTimeout to the correct location.

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/ingress.yaml
charts/prometheus-pushgateway/templates/servicemonitor.yaml

Signed-off-by: Stanislav Khalash <stanislav.khalash@sap.com>
Most of the templated resources are using the `prometheus-pushgateway.defaultLabels` template to insert labels. The only difference is `Ingress` and `ServiceMonitor`, where the labels are hard-coded. This PR eliminates code duplication by aligning label handling for all resources.

[prometheus-pushgateway] Align resource label handling

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/values.yaml

In the case of using custom CNI such us calico on EKS, prometheus-server needs to use hostNetwork. The same setting is available in kube-prometheus-stack chart.

[prometheus] Allow to enable hostNetwork

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

This updates the readme to include instructions for upgrading. These are just the standard 'upgrade your CRDs because Helm won't'.
Fixes #745 
Arguably we could remove a few of these CRDs, since the only change with them is a `categories` entry. However it's probably better to remain in lockstep with the upstream CRDs as much as possible.

[kube-prometheus-stack] Update README with 13.x to 14.x upgrade instructions

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/node-exporter/daemonset.yaml
charts/prometheus/values.yaml

Makes it configurable if node-exporter daemonset should mount `/` from host or not. Default to `true` to keep existing default behavior.
As seen in issue #467, it is not always possible to mount / from host in all environments.
- fixes #467 (but perhaps needs similar change to the node-exporter chart as well?)
> For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@gianrubio , @zanhsieh , @Xtigyro , @monotek , @naseemkullah

[prometheus] make path.rootfs conditional

---

charts/prometheus-statsd-exporter/Chart.yaml
charts/prometheus-statsd-exporter/templates/_helpers.tpl
charts/prometheus-statsd-exporter/templates/servicemonitor.yaml

Addresses https://github.com/prometheus-community/helm-charts/issues/649
Signed-off-by: Duncan Schulze <duncan.schulze@cloudcheckr.com>
- fixes #649

[prometheus-statsd-exporter] Fix statsd service monitor config

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/values.yaml

Bumps the postgres_exporter version to the 0.9.0 that was recently released:
https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.9.0
Also changing the image repo to point to the current one mentioned in the readme:
https://github.com/prometheus-community/postgres_exporter/tree/v0.9.0#quick-start

[prometheus-postgres-exporter] Update to postgres_exporter 0.9.0

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/values.yaml

Signed-off-by: ffafi <firas.fafi@polarsquad.com>
@monotek @naseemkullah 
I'm providing here minors changes for Service Annotations. I have noticed that it's not configurable via the Alertmanager Helm chart. 
The annotations might be useful for some custom clusters, in kube-stack-prometheus chart it's already enabled but here it's missing.
There are also cases when the alertmanager is linked to different Prometheus instances via external endpoint and this might involve exposure of service via LoadBalancer mode and custom annotations.
Example of usage for being able to expose service privately via LB mode or define domain using external-dns ... 
```
service:
annotations:
external-dns.alpha.kubernetes.io/hostname: mydomain.com
service.beta.kubernetes.io/azure-load-balancer-internal: true …
```

[Alertmanager] update: Enable annotations for service tpl

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/values.yaml

Updates node exporter to v1.1.2

[prometheus-node-exporter] AppVersion bump to 1.1.2

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Minor typo fix and formatting of comments that references PrometheusRules.
- fixes #

[kube-prometheus-stack] Fix typo and formatting in comments

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

Allows to opt-out the node-exporter deamonset mount of / from the host. This is necessary because it's not always possible to do it. To avoid changing the current behaviour of the chart the defaul value is set to true.
#467
Another PR (no. 737) with similar changes has already been merged, but it did not modify all required charts.
Moreover, in order to completely fix the related issue, the `kube-prometheus-stack` chart dependency version with this must be bumped to `1.15.*`. Let me know if I have to create another PR for this change or you can do it directly.

[prometheus-node-exporter] Allow to opt-out node exporter rootfs mount

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml

Signed-off-by: Andrey Afoninskiy <andrey.afoninskiy@mambu.com>
This PR fixes bug in "node-exporter" when existing service account is ignored (.Values.serviceAccount.name is specified and .Values.serviceAccount.create is `false`)

[prometheus-node-exporter] use custom service accounts

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml

@monotek @naseemkullah
**What this PR does / why we need it:**
It's a follow up fix from recently closed PR: https://github.com/prometheus-community/helm-charts/pull/767
The service tpl annotation was merged with wrong indentations.
I'm totally agreeing with @monotek  nit: reads better and much safe :) 
Issue:
```
{{- if .Values.service.annotations }}
annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
```
Fix:
```
{{- if .Values.service.annotations }}
annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
```
Thank you!

[Alertmanager] fix indentation service annotations

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml
charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/values.yaml

I think that bitnami rmq helm chart most popular. 
And they changed secret key for storing rabbitmq password from 'password' to 'rabbimq-password'
https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/secrets.yaml#L12

 [prometheus-rabbitmq-exporter] update default rabbitmq secret key

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/README.md
charts/prometheus-postgres-exporter/values.yaml

Adding the latest default queries.yaml from upstream:
https://github.com/prometheus-community/postgres_exporter/blob/v0.9.0/queries.yaml
Also updating some links that refer to the `wrouesnel/postgres_exporter` repo.
Figured this required a minor chart version bump since it will change the defaults.

[prometheus-postgres-exporter] Update to the latest default queries.yaml

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

This PR adds 2 new abilities to Alertmanager chart :
* add the possibility to specify our own command
* add the possibility add annotations to the statefulset Pod (e.g. podAnnotations)
When you want to use Vault Sidecar Injector (https://www.vaultproject.io/docs/platform/k8s/injector) you first need to be able to specify annotations to your pod.
This will create a file `/vault/secrets/whatever`.
Then, in order to take that file into account, the easier way is to use it on the command line, usually like this : `['source /vault/secrets/whatever; /bin/alertmanager']`
This is why this patch allows adding podAnnotations and command.
Note : I did not update Chart Version because it depends on when the PR is merged.
Edit : I finally updated it.

[Alertmanager] command podannotations

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Updates `kube-prometheus-stack` chart to use the latest `prometheus-node-exporter`. This is necessary to be able to use the new features added with PR #757 from the parent chart.
This completely solves the issue: #467

[kube-prometheus-stack] Update dependency version

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/_rules.tpl
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

When enforcedNamespaceLabel is enabled the default rules installed by the
helm chart also also changed dynamically by the operator at runtime.
This breaks cluster wide recorded rules and alert rules.
This patch ensures that default prometheus rules are automatically
added to `prometheusRulesExcludedFromEnforce`

[kube-prometheus-stack] Exclude default rules from namespace enforcement

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Vlad Paciu <vlad.paciu@adgear.com>
This PR is intended to give more control over what will be deployed 
if kubescheduler, kubeproxy, controllermanager, etcd exporters are enabled. 
Currently they are coupled with  grafana dashboard and prometheus rules altogether.
In my case I'm using this chart to monitor rancher cluster.
This system components are listening only on localhost in rancher cluster. 
To get metrics I'm using pushProx which already creates ServiceMonitor and service. 
- [ x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x ] Title of the PR starts with chart name

[kube-prometheus-stack] add more controls to kubescheduler,kubeproxy,controllermanager,etcd exporters

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/serviceaccount.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Signed-off-by: Ankit Mehta <ankit.mehta@appian.com>
This change adds `automountServiceAccountToken` to the serviceAccount template. This field has a default value of true and that is set on the values.yaml file in this PR. This would allow someone to set it to false for their use case.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
- fixes #
I am happy to add this field to serviceAccounts in other charts (in this repo) as well. Please let me know if that is something you all want.

[prometheus-elasticsearch-exporter]Allows you to set automountServiceAccountToken on ServiceAccount

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Esther Kim <jabbukka@naver.com>
- ClusterIP should not be set "None" when service type is `NodePort`.  
- Also, renamed wrong filename from `serviceThanosSIdecar.yaml` to `serviceThanosSidecar.yaml`
- Bump up to 14.3.1
- fixes #783

[kube-prometheus-stack] Invalid value "None" for clusterIP

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/prometheusrule.yaml

I don't know if we should keep the old rules, if we should only bump the patch version...
The existing rules are vague.

[prometheus-rabbitmq-exporter] Polish up Prometheus rules

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/daemonset.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Add support for host network on blackbox
Probes can require special network setup that is provided only by the host.

[prometheus-blackbox-exporter] Add support for hostNetwork

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

* Update Grafana dependency to 6.7.*
* Update kube-state-metrics in Chart.lock to 2.13.1
Would it be useful to use something like Renovate ( https://github.com/renovatebot/renovate ) to automatically create dependency Bump PRs? I believe Depenendabot does not support this (yet)

[kube-prometheus-stack] Update grafana dependency to 6.7.*

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/certmanager.yaml

@vsliouniaev , @bismarck , @gianrubio , @gkarthiks , @scottrigby , @Xtigyro 
cert-manager updates the certificate specification and sets the duration including minutes and seconds. this leads to a representation of e.g. `8760h0m0s` instead of `8760h` which is generally fine if you only apply and use the chart.
however, when using tools like argo-cd which synchronise and auto-heal out-of-sync manifests, this is detected as a drift and will get synchronised over and over again.
setting minutes and seconds in the specification resolves this problem.

[kube-prometheus-stack] set cert-manager generated certificate duration to include minutes and seconds

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

This PR adds `additionalRemoteWrite` and `additionalRemoteRead`. We are using `kube-prometheus-stack` as dependency in our helm chart and already added some `remoteWrite` configuration. It is common that our customers want to extend `remoteWrite` with additional configuration. In order to do it now, they have to copy our `remoteWrite` section and add their config at the end of it. This is because lists in helm config files are not merged. We would like to make it easier for them. `additionalRemoteRead` is added to keep parity with `remoteWrite`
N/A

[kube-prometheus-stack] add additionalRemoteRead and additionalRemoteWrite

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Signed-off-by: Imaya Kumar Jagannathan <ijaganna@amazon.com>
This PR bumps up the Prometheus chart version to v2.26 to include changes in [PR 8509](https://github.com/prometheus/prometheus/pull/8509)
@monotek

[prometheus] Bump up chart version to v2.26 

---

charts/prometheus-pingdom-exporter/Chart.yaml
charts/prometheus-pingdom-exporter/templates/_helpers.tpl
charts/prometheus-pingdom-exporter/templates/deployment.yaml
charts/prometheus-pingdom-exporter/templates/secret.yaml
charts/prometheus-pingdom-exporter/values.yaml

This PR adds the ability to specify an existing `Secret` in place of the generated secret when the chart is installed. This is useful in our case because we manage our secrets externally so already have a secure mechanism in place to generate this.
N/A

[prometheus-pingdom-exporter] Add secret override for pingdom exporter

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Ascii charaters are not well supported by kustomize due to pyyaml
underlying lib limitations.
Special chars doesn't bring any value here, so removing them
from the file is probably the most simple solution here.
Signed-off-by: Barthelemy Vessemont <bvessemont@gmail.com>

[kube-prometheus-stack] Avoid using non-ascii char in values.yaml

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

Signed-off-by: Vlad Paciu <vlad.paciu@adgear.com>
What this PR does / why we need it: 
- Allows adding custom initContainers to node-exporter.
It could be useful in case you enable textfile collector and you have to create a folder for it.
@bismarck
@vsliouniaev

[prometheus-node-exporter] 1.16.0 Allow to configure init containers

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

`.Values.prometheus.serviceAccount.annotations` is used in [/templates/prometheus/serviceaccount.yaml#L10](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/serviceaccount.yaml#L10) but not mentioned in values.yaml

[kube-prometheus-stack] Add service account annotations

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Vlad Paciu <vlad.paciu@adgear.com>
* Update node-exporter to 1.17.0
* Update Grafana dependency to 6.7.4
* Update kube-state-metrics in Chart.lock to 2.13.2

[kube-prometheus-stack] Update node-exporter dep to 1.17.0 + kube-state-metrics to 2.13.2 + grafana to 6.7.4

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
charts/kube-prometheus-stack/values.yaml

This PR adds an optional namespaceSelector to the `kube-state-metrics` ServiceMonitor. This is useful because if you override `kube-state-metrics.namespaceOverride` to deploy kube-state-metrics elsewhere, the ServiceMonitor that is deployed does not work. 
- fixes #820

[kube-prometheus-stack] add optional kube-state-metrics ServiceMonitor namespace selector

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/node-exporter/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: r.maika <r.maika@samsung.com>
This PR enables an argument for `proxyUrl` to any ServiceMonitor objects that are under the `./exporters/` path. 
This supports the pattern that is used by some to expose metrics for cluster components on localhost only, then scrape them through a proxy. For example, when using https://github.com/rancher/PushProx as a vehicle to expose metrics, it is now required to have `proxyUrl` configured on the ServiceMonitor. I would like to be able to do this while still using this chart to create/configure the ServiceMonitor object and other Prometheus objects. 
@vsliouniaev @bismarck @gkarthiks @scottrigby @Xtigyro

[kube-prometheus-stack] Add proxyUrl variable to exporters

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

The current version of this chart uses the `tpl` function for `extraContainers`, `extraVolumes` and `extraVolumeMounts` which enforces the user to provide them as strings like:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
name: prometheus-postgres-exporter
namespace: monitoring
spec:
chart:
spec:
chart: prometheus-postgres-exporter
version: ">=2.2.0 <2.3.0"
sourceRef:
kind: HelmRepository
name: prometheus-community
namespace: flux-system
interval: 5m0s
values:
enabled: true
extraContainers: |
- name: cloud-sql-proxy
image: gcr.io/cloudsql-docker/gce-proxy:1.17
command:
- "/cloud_sql_proxy"
- "-instances=INSTANCE_CONNECTION_NAME=tcp:5432"
securityContext:
runAsNonRoot: true
```
To make it more intuitive and to align more with other …

[prometheus-postgres-exporter] Use arrays instead of strings for extraContainers, extraVolumes and extraVolumeMounts

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/values.yaml

Upgrades prometheus-operator to https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.47.0

[kube-prometheus-stack] Update prometheus-operator to 0.47.0

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/templates/alertmanager/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceaccount.yaml

See: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
- fixes #

[kube-prometheus-stack] Recommanded Kubernetes labels

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
charts/kube-prometheus-stack/templates/prometheus/ingress.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml

Fixes the context change in the range loop of the paths causing root .Values to not be addressable.
Had to deal with DCO in #870 
- fixes oversight in https://github.com/prometheus-community/helm-charts/pull/850

bugfix: Urgent - Fix context change in range for ingress apiversions

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

This PR will fix https://github.com/prometheus-community/helm-charts/issues/876 which leads to issues if long lines used in grafana.ini block.

[kube-prometheus-stack] #876 Update kube-prometheus-stack grafana dependency to 6.8.0

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

cluster-peer name, was not exactly following statefullSet name. Now it should work also if nameOveride/fullNameOveride is used.
- fixes #

[alertmanager]fix cluster-peer name follow statefullSet name 

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

Signed-off-by: Pavol Stanka <stanka@ehs.sk>
Fixing my previous commit, it seems pod name is not sufficient for in cluster communication for peers. Most probably because of "headless" service port forwards.
- fixes #
Sorry for inconvenience.

[alertmanager] fix, cluster-peer needs to be name+service

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/deployment.yaml
charts/prometheus-mysql-exporter/templates/secret-env.yaml
charts/prometheus-mysql-exporter/values.yaml

* creates the possibility to use existingPasswordSecret, containing only the mysql password, where name and key can be configured
* keeps old exisitingSecret to not break functionality for existing users
- fixes #

[prometheus-mysql-exporter] make existing secret config more flexible

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml

When there is another service in kube-system that matches for the ServiceMonitor "kube-prometheus-stack-kubelet"
```
kube-prometheus-stack-kubelet                   ClusterIP   None          <none>        10250/TCP,10255/TCP,4194/TCP   39d
kubelet                                         ClusterIP   None          <none>        10250/TCP,10255/TCP,4194/TCP   31d
```
an error occurs like described in #614. This PR adds an additional filter that ignores the other service.
* fixes #614

[kube-prometheus-stack] Add matchLabel to prevent duplicate kubelet targets

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/values.yaml

Signed-off-by: Shaun Creary <shaun.creary@booking.com>
Bumps the Prometheus Adaptor to 0.8.4 to enable the latest version and benefit from the enhancements.
N/A

prometheus-adapter: upgrade appversion to v0.8.4

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/README.md
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/templates/role.yaml
charts/kube-state-metrics/templates/rolebinding.yaml
charts/kube-state-metrics/values.yaml

* Version bump kube-state-metrics to 2.0.0
* Upgrade chart api version to v2
@tariq1890

[kube-state-metrics] Version bump to 2.0.0

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

Signed-off-by: Evyatar Cohen <coevyatar@gmail.com>
This PR adds the option to specify Kafka broker version to `kafka_exporter`. While trying to install `kafka_exporter` via the chart, an error of connection failure is returned and looking under Kafka's logs an error regarding api key is returned.
Changing the broker version manually worked and this change will help those who encounter similar issue.
No issue in issues.

[prometheus-kafka-exporter] Add kafka broker version

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
charts/kube-prometheus-stack/templates/prometheus/ingress.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml

fix Capabilities.APIVersions.Has check for ingress API version. Latest chart version fails to install on Kubernetes v1.18 which is kind of stuck in the middle of the v1beta1 et v1 networking API
- fixes #884

[kube-prometheus-stack]: fix Capabilities.APIVersions.Has check for ingress API version

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Switches kube-state-metrics over to the new location inside of this repository
Synchronizes Chart.lock

[kube-prometheus-stack] New location for kube-state-metrics

---

charts/prometheus-nats-exporter/Chart.yaml
charts/prometheus-nats-exporter/templates/service.yaml
charts/prometheus-nats-exporter/values.yaml

Signed-off-by: brunopadz <bpadz@protonmail.com>
This PR adds the option to specify annotations in the service that exposes `nats-exporter`. This is necessary specially when creating a service type `LoadBalancer` on major cloud providers to specify what type of Load Balancer will be used and whether it's internal or external. 
No issue.

[prometheus-nats-exporter] support service annotations

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

Add templating helm function to kube-prometheus remote config. On using kube-prometheus as a dependent helm chart passing {{ .Release.Name}} & {{ .Release.Namespace }} the respective values aren't parsed as tpl function isn't used.
Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>
Parse `remoteWrite` & `remoteRead` config with template function to parse the `releaseName` & `namespace` when kube-prometheus is used as an dependent helm chart. 
#874

[kube-prometheus-stack]: Parse Prometehus remote config using tpl 

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

Signed-off-by: Boris Puterka <boris.puterka@gmail.com>
It's just a small thing, but it allows us to configure securityContext on container level.
- fixes #
Normally I would use `.Values.podSecurityContext` and `.Values.securityContext` but this allows backward compatibility.

[prometheus-cloudwatch-exporter] Allow container security context to be configured

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/additionalPrometheusRules.yaml

`helm lint` want metadata.name for every resource:
```
[WARNING] templates/prometheus/additionalPrometheusRules.yaml: object
name does not conform to Kubernetes naming requirements: "":
metadata.name: Invalid value: "": a lowercase RFC 1123 subdomain must
consist of lower case alphanumeric characters, '-' or '.', and must
start and end with an alphanumeric character (e.g. 'example.com', regex
used for validation is
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
1 chart(s) linted, 0 chart(s) failed
```

[kube-prometheus-stack] fix lint in additional-prometheus-rules

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceaccount.yaml

Signed-off-by: Simon Roberts <simon.roberts@anz.com>
Don't include elements that we don't need (and can cause problems for config-management systems).
Fresh PR to replace #918 
- fixes #917

[kube-prometheus-stack] Omit imagePullSecrets element if no secrets provided

---

charts/alertmanager/Chart.yaml
charts/alertmanager/values.yaml

Signed-off-by: Niklas Wagner <Skaro@Skaronator.com>
Using quary.io image instead of the docker hub image due to pull limits. This change is already done in the prometheus helm chart: https://github.com/prometheus-community/helm-charts/blob/8302e6aa5e5732a49a73943aa1b82050f690a077/charts/prometheus/values.yaml#L49-L51

[alertmanager] Use quay.io image instead of docker hub

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/README.md
charts/prometheus-adapter/values.yaml

After comparing values queried by metrics server and the prometheus adapter, I noticed about 2X factor,
It is originating from not filtering this query for rows with empty container.
- fixes #

[prometheus-adapter] filter resource metrics for pod for real row

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

Also, fixing syntax error related to configMapReload resource declaration
1. When alertmanager chart is used with `nodeSelector` `affinity` or `tolerations` along with `persistence.enabled = True`, the chart deployment fails due to indentation issues. These 3 keys are supposed to be a part of `spec.template.spec` whereas `volumeClaimTemplates` should be a child of `spec`. Fixed this by re-ordering.
2. For `configmapReload.resources`, fixed an indentation issue by chomping whitespace using `{{-`. Also used `nindent` to be consistent with the default container. [Check](https://github.com/prometheus-community/helm-charts/blob/079bcdf9d8d28a30aeb42b22027f6c298dcdd903/charts/alertmanager/templates/statefulset.yaml#L100)
NA

[alertmanager] Fixing indentation for node selector keys in case persistence is enabled

---

charts/prometheus/Chart.yaml

Update kube-state-metrics sub-chart to v3.0.*
None

[prometheus] Updated kube-state-metrics sub-chart to version 3.0.*

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/role.yaml
charts/kube-state-metrics/values.yaml

Looks like there is a bug affecting kube-state-metrics if a user sets `useClusterRole=false` and `namespace=<namespace1>,<namespace2>`. When a user sets those two values, they expect multiple `Role`s to be created (one per namespace), but instead it errors:
```
$ cd charts/kube-state-metrics/
$ helm template --debug --set namespaces="ns1\,ns2" --set namespace="ns1\,ns2" --set rbac.useClusterRole=false .
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /Users/machaffe/personal/mac-prom-helm/charts/kube-state-metrics
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
labels:
app.kubernetes.io/name: kube-state-metrics
helm.sh/chart: kube-state-metrics-3.0.2
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/instance: RELEASE-NAME …
```

[kube-state-metrics] Fix rbac.useClusterRole=false behavior

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

The current templating causes the combination of `persistence.enabled: false` and using `tolerations` or `nodeSelector` will produce an invalid StatefulSet spec with the storage volume sitting in the tolerations or nodeSelector stanza
- fixes #

[alertmanager] Move tolerations and nodeSelector to not disrupt volumes

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/daemonset.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: Cristi Vlad <vlad_crst@yahoo.com>
Add possibility to customize config file path
Needed for integration with vault and vault-agent-injector
n/a
@desaintmartin: Closed previous PR (980) and open a new one
Maybe you can help me again with this PR. Thank you !

[prometheus-blackbox-exporter] - Added option to customize config path by setting it into values file

---

charts/prometheus/Chart.yaml

To keep Prometheus chart updated with the latest kube-state-metrics chart.
None

[prometheus] kube-state-metrics subchart updated 3.0.* to 3.1.*

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml

Removes the API capability check on the ServiceMonitor. Reasoning here is that there's already an opt-in flag on `serviceMonitor.enabled`.
This fixes the use-case where `helm` is responsible only for templating and releasing is performed by another tool. This is the behavior of Spinnaker's manifest render engine that uses Helm to bake the manifests it applies to a cluster separately. The capabilities check fails and we have no way of getting a ServiceMonitor. 
I omitted changes to the `rbac` capability check in `/templates/_helpers.tpl` since that might have broader implications.

[prometheus-postgres-exporter] drop capability on service monitor

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/values.yaml

Previously the value of '--storage.tsdb.path' was set via '.Values.server.persistentVolume.mountPath'.
This commit adds the option to specify a 'server.hostPath' value. When
the 'server.hostPath' value is not empty, the 'server.hostPath' value is
used for '--storage.tsdb.path' instead.
Signed-off-by: Vincent Van Ouytsel <vvanouytsel@gmail.com>
Make it possible to configure '--storage.tsdb.path' directly via the values file. 
Previously it was 'hardcoded' to use .Values.server.persistentVolume.mountPath as the value of '--storage.tsdb.path'.
With this PR you can now overrule this functionality and set the '--storage.tsdb.path' directly using the 'storagePath' variable.
n/a
n/a

[prometheus] Add option to set --storage.tsdb.path

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/secrets.yaml

Adds a validation on `.Values.config.datasourceSecret` to avoid laying down a secret that isn't used. 
When the operator of this chart specifies `.Values.config.datasourceSecret` (commented as being mutually exclusive to `.Values.config.datasource`), the `Secret` is applied regardless. The `Deployment` uses the `datasourceSecret` exclusively when it's defined, so the `Secret` is never mounted and serves no purpose. 
I skipped a patch on the chart bump in light of #991.

[prometheus-postgres-exporter] Don't apply Secret when using one externally-managed

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/values.yaml

Updates blackbox exporter to the most recent version [v0.19.0](https://github.com/prometheus/blackbox_exporter/releases/tag/v0.19.0).
`no_follow_redirects` has been replaced with `follow_redirects`, so I changed the default to behave as before – see [release notes](https://github.com/prometheus/blackbox_exporter/releases/tag/v0.19.0).

[prometheus-blackbox-exporter] Bump version to v0.19.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/values.yaml

Only bumping minor here since CRDs didn't change.
* Sync CRDs to match Prometheus-Operator v0.48.0
* Prometheus-Operator v0.48.0
* Prometheus v2.27.1 (includes a fix for a vulnerability)
* Alertmanager v0.22.0
* Kube-Webhook-Certgen v1.5.2

Prometheus-Operator v0.48.0 and update used images

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/sts.yaml

As discussed in the StatefulSet deploy option of Prometheus server previously ignored the `server.storagePath` Helm value.
This patch fixes that behavior.
Signed-off-by: Jack Henschel <jackdev@mailbox.org>
fixes https://github.com/prometheus-community/helm-charts/issues/1002

[prometheus] Respect storagePath value when deployed as StatefulSet

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/psp.yaml
charts/prometheus-adapter/values.yaml

When trying to install prometheus-adapter into our EKS cluster with Calico CNI and rbac, psp, and serviceaccount enabled, we hit an issue that the ReplicaSet was unable to spin up a pod due to the following error:
```
Warning  FailedCreate  106s (x15 over 3m8s)  replicaset-controller  Error creating: pods "prometheus-adapter-85684bb67d-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].hostPort: Invalid value: 6443: Host port 6443 is not allowed to be used. Allowed ports: []]
```
We did set `hostNetwork: true` and `dnsPolicy: ClusterFirstWithHostNet` based on some notes in https://github.com/prometheus-community/helm-charts/pull/375, but our cluster does not allow the use of hostPorts by default. 
This PR adds the optional ability to include the …

[prometheus-adapter] Add hostPorts in psp

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/templates/prometheus/podDisruptionBudget.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/templates/prometheus/service.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecarExternal.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceperreplica.yaml

The upstream prometheus-operator changed the `app` labels to `app.kubernetes.io/name`, and that broke the prometheus service selector.
- fixes #1009

[kube-prometheus-stack] Update prometheus service selector for 0.48.0

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/psp.yaml

There is an indentation issue with the PSP annotation, causing the template rendering to fail with:
```
Error: error running dry run for a diff: YAML parse error on prometheus-node-exporter/templates/psp.yaml: error converting YAML to JSON: yaml: line 12: did not find expected key
```
This PR fixes the indentation.
- NA
Nil

[prometheus-node-exporter] Fix PSP annotation identation

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmap-dashboards.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-coredns.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/proxy.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/scheduler.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/statefulset.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml
charts/kube-prometheus-stack/values.yaml

It's possible that you already have deployed grafana in your k8s cluster and just want to add prometheus and grafana dashboards. This PR allows to deploy grafana dashboard without grafana itself.
fixes #921

[kube-prometheus-stack] Limit grafana deployment to dashboards

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/kube-prometheus-stack/values.yaml

Make admission Web Hook Jobs securityContext configurable
Signed-off-by: Dmitrii Ermakov <demonihin@gmail.com>
This PR makes Kube Prometheus Stack Jobs Security Context configurable. It allows a user to set required UID, GID for installation in restricted environments such as Openshift (please, take a look at #1038).
- fixes #1038

[kube-prometheus-stack] Fix issue #1038

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Bumps Alertmanager to v0.22.2 which includes some important bug fixes
- fixes #

[kube-prometheus-stack] Alertmanager v0.22.2

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Andres Alvarez <kir4h.gh@gmail.com>
This PR updates dependencies for `grafana` chart from `6.9` to `6.11`. It also bumps patch versions for `prometheus-node-exporter` and `kube-state-metrics`.
One of the benefits comes with [this commit](https://github.com/grafana/helm-charts/commit/e26d831611878d5bfa273012d433c319ba65208c#diff-8b8fb109a9ea067b4502be557279dbe8d342582d4850974f62766f3cd4c7b82c) as grafana secret is no longer overriden during upgrades.
Grafana changes seem safe to upgrade without further modification:
6.10 -> 6.11 https://github.com/grafana/helm-charts/commit/e5244943392c8b87d266d66bca8591e96c931923#diff-4ca0ec9c453f5f1f65d24210ec2e8068b2522937374dd462314125a8299ad5ae
6.9 -> 6.10 https://github.com/grafana/helm-charts/commit/880ef0d42892c6b45c9050380ec078be5c32 …

[kube-prometheus-stack] Version bump for grafana, node-exporter and kube-state-metrics

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: devincd <505259926@qq.com>
move relabelings filed to servicemonitor in kubeApiServer.
- fixes #

[kube-prometheus-stack] move relabelings filed to servicemonitor in kubeApiServer

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml

Increase prometheus-adapter realiness+liveness probes timeout
- fixes #
I am using HPAs with prometheus-adapter, sometimes they are reporting unhealthy statuses and spamming notifications
I tried to find a root cause and found that prometheus-adapter /healthz endpoint sometimes are responding very slow.. (seconds vs microseconds). I think it is happening then it is querying prometheus, but not sure
HPA events
```
Warning  FailedGetResourceMetric       28m (x72 over 39h)      horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server is currently unable to handle the …
```

[prometheus-adapter] Increase timeout seconds

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/proxy.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/scheduler.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml

Signed-off-by: Andres Alvarez <kir4h.gh@gmail.com>
This PR syncs grafana dashboards. It resolves current issue presenting some metrics like CPU empty because of min step set at `$__rate_interval` (see #1022) 
- fixes #1022

[kube-prometheus-stack] Sync grafana dashboards

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

In a previous PR (https://github.com/prometheus-community/helm-charts/pull/194)
support for specifying "extraVolumes" was introduced.
However, these extra volumes cannot be mounted in the main blackbox-exporter
container (only in sidecar containers).
This patch adds a new value "extraVolumeMounts" which lets the user mount
arbitrary volumes on the main container.
(none)
Signed-off-by: Jack Henschel <jackdev@mailbox.org>

[prometheus-blackbox-exporter] Allow specifying volumeMounts for container

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

* updates grafana chart dependency to 6.12.0 to get grafana 8.0
- fixes #

[kube-prometheus-stack] update grafana to 8.0 via chart version 6.12.0

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/clusterrolebinding.yaml
charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml
charts/kube-state-metrics/templates/rolebinding.yaml
charts/kube-state-metrics/templates/serviceaccount.yaml
charts/kube-state-metrics/templates/stsdiscovery-rolebinding.yaml

It makes all serviceAccount related resources be created which the right template helper **`kube-state-metrics.serviceAccountName`** instead of `kube-state-metrics.fullname`
None that I know of/have found
Before this PR, when installing with serviceAccount.name set
```
helm install --generate-name --set-string serviceAccount.name=somename prometheus-community/kube-state-metrics
```
All resources except deployment are created using the fullname template helper...
Ex:
```
kubectl get sa
NAME                            SECRETS   AGE
default                         1         4m45s
kube-state-metrics-1623393733   1         2m4s
```
which results in the following error in deployment:
```
kubectl get deployments.apps kube-state-metrics-1623393733 -o yaml
...
- lastTransitionTime: …
```

[kube-state-metrics] Fix: Use serviceAccountName template helper where it should

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: sturman <4456572+sturman@users.noreply.github.com>
This PR updates Grafana helm chart version in kube-prometheus-stack helm chart. Recently [new Grafana release v8.0.1](https://github.com/grafana/grafana/releases/tag/v8.0.1) has been published

[kube-prometheus-stack] Update grafana helm chart version

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/pushgateway/ingress.yaml
charts/prometheus/values.yaml

Adds support for ingressClassName for kubernetes >1.18.
- fixes #507 
Hi! i'm deploying pushgateway with ingress enabled and i was not rendering the value "ingressClassName". I see that these lines were not added for the pushgateway ingress in the PR #508
`spec:
{{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
{{- if .Values.pushgateway.ingress.ingressClassName }}
ingressClassName: {{ .Values.pushgateway.ingress.ingressClassName }}
{{- end }}
{{- end }}`
Add this would be completing the support for ingressClassName.
I take as a reference these PR: 
- PR #508 
- PR #265

[prometheus] add IngressClassName support for pushgateway

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/templates/alertmanager/sts.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml

We want to include some cacerts if they exists inside the namespace. by using the optional flag, this unifies our deployment in all namespaces.
N/A

[prometheus] expose optional flag for extra configmaps and secrets

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/values.yaml

It updates the `values.yml` default file to add a missing key : `annotations`.
@gkarthiks
@golgoth31
Do I have to change the version of the chart for such a simple change?
- fixes #1077

[prometheus-kafka-exporter] Add missing key `annotations` in `values.yml` example

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl

Signed-off-by: Kirchen99 <latias_latios@126.com>
This one https://github.com/prometheus-community/helm-charts/pull/1060 is closed since I have tried to resolve the conflicts by `git rebase`. But it brings more problems to solve. So I open a new pull request.
This PR adds support when this Chart is deployed on an Amazon EKS Cluster or a Google GKE Cluster. 
The Kube-Version of an EKS Cluster is like a pre-release version e.g. `v1.20.4-eks-6b7464` and of a GKE Cluster is like `v1.11.5-gke.3`, which makes helm confused thus rendered wrong apiVersion for resources like ingress of Alertmanager and Prometheus.
This PR, for example, replaces `v1.20.4-eks-6b7464` with `1.20.4`, if there is an `eks` in it or replaces `v1.11.5-gke.3` with `1.11.5` if there is a `gke` in it.
- fixes #1057
- fixes …

[kube-prometheus-stack] add extra support for Amazon EKS and Google GKE KubeVersion on ingress

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Matthias Winzeler <matthias.winzeler@gmail.com>
There's a new version of the grafana helm chart [6.13.0 which fixes a CVE in one of its dependencies.](https://github.com/grafana/helm-charts/pull/501).
This PR bumps the grafana chart version.
no issue exists.

[kube-prometheus-stack] bump grafana dep in kube-prometheus-stack to 6.13.*

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml
charts/prometheus/values.yaml

I have been looking for a way to use some values from values.yaml in sidecarContainers to use a specific image tag and end up with the following feature.
In my case it looks like this:
```
myproject:
image: &myproject-image-globals
...
prometheus:
server:
sidecarTemplateValues: *databand-image-globals
sidecarContainers:
my-sidecar-container: |-
{{ include "my-sidecar-container" . }}
...
````
```
{{- define "my-sidecar-container" -}}
image: "{{ .Values.server.sidecarTemplateValues.repository }}:{{ .Values.server.sidecarTemplateValues.tag }}"
...
{{- end -}}
```
Hope it's valuable 🙂
Is there a better workaround for this?
Let me know if further work is required.
--
@zanhsieh recreated https://github.com/prometheus-community/helm-charts/pull/1079

[prometheus] Allow templating sidecar containers for prometheus server

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Jaskaranbir Dhillon <jaskaranbir.dhillon@gmail.com>
Updates Grafana chart to 6.13.1.

[kube-prometheus-stack] Bump Grafana-chart to 6.13.1

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Kirchen99 <latias_latios@126.com>
This PR provides a possibility to add endpoint `metrics` (port 8081 for self monitor) in ServiceMonitor for kube-state-metrics.
It fixeds #424. If the user wants to have self monitor metrics of kube-state-metrics, the user could set
```
kubeStateMetrics:
selfMonitor:
enabled: true
kube-state-metrics:
selfMonitor:
enabled: true
```
- fixes #424
It looks duplicated with [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/servicemonitor.yaml#L1). But since we also have a [file](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml) for kube-state-metrics ServiceMonitor, we should …

[kube-prometheus-stack] add endpoint port mertics for kube-state-metrics self monitor

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/monitor.yaml
charts/prometheus-node-exporter/values.yaml

This PR adds the ability to define a proxyUrl in the ServiceMonitor. This is similar to  #789

[prometheus-node-exporter] Add the ability to define a proxyUrl via values

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/values.yaml

Add the option to add additional labels to pods.
One need that we have is to add the label app.kubernetes.io/part-of: redis-exporter to forward it to the right index pattern for our ELK log stack, but we could have wanted other labels as well for other needs.
Special notes for your reviewer:

[prometheus-redis-exporter] Add custom labels support

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

Signed-off-by: Paul de Nonancourt <pdenonancourt@octo.com>
This PR adds the possibility to specify arguments to `--include-databases` in the postgres-exporter Chart (see https://github.com/prometheus-community/postgres_exporter#automatically-discover-databases).
No issue was created for that.

[prometheus-postgres-exporter] Add --include-databases arguments to Chart values

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/alertmanager/ingress.yaml
charts/prometheus/templates/pushgateway/ingress.yaml
charts/prometheus/templates/server/ingress.yaml
charts/prometheus/values.yaml

Hi, I recently implemented version 14.2.1 of the prometheus chart and it sets the default "**pathType**" to "**ImplementationSpecific**" when apiVersion is networking.k8s.io/*
example:
`spec:
ingressClassName: alb-controller
rules:
- host: alertmanager.example.com
http:
paths:
- backend:
serviceName: prometheus-alertmanager
servicePort: 9093
path: /*
pathType: ImplementationSpecific
tls:
- hosts:
- alertmanager.example.com
`
Making these changes in the chart we can choose the "pathType" from the values.yaml file in case it is compatible with the apiVersion. 
Also simplify the support function for ingressClassName. [https://github.com/prometheus-community/helm-charts/pull/1061](https://github.com/prometheus-community/helm-charts/pull/1061)
I take as a reference these PR:
PR: …

[prometheus] chore: improve ingress support for k8s v1.18

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

recreate the pod if the config has changed and auto rereading is disabled.

[alertmanager] forse restart if configmapReload disable

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

Bumps kube-state-metrics to v2.1.0

[kube-state-metrics] Bump version to 2.1.0

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/daemonset.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: Ákos Hervay akoshervay@gmail.com
* Allows adding custom initContainers to blackbox-exporter.
@desaintmartin
@gianrubio
@rsotnychenko
@monotek

[prometheus-blackbox-exporter] 4.15.0 Allow to configure init containers

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/role.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml

I'd like to keep operator in separate namespace than prometheus instance itself. Currently despite `values.prometheusOperator.enabled: false` extra webhookconfigurations are being created which will point to the unexisting operator service in prometheus instance namespace.

[kube-prometheus-stack] Dont create webhookconfigurations when prometheus operator is disabled.

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
ct.yaml

* Update github actions to latest version
* Unify how we pull helm binary
* Remove stable and kube-state-metrics repositories as they are not used anymore
None of the above applies except DCO.

Update github actions and remove unused helm repositories

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Signed-off-by: Jim DAgostino <dagosti@synopsys.com>
Fix link to old helm repo in values.yaml documentation so it points to the correct `prometheus-community` repo.
- fixes n/a
- na

[prometheus] Fix link to repo in values.yaml

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml

Sets proper `web.route-prefix` when defining `server.prefixURL`

[prometheus] Fix missing web route prefix

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml

`label.hpa` is outdated and should now be `label.horizontalpodautoscaler`
From alerts in slack. Should be `HPA Default/*NAME*...
`![image](https://user-images.githubusercontent.com/4808216/124491046-1d932880-ddb3-11eb-80ed-713aeed2e76b.png)
Labels from alertmanager
- fixes #

[kube-prometheus-stack] Update outdated HPA label in prometheus rules

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

Signed-off-by: randrusiak <randrusiak@protonmail.com>
Users should be able to specify a custom deployment strategy. It may be useful especially if you use hostNetwork and pod with promethues-adapter is redeployed on the same worker node. With the default "RollingUpdate" strategy new pod won't be deployed because node port will be still allocated. So if we use hostNetwork we may specify "recreate" strategy which solves this problem. 
Default values are the same as k8s provides. 
n/a
n/a

[prometheus-adapter] Allow to specify deployment strategy

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py

- fixes #1159 
Tested by running the python script and the only change in the generated templates is that the expressions with `{}` are back in the templates.
chart maintainers: @vsliouniaev @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro

kube-prometheus-stack - dashboard templates; only remove lines with defaults

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/deployment.yaml

The current deployment yaml for `prometheus-snmp-exporter` is syntactically invalid and although it does not fail while doing a `helm install` it will error with other tooling that makes sure the rendered chart is valid i.e. `fluxcd`. This PR adds support for merging both `securityContext` yaml stanzas.

[prometheus-snmp-exporter] Merge duplicate security context in deployment

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

with k8s 1.21, we need to set fsGroup for all non-root pods to allow
access to the api token (via projected api).
ref: https://github.com/kubernetes/kubernetes/issues/70679
- fixes #1135

[prometheus-adapter] add pod securityContext

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml

Align both statefulset (`sts.yaml`) and deployment (`deploy.yaml`) manifests (some options were not available in both while applicable)
Personnally I will have moved most pod spec into a new named template under `/templates/_server.tpl` or `/templates/server/_helpers.tpl`

[prometheus] Align server sts & deploy manifests

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml

It disables the automounting of the service account token for blackbox exporter. This exporters does not need access to the Kubernetes API (as far as I can tell). By disabling the automount, potential attackers cannot access the Kubernetes API on behalf/through the pod.
I have not raised an issue. If it helps or is needed otherwise, I'd be glad to do so.

prometheus-blackbox-exporter: Do not automount service account token

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/README.md
charts/prometheus-node-exporter/values.yaml

* Bumps node exporter to v1.2.0
* Drops support for helm2 by upgrading to Chart apiVersion v2.

[prometheus-node-exporter] Version bump to 1.2.0; drop helm2 support

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

Disables VPA by default as it's not a default resource on clusters
- fixes #1131

[kube-state-metrics] Disable VPA by default

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml

It disables the automounting of the service account token for node exporter. This exporters does not need access to the Kubernetes API (as far as I can tell). By disabling the automount, potential attackers cannot access the Kubernetes API on behalf/through the pod.
I have not raised an issue. If it helps or is needed otherwise, I'd be glad to do so.

node-exporter: do not automount service account token

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/README.md
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/values.yaml

This change allows a user to specify a configmap that contains the
address at which a redis server can be reached. Following the same logic
already being used for authentication details from a provided secret.

[prometheus-redis-exporter] address via configmap

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Fix version mismatch
Signed-off-by: Aleksey Zhukov <alex@izhukov.ru>

[kube-prometheus-stack] Update README.md - Fix version mismatch

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/templates/psp.yaml
charts/prometheus-node-exporter/values.yaml

- allows a user to configure the hostPID setting of the daemonset
- the current values violate OPA gatekeeper [constraint 1](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-namespaces/template.yaml) and [constraint 2](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-network-ports/template.yaml), so users should be able to disable this at their own peril
- fixes #

[prometheus-node-exporter] Add configurable host PID

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

We often get `TargetDown` alerts for completed jobs. This adds the `Completed` phase to the pod scrape config.
cc chart contributors:
@gianrubio 
@zanhsieh 
@Xtigyro 
@monotek 
@naseemkullah

[prometheus] drop Completed pods

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

Version bumps kube-state-metrics to v2.1.1

[kube-state-metrics] Version bump to 2.1.1

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl

This PR simplifies the ingress API version and capability selection logic.
Fixes #1197
n/a

[kube-prometheus-stack] Fix ingress logic

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/values.yaml

Bumps to a new patch release https://github.com/prometheus/node_exporter/releases/tag/v1.2.1
- fixes #

[prometheus-node-exporter] Version bump to 1.2.1

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

Prometheus 2.24.0 adds support for TLS and basic auth on HTTP endpoints.
This commit enables configuring TLS in the kube-prometheus-stack helm chart.
Signed-off-by: Dongfang Qu <qudongfang@gmail.com>
- fixes #971

[prometheus-couchdb-exporter] add support for web TLS configuration

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/proxy.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/scheduler.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml
charts/kube-prometheus-stack/values.yaml

This PR adds ability to only enable multicluster option for etcd
dashboard, so it doesn't have to be enabled for all Kubernetes
dashboards.
If one collects metrics from more than one etcd cluster on single
Kubernetes cluster, e.g. when having Loki deployed, which use etcd
internally, etcd dashboard in Grafana becomes useless without
multicluster option enabled.
This PR also syncs Grafana dashboards and does some styling improvements to kube-prometheus-stack values.yaml file.
- Closes #965
I tested it manually on my cluster and everything works as expected.

[kube-prometheus-stack] Support multicluster dashboards only for etcd

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/ingress.yaml

Add missing pathType is not allowed when Ingress with apiVersion: networking.k8s.io/v1 is used for prometheus.
no issue opened for this tiny snippet
[Here](https://github.com/prometheus-community/helm-charts/pull/1150) were tests added, should I also? Can I just use this introduced test as a blueprint if it is needed?

[kube-prometheus-stack] Add default ingress pathType for prometheus

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

Upgrade `prometheus-operator` to [v0.50.0](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.50.0)

[kube-prometheus-stack] Upgrade prometheus-operator to v0.50.0

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/values.yaml

Bumps to latest node_exporter release v1.2.2
- fixes #

[prometheus-node-exporter] Version bump to 1.2.2

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/values.yaml

This PR updates postgres-exporter to v0.10.0 ([changelog](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.10.0)).
You need it because this chart deploys v0.9.0 but has `include-databases`, a features that was released in v0.10.0.
None
```bash
find ./charts/prometheus-postgres-exporter/ -type f -exec sed -i 's/0.9.0/0.10.0/g' {} \;
sed -i 's/2.3.5/2.3.6/g' ./charts/prometheus-postgres-exporter/Chart.yaml
```
I checked that the tag exists in quay.io/prometheuscommunity/postgres-exporter

[prometheus-postgres-exporter] Update to v0.10.0

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

Version bumps kube-state-metrics to v2.2.0

[kube-state-metrics] Version bump to 2.2.0

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

Signed-off-by: Edwin Hobor <edwinhobor@gmail.com>
Added the possibility to configure:
- log level
- sarama log level
- insecureSkipVerify for TLS
- any other extra args that are listed under https://github.com/danielqsj/kafka_exporter#flags
Also used proper version `image.tag` instead of using `latest`.
- fixes #1272
@gkarthiks, @golgoth31 would you please take a look? Thanks!

[prometheus-kafka-exporter] Configure log level and extra args

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/secret.yaml

Addresses #302
This allows us to use complex multi-line template strings in the alertmanager config when using `tplConfig` flag. Currently if you attempt to use a multi-line string, it will template but the operator will not be able to parse the default secret `alertmanager.yaml` configuration object due to it being considered a YAML string.
- fixes #302
-  [x] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

[kube-prometheus-stack] Fix alert manager complex config templating

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/values.yaml

Version bumps redis-exporter to v1.27.0

[prometheus-redis-exporter] Version bump to 1.27.0

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Signed-off-by: Geisler, James D <geislerjamesd@gmail.com>
This provides the ability to add arbitrary annotations to the prometheus-elasticsearch-exporter deployment. This will enable the use of any operators that rely on deployment annotations.
Example values.yaml:
```yaml
deployment:
annotations:
wave.pusher.com/update-on-config-change: "true"
```

[prometheus-elasticsearch-exporter] add optional annotations to deployment

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

Prometheus operator uses [BuildImagePath](https://github.com/prometheus-operator/prometheus-operator/blob/e2867fc585d77d08c6ed3c02ed8b3df4ee6b1445/pkg/operator/image.go#L30) function to define image path, please see also [here](https://github.com/prometheus-operator/prometheus-operator/blob/e2867fc585d77d08c6ed3c02ed8b3df4ee6b1445/pkg/prometheus/statefulset.go#L321).
`image` in Prometheus definition has precedence over baseImage, tag, and sha combinations, see [this](https://github.com/prometheus-community/helm-charts/blob/466e1228adb88142d8ac0cde26366f8b79953737/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml#L2263-L2267), so currently `sha` is ignored, e.g
```
helm upgrade --install kube-prometheus-stack-test charts/kube-prometheus-stack/ \
--set …
```

[kube-prometheus-stack] add option to configure Prometheus image using tag and/or sha256

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/service.yaml
charts/prometheus-adapter/values.yaml

Signed-off-by: Terje Sannum <terje.sannum@nav.no>
Add support for specifying the ip-address to use for the prometheus-adapter service

[prometheus-adapter] Add support for configurable service ip

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Replace admission webhook image from jettech/kube-webhook-certgen to k8s.gcr.io/ingress-nginx/kube-webhook-certgen.
See #1276 but in short the old image uses now removed k8s APIs.
This makes the chart work on Kubernetes 1.22+
- fixes #1276 
For the semver bump, I wasn't sure if this counts as minor or patch. Went with patch but I think either is arguable. Happy to change it to minor if that's the preference.

[kube-prometheus-stack] Replace admission webhook image

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/_helpers.tpl
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/templates/podsecuritypolicy.yaml
charts/prometheus-redis-exporter/templates/prometheusrule.yaml
charts/prometheus-redis-exporter/templates/role.yaml
charts/prometheus-redis-exporter/templates/rolebinding.yaml
charts/prometheus-redis-exporter/templates/service.yaml
charts/prometheus-redis-exporter/templates/serviceaccount.yaml
charts/prometheus-redis-exporter/values.yaml

Signed-off-by: Stanislav Chesnovskii <stanislav@chesnovsky.com>
This PR allows using custom labels in addition to the basic ones.

[prometheus-redis-exporter] allow using custom labels

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/values.yaml

Signed-off-by: Stanislav Chesnovskiy <s.chesnovskiy@semrush.com>
This PR allows using security context in containers

[prometheus-redis-exporter] allow using securityContext in containers

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Tim Balzer <tbalzer@bigpoint.net>
Updates version of the Grafana dependency.
Version 6.16.x (up until 6.16.4) feature:
* quay.io/kiwigrid/k8s-sidecar update from 1.12.2 to 1.12.3
* Grafana update from 8.1.0 to 8.1.2
* Several documentation updates
* Bugfix that allows specifying multiple files for datasources/notifiers/dashboardProviders to work correctly
* Upstream issue with multiple files for Grafana datasources/notifiers/dashboardProviders
* none

[kube-prometheus-stack] bump grafana to 6.16.*

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml

Adds Helm tpl function to ES URI injection on the command line so this value can expand values, really useful when using this as a subchart.
- fixes #1224
Check https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function

[prometheus-elasticsearch-exporter] Adds tpl function to ES URI injection

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
charts/kube-prometheus-stack/values.yaml

Switch kube-state-metrics ServiceMonitor static `honorLabels` value from to parametrized value in `kube-prometheus-stack` like in `kube-state-metrics` helm chart.
Required for moving old infrastructure on kube-prometheus-stack to not break existing rules, dashboards and historical data.
Most ServiceMonitors affects system and prometheus-related data and easy to handle, when kube-state-metrics is in wide use by customers with own rules and dashboards.

[kube-prometheus-stack] Optional honorLabels for kube-state-metrics ServiceMonitor

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/deployment.yaml
charts/prometheus-pushgateway/values.yaml

Signed-off-by: DilasserT <dilassert@gmail.com>
Allow additionnal volumes to be added, can be used to add shared volumes
Also added emptyDir in case `persistentVolume.enabled: false`, as it is specified in `values.yaml`
- fixes #

[prometheus-pushgateway] add extraVolumes and extraVolumeMounts to chart

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

The current use of `server.sidecarContainers` raises:
```
warning: cannot overwrite table with non table for sidecarContainers (map[])
```
Changing it to be a list gets rid of the warning and also stays consistent with [previous usage of sidecar injection](https://github.com/prometheus-community/helm-charts/blob/cc8b7cb3d4f3c7445b56eeb91ca64340efdae2ed/charts/kube-prometheus-stack/values.yaml#L575-L577).
- N/A

[prometheus] Turn server.sidecarContainers into list

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
charts/kube-prometheus-stack/values.yaml

This is a simple addition to the ServiceMonitor values of **kube-state-metrics**.
The `scrapeTimeout` is added as an option. The intention is for this value to be configured to something else than the default when needed (for example because of timeouts due to wildcards being used with `--metric-labels-allowlist` etc)

[kube-prometheus-stack] Add scrapeTimeout in kubeStateMetrics

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml

Signed-off-by: Stefan Steinert <ststefa@heldenzeit.net>
`.Values.prometheus.thanosIngress.tls` is used as-is instead of templating the contents. This leads to an invalid template if the values itself use `.Values`.
The fix is just copied over from `charts/kube-prometheus-stack/templates/prometheus/ingress.yaml` where this is already properly done.
- fixes #
I verified that this works as expected. After all it should be save because it just duplicates code from `ingress.yaml` to `ingressThanosSidecar.yaml`.

[kube-prometheus-stack]: adds templating for .Values.prometheus.thanosIngress.tls

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecarExternal.yaml
charts/kube-prometheus-stack/templates/prometheus/servicemonitorThanosSidecar.yaml
charts/kube-prometheus-stack/values.yaml

Adds the http port to the Thanos discovery service, and a ServiceMonitor
pointing to that port to scrape Thanos sidecar metrics.
The current workaround is to create an extra port on the main Prometheus
service, and separately add a ServiceMonitor (see #560), but imo it's
cleaner if we support this as a first-class construct?
- fixes #1291
- fixes #1055
Ping @vsliouniaev @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro 🙏 
Let me know if anything seems wrong here; I've tested the chart locally and it works nicely in our Prometheus + Thanos install, but I'm not sure whether the port naming etc is as good as it could be!

[kube-prometheus-stack] Configure Thanos Sidecar monitoring

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

This PR allows you to specify params for metrics targets in kubernetes service discovery for pods and services. This is currently not possible afaik for kubernetes service discovery scrapers.  For example, metrics server could be http://service/metrics?target=1.2.3.4. Before this patch prometheus could not discover this target properly. 
This PR introduces a new annotation for kubernetes services and pods like this:
```yaml
annotations:
prometheus.io/scrape: 'true'
prometheus.io/path: '/pve'
prometheus.io/param_target: '192.168.1.12'
prometheus.io/param_foo: 'bar'
prometheus.io/port: '9221'
prometheus.io/scheme: 'http'
```
Which would then scrape the target http://some-kubernetes-service/pve?target=192.168.1.12&foo=bar
- [ x] [DCO](https://github.com/prometheus-community/helm-charts/blob/m …

[prometheus] Support metrics target parameters

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/alertmanager-overview.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-coredns.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/proxy.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/scheduler.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/statefulset.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml
charts/kube-prometheus-stack/values.yaml

Allow to set a timezone for the default grafana dashboards.
The default dashboards have different timezones (utc, UTC, browser) and are loaded as read only in Grafana. Therefore, any change the user performs regarding the timezone, it cannot be saved.
This MR gives the user the possibility to set the some default timezone for all the dashboards (i.e. his / her own local timezone), without the need of modifying them.
Fixes #780 
Signed-off-by: Fabio Kruger <10956489+krufab@users.noreply.github.com>

[kube-prometheus-stack] Allow to set a timezone for the default grafana dashboards

---

charts/prometheus-statsd-exporter/Chart.yaml
charts/prometheus-statsd-exporter/values.yaml

Version bumps statsd-exporter to v0.22.1

[prometheus-statsd-exporter] Bump statsd-exporter to version to 0.22.1

---

charts/prometheus-druid-exporter/Chart.yaml
charts/prometheus-druid-exporter/templates/deployment.yaml
charts/prometheus-druid-exporter/values.yaml

Signed-off-by: Jake Becker <jbecker@conviva.com>
I'm using prometheus-druid-exporter but I can't assign it to run on the same node pools as our druid workload so I added the `nodeSelector`.  The `affinity` and `tolerations` are just as helpful so I added them too (basically just copied the relevant sections from blackbox-exporter).

[prometheus-druid-exporter] Add nodeSelector, tolerations, and affinity

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/values.yaml

* Fix in prometheus chart `alertmanager/deploy.yaml` missing `cluster.listen-address` when `alertmanager.service.enableMeshPeer` it's `true`.
Alertmanager `--cluster.listen-address` default value is `0.0.0.0:9094` so we need to overwrite it to `0.0.0.0:6783`
* Fix in prometheus chart when adding multiple `clusterPeer=` at Alertmanager `extraArgs`
example:
```
alertmanager.extraArgs:
cluster.peer: "foo:6783"
cluster.peer: "bar:6783"
```
Because extraArgs it's defined as a Map, Helm will only render the last `clusterPeer` defined when executing the `range` command

[prometheus] Fix AlertManager deploy.yaml missing `cluster.listen-address`

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

With https://github.com/kubernetes/kube-state-metrics/pull/1468 kube-state-metrics v2.2.0 added the possibility to configure annotation metrics, similar to how label metrics are currently configured.
This PR adds a configuration option for configuring annotation metrics to this helm chart.

[kube-state-metrics] Enable configuring kubernetes annotation metrics

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/ci/pod-security-policies.yaml
charts/prometheus-elasticsearch-exporter/templates/_helpers.tpl
charts/prometheus-elasticsearch-exporter/templates/role.yaml
charts/prometheus-elasticsearch-exporter/templates/rolebinding.yaml

Signed-off-by: Christof Koenig <koenig@crealytics.de>
Newer versions of Kubernetes deprecated `rbac.authorization.k8s.io/v1beta1` in favor of `rbac.authorization.k8s.io/v1`.
The changes in this PR are based on similar changes, which have already been merged for other exporters, e.g. https://github.com/prometheus-community/helm-charts/pull/385.

[prometheus-elasticsearch-exporter] Use appropriate apiVersion for rbac

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Updates version of the Grafana dependency.
Version 6.16.9 feature:
- Update to grafana 8.1.5
- Adding envFromSecrets to allow multiple optional secrets to provide environment variables
- Fix PodSecurityPolicy contradicting the init container settings
- none

[kube-prometheus-stack] bump grafana to 6.16.9

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

I wanted to add in the rest of the limit enforcement settings that the operator and PrometheusSpec support. The chart was missing several of them.
I think this is fairly simple - we tested it ourselves and it's working.

[kube-prometheus-stack] Support all of the enforce*Limit settings

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

This PR intents to add the metricRelabelings and relabelings options. We need it to override some important labels like the node name to instance.
Example:
For values.yaml:
```yaml
prometheus:
monitor:
enabled: true
relabelings:
- targetLabel: instance
sourceLabels:
- __meta_kubernetes_pod_node_nam
```
Template result:
```yaml
kind: ServiceMonitor
metadata:
name: RELEASE-NAME-kube-state-metrics
namespace: default
labels:
app.kubernetes.io/name: kube-state-metrics
helm.sh/chart: "kube-state-metrics-3.5.2"
app.kubernetes.io/instance: "RELEASE-NAME"
app.kubernetes.io/managed-by: "Helm"
spec:
selector:
matchLabels:
app.kubernetes.io/name: kube-state-metrics
app.kubernetes.io/instance: RELEASE-NAME
endpoints:
- port: http
relabelings:
- sourceLabels:
- __meta_kubernetes_pod_node_name …
```

[kube-state-metrics] Add metricRelabelings and relabelings options

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: Philippe Bürgisser <philippe.burgisser@camptocamp.com>
It allows the serviceaccount to automount its secret, needed in case of a sidecar container like oauthproxy to have its token to exchange with the API

[prometheus-blackbox-exporter] Allow automount of the serviceaccount token for sidecar containers

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/scheduler.yaml

Fix drilldown links for Grafana dashboards, sync dashboards
https://github.com/prometheus-community/helm-charts/issues/1086

[kube-prometheus-stack] Fix drilldown links for Grafana dashboards

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/NOTES.txt
charts/alertmanager/templates/ingress.yaml
charts/alertmanager/unittests/__snapshot__/ingress_test.yaml.snap
charts/alertmanager/unittests/ingress_test.yaml
charts/alertmanager/values.yaml

This PR adds support for ingressClassName since the old [ingress.class annotation](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) is now considered as deprecated.
I had to introduce a breaking change to support the new pathType field.

[alertmanager] Add support for ingressClassName

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

- Update Grafana helm chart to 6.17.5
- #1484 
- [Grafana 8.2.3 bug fix version for CVE-2021-41174](https://grafana.com/blog/2021/11/03/grafana-8.2.3-released-with-medium-severity-security-fix-cve-2021-41174-grafana-xss)

[kube-prometheus-stack] Update Grafana chart version to 6.17.5

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

When the prometheus-operator subchart was in the upstream repo (version 0.29), there was the ability to specify this already:
> ```yaml
>           args:
>           {{- if .Values.kubeletService.enable }}
>             - --kubelet-service={{ .Values.kubeletService.namespace }}/{{ .Values.kubeletService.name }}
>           {{- end }}
> ```
> Source: https://github.com/prometheus-operator/prometheus-operator/blob/release-0.29/helm/prometheus-operator/templates/deployment.yaml#L26
When the chart was moved (first in the helm monorepo, I think), the parameter `.Values.kubeletService.name` got replaced by a template function.
This service is created outside helms control (trough the operator) and left back upon chart uninstall.
As we use terrafom together with terratest from gruntwork we test …

[kube-prometheus-stack] Ability to specify kubelet-service again

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/service.yaml

This PR removes the label selector app:alertmanager from the alertmanager service. As the label has been removed by the Prometheus Operator stateful set in the current version 0.52.2
The alertmanager service does not have any endpoints after updating the Prometheus Operator image to 0.52.2. Because the label selector as been changed.
https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.52.0
https://github.com/prometheus-operator/prometheus-operator/pull/4350

[kube-prometheus-stack] removed app:alertmanager label

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

Add names to the ports of the deployment/statefulset. This allows scraping using a `PodMonitor`, which requires named ports.
- fixes #

[kube-state-metrics] Named deployment ports

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

[kube-state-metrics] Bump to v2.2.4

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

Previously it was not possible to set different values for requests/limits of the config reloader. This simply separates `configReloaderCpu` and `configReloaderMemory` into two each for specifying both the limit and request.

[kube-prometheus-stack] Separate config reloader limit and request

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/templates/monitor.yaml

#1515
Signed-off-by: RyuSA <kommsussertad@gmail.com>
We can set a namespace of ServiceMonitor distinct from node-exporter.
- fixes #1515 
NONE

[prometheus-node-exporter]Add availability to deploy ServiceMonitor onto a specific namespace. 

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md
charts/prometheus/values.yaml

This  PR aligns metric relabelings with the convention used in prometheus (https://github.com/prometheus/prometheus/pull/9832), prometheus-operator, kube-state-metrics, kubernetes instrumentation, and monitoring mixins.
This is a breaking PR as following metric labels changed:
- `kubernetes_namespace` -> `namespace`
- `kubernetes_name` -> `service`
- `kubernetes_pod_name` -> `pod`
- `kubernetes_node` -> `node`
I bumped chart major version to note the breaking change.
- fixes #

prometheus: align relabelling convention with prometheus example

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/serviceaccount.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Signed-off-by: Jon Winton <jwinton@squareup.com>
This PR adds support for annotations on the `ServiceAccount`. In an EKS cluster I'm running I need the pod running the exporter to be able to [assume an AWS IAM role to authenticate with an ElasticSearch cluster](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html), which requires annotating the service account. 
This PR will make any annotations completely optional and will default to no annotations at all.
N/A
N/A

[prometheus-elasticsearch-exporter] Support ServiceAccount Annotations

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml

Signed-off-by: Aidan Jensen <aidan@artificial.com>
Applies existing scrapeTimeout to all service monitor endpoints for kubelet
- fixes #
@vsliouniaev @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro

[kube-prometheus-stack] Apply scrapeTimeout config to all kubelet service monitors

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/secret.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Signed-off-by: Yu Kato <y.katsew@gmail.com>
This PR enables users to append custom labels to the secret used for serviceAccountKey.
We currently use the custom helm chart for stackdriver-exporter, but we want to migrate ours to this one.
However, our chart is integrated with webhook to mutate secrets labelled like `secret-webhook-enabled: true`.
To migrate our chart, I add support for appending custom labels to the secret.

[prometheus-stackdriver-exporter] add support for secret labels

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

* Update grafana helm chart to 6.17.10
* Update prometheus-node-exporter helm chart to 2.2.1
* It adds the possibility to configure a new variable in the grafana dashboard sidecar container: https://github.com/grafana/helm-charts/pull/847
* Bump grafana to 8.2.5 by default: https://github.com/grafana/helm-charts/pull/834
* Make security context configurable for sidecars: https://github.com/grafana/helm-charts/pull/845
* Make configurable datasource sidecar watch method: https://github.com/grafana/helm-charts/pull/807
* Allow to add extra volumes on dashboard sidecar container: https://github.com/grafana/helm-charts/pull/862
I also had to update the prometheus-node-exporter chart:
* Allow to deploy ServiceMonitor in specific namespace: …

[kube-prometheus-stack] Bump grafana to 6.17.10

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

This PR add capabilities to the _kube-state-metrics_ chart ServiceMonitor that are present in the override ServiceMonitor in the _kube-prometheus-stack_ chart with the intention that the _kube-prometheus-stack_ should use the _kube-state-metrics_ chart ServiceMonitor.
This PR is the first PR of 3 for #1425.
I've not implemented the template logic from the _kube-prometheus-stack_ as it's not a valid pattern, only strings should be run through the `tpl` command. It's possible to implement it correctly here if required and I'm happy to do so.
I've bumped the chart minor version as this is a feature release.

[kube-state-metrics] Improve ServiceMonitor

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Marc Lallaouret <mlallaouret@libon.com>
* Update Grafana helm chart to 6.18.* which updates Grafana to 8.3.0
* Bump prometheus-node-exporter to 2.2.2

[kube-prometheus-stack] Update Grafana chart version to 6.18.*

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/templates/exporters/node-exporter/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

[kube-prometheus-stack] Istio portnaming convention

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

This PR updates the grafana helm chart dependency to 6.18.2 in order to get grafana 8.3.1
This is critical because of a high severity security fix therein.
See https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/

[kube-prometheus-stack] update grafana dependency to 6.18.2

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/unittests/alertmanager/alertmanager_test.yaml

fix for #1572 + added some unittest for both the initial issue and this regression

[kube-prometheus-stack] add alertmanager unittest

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Addressing https://github.com/prometheus-operator/prometheus-operator/issues/4435
I am not sure if there is a usual process for releasing appVersion updates between minor chart releases, or if I'd be short-circuiting that, but this one has been in the pipe for a while and we have pinned kube-prometheus-stack at 19.3.0 until it is incorporated here:
* https://github.com/fluxcd/flux2/pull/2194
* https://github.com/fluxcd/flux2/issues/2192

Upgrade prometheus-operator to v0.52.1

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

This PR enables the `ServiceMonitor` `jobLabel` to be overridden and keeps consistency with the _prometheus-node-exporter_ chart (#1591).
n/a

[kube-state-metrics] Enable custom ServiceMonitor jobLabel

---

charts/kube-prometheus-stack/Chart.yaml

Fixes accidentally committed change in 2e714c1a49582d1db2b82d0f1be3c7d3201fc575 which downgraded to prometheus-operator 0.52.0

[kube-prometheus-stack] Re-Bump to prometheus-operator 0.52.1

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Security: Fixes CVE-2021-43813 and CVE-2021-PENDING
Signed-off-by: Amarnath K <amarnath_k@outlook.com>

[kube-prometheus-stack] bump grafana dependency to 6.19.2

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml
charts/prometheus-node-exporter/values.yaml

This PR updates the _Prometheus Node Exporter_ image to [v1.3.1](https://github.com/prometheus/node_exporter/releases/tag/v1.3.1) and enables the `ServiceMonitor` `jobLabel` to be overridden. Overriding the `ServiceMonitor` `jobLabel` and is required to enable the use of the chart `ServiceMonitor` by the _kube-prometheus-stack_ chart.
Fixes #1605.
This PR is is required for for #1425 and is an extension of #1566.

[prometheus-node-exporter] Update image to v1.3.1 & enable custom ServiceMonitor jobLabel

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

Bumps kube-state-metrics to v2.3.0

[kube-state-metrics] Version bump to 2.3.0

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Modifies the prometheus scrape jobs for pods and services, in order to use just the `-slow` versions if both `prometheus.io/scrape: "true"` and `prometheus.io/scrape-slow: "true"` annotations are set.
There are some applications, like istio, that can inject the `prometheus.io/scrape: "true"` annotation, so if there is another `prometheus.io/scrape-slow: "true"` one, it results in a duplicated scrapping configuration.
none

[prometheus] Prometheus scrapes with both scrape and scrape-slow annotations

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/servicemonitor.yaml
charts/prometheus-mysql-exporter/values.yaml

Every Charts' service monitor supports namespace except MySQL exporter.

[prometheus-mysql-exporter] Add namespace support to service monitor of MySQL exporter

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/certmanager.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Ethern Su <ehaprime@gmail.com>
This PR added support for customization on cert duration in kube-prometheus-stack helm chart.
- fixes #551

[kube-prometheus-stack] added support for cert duration customization;

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/values.yaml

* enable nodeexporter servicemonitor by default again
* was accidently disabled in: https://github.com/prometheus-community/helm-charts/pull/1593
- fixes https://github.com/prometheus-community/helm-charts/issues/1638

[kube-prometheus-stack] enable nodeexporter servicemonitor by default again

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/serviceaccount.yaml
charts/prometheus-mysql-exporter/values.yaml

This Pr adds annotations to prometheus-mysql-exporter service account, this in my case is to add google workload identity

[prometheus-mysql-exporter] add annotations to service account

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/config-reloaders.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-state-metrics.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-resources.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-network.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

* new feature in the sync_prometheus_rules.py hack : any Prometheusrule alert can now be disabled in values.yaml using `Values.defaultRules.disabled.<name of the alert>`.
* sync rules with this new feature
This PR fixes non-referenced issues (as far as I know) with alerts that are broken in specific cases and that users would want to disable.
Such cases are so specific that users would not want to open an issue. Or if they opened an issue (like the `NodeRAIDDegraded` below) it would be closed soon as "won't fix" because yes, they are too specific.
In my own case : my QNAP NAS will define a lot of RAID1 slots but use only 2 because I have only 2 disks (the 2 `U` below).
```
$ cat /proc/mdstats
...
md13 : active raid1 sdb4[0] sda4[24]
458880 blocks super 1.0 [24/2] …
```

[kube-prometheus-stack] Disable specific alert in values.yaml

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

increases the minor chart version of grafana
sorry for the two PRs, i deleted the old one, I created a new branch because of the signoff, I couldn't amend one of the commits

[kube-prometheus-stack] bump grafana version in umbrella chart #1660

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/serviceaccount.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

Fixes indentation of ServiceAccount annotations when more than one annotation is provided.
It also excludes the `annotation` key from the manifest if no annotations are provided.
Signed-off-by: Keenan Lorenzo Lawrence <keenan.l.lawrence@gmail.com>

[prometheus-cloudwatch-exporter] Fix indentation for multiple annotations of ServiceAccounts

---

.github/CODEOWNERS
charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/OWNERS

Added dotdc as a maintainer for kube-state-metrics
- fixes #

[kube-state-metrics] added dotdc as a maintainer

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/values.yaml

PSPs are deprecated in Kubernetes 1.21 and will be removed in Kubernetes 1.25. Therefore they should not be created by default.
https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/
Signed-off-by: Frederik Weber <frederik.weber@bs.ch>
This PR disables PSPs by default as they are deprecated.
- fixes #1386

[kube-prometheus-stack] Disable PodSecurityPolicies Creation by Default

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml

https://github.com/prometheus-community/helm-charts/commit/51351ed2db55a180105598ac83255afde0a12765
This introduced the functionality to disable unnecessary alerts. But the implementation will only add the condition block around the first matched alert. This PR will find out all matched alerts and add condition block

[kube-prometheus-stack] disable all matched alerts

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml

For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@andrewgkew @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro
We have strict requirements to use sha256 on all our container images. Alertmanager's template did not allow for that. Even though you can configure it in the spec.sha field, it wasn't used.
This is the same logic that is used to template the Prometheus instance
There should be no breaking changes

[kube-prometheus-stack] image tag and sha logic for alertmanager instance

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

kube-controller-manager since Kubernetes 1.22 and kube-scheduler since
1.23 by default only serve secure endpoints on new ports with HTTPS
enabled, this commit makes default values for scraping dynamic, based on
used Kubernetes version.
- Closes #1310

[kube-prometheus-stack] Support new default ports for controlplane

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

I am bringing back the service monitor selectorOverride option that were removed in v24 (https://github.com/prometheus-community/helm-charts/commit/c75ec1c8ead17a745b9e141da4ebd51922626794) when deprecating the kube-prom-stack Service Monitors in favour of the tools specific chart Service Monitors.
While I could not find the old issue from many years ago, this override was introduced to solve problems with various deployment tools that take over labels. In our case ArgoCD which changes the value the instance label. Once I upgraded to 24 I realised I lost a lot of metrics and that is because the service monitor labels were all wrong and I could find no equivalent new field.
Once merged I Can make a PR for prom stack chart

[kube-state-metrics] reintroduce service monitor selectorOverride

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Fix to avoid a warning on a chart install/upgrade:
```
coalesce.go:199: warning: destination for sidecarContainers is a table. Ignoring non-table value []
```
Since `sidecarContainers` in [sts.yaml](https://github.com/prometheus-community/helm-charts/blob/d50ef73002549f30368143a918c2dfc374e0db6d/charts/prometheus/templates/server/sts.yaml#L175) expects map, not a list. 
`---`
@gianrubio 
@zanhsieh 
@Xtigyro 
@monotek 
@naseemkullah

[prometheus] Set sidecarContainers in a default values.yaml to {}

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml
charts/prometheus-node-exporter/values.yaml

I am bringing back the service monitor selectorOverride option that were removed in v24 (https://github.com/prometheus-community/helm-charts/commit/c75ec1c8ead17a745b9e141da4ebd51922626794) when deprecating the prometheus-node-exporter Service Monitors in favour of the tools specific chart Service Monitors.
While I could not find the old issue from many years ago, this override was introduced to solve problems with various deployment tools that take over labels. In our case ArgoCD which changes the value the instance label. Once I upgraded to 24 I realised I lost a lot of metrics and that is because the service monitor labels were all wrong and I could find no equivalent new field.
Once merged I Can make a PR for prom stack chart

[prometheus-node-exporter] reintroduce service monitor selectorOverride

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

This PR is to propose an update of the docker image used by this chart to be aligned with the current latest
From the changelog, no breaking changes are introduced.
Just removal of possible security issues coming from dependencies.

[prometheus-cloudwatch-exporter] update the cloudwatch-exporter image from 0.10.0 to 0.12.2

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/pvc.yaml
charts/prometheus/templates/pushgateway/pvc.yaml
charts/prometheus/templates/server/pvc.yaml

This PR fixes the field name for `volumeBindingMode` in PersistentVolumeClaims
- fixes #1713 
@gianrubio @Xtigyro @monotek @naseemkullah

[prometheus] Fix field name for PVC volumeBindingMode

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/_helpers.tpl

There's an error when using rolebindings on the prometheus chart, which has kube-state-metrics as a dependency. This small change enables kube-state-metrics to be inherited as a subchart, and for the useClusterRole to be set to false.
- fixes #1709 
- [ x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed

[kube-state-metrics] Minor change to label templating, to stop errors when it is a subchart and RoleBindings are toggled

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/podDisruptionBudget.yaml

The [pod disruption budget](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/alertmanager/podDisruptionBudget.yaml) for alertmanager in kube-prometheus-stack does not work because it has an [extra label](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/alertmanager/podDisruptionBudget.yaml#L19) in the selector which is not present on the pods
This PR removes the label which will make the PDB work again.

[kube-prometheus-stack] Remove extra label from pdb selector for alertmanager

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/values.yaml

This PR introduces a new field in the `prometheus-rabbitmq-exporter` chart to add additional labels to the deployment object. This is useful for installations of this chart which requires custom labels to be present on the k8s objects, for reasons like auditing/monitoring, etc.

[prometheus-rabbitmq-exporter] Introduce a new field to add additional labels for prometheus-rabbitmq-exporter deployment object

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml

This PR fixes the `matchExpression` for alertmanager `podAntiAffinity` configuration. Replacing `app` with `app.kubernetes.io/name` since alertmanager pods do NOT have an `app` label so the podAntiAffinity config didn't actually work.

[kube-prometheus-stack] Fix alertmanager podAntiAffinity

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

I am bringing back the service monitor selectorOverride option that were removed in v24 (https://github.com/prometheus-community/helm-charts/commit/c75ec1c8ead17a745b9e141da4ebd51922626794) when deprecating the kube-prom-stack Service Monitors in favour of the tools specific chart Service Monitors.
While I could not find the old issue from many years ago, this override was introduced to solve problems with various deployment tools that take over labels. In our case ArgoCD which changes the value the instance label. Once I upgraded to 24 I realised I lost a lot of metrics and that is because the service monitor labels were all wrong and I could find no equivalent new field.
Now that prometheus-node-exporter and kube-state-metrics charts have been updated, update prom stack.

[kube-prometheus-stack] final PR to finalise selectorOverrider

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/role.yaml

Fix an issue where cluster role would be generated multiple times when "namespaces" value is set (i.e. when only collecting information about
specific namespaces).
* Fixes an issue introduced in #953
Just adding a condition to loop only once when using cluster roles.
@mrueg  @tariq1890 @dotdc

[kube-state-metrics] Fix cluster role generation

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: Sven Haardiek <sven.haardiek@uni-muenster.de>
It is possible to change the `runAsUser`, but not the `runAsGroup` in the deployment. So despite the fact that the Pod is running as the user 1000, it is still running with the root group. This pull request makes in configurable and also set the default to 1000. Same id as the user.
I do not this there is an issue about it.

[prometheus-blackbox-exporter] Added runAsGroup to Deployment

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml

Fixed the selectorMonitor overrides that I added.
- fixes #

[kube-state-metrics] fix serviceMonitor override indentation

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Jürgen Weber <jurgen.weber@massive.co>
Patch update for grafana and kube-state-metrics
https://github.com/prometheus-community/helm-charts/pull/1763
https://github.com/grafana/helm-charts/commit/d6792e3b02e5b8e5aa6a8e4814e7da83ce016620
https://github.com/grafana/helm-charts/commit/959fa99a566e18881108e9517228633d9c3554a9
Bad labels and yaml formatting.

[kube-prometheus-stack] patch updates for kube-state-metrics and grafana

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

Signed-off-by: heriet <heriet@heriet.info>
Alertmanager supports [HTTPS and authentication](https://prometheus.io/docs/alerting/latest/https/). It requires `--web.config.file`. Therefore, I think alertmanager chart needs extraSecretMounts.
similar #1193
- This PR enables configure basic_auth_users, but error occurs by liveness/readiness prove. I think needs another fix.
```
Warning  Unhealthy  15m (x5 over 15m)   kubelet            Liveness probe failed: HTTP probe failed with statuscode: 401
Warning  Unhealthy  10m (x44 over 15m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 401
```

[alertmanager] Add alertmanager extraSecretMounts

---

.github/CODEOWNERS
charts/kube-prometheus-stack/Chart.yaml

Adding GMartinez-Sisti as new maintainer for kube-prometheus-stack
Related to #1656

[kube-prometheus-stack] Adding GMartinez-Sisti as new maintainer

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/servicemonitor.yaml

cc: @apenney @rpahli 
Updates `ServiceMonitor` to use `fullname` instead of `name`. This was preventing multiple releases of the chart to be deployed in a single namespace.
Prevents error: `Unable to continue with install: ServiceMonitor "prometheus-stackdriver-exporter" in namespace "ns" exists and cannot be imported into the current release`

[prometheus-stackdriver-exporter] Fix servicemonitor name

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/certmanager.yaml
charts/prometheus-adapter/templates/pdb.yaml
charts/prometheus-adapter/templates/secret.yaml

Signed-off-by: Kazuki Suda <kazuki.suda@gmail.com>
This PR fixes missing namespace field in some manifests. if there is no namespace field, there is no meaning if we use `--namespace` option to specify namespace with `helm template` command.
~This PR fixes a bug that cert-manager resources included in prometheus-adapter chart do not have namespace, so it is not set if namespace is specified.~
- fixes #
cc/ @mattiasgees @steven-sheehy @hectorj2f

[prometheus-adapter] Fix missing namespace field

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml
charts/prometheus/values.yaml

**What this PR does / why we need it:**
This PR gives you the ability to override default flags of the Prometheus server. It's useful when you need to run the Prometheus in agent mode, by avoiding usage of some flags such as `--storage.tsdb.retention.time` and etc.

[prometheus] adding defaultFlagsOverride key for Prometheus server

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

- Update Grafana Helm Chart to version 6.21.5
- fixes #1803

[kube-prometheus-stack] Update Grafana Chart version to 6.21.5

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/servicemonitor.yaml

Add missing namespaceSelector to MySQL exporter chart

[prometheus-mysql-exporter] Add missing namespaceSelector to servicemonitor

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/README.md
charts/prometheus-stackdriver-exporter/templates/deployment.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Upgrade app version to 0.12.0 https://github.com/prometheus-community/stackdriver_exporter/releases/tag/v0.12.0
This version comes with a breaking change of dropping env variables config for this exporter: https://github.com/prometheus-community/stackdriver_exporter/pull/142
- fixes #
I bumped the chart version to 2.0.0 due to the change in how config is passed to the exporter.

[prometheus-stackdriver-exporter] Switch exporter config to agrs instead of env variables.

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/deployment.yaml
charts/prometheus-stackdriver-exporter/values.yaml

This PR adds support for `imagePullSecrets`, in order to pull the Stackdriver Exporter image from private container registries.

[prometheus-stackdriver-exporter] Add support for imagePullSecrets

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml
charts/prometheus/values.yaml

Support running prometheus-server with hostPort

[prometheus] support using hostPort on prometheus-server

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/deployment.yaml
charts/prometheus-pushgateway/values.yaml

Signed-off-by: Jürgen Weber <jurgen.weber@massive.co>
This PR gives you the ability in the chart to manipulate httpHeaders for the live and ready probe. This is required when you attempt to turn on basic http auth with the pushgateway as it turns it on for [ALL http endpoints](https://github.com/prometheus/pushgateway#tls-and-basic-authentication).

[prometheus-pushgateway] give the pushgateway live/ready probes the ability to add httpHeaders

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/_rules.tpl
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-burnrate.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-histogram.rules.yaml

Signed-off-by: Stanislav Khalash <stanislav.khalash@sap.com>
The PR makes the burnrate and the histogram apiserver rules optional and aligns them with the availability and the slo rules. The rules can be now disabled via the values.
https://github.com/prometheus-community/helm-charts/issues/1283

[kube-prometheus-stack] Make burnrate and histogram apiserver rules optional

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/service.yaml
charts/kube-state-metrics/values.yaml

Signed-off-by: Michael McLellan <jmikem825@gmail.com>
Allow specifying `clusterIP`, which can be set to `None` to create a headless service (useful with sharding so that the service can be used to query multiple replicas).
- Related to #1475

[kube-state-metrics] Allow specifying clusterIP

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml

Signed-off-by: Samarth MK <sam0392in@gmail.com>
- fix missing sourceLabels in servicemonitor.yaml
when chart is deployed with servicemonitor enabled in values.yaml, it throws below error:
```
Error: UPGRADE FAILED: failed to create resource: ServiceMonitor.monitoring.coreos.com "blackbox-exporter-prometheus-blackbox-exporter" is invalid: spec.endpoints.metricRelabelings.sourceLabels: Required value
```
After adding the sourceLabels, chart deploy successfully.
This PR aims to fix the bug in servicemonitor

[prometheus-blackbox-exporter] fix servicemonitor sourceLabels

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/cm.yaml
charts/prometheus/values.yaml

This PR will allow us to insert rules files (record and alert) by using prometheus internal label interpolation (eg `{{ $labels.namespace }}` without conflicting with helm rendering mechanism
Currently the chart give us the ability to split the rule files (alert and record) and insert in the prometheus-server pod through the configmap, which is pretty cool to organize the rules accross mulitple files (by group, by theme, ...)
We currently do it by adding a key named with the rule file name under the `serverFiles` root field in the `values.yaml`
Example:
```
serverFiles:
alert-jobs.yaml:
groups:
- name: KubeJobs
rules:
- alert: jobs-not-healthy
expr: kube_job_failed > 0
for: 5m
labels:
severity: critical
alerttype: general
annotations:
description: "job is in a non-ready state"
```
``` …
```

[prometheus] add ruleFiles value to insert rule files with label interpolation

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

We want to further configure the Kubernetes container security context for the Prometheus Operator, so we can set other container-specific settings such as capabilities -> drop -> ALL. Therefore we expose the container-specific security context using `containerSecurityContext` as the input (as used in other prometheus helm-charts e.g. [node-exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L79)).
We understand that some other Prometheus containers such as the node-exporter do not support dropping capabilities (in that case, because it did not have any in the first place) - this pull request assumes that isn't the case for Prometheus Operator, but please do let us know if that is an incorrect assumption.

[kube-prometheus-stack] Expose the container-specific security context for Prometheus Operator

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/values.yaml

Signed-off-by: AleksaC <aleksacukovic1@gmail.com>
Fixes indentation in example resources comment for prometheus-pushgateway chart.

[prometheus-pushgateway] Fix indentation in resources example comment

---

.github/CODEOWNERS
charts/prometheus-node-exporter/Chart.yaml

Related to https://github.com/prometheus-community/helm-charts/issues/1656#issuecomment-1005306520

[prometheus-node-exporter] Add zanhsieh as one of maintainers

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/servicemonitor.yaml

Currently scrapeTimeout value for serviceMonitor is ignored if interval value is not specified. This PR allows to specify scrapeTimeout independently.

[prometheus-stackdriver-exporter] ServiceMonitor: allow to specify scrapeTimeout independently

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml

Signed-off-by: Michael Kirpichev <m.kirpichev@haut.ai>
Today I tried to migrate to new grafana alerting and noticed following diff in one of my dashboards:
So now grafana relates on uid to reference data source from dashboard. To avoid any potential issues I think that is a good idea to fix uid of default data sources. I dont think this change will affect anybody with old alerts and will ease migration to new system.
P.S. 
Grafana dashboard migration results after uid was specified:

[kube-prometheus-stack] Add uid to grafana default datasources

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/_helpers.tpl
charts/prometheus-postgres-exporter/values.yaml

Closes #1845
It implements feature request #1845 to support custom DB [connection parameters](https://www.postgresql.org/docs/14/libpq-connect.html#LIBPQ-PARAMKEYWORDS) for DATA_SOURCE_URI
- fixes #1845
It is backwards compatible.
With default settings (when `.Values.config.datasource.extraParams` is empty) the only side effect is that `DATA_SOURCE_URI` will end with `&` unlike before, but that is ok for Postgres (tested). This allows simpler string concatenation with `.Values.config.datasource.extraParams` without needing to add `&` to the beginning of the value before first parameter
In values.yaml override `.Values.config.datasource.extraParams` value for example with `application_name=prometheus-postgres-exporter`. If you want to add multiple parameters, separate them with `&`.

[prometheus-postgres-exporter] Support custom DB connection parameters

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/templates/prometheusrule.yaml
charts/prometheus-json-exporter/templates/servicemonitor.yaml
charts/prometheus-json-exporter/values.yaml

- Add an option to create a ServiceMonitor for each json-exporter target.
- Add the ability to provide prometheus rules

[prometheus-json-exporter] Add ability to create a serviceMonitor and prometheus rules

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/_helpers.tpl

If `.Values.config.datasource.extraParams` is not configured during the upgrade the URI will end with `&`.
Despite not being an issue for the connection I find it cleaner to strip it out of the connection string.

[prometheus-postgres-exporter] trimmed data_source_uri if no extra options are provided

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl

Fixes an issue if this chart is wrapped and given a version that is on a PR or branch with a +. The chart ID is protected but the main version is not.

[kube-prometheus-stack] Replace invalid characters in the version

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/README.md
charts/prometheus-snmp-exporter/templates/servicemonitor.yaml
charts/prometheus-snmp-exporter/values.yaml

Signed-off-by: Taro Kitano <unchemist@gmail.com>
When using ServiceMonitor, it works even if there are multiple targets. This PR is inspired by the implementation of prometheus-blackbox-exporter:
* https://github.com/prometheus-community/helm-charts/blob/prometheus-blackbox-exporter-5.4.1/charts/prometheus-blackbox-exporter/values.yaml#L224-L231
* https://github.com/prometheus-community/helm-charts/blob/prometheus-blackbox-exporter-5.4.1/charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
In version 0.x, only a single snmp target works, as shown in the following issue.
To maintain compatibility as much as possible, I used existing keys, but version 0.x did not fundamentally support multiple targets, so I had to raise the major version.
- fixes #1734
I have checked it in my …

[prometheus-snmp-exporter] Support for multiple targets when using ServiceMonitor

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node.rules.yaml
charts/kube-prometheus-stack/values.yaml

* Bump prometheus-operator to v0.55.0
* Bump thanos to 0.25.1
* Bump prometheus to 2.33.5
* Sync charts
* Sync crds
* Sync dashboards
* Sync rules

[kube-prometheus-stack] Prometheus-Operator v0.55.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

prometheus-operator 0.55 introduced a new config key in alertmanager (alertmanagerConfiguration). Routing this new key from the chart value.
`helm template foo . --show-only templates/alertmanager/alertmanager.yaml`
```
[...]
logFormat: "logfmt"
logLevel:  "info"
retention: "120h"
alertmanagerConfigSelector: {}
alertmanagerConfigNamespaceSelector: {}
routePrefix: "/"
[...]
```
and with new value
`helm template foo . --show-only templates/alertmanager/alertmanager.yaml --set alertmanager.alertmanagerSpec.alertmanagerConfiguration.name=foo`
```
[...]
logFormat: "logfmt"
logLevel:  "info"
retention: "120h"
alertmanagerConfigSelector: {}
alertmanagerConfigNamespaceSelector: {}
alertmanagerConfiguration:
name: foo
routePrefix: "/"
[...]
```

[kube-prometheus-stack] Add alertmanager alertmanager configuration

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/servicemonitor.yaml
charts/prometheus-mysql-exporter/values.yaml

Add relabelings to servicemonitor for prometheus-mysql-exporter like other exporters.

[prometheus-mysql-exporter] Add relabelings to servicemonitor

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/NOTES.txt
charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml

Fix a `nil pointer evaluation` and missing namespace update in NOTES.txt introduced by this PR: https://github.com/prometheus-community/helm-charts/pull/1878#issuecomment-1073390542
```
Error: template: prometheus-blackbox-exporter/templates/_helpers.tpl:77:16: executing "prometheus-blackbox-exporter.namespace" at <.Values.namespaceOverride>: nil pointer evaluating interface {}.namespaceOverride
```

[prometheus-blackbox-exporter] Fix namespace override

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
charts/prometheus-postgres-exporter/values.yaml

Add relabelings to servicemonitor to postgres exporter

[prometheus-postgres-exporter] Add relabelings to servicemonitor

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

Signed-off-by: Thomas Steinheber <16717418+steinheber@users.noreply.github.com>
Security best practices demand that deployments shall be disallowed from escalating privileges. This may be enforced by gatekeepers like OPA policies. 
This PR will disallow privileges to be escalated by the blackbox exporter container by default.

[prometheus-blackbox-exporter] disallow privilege escalation

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml

Signed-off-by: Sebastian Struß <struss@justtrack.io>
We are getting errors in our k8s event logs like
```
Exec lifecycle hook ([/bin/bash -c sleep 20]) for Container "exporter" in Pod "prometheus-elasticsearch-exporter-654596b9d5-qb7gx_elasticsearch(bd9d0706-fd45-45c9-af18-0ecf86819142)" failed - error: command '/bin/bash -c sleep 20' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"/bin/bash\": stat /bin/bash: no such file or directory: unknown\r\n"
```
We need this pr to get less errors in the logs.
Prove:
```
$ docker run --rm --entrypoint /bin/bash quay.io/prometheuscommunity/elasticsearch-exporter:v1.3.0 && echo $?
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: …
```

[prometheus-elasticsearch-exporter] fixed pre-stop lifecycle hook

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
charts/kube-prometheus-stack/values.yaml

It allow to override the default Grafana datasources UID created by the helm chart
Fixes: #1720

[kube-prometheus-stack] Allow to override Grafana datasources UID

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

Needed for scraping reloader metrics
Signed-off-by: Alexis Guerville <alexis.guerville@messagebird.com>
This allows exposing ports on the configmapreloaders containers. It is necessary to allow scraping the reloaders metrics.

[alertmanager] Allow exposing configmap reloaders port

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

prometheus-node-exporter will not be upgraded without a regeneration of the `Chart.lock` file.

[kube-prometheus-stack] Regenerate lock file

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@MattiasGees @steven-sheehy @hectorj2f
As we migrate most of our anti-affinities to topology spread constraints, we need a way to configure them on prometheus-adapter pods. This PR introduces this from the values.yaml. No breaking changes are introduced
Cheers!

[prometheus-adapter] support for topology spread constraints

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Clearly indicates the presence of ingressclassname.
For Kubernetes >= 1.18 We should specify the ingress-controller via the field ingressClassName
See https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
- related #483
This commit doesn’t change any behavior.
It was previously possible to operate as follows,
```
helm install --set grafana.ingress.enabled=true --set grafana.ingress.ingressClassName=nginx kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 34.7.0
```

[kube-prometheus-stack] Add values grafana.ingress.ingressClassName

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Upgrades dependency Grafana to 6.26.0 to fix grafana/grafana#47240. 
Do not merge before 6.26.0 is released! See grafana/helm-charts#1185

[kube-prometheus-stack] Upgrade Grafana to 6.26

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Signed-off-by: Endre Kadas <ekadas@gmail.com>
Changes made in https://github.com/prometheus-community/helm-charts/pull/1520, which ensure alignment with Prometheus labeling conventions, have caused issues in cases where a resource is publishing metrics about another resource.
One example is kube-state-metrics, which publishes metrics about other kubernetes resources with labels respecting the convention, however prometheus overwrites these with labels that are true about kube-state-metrics.
This PR fixes that.
I've opted to add `honor_labels: true` only to scrape configurations updated in that PR.
- fixes https://github.com/prometheus-community/helm-charts/issues/1548
- …

[prometheus] Existing labels are honored

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/node-exporter/daemonset.yaml
charts/prometheus/values.yaml

We're using **kyverno** as a Validation Admission Controller on EKS cluster. And one of the rule that we have configured there is to prevent the admisison of Pods on the cluster which doesn't specify allowPrivilegeEscalation attribute in securityContext section at container level. Since **NodeExporter** pods doesn't provide that capability so we were unable to deploy the prometheus helm chart on EKS cluster.
This PR addresses that problem.
- fixes #1992 
[@gianrubio](https://github.com/gianrubio) [@zanhsieh](https://github.com/zanhsieh) [@Xtigyro](https://github.com/Xtigyro) [@naseemkullah](https://github.com/naseemkullah) - Please review this PR and let me know if any change is required. For now, we have disabled the kyverno on EKS cluster in Dev environment. I'll greatly appreciate if …

[prometheus]Added securityContext for nodeExporter container

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/values.yaml

Routine minor upgrade of blackbox exporter. Change set: https://github.com/prometheus/blackbox_exporter/releases/tag/v0.20.0
n/a
- [x ] Chart Version bumped
- [x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

[prometheus-blackbox-exporter] Upgrade blackbox exporter from v0.19.0 to v0.20.0

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/deployment.yaml
charts/prometheus-snmp-exporter/values.yaml

Signed-off-by: tom1299 <tom1299@jeeatwork.com>
Adds the ability to add pod security and container security context to the deployment by specifying them as values.
None

[prometheus-snmp-exporter] Add pod and container security context

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

This is a tiny, cosmetic PR, addressing the [deprecation of the `git.io` URL shortener service](https://github.blog/changelog/2022-04-25-git-io-deprecation/) by replacing the Prometheus StatefulSet datasource reference of the `prometheus-operator` to an unshortened link.
n/a
~I've not bumped the Chart version as I'm not sure it should be bumped even for such a cosmetic update.~
EDIT: The chart version bumped as requested

[kube-prometheus-stack]: Update prometheus-operator ref URL

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/deployment.yaml
charts/prometheus-pushgateway/templates/serviceaccount.yaml
charts/prometheus-pushgateway/templates/servicemonitor.yaml
charts/prometheus-pushgateway/values.yaml

Signed-off-by: Philippe <philippe.burgisser@camptocamp.com>
- Support of side car containers to run for example the oAuth proxy.
- Adding annotations to SA (used in OpenShift for internal TLS certification generation)
- Adding support of authentication in ServiceMonitor when the pushproxy is behind a proxy like the oAuth proxy

[prometheus-pushgateway] Adding extra containers

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/README.md
charts/prometheus-postgres-exporter/values.yaml

Signed-off-by: secustor <sebastian@poxhofer.at>
The default query currently produces errors and fail as the columns of `pg_stat_statements` have changed.     
There are no split into exec time and plan time. This PR modifies the query to combine both values so that the metrics are working again as expected.      
This potentially breaks PG instances before 13, but I have no instances to confirm this assumption.  
https://github.com/prometheus-community/postgres_exporter/issues/541

[prometheus-postgres-exporter]:  use new time column scheme of PG13

---

.github/CODEOWNERS
charts/prometheus-elasticsearch-exporter/Chart.yaml

removing myself from es exporter maintainers list.
not sure if this requires a chart version bump as well

[prometheus-elasticsearch-exporter] remove me from elasticsearch chart

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes-darwin.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
charts/kube-prometheus-stack/values.yaml

* Update prometheus-operator to 0.56.2
* Sync CRDs
* Sync Dashboards
* Sync prometheus rules
* Update chart deps

[kube-prometheus-stack] Version bump to 0.56.2

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/values.yaml

Signed-off-by: Pierre Magne <pierre.magne@qonto.com>
Support REDIS_USER environment variable to use Redis 6 ACL.
cf https://github.com/oliver006/redis_exporter#command-line-flags
(Without this PR, REDIS_USER can be set via the `env` setting in values.)

[prometheus-redis-exporter] Add support for REDIS_USER

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml
charts/prometheus-node-exporter/values.yaml

Signed-off-by: Tomasz Drachenberg <tdrachen@intercars.eu>
This PR lets use basic authentication in node-exporter. It's important to protect access to sensitive data about the cluster, especially when these data can't be protected using network policies. The cross-dependency between a service mesh and a monitoring stack is not good for everyone.

[prometheus-node-exporter] Add basicAuth configuration to ServiceMonitor

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml

#2033 caused Helm errors if users didn't define `additionalRelabeling` for each rule because there wasn't a default.
@desaintmartin 
Signed-off-by: Evan Pitstick <epitstick@paloaltonetworks.com>

[prometheus-blackbox-exporter] need default for additionalRelabeling

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/servicemonitor.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Current configuration of `jobLabel` in Elasticsearch Exporter ServiceMonitor does not allow users to define this value themselves. Also its current values has no effect as it tries to use the release name as a value whereas this parameter is supposed to match a Kubernetes Endpoints label to let Prometheus Operator use its value for Prometheus `job` label.
This PR uses the same strategy as available in prometheus-node-exporter chart:
* allow users to provide `jobLabel` in helm values
* default value refers to Endpoints label `app.kubernetes.io/name`: a [well-known Kubernetes label](https://kubernetes.io/docs/reference/labels-annotations-taints/#app-kubernetes-io-name)
* since this label is not set to the service resource as of now: default behavior for elasticsearch-exporter would remain …

[prometheus-elasticsearch-exporter] Allow jobLabel configuration

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

Signed-off-by: sepaper <sepaper@naver.com>
Depending on a k8s cluster environment, runAsUser in Deployment is determined by the cluster security policy. 
For example, when setting runAsUser as 10001 in my openshift cluster, it occurs a policy violation error of runAsUser range.
Considering the policy difference between each cluster, I think it is better to allow runAsUser in Deployment to be configurable as a chart value. 
None
I guess fsGroup in Deployment is in the same case as runAsUser is, and it is already configurable as a chart value.

[prometheus-adapter] Add runAsUser value to Deployment

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/pushgateway/service.yaml

This simple PR adds the ability to define the PushGateway service node port number in the same way as Prometheus and AlertManager, by adding a ```nodePort``` parameter: ```pushgateway.service.nodePort```. This is an important feature to our projects for integration testing with microclusters where we open ports on clusters before testing, so must know and set the application ports in advance in order to connect through to the API/frontend.
Full backwards compatibility, doesn't affect any deployments where ```pushgateway.service.nodePort``` is not explicity defined as it will still randomise. Minor version update.

[prometheus] Add ability to define PushGateway node port number

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Zadkiel Aharonian <zadkiel_aharonian@carrefour.com>
This PR adds the missing defaultRules.rules.kubeApiserverBurnrate field in the Helm values

[kube-prometheus-stack] add missing defaultRules.rules.kubeApiserverBurnrate

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/_helpers.tpl
charts/prometheus-adapter/templates/pdb.yaml

Concerning the prometheus-adapter chart, this PR enables using the policy/v1 apiversion for pod disruption budgets, if the apiversion exists on the given cluster.
This is being added because the policy/v1beta1 apiversion is being removed in Kubernetes 1.25.

[prometheus-adapter] conditionally use the policy/v1 apiversion for PDBs

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/alertmanager/pdb.yaml
charts/prometheus/templates/pushgateway/pdb.yaml
charts/prometheus/templates/server/pdb.yaml

Uses policy/v1 apiversion for creating poddisruptionbudgets when running against a cluster using a new enough kubernetes version. This is important because policy/v1beta1 is being removed in kubernetes 1.25.

[prometheus] use policy/v1 for poddisruptionbudgets, when available

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Signed-off-by: Matt Oddie <github@mattoddie.com>
This PR fixes an issue that prevents correct scraping of IPv6 targets. The current regular expression used to override the port
```
([^:]+)(?::\d+)?;(\d+)
``` 
does not support IPv6 in the first match group due to `:` in addresses. This results in prometheus falling back to discovered ports which often do not serve metrics and therefore show as `down`. The following regex should fix that by using a non-greedy expression.
```
(.+?)(?::\d+)?;(\d+)
```
and works on both IPv4 and IPv6 addresses, with and without ports:
```
70.97.31.116;9090 -> 70.97.31.116:9090
70.97.31.116:8080;9090 -> 70.97.31.116:9090
[ea2d:d25e:8198:4efb:d928:15b6:a52e:3968];9090 -> [ea2d:d25e:8198:4efb:d928:15b6:a52e:3968]:9090 …
```

[prometheus] Update scrape config to support IPv6

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/_helpers.tpl
charts/prometheus-stackdriver-exporter/templates/deployment.yaml
charts/prometheus-stackdriver-exporter/templates/secret.yaml
charts/prometheus-stackdriver-exporter/templates/service.yaml
charts/prometheus-stackdriver-exporter/templates/serviceaccount.yaml
charts/prometheus-stackdriver-exporter/templates/servicemonitor.yaml
charts/prometheus-stackdriver-exporter/values.yaml

Current chart is labelling resources with:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: example-prometheus-stackdriver-exporter
labels:
app: prometheus-stackdriver-exporter
app.kubernetes.io/name: prometheus-stackdriver-exporter
chart: prometheus-stackdriver-exporter-2.2.0
heritage: Helm
release: example
spec:
```
This PR reconciles these labels in favour of using Kubernetes [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) to `prometheus-stackdriver-exporter`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: example-prometheus-stackdriver-exporter
labels:
helm.sh/chart: prometheus-stackdriver-exporter-3.0.0
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/component: metrics
app.kubernetes.io/part-of: …
```

[prometheus-stackdriver-exporter] Add: Kubernetes recommended labels and custom labels

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

Add new arguments for service monitor template files to set up required settings to collect metrics when using Istio in mtls mode.

[kube-state-metrics] Add scheme and tlsConfig arguments to serviceMonitor

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

…
Ammends #2089 to fix the resource type for built-in exclusions
Ammends #2089

[kube-prometheus-stack] Add support for setting excludedFromEnforce in PrometheusSpec ADDENDUM

---

charts/prometheus-mongodb-exporter/Chart.yaml
charts/prometheus-mongodb-exporter/README.md
charts/prometheus-mongodb-exporter/templates/_helpers.tpl
charts/prometheus-mongodb-exporter/templates/deployment.yaml
charts/prometheus-mongodb-exporter/templates/secret.yaml
charts/prometheus-mongodb-exporter/templates/service.yaml
charts/prometheus-mongodb-exporter/templates/serviceaccount.yaml
charts/prometheus-mongodb-exporter/templates/servicemonitor.yaml
charts/prometheus-mongodb-exporter/templates/tests/test-connection.yaml
charts/prometheus-mongodb-exporter/values.yaml

* use percona/mongodb_exporter:0.31.0 docker image
* readme and chart.yaml are refering to percona/mongodb_exporter but ssheehy/mongodb-exporter is used
* the currently used ssheehy/mongodb-exporter docker image seems unmaintained -> https://github.com/steven-sheehy/mongodb_exporter
* newest 0.32.0 image of percona image has a bug and therfore the older one is used. see: https://github.com/percona/mongodb_exporter/issues/483
* The commnad arguments of the exporter have changed. If you have custom `extraArgs` settings you have to adjust them. Because of the newer version of the exporter image metrics may varry though, so you might need to adjust your dashboard querries or try out the "--compatible-mode" parameter in `extraArgs`.
* use …

[prometheus-mongodb-exporter] use docker image described in readme and chart.yaml

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

Signed-off-by: czomo <tomaszjdul@gmail.com>
- Bump kafka-exporter to 1.4.2 acording to https://github.com/danielqsj/kafka_exporter/releases/tag/v1.4.2 along with new flags
- Bump kafka to highest 2.*.* release from bitnami
Fixes https://github.com/bitnami/charts/issues/10539 as kafka dependency is no longer available from index

[prometheus-kafka-exporter] Bump kafka-exporter to 1.4.2, bump bitnami kafka

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Change the default grouping in Alertmanager to group by 'namespace' instead of 'job'. The 'job' grouping seems to be quite arbitrary, as most alerts are not related to a job.
This is also the default grouping used by kube-prometheus, see:
https://github.com/prometheus-operator/kube-prometheus/blob/3f3b56e/jsonnet/kube-prometheus/components/alertmanager.libsonnet#L44

[kube-prometheus-stack] Change default grouping for Alertmanager to 'namespace'

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Currently the `InfoInhibitor` rule does not actually inhibit info alerts; i.e. it does still fire on it's own, but does not mute the underlying `severity = 'info'` alerts. This PR adds 3 inhibition rules, based on the ones implement [in `kube-prometheus`](https://github.com/prometheus-operator/kube-prometheus/blob/3f3b56e/jsonnet/kube-prometheus/components/alertmanager.libsonnet#L30-L42), which do the following:
- if the `InfoInhibitor` alert is firing, any alert with `severity = 'info'` within the same namespace will be muted;
- if an alert with `severity = 'warning'` is firing, any alert with `severity = 'info'` with the same alertname and within the same namespace will be muted;
- if an alert with `severity = 'critical'` is firing, any alert with `severity = 'info'` or `severity = …

[kube-prometheus-stakc] Add inhibit rules to default Alertmanager config

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/extra-manifests.yaml
charts/prometheus/values.yaml

Signed-off-by: Yu Kato <yu-kato@colopl.co.jp>
This PR offers to deploy extra manifests, which includes any template inside prometheus helper.
When we want to deploy extra manifests using template helper the chart provides,
`server.extraObjects` does not help in some cases.
fixes #2139

[prometheus] Add extra manifest templates

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/README.md

Adding instructions about how to upgrade chart from version 2.x to 3.x (missed on previous [PR](https://github.com/prometheus-community/helm-charts/pull/2125)).
- none
None.

[prometheus-stackdriver-exporter] Add: README instructions to upgrade 2.x to 3.x

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/_helpers.tpl
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/templates/podsecuritypolicies.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

The Bitnami charts have a convention that allows one to set a set of global imagePullSecrets which are inherited if you depend on a specific chart from another chart. This obviates the need to repetitively specify the same image pull secrets for all images and charts. This PR adds that same functionality to the elasticsearch-exporter.
Also this PR updates the PodSecurityPolicy to use the non-deprecated apiGroup if it is available, making the chart compatible with modern K8s versions.

[prometheus-elasticsearch-exporter] Allow to set global imagePullSecrets

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/service.yaml
charts/prometheus-redis-exporter/templates/servicemonitor.yaml
charts/prometheus-redis-exporter/values.yaml

Add scheme and tlsConfig arguments to service monitor which allows to set up special settings to work with istio in mtls strict mode, and add an option to allow custom service port name.

[prometheus-redis-exporter] Add tls config options for servicemonitor

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/pdb.yaml

Signed-off-by: Zhang, Henry <Haijun.Zhang@fmr.com>
The policy/v1beta1 API version of PodDisruptionBudget will no longer be served in v1.25.
Migrate manifests and API clients to use the policy/v1 API version, available since v1.21.
- fixes #https://github.com/prometheus-community/helm-charts/issues/1967

[kube-state-metrics] - Upgrade pdb version to apiVersion: policy/v1

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/pdb.yaml

Signed-off-by: Zhang, Henry <Haijun.Zhang@fmr.com>
The policy/v1beta1 API version of PodDisruptionBudget will no longer be served in v1.25.
Migrate manifests and API clients to use the policy/v1 API version, available since v1.21.
- fixes # https://github.com/prometheus-community/helm-charts/issues/1967

[alertmanager] - Upgrade pdb version to apiVersion: policy/v1

---

charts/prometheus-mongodb-exporter/Chart.yaml
charts/prometheus-mongodb-exporter/templates/service.yaml
charts/prometheus-mongodb-exporter/templates/servicemonitor.yaml
charts/prometheus-mongodb-exporter/values.yaml

Add service monitor arguments to define TLS configuration which is necessary when using Istio in mTls strict mode. Also, add a new argument to change the service name once Istio needs a protocol prefix.

[prometheus-mongodb-exporter] Add tls configuration option for service monitor

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

The latest version of the KSM chart allows configuring the new CustomResourceStateMetrics feature:
* https://github.com/prometheus-community/helm-charts/pull/2167
* https://github.com/kubernetes/kube-state-metrics/pull/1710

[kube-prometheus-stack] update kube-state-metrics and grafana to latest patch version

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Gustav Tonér <gustav.toner@gmail.com>
This upgrades the Grafana chart to version 6.31.x which in turn uses the newly released Grafana version 9.

[kube-prometheus-stack] Upgrade Grafana chart to 6.31.x (with Grafana version 9)

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/NOTES.txt

Fixes a minor documentation bug.
Fixes #2187.
I assume that this change is too minor for a version bump?

[prometheus-postgres-exporter] Use correct port in port-forward command

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/podsecuritypolicy.yaml

Signed-off-by: Othmane El Warrak <othmane.el.warrak@ibm.com>
@gianrubio @zanhsieh 
The policy/v1beta1 pod security policy is deprecated starting v1.21 and will be removed starting v1.25. this PR aims to use policy/v1 when possible or policy/v1beta1 otherwise. 
- fixes #2207 
- closes #2207 
This PR is based on https://github.com/prometheus-community/helm-charts/pull/2201

[prometheus-postgres-exporter] Use policy/v1 PodSecurityPolicy when available

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

Use the templated name for container, instead of using chart name in solo.
Required if user wants to override the chart name (i.e. using `alias` from a parent chart).
None
None

[kube-state-metrics] Use template name for container

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

Signed-off-by: Kazuyuki Iijima <iijimakazuyuki@gmail.com>
@tariq1890 @mrueg @dotdc 
This PR adds a feature to configure topology spread constraints on kube-state-metrics pods.
None
There will be no breaking changes.

[kube-state-metrics] Support for topology spread constraints

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/service.yaml
charts/kube-state-metrics/values.yaml

Adds a `selfMonitor.telemetryNodePort` field to values.yaml so that a NodePort for the telemetry endpoint can be specified when `service.type` is set to `NodePort`.
Tagging @tariq1890 @mrueg @dotdc as per the PR template comment.
There is a slight incongruence here in that if `selfMonitor.telemetryNodePort` is specified but `service.type` is not set to `NodePort`, the deployment will fail. Options to fix, if desired:
* put the telemetry endpoint fields under `service`
* create separate Services for telemetry and core metrics
* set the Service type to `NodePort` if either `service.nodePort` or `selfMonitor.telemetryNodePort` are specified
(In the existing chart, the deployment will also fail if `services.nodePort` is non-zero while `services.type` is not `NodePort` - but that's a bit less …

[kube-state-metrics] Add selfMonitor.telemetryNodePort field to values

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/templates/alertmanager/sts.yaml

To fix a typo in probeHeaders usage in alertmanager/sts.yaml and alertmanager/deploy.yaml
* fixes #(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
- fixes #2228 
- [ x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

[prometheus] typo in probeHeaders, should be alertmanaeger.probeHeaders not server.probeHeaders

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/templates/statefulset.yaml

Alertmanager HA setup with mutiple replicas is broken because of the issue tagged below. This PR resolves it.
- fixes #2230
Signed-off-by: Prashant Shahi <me@prashantshahi.dev>

fix(alertmanager): 🚑 resolve replicaCount comparision type issue

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@andrewgkew
@bismarck
@desaintmartin
@gianrubio
@gkarthiks
@GMartinez-Sisti
@scottrigby
@Xtigyro
Adds capability to configure Alertmanager TLS auth
- fixes #2240

[kube-prometheus-stack] Add web property to AlertmanagerSpec

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/values.yaml

This PR adds support for `objectStorageConfig` on thanos-ruler template
- fixes #2226

[kube-prometheus-stack]: Add objectStorageConfig for thanos-ruler

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
charts/kube-prometheus-stack/values.yaml

This adds support for `exemplarTraceIdDestinations` in the default Prometheus datasource for linking it to an existing(provisioned with `additionalDataSources`) tracing datasource(Jaeger/Zipkin ...etc )  in order to easily switch between metrics/traces from Grafana dashboards.
See https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-prometheus-data-source

[kube-prometheus-stack] Add exemplar support for Grafana datasource

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

Signed-off-by: Michael Kotten <michaelkotten@gmail.com>
- fixes #2144

[kube-state-metrics] adds deployment annotations for kube-state-metrics

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/values.yaml

Add some default metric relabel config values to cAdvisor and apiserver
configuration to reduce default cardinality. This will likely save a
couple hundred MiB of memory off Prometheus in the default
configuration.
Fixes: https://github.com/prometheus-community/helm-charts/issues/2133

[kube-prometheus-stack] Update metric relabel values

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Bump dependencies' versions of kube-prometheus-stack chart.
grafana: 6.32.2
kube-state-metrics: 4.13.0
This PR allows to use new features provided by KSM.

[kube-prometheus-stack]: Bump grafana and KSM versions

---

charts/prometheus-statsd-exporter/Chart.yaml
charts/prometheus-statsd-exporter/templates/deployment.yaml
charts/prometheus-statsd-exporter/templates/tests/test-connection.yaml
charts/prometheus-statsd-exporter/values.yaml

Adds the following parameters in `values.yaml`:
* `extraEnv`: additional container environment variables
* `extraArgs`: additional arguments in the statsd_exporter command line
These new parameters are already present in other prometheus exporter charts (e.g. https://github.com/prometheus-community/helm-charts/blob/f7368412de885085b61082cf44a2a37d6ec2aea3/charts/prometheus-blackbox-exporter/values.yaml#L21, and https://github.com/prometheus-community/helm-charts/blob/f7368412de885085b61082cf44a2a37d6ec2aea3/charts/prometheus-blackbox-exporter/values.yaml#L204).
In our case, we need this feature to change the logging format to `json`.

[prometheus-statsd-exporter] Add extraEnv and extraArgs

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

This MR adds support to define additional labels on exporters' `servicemonitors`.
- fixes #

[kube-prometheus-stack] support additional labels on exporters servicemonitors

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

Signed-off-by: Piotr Hryszko <piotr.hryszko@imgarena.com>
This PR adds optional `topologySpreadConstraints` to statefulset  that gives users control over how pods are scheduled across failure domains such as regions, zones, nodes, and other user-defined topology domains. This can help to achieve high availability as well as efficient resource utilization.
- fixes #
This is a new feature
- [ x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed

[alertmanager] Add optional topologySpreadConstraint to statefulset

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/values.yaml

Without this change v37 broke certain metrics which are useful, namely network metrics such as `container_network_receive_bytes_total`
While this issue was identified on k3s, I have encountered the issue on both an AKS and GKE cluster (running v1.21 and v1.23 respectively). You can see the problem if you run the following command `kubectl get --raw /api/v1/nodes/NODE_NAME/proxy/metrics/cadvisor | grep 'container_network'` (replacing NODE_NAME with a nodes name in your cluster)
- fixes https://github.com/k3s-io/k3s/issues/5891

[kube-prometheus-stack] Remove a cAdvisor metric relabelling

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

This PR bumps grafana chart dependency. This new version includes **significant** bugfixes for anonymous authentication.
- fixes #1806 (not sure if this issue tracks that specifically, but the symptoms of the issue match 100%).

[kube-prometheus-stack] Bump grafana to 6.32.7

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/values.yaml

Signed-off-by: Jordan Brown <jordan.brown@workday.com>
Currently, there is no way to pass a imagePullSecrets flag to the rabbitmq-exporter. This PR adds the feature flag necessary for this functionality.

[prometheus-rabbitmq-exporter] Add imagePullSecrets feature flag

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

This pr allows kube-state-metrics to only watch the release namespace for collecting metrics. This is particularly useful for users running in multi tenant Kubernetes clusters where their access is restricted to 1 namespace.
Similar functionality is already available in Grafana/Prometheus-Operator helm charts.

[kube-state-metrics] - Add option to only use the release namespace

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/templates/servicemonitor.yaml

The chart now creates multiple, differently named, ServiceMonitors to allow for multiple targets to be scraped.
Multiple targets did not create differently named ServiceMonitors resulting in the following error when defining more than one target:
`Error: servicemonitors.monitoring.coreos.com "json-exporter-prometheus-json-exporter" already exists`
_None_

[prometheus-json-exporter] fix: Multiple targets are now created as differently named ServiceMonitors

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Bump default version of the exporter to 1.5.0.
Breaking change if you upgrade from 1.3.0 or earlier. See [changelog](https://github.com/prometheus-community/elasticsearch_exporter/blob/master/CHANGELOG.md#150--2022-07-28)
Doesn't apply if you upgrade from 1.4.0

[prometheus-elasticsearch-exporter] Bump exporter to 1.5.0

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

Signed-off-by: Arthur Legrand <artlegrand@live.ca>
This is useful for people like me who use [Google Cloud SQL Proxy ](https://cloud.google.com/sql/docs/mysql/sql-proxy) as a sidecar to connect to the postgres server. 
Since it's a side car, the exporter sees the server as `127.0.0.1` which isn't very descriptive for many reasons, especially if you start having multiple PG Exporters for multiple servers.
Bumped the minor version of the chart as this adds a functionality in a backwards compatible manner.

[prometheus-postgres-exporter] Add possibility to have hostAliases defined in deployment spec

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
charts/kube-prometheus-stack/values.yaml

Hi all!
You forgot to add an option to _enable/disable_ `kubernetes-system-controller-manager` PrometheusRule.
Look, all files in the [rules folder](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14) contain option to disable or enable PrometheusRule deployment by set in the variables as `.Values.defaultRules.rules.<name>`, for example (scroll to the end of the line below):
https://github.com/prometheus-community/helm-charts/blob/a3a8328e9e6449c1fa02302715ecabb10663b275/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml#L7
or
https://github.com/prometheus-community/helm-charts/blob/a3a8328e9e6449c1fa02302715ecabb10663b275/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/co …

[kube-prometheus-stack] Add an option to enable/disable `kubernetes-system-controller-manager` PrometheusRule

---

.github/CODEOWNERS
charts/prometheus-smartctl-exporter/.helmignore
charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/templates/_helpers.tpl
charts/prometheus-smartctl-exporter/templates/configmap.yaml
charts/prometheus-smartctl-exporter/templates/daemonset.yaml
charts/prometheus-smartctl-exporter/templates/prometheusrule.yaml
charts/prometheus-smartctl-exporter/templates/rolebinding.yaml
charts/prometheus-smartctl-exporter/templates/service.yaml
charts/prometheus-smartctl-exporter/templates/serviceaccount.yaml
charts/prometheus-smartctl-exporter/templates/servicemonitor.yaml
charts/prometheus-smartctl-exporter/values.yaml

[prometheus-smartctl-exporter] Initial stab at a prometheus-smartctl-exporter chart

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

Signed-off-by: francisco.rangel-heb <rangel.francisco@heb.com>
This PR adds support for image sha (also called digest) for the image field. This is needed when signed images are used vs regular images with only tag.
- fixes #2369

feat[kube-state-metrics]: add image sha support for image specified

---

charts/prometheus-stackdriver-exporter/Chart.yaml
charts/prometheus-stackdriver-exporter/templates/deployment.yaml

Signed-off-by: Tuan Anh Nguyen <tuananh.nguyen-ext@commercetools.de>
With the serviceAccountName spec missing, helm won't be able to apply the change to deployment when we change the service account name.
Step to reproduce the bug
- Install prometheus-stackdriver-exporter using helm with default setting
- `helm get manifest` shows `serviceAccount: default`
- `kubectl get deployment` shows `serviceAccount: default` and `serviceAccountName: default`
- Change serviceAccount.create to true and upgrade the current release. 
- `helm get manifest` shows  `serviceAccount: ` with new value (generated from release name)
- `kubectl get deployment` still shows `serviceAccount: default` and `serviceAccountName: default`
The correct spec is `serviceAccountName` following …

[prometheus-stackdriver-exporter] Fix spec.serviceAccountName

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/_helpers.tpl

Signed-off-by: sagdeevrr <sagdeevrsrf@gmail.com>
This PR fix deploy when override value: `config.datasource.port`
example:
`helm template . --set config.datasource.user=dbuser --set config.datasource.password=qwerty --set config.datasource.database=test --set config.datasource.host=127.0.0.1 --set config.datasource.port="6432"`
Connection url will incorrect:
`  - name: DATA_SOURCE_URI
value: "127.0.0.1:%!s(int64=6432)/test?sslmode=disable"
`
N/A

[prometheus-postgres-exporter] Fix convert port variable to int

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/values.yaml

We need to set `timeoutSecond` in helm template for admission MutatingWebhookConfiguration in Prometheus Operator
- fixes #2020,#1041

[kube-prometheus-stack] Setting a custom timeout in admission mutatingWebhookConfiguration - Prometheus Operator chart Template

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/README.md
charts/prometheus-node-exporter/templates/NOTES.txt
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/templates/endpoints.yaml
charts/prometheus-node-exporter/templates/service.yaml
charts/prometheus-node-exporter/templates/serviceaccount.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml

- fixes #
This PR updates the node exporter labels to match the best practice described here: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

[prometheus-node-exporter] Update labels to match best practices

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/values.yaml

Signed-off-by: Sébastien Prud'homme <sebastien.prudhomme@gmail.com>
Fix SQL query indentation so that copy/paste values in an Ansible playbook works well in some editors (in my case Visual Studio Code).

[prometheus-postgres-exporter] Fix indentation
