prometheus-community/helm-charts

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/daemonset.yaml
charts/prometheus-snmp-exporter/values.yaml

Signed-off-by: Taro Kitano <unchemist@gmail.com>
When using snmp-exporter, DaemonSet is also made available in addition to Deployment.
* This PR is inspired by the implementation of [prometheus-blackbox-exporter](https://github.com/prometheus-community/helm-charts/commit/1ad1c1e1d3638325297a30e46e7d06e8d0b4e003).
* The only difference from Deployment is the removal of `replicas` and `strategy` , everything else is the same.
* `Deployment` is selected by default, and no effect will occur on the existing chart.

[prometheus-snmp-exporter] make DaemonSet available

---

charts/prometheus-mongodb-exporter/Chart.yaml
charts/prometheus-mongodb-exporter/values.yaml

Fixing a typo in the MongoDB URI in values.yaml file
Now the exporter can find MongoDB service running on the cluster

[prometheus-mongodb-exporter] fixing default mongodb uri

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/values.yaml

Signed-off-by: sat-devopsnow <sat@opsverse.io>
Especially useful when one exporter is scraping multiple targets with different password by [taking advantage of the exporter's `redis.password-file | REDIS_PASSWORD_FILE` options](https://github.com/oliver006/redis_exporter/tree/v1.27.0#command-line-flags)... Details here and in the `Test Results` section:
The Redis exporter [supports metric scraping of multiple redis instances by exposing the `/scrape` endpoint](https://github.com/oliver006/redis_exporter/tree/v1.27.0#prometheus-configuration-to-scrape-multiple-redis-hosts). However, if auth is enabled on those instances (and if each of these instances have different passwords), the only workaround is to run multiple exporters - because only a single password can be passed to the exporter. …

[prometheus-redis-exporter] support redis password file secret volume mount

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

[kube-prometheus-stack]
* Hint for replacing image sources for containers:
- grafana
- sidecar
- kube-state-metrics
- prometheus-node-exporter
Signed-off-by: moroviintaas <moroviintaas@gmail.com>
[kube-prometheus-stack]
* Bump chart version
Signed-off-by: moroviintaas <moroviintaas@gmail.com>
I was deploying kube-prometheus-stack on offline environment with internal image registry. I have created own values.yml file with changed image sources pointing to my registry. Yet some images failed to be pulled, as they had been defined in dependency charts. Maybe it is worth to note that default grafana image tag (in dependency chart) is currently set to "", which should resolve to "latest" as far as I know and potentially lead to stability issue.   
This PR does not change chart behavior, only …

[kube-prometheus-stack] Hinting containers' image source values for offline deployment

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/kube-prometheus-stack/values.yaml

Stumbled in to this when working with kyverno and enforced strict policies.
Kyverno and using strict policy configuration, job create for `ingress-nginx-admission-create` fails with policies `require-drop-all`and `disallow-privilege-escalation`. 
Adding the ability to configure containers in webhooks create and patch from helm values.
> k describe job monitoring-kube-prometheus-admission-patch
```
resource Pod/my-namespace/monitoring-kube-prometheus-admission-patch-njdkq was blocked due to the following policies
disallow-capabilities-strict:
require-drop-all: 'validation failure: Containers must drop `ALL` capabilities.'
disallow-privilege-escalation:
privilege-escalation: 'validation error: Privilege escalation is disallowed. The
fields …
```

[kube-prometheus-stack] SecurityContext for webhook job create/patch container

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

fix telemetry-port
Signed-off-by: Zhaojun Li <zhaojun.li@hotmail.com>
fix selfMonitor port

[kube-state-metrics] Fix selfMonitor port

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/ingress.yaml

Ingress API Version has been changed during kubernetes upgrades, the old api version is not supported:
For example, the 'networking.k8s.io/v1beta1' has been remove from kubernetes 1.22
This PR fixes the issue for ingress api version for different kubernetes version.
- fixes #

[prometheus-snmp-exporter] update ingress api version template to support multiple kubernetes versions

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

Bumps the version of the referenced kube-state-metrics image to the latest released version v2.6.0.

[kube-state-metrics] Bump kube-state-metrics version

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

Signed-off-by: Kevin Huang <git@kevin.huang.to>
To export the disk's SMART status using a sidecar attached to node-exporter, we would like to mount the /dev from the node to the sidecar in read-only.
To do so, we add a `sidecarHostVolumeMounts` value, that works similarly to `extraHostVolumeMounts`.

[prometheus-node-exporter] Add sidecarHostVolumeMounts

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Updated grafana to helm version 6.38.0 and app version 9.1.4

[kube-prometheus-stack] bump grafana 6.38.0 (9.1.4)

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml

…o define secret name.
Signed-off-by: Nikolay Osmolovskiy <nikolay.osmolovsky@gmail.com>
I want to use prometheus-elasticsearch-exporter as dependency in my helm chart and I want to have ability to set k8s secret name using tpl function, it will help to cope code duplication and I think it will be convenient for others to leverage this option.
@svenmueller @desaintmartin please look at this changes.

[prometheus-elasticsearch-exporter] Added option to use tpl to define secret name.

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: Zemtsov Vladimir <vl.zemtsov@gmail.com>
`walCompression` - bool variable
In helm construction:
```
{{- if .Values.prometheus.prometheusSpec.walCompression }}
walCompression: {{ .Values.prometheus.prometheusSpec.walCompression }}
{{- end }}
```
If walCompression = true, in CRD Prometheus added:
```
walCompression: true
```
if walCompression = false, IF in helm don't add walCompression field to CRD, and Prometheus used default - TRUE
Doesn't matter what you set to `walCompression` variable in helm, WalCompression always be enable in Prometheus.
I fix it.

[kube-prometheus-stack] Fix variable WalCompression

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/values.yaml

* add releaseLabel
* set to true to add the release label so scraping of the servicemonitor with kube-prometheus-stack works out of the box
* enables: https://github.com/prometheus-community/helm-charts/pull/2440

[prometheus-node-exporter] add releaseLabel

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/hack/update_crds.sh
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes-darwin.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
charts/kube-prometheus-stack/values.yaml

- Bumps the kube-state-metrics dependency version to latest

[kube-prometheus-stack] prometheus-operator0.59.1/Prometheus2.38.0/all dependencies

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/values.yaml

Automatically set "dnsPolicy" to "ClusterFirstWithHostNet" when using "hostNetwork"
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

[prometheus] Automatically set "dnsPolicy" to "ClusterFirstWithHostNet" when using "hostNetwork"

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml

If you set `server.containerSecurityContext` (when `kind: Deployment`) helm-install fails with the following error
```
error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 95: mapping key "securityContext" already defined at line 49
```
Apparently by some changes earlier this year `securityContext` gets set twice for the server-container.
This PR removes one of them and also aligns a similar section in `kind: StatefulSet` to look the same as in the deployment.

[prometheus] fix double securityContext for server-container in prometheus-deployment

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml
charts/prometheus-node-exporter/values.yaml

Signed-off-by: lusson <lusson@foxmail.com>
Add values prometheus.monitor.apiVersion to modify serviceMonitor api.
To meet the needs of modifying the apiversion of serviceMonitor to access the monitoring platforms of some cloud manufacturers.
no
- fixes #

[prometheus-node-exporter] custom servicemonitor apiversion

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/NOTES.txt

prometheus-pushgateway pod port is 9091, but install notify is 8080. i update to real port 9091.

[prometheus-pushgateway] update notes.txt notify port

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

This adds support for `minReadySeconds` in the StatefulSet, can be useful in cases where Pod IPs are used for discovery and they rotate too fast for DNS TTL.
-

[kube-prometheus-stack] Add support for StatefulSet minReadySeconds

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/verticalpodautoscaler.yaml
charts/kube-state-metrics/values.yaml

This PR adds VPA support to kube-state-metrics as we currently need to fork it to be able to have the VPA cababilities enable

[kube-state-metrics] Add vpa support

---

.github/workflows/release.yaml
.github/workflows/sync-readme.yaml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml
charts/prometheus-blackbox-exporter/values.yaml

Now if you deploy blackbox-exporter via this chart it will not create ServiceMonitor for itself, only for targets. This PR provides the ability to do it by overriding variables and enabling selfMonitor, similar to what kube-prometheus-stack chart does for alert-manager for example https://github.com/prometheus-community/helm-charts/blob/63a64f62d19f2c505a5139e91dc544ad1891273e/charts/kube-prometheus-stack/values.yaml#L405-L409 The problem was originally raised in #1936
Not sure about value structure and formatting, open to suggestions

[prometheus-blackbox-exporter] Add selfMonitor support

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/_helpers.tpl
charts/prometheus-pushgateway/values.yaml

Add a new value `topologySpreadConstraints` to the values file for the Pushgateway, to set the topology spread constraints in the Deployment / StatefulSet.

[prometheus-pushgateway] Add topologySpreadConstraints

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/values.yaml

What this PR does / why we need it:
Add loadBalancerIP and loadBalancerSourceRanges to Alertmanager Helm chart
Checklist:
Signed-off-by: Kyle Nguyen <nvietthu@gmail.com>

[alertmanager] add loadBalancerIP and loadBalancerSourceRanges

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

This PR adds `extraEnv` as an option in the values.yaml which can be used to add extra environment variables to the deployment. To simplify the `env` logic I've added `POD_IP` as an env var that will always be present.
The reason it's needed is that I want the option to set an environment variable `AWS_SHARED_CREDENTIALS_FILE` to instruct where the aws credentials file exists on disk, so that I can use the vault injector to mount the creds to a specific directory.
I'm happy to modify the logic if required, please let me know

[prometheus-cloudwatch-exporter] Add extraEnv to values file to specify extra env vars being added to the deployment

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/pushgateway/deploy.yaml
charts/prometheus/values.yaml

Allows custom HTTP headers within the PushGateway HTTP Probes. This is because the PushGateway supports the use of basic authentication which also applies to the default probe endpoints. With basic auth enabled, probes will fail without being able to provide the Auth header.
- fixes #

[prometheus] Allow custom HTTP headers in PushGateway Probes

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/crds/crd-probes.yaml
charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/values.yaml

Updates Prometheus Operator to 0.59.2, prometheus-node-exporter, kube-state-metrics and Grafana to latest

[kube-prometheus-stack] - prometheus-operator0.59.2/dependencies

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/_helpers.tpl
charts/prometheus-pushgateway/values.yaml

This PR adds the ability for specifying init containers for the pushgateway helm chart.  We intend to use this to allow creating a DNS record pointing at our podIP to allow external consumers to use pushgateway without needing the cost of a ingress loadbalancer
N/A
This change was basically lifted directly from prometheus-blackbox-exporter as it has that support.
Testing output of pod with init container specified
```
Name:         test-pushgateway-prometheus-pushgateway-7fb84dc66f-j2qsq
Namespace:    do2
Priority:     0
Node:         ip-10-31-229-39.ca-central-1.compute.internal/10.31.229.39
Start Time:   Thu, 22 Sep 2022 09:24:41 -0600
Labels:       app=prometheus-pushgateway
chart=prometheus-pushgateway-1.18.4
heritage=Helm
pod-template-hash=7fb84dc66f
release=test-pushgateway …
```

[prometheus-pushgateway] - Add extra init containers for pushgateway helm chart

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/templates/role.yaml
charts/kube-state-metrics/templates/rolebinding.yaml
charts/kube-state-metrics/values.yaml

Allow namespaces to be defined as both string/list.
This was inspired by the fact that Prometheus-Operator requires [namespaces list](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1664) and not string. By supporting this a kube-prometheus-stack user can use [yaml anchors ](https://helm.sh/docs/chart_template_guide/yaml_techniques/#yaml-anchors) in values.yaml in order to define the watched namespaces once and reuse in both deployments.

[kube-state-metrics] Allow namespaces to be defined as both string/list

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/values.yaml

This PR allows detailed configuration of the Thanos Query endpoint for Thanos Ruler. Prometheus operator [already supports](https://docs.openshift.com/container-platform/4.8/rest_api/monitoring_apis/thanosruler-monitoring-coreos-com-v1.html) providing `queryConfig` parameter specified in [Thanos API](https://thanos.io/tip/components/rule.md/#query-api). The primary motivation is to connect Thanos Ruler to Thanos Query with TLS certificates configured so requests can be called against HTTPS protocol.
This PR also adds missing `queryEndpoints` parameter documentation to the `values.yaml` file.
No issue created
Signed-off-by: Jan Safarik <cowjen01@gmail.com>

[kube-prometheus-stack] Add queryConfig to thanosRulerSpec

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Signed-off-by: arukiidou <arukiidou@yahoo.co.jp>
This Pull Request updated Prometheus versions deployed in kube-prometheus-stack chart from v2.36.2 to v2.39.1.
This is helpful to benefit from this releases memory improvements.
see: https://github.com/prometheus/prometheus/releases
relates: #2524
(optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged)
None.

[prometheus] Update Prometheus to v2.39.1

---

charts/prometheus-statsd-exporter/Chart.yaml
charts/prometheus-statsd-exporter/templates/servicemonitor.yaml
charts/prometheus-statsd-exporter/values.yaml

Current metrics labels from `prometheus-statsd-exporter` are quite useless for Grafana Dashboards (i.e., `container`, `instance`, `service`, etc.). It's good to have the ability to relabel these labels by labels from the source.
None
Pls, ping me if you have any issues or proposals for my PR.
Signed-off-by: Dmytro Horkhover <gd.mail.89@gmail.com>

[prometheus-statsd-exporter] support relabelings and metricsRelabelings in ServiceMonitor

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/psp.yaml

policy/v1beta1 for PodSecurityPolicy is deprecated in K8S 1.25. This change configures template to recognize k8s version and ses appropriate api version.  
prometheus-node-exporter chart broken on 1.25

[prometheus-node-exporter] use recent version of PSP API in K8S 1.25

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/server/cm.yaml
charts/prometheus/values.yaml

This PR allows addition of extra labels to Prometheus ConfigMap (ConfigMap that holds the prometheus configuration).
Main motivation is to solve Prometheus issue with loading of configuration from multiple files - https://github.com/prometheus/prometheus/issues/8543. 
I use a small sidecar that merges configuration from multiple ConfigMaps (https://github.com/Lirt/prometheus-config-merger/) - first ConfigMap is the one created from Prometheus helm chart and additional one is created by myself. The sidecar is watching for ConfigMaps with specific label and merges their content into a final configuration file that Prometheus uses (eg. `/etc/config/prometheus.yml`).
Since this helm chart doesn't support adding extra labels to the main Prometheus ConfigMap I would like to add support for it. …

[prometheus] Allow addition of extra labels to prometheus configmap

---

charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/templates/daemonset.yaml

[prometheus-smartctl-exporter] Fix quoting issue in new arguments

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/kube-prometheus-stack/values.yaml

When deploying via ArgoCD the ArgoCD app will be in a synchronization loop due to the kube-prometheus-stack jobs being removed due the `ttlAfterFinished: 0`. Using annotations we can inform ArgoCD not to recreate the Jobs in an infinite loop.
Currently the jobs can't be annotated and therefore we need this PR to allow the deployment of `kube-prometheus-stack` using ArgoCD.
- fixes #2516
@andrewgkew @desaintmartin @gianrubio @gkarthiks @scottrigby @Xtigyro

[kube-prometheus-stack] Allow annotations on the admissionWebhook Jobs

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/verticalpodautoscaler.yaml
charts/prometheus-node-exporter/values.yaml

Signed-off-by: QuentinBisson <quentin@giantswarm.io>
This PR adds support the the vertical pod autoscaler so users do not have to care about the resource usage of the node exporter and let the vertical pod autoscaler do it's job.
- fixes #

[prometheus-node-exporter] Add Vertical Pod Autoscaler support

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

In the Prometheus operator spec, a generated label referenced in a `matchExpression` for Pod anti-affinity does not work as expected if `values.cleanPrometheusOperatorObjectNames` is defined, this can result in Prometheus Pods being scheduled on a single node.
- fixes #2548

[kube-prometheus-stack] Fix generated label for Prometheus Pod anti-affinity

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/_helpers.tpl

Currently Cloudwatch exporter only supports `networking.k8s.io/v1beta1` for ingress objects, but this apiObject version was deprecated in 1.22. There should be an option to support` networking.k8s.io/v1`

[prometheus-cloudwatch-exporter] Support networking.k8s.io/v1 in helpers file for k8s clusters > 1.21

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/_helpers.tpl
charts/prometheus-cloudwatch-exporter/templates/ingress.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

Signed-off-by: James Wojewoda <jwojewoda1@gmail.com>
Enables ingress support for apiVersion: networking.k8s.io/v1 for cloudwatch-exporter
- fixes #2557

[prometheus-cloudwatch-exporter] Support ingress objects for k8s clusters >= 1.22

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/psp-role.yaml
charts/kube-prometheus-stack/templates/alertmanager/psp-rolebinding.yaml
charts/kube-prometheus-stack/templates/alertmanager/psp.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/psp-clusterrole.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/psp-clusterrolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/psp.yaml
charts/kube-prometheus-stack/templates/prometheus/psp-clusterrole.yaml
charts/kube-prometheus-stack/templates/prometheus/psp-clusterrolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus/psp.yaml

Try to fix PodSecurityPolicy being removed after Kubernetes 1.25+. See:
https://github.com/prometheus-community/helm-charts/issues/2556
- `policy/v1' does `NOT` contain PodSecurityPolicy. Please don't mix with PodDisruptionBudget.

[kube-prometheus-stack] PodSecurityPolicy being removed from Kubernetes

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/alertmanager/psp.yaml
charts/prometheus/templates/node-exporter/psp.yaml
charts/prometheus/templates/pushgateway/psp.yaml
charts/prometheus/templates/server/psp.yaml

Try to fix PodSecurityPolicy being removed after Kubernetes 1.25+. See:
https://github.com/prometheus-community/helm-charts/issues/2556
- `policy/v1' does `NOT` contain PodSecurityPolicy. Please don't mix with PodDisruptionBudget.

[prometheus] handle PSP removed in k8s 1.25+

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/psp.yaml

[prometheus-adapter] Fix PSP deprecation after k8s 1.25+

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/podsecuritypolicies.yaml

[prometheus-elasticsearch-exporter] Fix PSP deprecation after k8s 1.25+

---

charts/prometheus-couchdb-exporter/Chart.yaml
charts/prometheus-couchdb-exporter/templates/podsecuritypolicy.yaml

[prometheus-couchdb-exporter] Fix PSP deprecation after k8s 1.25+

---

charts/prometheus-consul-exporter/Chart.yaml
charts/prometheus-consul-exporter/templates/podsecuritypolicy.yaml

[prometheus-consul-exporter] Fix PSP deprecation after k8s 1.25+

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml

[prometheus-blackbox-exporter] Fix PSP deprecation after k8s 1.25+

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/podsecuritypolicy.yaml
charts/kube-state-metrics/templates/psp-clusterrole.yaml
charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml

[kube-state-metrics] Fix PSP deprecation after k8s 1.25+

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/podsecuritypolicy.yaml

[prometheus-redis-exporter] Align PSP deprecation with other charts

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/podsecuritypolicy.yaml

[prometheus-postgres-exporter] Align PSP deprecation with other charts

---

charts/prometheus-fastly-exporter/Chart.yaml
charts/prometheus-fastly-exporter/templates/podsecuritypolicy.yaml

[prometheus-fastly-exporter] Fix PSP deprecation after k8s 1.25+

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
charts/prometheus-node-exporter/templates/psp.yaml

[prometheus-node-exporter] Fix PSP deprecation after k8s 1.25+

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/podsecuritypolicy.yaml

[prometheus-kafka-exporter] Fix PSP deprecation after k8s 1.25+

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/role.yaml
charts/kube-state-metrics/values.yaml

Signed-off-by: Craig Skinfill <craig.skinfill@gmail.com>
Adds `leases` to the collectors for kube-state-metrics

kube-state-metrics add leases to collectors

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/service.yaml

Doing a `helm install` with the following values leads to the error below:
```
service:
type: LoadBalancer
runAsStatefulSet: true
```
```
Error: INSTALLATION FAILED: Service "prometheus-pushgateway" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for LoadBalancer services
```
This PR fixes this.

[prometheus-pushgateway] Omit clusterIP if service is of type LoadBalancer

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/configmap.yaml
charts/prometheus-postgres-exporter/values.yaml

Allows a Prometheus postgres exporter user to specify their own queries, and these will be merged with the default ones. This is a useful feature because it means users don't have to fully override default queries when they want to add a thing or two.
For instance, a test config that proves user-defined queries will override a default one and also a new one would be added to config.yaml would look like:
````
userQueries: |-
pg_database:
query: "SELECT pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
master: true
cache_seconds: 30
metrics:
- datname:
usage: "LABEL"
description: "Name of the database"
- size_bytes:
usage: "GAUGE"
description: "Disk space used by the database"
new_pg:
query: "SELECT pg_database_size(pg_database.datname) as size_bytes FROM pg_database" …
```

[prometheus-postgres-exporter] Allow user queries to merge with default queries

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Updated grafana to helm version 6.43.0 and app version 9.2.1
Changes: https://github.com/grafana/helm-charts/compare/grafana-6.40.4...grafana-6.43.0

[kube-prometheus-stack] bump grafana to 6.43.0 (9.2.1)

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/alertmanager/deploy.yaml
charts/prometheus/templates/alertmanager/sts.yaml
charts/prometheus/templates/server/deploy.yaml
charts/prometheus/templates/server/sts.yaml
charts/prometheus/values.yaml

Add possibility to disable securityContext for Prometheus and Alertmanager workloads
Signed-off-by: Roman Slipchenko <romanslipchenko@gmail.com>
* Add the possibility to disable security context for Prometheus and Alertmanager workloads for smooth deployment to OpenShift.
If securityContext is omitted, OpenShift SCC Admission controller can inject needed securityContext on chart deploy time.
More details - https://docs.openshift.com/container-platform/4.11/authentication/managing-security-context-constraints.html
None

[prometheus]: Add possibility to disable securityContext for Prometheus and Alertmanager workloads

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml

Signed-off-by: João Estrela <jestrela@barracuda.com>
This PR fixes not being able to use values such as:
```yaml
prometheus:
monitor:
enabled: true
selectorOverride:
myNewLabel: myNewLabelValue
myNewLabelTwo: myNewLabelValueTwo
```

[prometheus-node-exporter] ServiceMonitor selectorOverride fix

---

.github/CODEOWNERS
charts/jiralert/.helmignore
charts/jiralert/Chart.yaml
charts/jiralert/Readme.md
charts/jiralert/ci/example-receivers-values.yaml
charts/jiralert/templates/_helpers.tpl
charts/jiralert/templates/deployment.yaml
charts/jiralert/templates/ingress.yaml
charts/jiralert/templates/secret.yaml
charts/jiralert/templates/service.yaml
charts/jiralert/templates/serviceaccount.yaml
charts/jiralert/values.yaml

Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>
- fixes https://github.com/prometheus-community/jiralert/issues/104

[jiralert] Setup chart

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Signed-off-by: gadisn <gadisn@gmail.com>
A fix for the recent https://github.com/prometheus-community/helm-charts/pull/2540.
Since the value here is a boolean, and the default is true, the previous template had no way to set `false` for enableHttp2...
Instead, now we always take the value and and it to the created resource
- fixes #

[kube-prometheus-stack]: Fix for alert mgr service monitor: enableHttp2

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/_helpers.tpl
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

Signed-off-by: Markus Blaschke <mblaschke82@gmail.com>
adds support for servicemonitor/podmonitor scrape limits (eg. sampleLimit) to kube-prometheus-stack

[kube-state-metrics] add servicemonitor scrape limits

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/templates/servicemonitor.yaml
charts/prometheus-node-exporter/values.yaml

Signed-off-by: Markus Blaschke <mblaschke82@gmail.com>
adds support for servicemonitor/podmonitor scrape limits (eg. sampleLimit) to prometheus-node-exporter

[prometheus-node-exporter] add servicemonitor/podmonitor scrape limits

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>
If no alertmanager or alerting config is present, avoid the alerting key in the prometheus CR. This is needed, if the prometheus is configured for agent mode. See linked issue.
Let me know, if a dedicated toggle if preferred over an implicit one.
- relates https://github.com/prometheus-community/helm-charts/issues/2506#issuecomment-1277362029

[kube-prometheus-stack] avoid alerting field in prometheus CR, if alertmanager config is empty

---

.github/workflows/release.yaml

Signed-off-by: Scott Rigby <scott@r6by.com>
GH Action to provide Helm OCI support for existing and new chart versions.
- partially addresses #2454 
- You can see a working example here: https://github.com/scottrigby/ghcr-helm-oci
- ~~[ ] Chart Version bumped~~

[ALL CHARTS] Publish new charts to OCI registry

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/README.md
charts/prometheus-mysql-exporter/templates/_helpers.tpl
charts/prometheus-mysql-exporter/templates/deployment.yaml
charts/prometheus-mysql-exporter/templates/secret.yaml
charts/prometheus-mysql-exporter/templates/service.yaml
charts/prometheus-mysql-exporter/templates/serviceaccount.yaml
charts/prometheus-mysql-exporter/values.yaml

This PR enables support for [Workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) for cloudsqlproxy, Adding the parameters for workload identity
```
cloudsqlproxy:
workloadIdentity: 
enabled: false
serviceAccountEmail: ""
```
When workload identity is enabled, you should provide a google service account email.
No issue
Also updated the cloudsql proxy image

[prometheus-mysql-exporter] Support Workload Identity

---

.github/workflows/release.yaml

I made a regex mistake in #2631. The result is that charts with names containing dashes do not get added to the transparency log with cosign. Here is an example of the failed GH action run, before it was re-run (it would not fail on re-run because chart release has already released, so it will stop at "nothing to do") https://github.com/prometheus-community/helm-charts/actions/runs/3423809885/jobs/5702815968.
You can simulate the regex fix locally:
```console
$ helm pull prometheus-community/kube-prometheus-stack
$ mkdir .cr-release-packages && mv kube-prometheus-stack-41.7.3.tgz .cr-release-packages/
$ pkg=.cr-release-packages/kube-prometheus-stack-41.7.3.tgz
$ file=${pkg##*/} && echo $file
kube-prometheus-stack-41.7.3.tgz
$ name=${file%-*} && echo $name
kube-prometheus-stack
$ …
```

[ALL CHARTS] Fix version regex for cosign and annotate

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Signed-off-by: Stevo Slavić <stevo.slavic@form3.tech>
This PR updates Grafana Helm chart dependency in kube-prometheus-stack Helm chart to help address a security vulnerability. Namely a new version (9.2.4) of Grafana has been released [fixing a critical vulnerability](https://grafana.com/blog/2022/11/08/security-release-new-versions-of-grafana-with-critical-and-moderate-fixes-for-cve-2022-39328-cve-2022-39307-and-cve-2022-39306/) and more. Grafana Helm chart version 6.43.5 has been released with the Grafana update (see [related PR](https://github.com/grafana/helm-charts/pull/1958/)).
- fixes #

[kube-prometheus-stack]: bump grafana chart dependency to 6.43.5

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl

v4.5.1 introduces a line break issue in labels
- fixes #2681 
@gianrubio @zanhsieh

[prometheus-node-exporter] Line break issue in labels

---

charts/jiralert/Chart.yaml
charts/jiralert/templates/_helpers.tpl

Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>
Standardized Kubernetes labels on all objects. initially copied from kube-state-metrics.
Since the template jiralert.name has been changed, labelSelector has been changed, too. This is a backward incompatible changes. This is the reason for a major version bump. In umbraella chart situations, if `app.kubernetes.io/name` is set to release.name, the resource has no good known unique labels.

[jiralert] Standardize labels

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

Bumps the version of the referenced kube-state-metrics image to the latest released version v2.7.0.
- fixes #2736
Signed-off-by: Iago Santos <iago.santos.pardo@adfinis.com>

[kube-state-metrics] Bump kube-state-metrics version to v2.7.0 #2736

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml

Signed-off-by: Silas Parker <silas@srp.me.uk>
Correct indentation of environment variables in the prometheus-node-exporter chart.
Without this, adding the option `--set-string env.GOMAXPROCS=1` will produce the error message:
```
Error: YAML parse error on prometheus-node-exporter/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 54: did not find expected key
```
- fixes  #2743

[prometheus-node-exporter] Correct indentation of environment variables

---

charts/prometheus/Chart.yaml

Signed-off-by: Silas Parker <silas@srp.me.uk>
Update referenced node-exporter to 4.7.*
Allows to use new node-exporter chart 4.7.1 which allows setting environment variables correctly, which should allow the `GOMAXPROCS=1` work around described in https://github.com/prometheus/node_exporter/issues/2500 to be applied

[prometheus] Update referenced node-exporter to 4.7.*

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md

- When the Prometheus Alertmanager was moved to a subchart in https://github.com/prometheus-community/helm-charts/pull/2717, the list of subcharts in the README wasn't updated to include it.
- update README.md - add chart dependencies(alertmanager)
- follow-up #2717
- relates #2725

[prometheus]Update 'prometheus' README to mention alertmanager #2717

---

charts/prometheus/Chart.yaml

- update chart dependency, kube-state-metrics (4.22 to 4.24)
-  update image, kube-state-metrics(2.6.0 to 2.7.0)
- images security rating will be restored
None.
- relates #2737

[prometheus]update chart dependency kube-state-metrics (4.22 to 4.24), image 2.7.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml

Signed-off-by: Marco De Luca <marcodl404@gmail.com>
In some cases, the 10-second timeout is not enough, resulting in a failed helm upgrade.
After checking the validatingwebhook template, I found that there is no way to define the timeout.
In the mutatingwebhook template the value of "prometheusOperator.admissionWebhooks.timeoutSeconds" is considered. I have adjusted the ValidatingWebhook accordingly.

[kube-prometheus-stack] Allow setting timeoutSeconds in ValidatingWebhook

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

- this pr updates [configmap-reload image(to v0.8.0)](https://hub.docker.com/layers/jimmidyson/configmap-reload/v0.8.0/images/sha256-084de2d3533f9215eceef9a1feccfc11cad43cf382ea82ddfa4272f68df0614f?context=explore)
None.

[prometheus]updates configmap-reload image to v0.8.0

---

charts/prometheus/Chart.yaml

- update chart dependency, [prometheus-node-exporter (4.7 to 4.8)](https://artifacthub.io/packages/helm/prometheus-community/prometheus-node-exporter)
-  update image, [prometheus-node-exporter(1.4.0 to 1.5.0)](https://quay.io/repository/prometheus/node-exporter?tab=tags&tag=v1.5.0)
- images security rating will be restored
None.
- upstream #2766

[prometheus]update chart dependency prometheus-node-exporter (to 4.8.0)

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/README.md
charts/prometheus-elasticsearch-exporter/ci/security-context.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

To allow the use of configuration conforming to the Pod Security Standard level "restricted" it is necessary to be able to adapt the securityContext on pod and container level. Since the implementation up to now is not very flexible and a bit misleading (securityContext.enabled only affects the pod level securityContext) the approach taken is to align it with the way of charts created by `helm create` implement this. 
- fixes #2617
- fixes #2494 
Unfortunately aligning it with the behaviour of other charts implies a breaking change as "securityContext" of 4.x is renamed to "podSecurityContext" and "securityContext" is used for the container level "securityContext" going forward. "securityContext.enabled" is removed altogether. To remove the configuration from the pod users should set …

[prometheus-elasticsearch-exporter] Refactor securityContext configuration

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/networkpolicy.yaml

This PR fixes the network policy for the prometheus-operator that prevents the prometheus-operator to call the apiserver `/version` endpoint
Before:
```sh
k logs -n kube-system prometheus-operator-app-operator-6476f7ffd4-m45ff
level=info ts=2022-12-05T19:59:21.088271586Z caller=main.go:220 msg="Starting Prometheus Operator" version="(version=0.60.1, branch=refs/tags/v0.60.1, revision=ab3fe2aba8f6e43461819d9648e2b8fae9d74c43)"
level=info ts=2022-12-05T19:59:21.088315531Z caller=main.go:221 build_context="(go=go1.18.6, user=Action-Run-ID-3224998444, date=20221011-07:43:14)"
level=warn ts=2022-12-05T19:59:51.097587134Z caller=operator.go:328 component=prometheusoperator msg="failed to check if the API supports the endpointslice resources" err="Get …
```

[kube-prometheus-stack] Fix netpol to allow access to the api-server

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/pdb.yaml

Signed-off-by: toVersus <toversus2357@gmail.com>
Fix a regression introduced in the part of refactoring. (#2781)
After this patch, we can generate manifests without any errors.
Enable PDB on default values file:
```yaml
podDisruptionBudget:
maxUnavailable: 1
```
Genarate manifests using Helm template:
```console
❯ helm template alertmanager .
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
name: alertmanager
labels:
helm.sh/chart: alertmanager-0.22.2
app.kubernetes.io/name: alertmanager
app.kubernetes.io/instance: alertmanager
app.kubernetes.io/version: "v0.24.0"
app.kubernetes.io/managed-by: Helm
spec:
selector:
matchLabels:
app.kubernetes.io/name: alertmanager
app.kubernetes.io/instance: alertmanager
maxUnavailable: 1
```
- fixes #2795

[alertmanager] fix broken PDB due to missing line break

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

Bumps the Grafana helm chart version to fix stale sidecar issues
- fixes #2800

Bump Grafana Chart to most recent commit

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/README.md
charts/prometheus-postgres-exporter/values.yaml

After the merge of https://github.com/prometheus-community/postgres_exporter/pull/613, `postgres-exporter` installed by recent versions of the prometheus-postgres-exporter Helm chart is throwing 500 errors like:
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 29 Nov 2022 11:08:41 GMT
Content-Length: 1418
An error has occurred while serving metrics:
4 error(s) occurred:
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"template0" > label:<name:"server" value:"10.188.0.2:5432" > gauge:<value:8.225283e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"postgres" > label:<name:"server" value:"10.188.0.2:5432" …
```

[prometheus-postgres-exporter] Remove pg_database query

---

charts/kube-prometheus-stack/Chart.yaml

- fix Chart.yaml - remove engine: gotpl
https://github.com/prometheus-community/helm-charts/issues/2813
- This is the patch bump. removing  but it's not allowed.

[kube-prometheus-stack] fix Chart.yaml - remove engine: gotpl

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

Signed-off-by: paoloyx <paoloyx@gmail.com>
It is often useful to keep K8s label from services/pods when scraping metrics: `targetLabels` and `podTargetLabels` from the [ServiceMonitor Spec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ServiceMonitorSpec) are exactly providing this functionality
There no issue created as it's a very simple case, I can create one if needed
Nothing in particular

[kube-state-metrics] Manage 'targetLabels' and 'podTargetLabels' in Servicemonitor

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/templates/deployment.yaml

Add annotation to deployment to auto rollover the deployment on changes to the configmap
(https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)
Currently you need to manually delete the pod to get the new config from the configmap.

[prometheus-json-exporter] Automatically rollover deployment when configmap changed.

---

.github/workflows/release.yaml

* disable ghcr uploads
- fixes #
* disabled as it constantly fails anyway

disable ghcr uploads

---

charts/alertmanager/Chart.yaml

- this pr updates [alertmanager image(to v0.25.0)](quay.io/prometheus/alertmanager:v0.25.0)
None.

[alertmanager] updates alertmanager image to v0.25.0

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/values.yaml

This propagates important notification that is available in source and ppl still get caught by that: https://github.com/prometheus-community/postgres_exporter/issues/549
N/A
This just propagates the warning from upstream to chart.

[prometheus-postgres-exporter] fix: propagate warning from upstream

---

charts/prometheus/.gitignore
charts/prometheus/Chart.lock
charts/prometheus/Chart.yaml

- update chart dependency [alertmanager (to 0.24)](https://artifacthub.io/packages/helm/prometheus-community/alertmanager/0.24.0)
-  updates [alertmanager image(to v0.25.0)](https://quay.io/prometheus/alertmanager:v0.25.0)
-  updates [prometheus image(to v2.41.0)](https://quay.io/prometheus/prometheus:v2.41.0)
-  add [Chart.lock](https://helm.sh/docs/helm/helm_dependency_build/#synopsis)
- Closes #2855
- upstream https://github.com/prometheus-community/helm-charts/pull/2846

[prometheus] update chart dependency alertmanager (to 0.24)

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

- this pr updates [alertmanager image(to v0.25.0)](quay.io/prometheus/alertmanager:v0.25.0)
- [add license annotations](https://artifacthub.io/docs/topics/annotations/helm/)
None.
- referred to #2846

[kube-prometheus-stack] updates alertmanager image to v0.25.0

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md

Updates documentation in README.md
The documentation. There was a minor typo using camelCase instead of kebab-case.

[prometheus] kubeStateMetrics.enabled is now kube-state-metrics.enabled

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/_helpers.tpl
charts/kube-state-metrics/values.yaml

This PR adds support for overriding selector labels.

[kube-state-metrics] add support for overriding selector labels

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

This PR adds support for `securityContext` in the kafka-exporter's container enabling thus transition from PSP to Pod Security Standards. 
Since value `securityContext` is already used for pod's security context, `containerSecurityContext` has been chosen for that of the container.
None

[prometheus-kafka-exporter] Add support for securityContext

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/README.md
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

This PR makes setting container's `securityContext` possible through the values file and enables thus setting `seccompProfile` as well. The value `runAsUser` is being merged with the new `securityContext`.
Changes to the securityContext values themselves as they have been set so far have not been made.
None

[prometheus-adapter] Make securityContext user-settable

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/deployment.yaml
charts/prometheus-mysql-exporter/values.yaml

let user set registry pull secrets if they want to use their private registry.
add imagePullSecrets to mysql-exporter chart  
add fullname override(You had it in helpers templates but not in values file)  
set default image tag from .Values.image.tag to .Chart.AppVersion

[prometheus-mysql-exporter] add imagePullSecrets and fullname override

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

Prometheus operator release feature `alertmanagerConfigMatcherStrategy` by https://github.com/prometheus-operator/prometheus-operator/pull/5084 at `v0.61.0`, but not contains in this helm chart.

[kube-prometheus-stack] add alertmanagerConfigMatcherStrategy for alertmanager

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

Adds logic so it will use appVersion to set the container image tag and we don't need to repeat ourselves.

[kube-state-metrics] Use appVersion to define container image version

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/README.md
charts/prometheus-adapter/values.yaml

Update the `prometheus-adpater` chart example PromQL queries to be compatible with the `kube-prometheus-stack` chart defaults.
* Use `node_exporter` metrics for `nodeQuery` examples.
* Use `avg_over_time()` on memory queries to match the 3m window.
* Format queries based on PromQL style guide.
Signed-off-by: SuperQ <superq@gmail.com>
* https://github.com/kubernetes-sigs/prometheus-adapter/issues/549
* https://github.com/kubernetes-sigs/prometheus-adapter/pull/516
* https://github.com/prometheus-community/helm-charts/pull/2822

[prometheus-adapter] Update PromQL queries

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml

The node_exporter added an additional udev path config flag to support additional disk metadata in v1.4.0. If the rootfs is mounted in, we can configure this flag.
- Related to: https://github.com/prometheus/node_exporter/issues/2579

[prometheus-node-exporter] Add udev path arg

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml

There is a bug in the chart. The option in `values.yaml` to set the targetPort only affects the Service. The prometheus-exporter Pod itself does not listen to the targetPort, it still listens to the default port. This PR fixes this bug by passing the targetPort on to the pod as a flag argument.

[prometheus-postgres-exporter] Fix bug in targetPort

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Added commented out example of `metric_relabel_configs` usage for prometheus helmchart.
Used same example as in `kube-prometheus-stack`, but stayed with prometheus chart's action->regex order
Tested by uncommenting in our local prometheus cluster, adds:
```
metric_relabel_configs:
- separator: ;
regex: (kubernetes_io_hostname|failure_domain_beta_kubernetes_io_region|beta_kubernetes_io_os|beta_kubernetes_io_arch|beta_kubernetes_io_instance_type|failure_domain_beta_kubernetes_io_zone)
replacement: $1
action: labeldrop
```
Should i add it to other defined scrape jobs?
- fixes #894

[prometheus] Add commented metric_relabel_configs example

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

This PR adds the ability to set annotations on the Deployment resource itself, which is currently not possible. Tooling like `stakater/Reloader` requires that the annotation be set on the deployment/statefulset workload and not as a pod annotation.
I also fixed an issue with a duplicate key in `spec.metadata.annotations` for the deployment resource that kubeconform found when setting the `customAnnotations` key.

[prometheus-adapter]: allow setting annotations on the deployment

---

.github/CODEOWNERS
charts/alertmanager-snmp-notifier/.helmignore
charts/alertmanager-snmp-notifier/Chart.yaml
charts/alertmanager-snmp-notifier/README.md
charts/alertmanager-snmp-notifier/ci/default-values.yaml
charts/alertmanager-snmp-notifier/ci/ingress-values.yaml
charts/alertmanager-snmp-notifier/ci/secret-values.yaml
charts/alertmanager-snmp-notifier/ci/templates-values.yaml
charts/alertmanager-snmp-notifier/templates/NOTES.txt
charts/alertmanager-snmp-notifier/templates/_helpers.tpl
charts/alertmanager-snmp-notifier/templates/configmap.yaml
charts/alertmanager-snmp-notifier/templates/deployment.yaml
charts/alertmanager-snmp-notifier/templates/hpa.yaml
charts/alertmanager-snmp-notifier/templates/ingress.yaml
charts/alertmanager-snmp-notifier/templates/secrets.yaml
charts/alertmanager-snmp-notifier/templates/service.yaml
charts/alertmanager-snmp-notifier/templates/serviceaccount.yaml
charts/alertmanager-snmp-notifier/templates/servicemonitor.yaml
charts/alertmanager-snmp-notifier/values.yaml

This PR creates a SNMP notifier chart, for creating an alertmanager webhook that sends alerts as SNMP traps.
I created a previous PR, but closed and created a new one, squashed, and up-to-date with a newest version.

[alertmanager-snmp-notifier] add SNMP notifer chart

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
charts/prometheus-blackbox-exporter/values.yaml

Allows adding an optional hostname parameter for serviceMonitor targets that will set the Host header and TLS SNI for HTTP probes. This avoids the need to created individual modules with specific tlsconfigs when probing against targets that are vhosts

[prometheus-blackbox-exporter] adding optional additional hostname parameter to servicemonitor 

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/NOTES.txt
charts/prometheus-blackbox-exporter/templates/_helpers.tpl
charts/prometheus-blackbox-exporter/templates/ingress.yaml
charts/prometheus-blackbox-exporter/values.yaml

Some managed Kubernetes services do not occasionally follow versioning according to semver. This PR provides an option to override such a version. This is important for those resources for which multiple APIs exist, e.g. ingress, and a decision has to be taken based on the Kubernetes version.
- fixes #2953

[prometheus-blackbox-exporter] Support for Kubernetes version override

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml

Signed-off-by: Jan-Otto Kröpke <joe@cloudeteer.de>
Support multi cluster scenarios.
- fixes #
I would recommend to apply the cluster labels on all rules, if possible. 
See also: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/817

[kube-prometheus-stack] Support multi-cluster alerting rules for prometheus-operator

---

charts/prom-label-proxy/Chart.yaml
charts/prom-label-proxy/templates/deployment.yaml
charts/prom-label-proxy/values.yaml

This PR adds the possibility to add labels for pods.
Some network policies from helm charts have restrictive filters that only pods with certain label can reach a pod. In our current case, this is the case with Thanos: [Bitnami Thanos Chart](https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/networkpolicy.yaml)
not opened

Add podLabels to prom-label-proxy

---

charts/kube-prometheus-stack/Chart.lock
charts/kube-prometheus-stack/Chart.yaml

In order to use traceQL with Tempov2 we need grafana 9.3.2 or greater, and currently we are using grafana 9.3.1
Signed-off-by: Rodrigo Mompo Redoli <rodrigo@rodrigomompo.com>
We need  to upgrade grafana to a version 9.3.2 or greater to support traceQL in Grafan with Tempov2 which was recently release.
Upgrade Chart.lock to get the latest version of the grafana helm-chart with use grafana 9.3.6

[kube-prometheus-stack] Update helm Chart.lock to get latest grafana version. 

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/values.yaml

After a previous change to enable full customisation of the liveness and readiness probes in this helm chart, the liveness probe was altered from using /healthy to /ready. I believe this was likely a copy-paste mistake and this PR aims to alter the default back to /healthy so that others don't need to override the value.

[prometheus-pushgateway] Adjust Liveness probe default to /healthy

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/templates/thanos-ruler/extrasecret.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ingress.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/podDisruptionBudget.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/service.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/serviceaccount.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/servicemonitor.yaml

Allows for deployment of Thanos Ruler
Fixes error where the thanos-ruler name was too long (longer then 63 characters, since thanos-ruler resources were using   the chart fullname and not the shortened name)
- fixes #3020

[prometheus-kube-stack] Fixes deployment of Thanos Ruler - Addresses Default Thanos Ruler name too long

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml

Version 45.0.0 introduced a bug where the monitoring-kube-prometheus-operator ClusterRole lacks the permission to alertmanagers/status.
- fixes https://github.com/prometheus-community/helm-charts/issues/3015
@andrewgkew @gianrubio @gkarthiks  @GMartinez-Sisti @scottrigby @Xtigyro @QuentinBisson

[kube-prometheus-stack] Add permission to the alertmanagers/status resource

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Signed-off-by: Jacek Ewertowski <jacek.ewertowski1@gmail.com>
- #1470
- [istio-35915](https://github.com/istio/istio/issues/35915)
This relabel configuration works with IPv4 and IPv6 without specifying networking stack, like it was in [#1502](https://github.com/prometheus-community/helm-charts/pull/1502).
I tested this change on OpenShift clusters with IPv4 and IPv6 networking and I also verified these rules in Prometheus [unit tests](https://github.com/prometheus/prometheus/compare/main...jewertow:prometheus:relabel-dual-stack-ip?expand=1).

[prometheus]: Add relabel configs for dual stack to kubernetes-pods jobs

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

Add support for optionally overriding the registry hostname from a parent chart.
This is important for air-gapped installations which do not have direct access to the public internet and must use a private, internal container registry.
It also avoids having to modify the Kube-State-Metrics Helm chart directly.
FAO: @tariq1890  @mrueg @dotdc

[kube-state-metrics] Allow parent charts to override registry hostname

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Further to https://github.com/prometheus-community/helm-charts/pull/3060, the reason that users may want to disable the admission webhook is because it would seem that kube-webhook-certgen v1.3.0 is incompatible (to some degree) with Kubernetes 1.22+
See a related issue here: https://github.com/kubernetes/ingress-nginx/issues/7418
This PR bumps the version of kube-webhook-certgen to the latest (per [this link](https://registry.k8s.io/v2/ingress-nginx/kube-webhook-certgen/tags/list), which is currently `v20221220-controller-v1.5.1-58-g787ea74b6` (_no concise tags were published since v1.3.0_).

[kube-prometheus-stack] Bump version of kube-webhook-certgen

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/daemonset.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml

When this chart is used as a subchart, this PR allows the securityContext in the container to be unset from the parent chart without change in previous behaviour.

[prometheus-blackbox-exporter] Make it possible to unset the container "securityContext“

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/role.yaml
charts/prometheus-blackbox-exporter/templates/rolebinding.yaml

Currently, if `pspEnabled=true` and the cluster does not support PodSecurityPolicy API (1.25+), the pod security policy itself does not get installed but the related role and rolebinding do. Since these refer exclusively to the policy, they should only be installed together with it.
None

[prometheus-blackbox-exporter] Update PSP-related templates

---

.github/CODEOWNERS
charts/prometheus-pgbouncer-exporter/.helmignore
charts/prometheus-pgbouncer-exporter/Chart.yaml
charts/prometheus-pgbouncer-exporter/README.md
charts/prometheus-pgbouncer-exporter/ci/ci-values.yaml
charts/prometheus-pgbouncer-exporter/templates/NOTES.txt
charts/prometheus-pgbouncer-exporter/templates/_helpers.tpl
charts/prometheus-pgbouncer-exporter/templates/deployment.yaml
charts/prometheus-pgbouncer-exporter/templates/networkpolicy.yaml
charts/prometheus-pgbouncer-exporter/templates/pdb.yaml
charts/prometheus-pgbouncer-exporter/templates/prometheusrule.yaml
charts/prometheus-pgbouncer-exporter/templates/role.yaml
charts/prometheus-pgbouncer-exporter/templates/rolebinding.yaml
charts/prometheus-pgbouncer-exporter/templates/secrets.yaml
charts/prometheus-pgbouncer-exporter/templates/service.yaml
charts/prometheus-pgbouncer-exporter/templates/serviceaccount.yaml
charts/prometheus-pgbouncer-exporter/templates/servicemonitor.yaml
charts/prometheus-pgbouncer-exporter/values.yaml

This PR adds a helm chart for deploying pgbouncer_exporter. 
Fixes #3048 
This work was directly copied from the prometheus-postgres-exporter chart and tweaked accordingly. There would likely be some room for improvement on this, but it has been tested with a crunchydata deployment of pgbouncer in GKE successfully. The connectionstring has been crafted to support a complex autogenerated password from crunchydata, though this might need to updated/tested with other connection string variations. Happy to take some guidance

[prometheus-pgbouncer-exporter] add initial helm chart for pgbouncer

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/deployment.yaml
charts/prometheus-mysql-exporter/values.yaml

Allow setting `image.registry` value to specify the registy the image should be pulled from.
Also makes the default to be `quay.io`, which seems to be more consistent with various other charts in this repository.

[prometheus-mysql-exporter] Allow overriding of image registry and add quay.io default

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/_helpers.tpl
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

We need to split registry and repository values in a proper way as usual in another charts. Also currently it's a bug if you want to use the global imageRegistry variable in kube-prometheus-stack it actually broke this sub chart, because currently, we expect a full path for the image, but in all others, we expect here only the registry name.
- fixes #3075

[kube-state-metrics] fix/split Registry and Repository Values in a proper way

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

- What: excluded `.Values.Config` from the conditions to enabled reloader
- Why: want to solve the problem that reloader cannot be used when alertmanager.yml is mounted using `extraSecretMounts ` without using .`Values.Config`
Example: 
```
extraSecretMounts:
- name: alertmanager-config
mountPath: /etc/alertmanager
subPath: alertmanager.yml
secretName: alertmanager-config
readOnly: true
```
- fixes #

[alertmanager]  exclude `.Values.Config` from the conditions to enabled reloader

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md
charts/prometheus/templates/deploy.yaml
charts/prometheus/values.yaml

The new reloader is actively maintained by the prometheus operator team and also gets published to both GHCR and Quay.io. Considering the upcoming changes to docker hub and [this old ticket](https://github.com/jimmidyson/configmap-reload/issues/58) I think it makes sense to switch.

[prometheus] Switch to use a different config map reloader

---

charts/prometheus/Chart.yaml

Bump AppVersion to fix GHSA-vvpx-j8f3-3w6h and CVE-2022-28391.
See: https://github.com/prometheus-community/helm-charts/issues/3139

[prometheus] hotfix CVE-2022-28391

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/servicemonitor.yaml
charts/kube-state-metrics/values.yaml

This PR introduces the `annotations` metadata in the `ServiceMonitor` object. It is needed in case users want to add extra annotations to the object. For example, when using ArgoCD, you need to add extra [annotations ](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types) for more `SyncOptions`

[kube-state-metrics] Add annotations to service-monitor object

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/deploy.yaml
charts/prometheus/templates/sts.yaml
charts/prometheus/values.schema.json
charts/prometheus/values.yaml

With this PR I am proposing to introduce support for [pod topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) in deployment and statefulset templates allowing for desired distribution of Prometheus' pods across zones and nodes.
- fixes #3164

[prometheus] Add support for pod topology spread constraints

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/csi-secret.yaml

kps deployment fails when disabling thanos sidecar by setting `prometheus.prometheusSpec.thanos` field to null due to the reference of a field `thanos.secretProviderClass` in csi-secret.yaml. This change gives the ability to disable thanos sidecar by setting `prometheus.prometheusSpec.thanos=null`
This PR fixes the kps deployment failure when `prometheus.prometheusSpec.thanos` field is set to null and thus gives the ability to disable thanos sidecar by setting `prometheus.prometheusSpec.thanos=null` in the overriding values files.

[kube-prometheus-stack] fix kps deployment when thanos field is set to null

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml
charts/prometheus-node-exporter/values.yaml

This PR allows setting the "attachMetadata > node" property of the ServiceMonitor created by the prometheus-node-exporter chart, the same way it is already possible for the PodMonitor.
We want to query metrics based on a label attached to the node but keep using the ServiceMonitor (as is the default when using kube-prometheus-stack).

[prometheus-node-exporter] add attachMetadata to ServiceMonitor

---

charts/prometheus-smartctl-exporter/Chart.yaml

Signed-off-by: yellowhat <yellowhat46@gmail.com>
This PR updates the image of smartctl-importer to v0.9.1.
* https://github.com/prometheus-community/smartctl_exporter/releases/tag/v0.9.1
-

[prometheus-smartctl-exporter] Upgrade to smartctl exporter v0.9.1

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml

In this PR we add ability to rewrite Pod container port name (set it the same as Service port name) to be able to avoid hardcoded `http` value.
For our particular case, we use internal rule to name all ports targets of `ClusterPodMonitor` as `metrics` with `NetworkPolicy` where we allow `gmp-system` to collect metrics from named port. 
Please take a look: @svenmueller , @desaintmartin .

[prometheus-elasticsearch-exporter]: Set Pod container name to Service port name

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/values.yaml

sha is for digest without digest type.
digest is more commonly used, and prepare for possible future digest types
This is related to ~~https://github.com/prometheus-community/helm-charts/pull/3044~~ https://github.com/prometheus-community/helm-charts/pull/2377.

[prometheus-node-exporter]  Use digest instead of sha

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

This permits installing this change in a namespace with PodSecurity set to `restricted`.
- fixes #

[kube-state-metrics] set parameters for podsecurity restricted

---

.github/workflows/lint-test.yaml

Update `.github/workflows/lint-test.yaml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=changed::true"
```
**TO-BE**
```yml
echo "changed=true" >> $GITHUB_OUTPUT
```
- fixes #3221

Replace deprecated command with environment file

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

@monotek @naseemkullah 
Adding hostAlises support to the Alertmanager chart. This is a necessary requirement for my organization due to some interesting network decisions.

[alertmanager] Adding hostAliases to Alertmanager chart.

---

charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/templates/servicemonitor.yaml
charts/prometheus-smartctl-exporter/values.yaml

* expose serviceMonitor `interval` option
* expose serviceMonitor `scrapeTimeout` option

[prometheus-smartctl-exporter]: expose serviceMonitor `interval` and `scrapeTimeout`

---

charts/kube-prometheus-stack/Chart.yaml

Updates kube-prometheus-stack dependencies (kube-state-metrics and grafana). 
This brings improved securityContext to both.
SecurityContext diffs:
grafana:
kube-state-metrics

[kube-prometheus-stack] bump chart dependencies

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml

The MutatingWebhookConfiguration and ValidatingWebhookConfiguration pull their namespaces from the release namespace, thus not taking into account values set in namespaceOverride.
For users installing this chart as a sub-chart where release namespace != namespaceOverride and cert-manager is enabled this will cause errors.

[kube-prometheus-stack] fix: webhook ignores namespaceOverride

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

The `prometheuses` CRD supports `spec.version` which if set can then override the Prometheus version determined by the operator from the Prometheus image tag. Currently, the field is set to the image tag.
This PR makes the field available to users so that a semver-incompatible image tag can still be used whilst telling the operator which Prometheus version it is supposed to support in the given resource. The default value remains the Prometheus image tag.   
- fixes #3108

[kube-prometheus-stack] Support setting Prometheus version

---

charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/templates/daemonset.yaml
charts/prometheus-smartctl-exporter/values.yaml

Allow to add custom annotations to the `daemonset` from `values.yaml`.

[prometheus-smartctl-exporter]: allow annotation to daemonset 

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/service.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-dns/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

There are a handful of exporters shipping with this chart.  If new ones are added over time, folks who are opting out may get them by mistake.  A top level flag to control all of them provides an easy way to specify folks want opt out of all exporters.
- fixes #

[kube-prometheus-stack] Add flag to disable all exporters

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/ciliumnetworkpolicy-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/ciliumnetworkpolicy-patchWebhook.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/networkpolicy-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/networkpolicy-patchWebhook.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/ciliumnetworkpolicy.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/networkpolicy.yaml
charts/kube-prometheus-stack/templates/prometheus/ciliumnetworkpolicy.yaml
charts/kube-prometheus-stack/templates/prometheus/networkpolicy.yaml
charts/kube-prometheus-stack/values.yaml

This PR adds ciliumnetworkpolicy support to kps
- fixes #

[kube-prometheus-stack] Add cilium networkpolicy support

---

charts/prometheus-cloudwatch-exporter/Chart.yaml

@gianrubio @torstenwalter @asherf 
As discussed in https://github.com/prometheus-community/helm-charts/issues/3240 , we would need to update to the latest version of cloudwatch.
- fixes #3240

[prometheus-cloudwatch-exporter] Appversion bump to 0.15.3

---

charts/prometheus-kafka-exporter/Chart.lock
charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/README.md

- fix Chart.yaml - remove engine: gotpl , see #2813
- drop Helm v2 support
- add Chart.lock
- https://github.com/prometheus-community/helm-charts/issues/2813
- This does not change the template. 
- But, I think it's a major bump, because dropped Helmv2

[prometheus-kafka-exporter] fix Chart.yaml - remove engine: gotpl

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

Value `service.port` can be changed. Such a change then leads to configmap-reload failing to connect to alertmanager as the former is using that value in its webhook-url flag. In this PR I am proposing to set the port in the webhook-url flag to the same value as the alertmanager's port, i.e. constant `9093`. Although one could introduce a new value for this purpose, I do not consider it necessary.
- fixes #3055

[alertmanager] Adjust configmap-reload port

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/pdb.yaml

prometheus chart is in violation of the guidelines for this section:
https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#deployments-statefulsets-daemonsets-selectors
>spec.selector.matchLabels defined in Deployments/StatefulSets/DaemonSets >=v1/beta2 must not contain helm.sh/chart label or any label containing a version of the chart, because the selector is immutable. The chart label string contains the version, so if it is specified, whenever the Chart.yaml version changes, Helm's attempt to change this immutable field would cause the upgrade to fail.
This PR resolves failures that may occur when updating to future Chart versions.
none

[prometheus]Remove 'app.kubernetes.io/version' label from selector

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/_helpers.tpl
charts/prometheus-postgres-exporter/templates/pdb.yaml

This feature templates the `apiVersion` of the Prometheus Postgres Exporter's `PodDisruptionBudget` based on the capabilities of the utilized k8s API version (`.Capabilities.APIVersions.Has`).
Due to the previously hard-coded `apiVersion: policy/v1beta1` , this helm chart is not compatible for k8s versions >= 1.25 from which this `apiVersion` got removed.
`apiVersion: policy/v1` replaces the deprecated `apiVersion: policy/v1beta1` since k8s v1.21.
–
–

[prometheus-postgres-exporter] template apiVersion based on capabilities for the pod disruption budget

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

See https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.AlertmanagerSpec

[kube-prometheus-stack] Remove deprecated sha in prometheusSpec

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

To avoid the following diff with server-side apply:
```diff
excludedFromEnforcement:
-    - group: monitoring.coreos.com
-      name: prometheus-stack-kube-prom-alertmanager.rules
+    - name: prometheus-stack-kube-prom-alertmanager.rules
...
```
- fixes #

[kube-prometheus-stack] Avoid diff with server-side apply when enforcedNamespaceLabel is set

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/ciliumnetworkpolicy.yaml

Ensures cilium network policy configured correctly templated for prometheus operator.
-

[kube-prometheus-stack] Fix body must be of type string bug for cilium network policy

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/prometheus/Chart.yaml
charts/prometheus/README.md
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/clusterrole.yaml
charts/prometheus/templates/clusterrolebinding.yaml
charts/prometheus/values.yaml

I will be deploying Prometheus in N number of namespaces per cluster and currently `ClusterRole` and `ClusterRoleBinding` get created with the same name as PVC and VolumeMounts which already exists and need to follow specific naming convention
In the interest of not having to decouple the `ClusterRole` and `ClusterRoleBinding` away from the community chart it would be great to be able to rename the 2 objects independently from `fullnameOverride` 
N/A
N/A

[prometheus] Add support for renaming Cluster Role and Binding

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/ciliumnetworkpolicy.yaml

Ensures cilium network policy configured correctly templated for kube-state-metrics
none
```
$kubectl explain CiliumNetworkPolicy.spec.ingress.toPorts.ports
KIND:     CiliumNetworkPolicy
VERSION:  cilium.io/v2
RESOURCE: ports <[]Object>
DESCRIPTION:
Ports is a list of L4 port/protocol
PortProtocol specifies an L4 port with an optional transport protocol
FIELDS:
port	<string> -required-
Port is an L4 port number. For now the string will be strictly parsed as a
single uint16. In the future, this field may support ranges in the form
"1024-2048 Port can also be a port name, which must contain at least one
[a-z], and may also contain [0-9] and '-' anywhere except adjacent to
another '-' or in the beginning or the end.
protocol	<string>
Protocol is the L4 protocol. If omitted or empty, any …
```

[kube-state-metrics] Fix body must be of type string bug for cilium network policy

---

charts/jiralert/Chart.yaml
charts/jiralert/values.yaml

Escaping really breaks the template engine - bare string comes to JIRA, instead templated result

jiralert: values: fixed config: there is no need to do escaping

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/config-reloaders.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-burnrate.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-histogram.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-prometheus-general.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-prometheus-node-recording.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-scheduler.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-state-metrics.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubelet.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-resources.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-network.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml

Resolves bug for issue #3396 , PrometheusRule cannot have null labels
- fixes #3396
If the given rule does not already have a label, and the user has not passed in their own, the empty `labels:` field is now omitted 
```diff
expr: |-
kube_pod_container_resource_limits{resource="cpu",job="kube-state-metrics"}  * on (namespace, pod, cluster)
group_left() max by (namespace, pod, cluster) (
(kube_pod_status_phase{phase=~"Pending|Running"} == 1)
)
record: cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits
+     {{- if .Values.defaultRules.additionalRuleLabels }}
labels:
-{{- if .Values.defaultRules.additionalRuleLabels }}
-{{ toYaml .Values.defaultRules.additionalRuleLabels | indent 8 }}
-{{- end }}
+        {{ toYaml .Values.defaultRules.additionalRuleLabels | nindent 8 }}
+ …
```

[kube-prometheus-stack] - resolve issue 3396, no null labels allowed for PrometheusRules

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

This PR makes the correct work for prometheus-operator in huge cluster.  In my case prometheus-operator used more than 2Gb RAM and kube-api more then 5Gb RAM answering the requests, with not set `secretFieldSelector`. 
I really don't understand why prometheus-operator need to watch secret types which are excluded in this PR.
No issue

[prometheus-operator] Set secretFieldSelector to exclude not necessary secret types 

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/values.yaml

When you use prometheus chart, template helper will generate name like this
`prometheus-prometheus-node-exporter`
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/_helpers.tpl#L22
It is inconvenient, especially when you are upgrading from the old chart version (like 15.x)
This name could be overrode, but there is no such variables names in `values.yaml` and this PR solves it.

[prometheus-node-exporter] added fullnameOverride to values.yaml

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml

This fixes a typo introduced with PR #3288, specifically the fact that for the kubeProxy **additional labels** block, additionalRuleGroup**Annotations**.kubeProxy is checked, instead of the correct additionalRuleGroup**Labels**.kubeProxy.
Therefore, when using a values file like
```
defaultRules:
additionalRuleGroupLabels:
kubeProxy:
owner: something
```
the additional label is not added.

[kube-prometheus-stack] Fix typo in kubeProxy additional rule labels

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

Currently we're unable to set the values of `clusterGossipInterval`, `clusterPushpullInterval` and `clusterPeerTimeout` for the Alertmanager object created by the chart.

[kube-prometheus-stack] add AlertmanagerSpec clusterGossipInterval, clusterPushpullInterval and clusterPeerTimeout

---

charts/jiralert/Chart.yaml
charts/jiralert/templates/pdb.yaml

I do a mistake and I did not revalidate a [suggestion](https://github.com/prometheus-community/helm-charts/pull/3452#event-9414439084) from an other maintainer. This PR fixed the error:

[jiralert] fix invalid PodDisruptionBudget

---

charts/alertmanager/Chart.yaml
charts/alertmanager/values.schema.json
charts/alertmanager/values.yaml

List of changes:
* fix `configmapReload` - replace properties under the `properties` key;
* add `configmapReload` description;
* add inlined schema on the top of the values.yaml - useful for editing via IDE(e.g. VS Code).
`The main advantage is that it is available under the hood with all recent IDEs by using the YAML Language Server.`
Sources: 
* <https://github.com/redhat-developer/yaml-language-server#using-inlined-schema>
None
None.

[alertmanager] Fix alertmanager's configmapReload schema

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/values.yaml

The PR enables the prometheus-postgres-exporter to read the username from a Kubernetes secret.
In my use case, I store Postgres credentials inside vault secrets. On the basis of these vault secrets an external-secret operator instance automatically creates kubernetes secrets with the needed credentials. My deployment infrastructure itself does not have access to the vault. Thus I cannot dynamically add the value to the chart while rolling it out. In order to not loose my vault as a single point of truth for my complete credential set, I depend on that feature.
No related issue.
Since there is a reasonable default value for the user name, I decided to not validate that the username is only set once. It differs from the password validation approach since otherwise user would have been set …

[prometheus-postgres-exporter] user from secret

---

charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

Upgrading config-reloader image to release [0.66.0](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.66.0) due to 
- [BUGFIX] Fix config-reloader not handling SIGTERM signal
None

[prometheus] Upgrade config-reloader

---

charts/prometheus-node-exporter/Chart.yaml

- Updates [Prometheus Node Exporter image(to 1.6.0)](https://github.com/prometheus/node_exporter/releases/tag/v1.6.0)
-  https://github.com/prometheus/node_exporter/compare/v1.5.0...v1.6.0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6
- maintenance, reduced vulnerability detection
- add [license annotations](https://artifacthub.io/docs/topics/annotations/helm/)
- none.
- none.
- it is minor, update image version

[prometheus-node-exporter] updates Node Exporter image to 1.6.0

---

.github/CODEOWNERS
charts/prometheus-windows-exporter/.helmignore
charts/prometheus-windows-exporter/Chart.yaml
charts/prometheus-windows-exporter/README.md
charts/prometheus-windows-exporter/templates/_helpers.tpl
charts/prometheus-windows-exporter/templates/config.yaml
charts/prometheus-windows-exporter/templates/daemonset.yaml
charts/prometheus-windows-exporter/templates/podmonitor.yaml
charts/prometheus-windows-exporter/templates/service.yaml
charts/prometheus-windows-exporter/templates/serviceaccount.yaml
charts/prometheus-windows-exporter/templates/servicemonitor.yaml
charts/prometheus-windows-exporter/values.yaml

Add helm chart for windows export.
Tested on a AKS with WS 2022 nodes.
Based on https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/kubernetes.md
- fixes #

[prometheus-windows-exporter] Add chart

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/values.yaml

- Updates [Prometheus Pushgateway image(to 1.6.0)](https://github.com/prometheus/pushgateway/releases/tag/v1.6.0)
-  https://github.com/prometheus/pushgateway/compare/v1.5.1...v1.6.0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6
- maintenance, reduced vulnerability detection
- add [license annotations](https://artifacthub.io/docs/topics/annotations/helm/)
- Fixes #3507
- Fixes #3485
- Fixes #3019 
- none.
- it is minor, update image version

[prometheus-pushgateway] updates pushgateway image to 1.6.0

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/role.yaml

When `endpointslices` are enabled in collectors (not the default), `kube-state-metrics` logs the following error:
```
2023-06-20T17:51:58.346283983-05:00 E0620 22:51:58.346134       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:monitoring:prometheus-kube-state-metrics" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
```
And no `kube_endpointslice_` metrics are collected.
Reviewers: @tariq1890 @mrueg @dotdc

[kube-state-metrics] Add endpointslices to ClusterRole/Role

---

charts/prometheus/Chart.yaml

- Updates [Prometheus  image(to v2.45.0)](https://github.com/prometheus/prometheus/releases/tag/v2.45.0)
- https://github.com/prometheus/prometheus/compare/v2.44.0...v2.45.0
- maintenance, This version is a LTS (Long-Term Support) release of Upstream
- none.
- May include in #3422, @zeritti
- it is minor, update image version

[prometheus] updates  Prometheus image to 2.45.0(LTS)

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/ingress.yaml
charts/prometheus-blackbox-exporter/values.yaml

The promtheus ingress manifest inside kube-prometheus-stack is passing the ingress hostname through helm tpl function.
Ref: https://github.com/prometheus-community/helm-charts/blob/94f2914d47ecab6dc062f941d10b78a81c27f912/charts/kube-prometheus-stack/templates/prometheus/ingress.yaml#L33
I would like to see this behavior in blackbox_exporter too.
- fixes #

[prometheus-blackbox-exporter] Pass ingress hostname through tpl function

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml

Currently when `kube-prometheus-stack` is deployed, the `imagePullSecrets` are not specified in the resulting `Deployment` regardless of what the `global.imagePullSecrets` is. It results in the container runtime not being able to pull the image if it comes from a repository which requires authentication.  
This PR adds the `imagePullSecrets` section to the prometheus-operator Deployment.
none

[kube-prometheus-stack]  use imagePullSecrets in deployment for prometheus-operator

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/README.md
charts/prometheus-postgres-exporter/templates/_helpers.tpl
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/templates/secrets.yaml
charts/prometheus-postgres-exporter/values.yaml

What this PR does / why we need it
When we want to do sub-charting (eg. in a postgres chart) we need to duplicate the datasource config code in the values file. We want to avoid duplicating this configuration as the postgresql-chart is used by multiple applications and we want to avoid having to duplicate all these values in each sub-chart using this.
Furthermore the tpl function does not incur any form of regression on the previous setup thus the change is non-breaking.
Checklist

[prometheus-postgres-exporter] Add tpl functionality to the datasource config of Postgres-exporter

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/values.yaml

- Using quary.io image instead of the docker hub image. This change is already done in the prometheus, alertmanager, node-exporter helm chart:
- see #928
- fixes #3562

[prometheus-pushgateway] move registry to quay.io

---

.github/workflows/release.yaml

* Enables release note generation via an [option](https://github.com/helm/chart-releaser#create-github-releases-from-helm-chart-packages) provided by chart-releaser. chart-releaser uses GitHub's feature for automatic release note generation ([docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)).
* Current release notes provided in the release are unusable with tools like [Renovate](https://github.com/renovatebot/renovate).

chore(github): Generate release notes

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/values.yaml

Currently, the values passed to the RabbitMQ URL env var has to be hardcoded. This is especially cumbersome to maintain when integrating the Prometheus Exporter with other dependencies in one chart when the Prometheus Exporter is pulled as dependency. This makes it easy to build the reference URL in cases where the RabbitMQ k8s service endpoint is used and so forth.

[prometheus-rabbitmq-exporter]  allow RabbitMQ URL to be passed as a templated field

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/verticalpodautoscaler.yaml
charts/kube-prometheus-stack/values.yaml

By default, VPA Updater triggers eviction only with 2+ replicas. With single replica deployment, [`minReplicas`](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml#L382) is required to be set to `1` be updated by VPA Updater.
- fixes #

[kube-prometheus-stack] Allow minReplicas to be set for VPA

---

charts/prom-label-proxy/Chart.yaml
charts/prom-label-proxy/templates/service.yaml

- Add prom-label-proxy service annotations support mentioned in default values.yaml

[prom-label-proxy] Add svc annotations support

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/networkpolicy.yaml

This PR fixes Prometheus network policy for Prometheus Agent mode (introduced in #3520).
The selectors are updated to
1. conditionally match pods with `prometheus-agent` (instead of `prometheus`) label,
2. use `operator.prometheus.io/name` instead of short `prometheus` label to match Prometheus name, which is not set for pods in Agent mode.
No issue.
See Prometheus Operator code for missing `prometheus` label in Agent mode:
- Prometheus Server has label `prometheus` set
https://github.com/prometheus-operator/prometheus-operator/blob/45a45f9737ae33b5d0eb4dddfbb6ee5444c3dfbd/pkg/prometheus/server/statefulset.go#L351
- Prometheus Agent doesn't have label `prometheus` set
https://github.com/prometheus-operator/prometheus-operator/blob/45a45f9737ae33b5d0eb4dddfbb6ee5444c3dfbd/pkg/prometheus/age …

[kube-prometheus-stack] Fix network policy for agent mode

---

charts/jiralert/Chart.yaml
charts/jiralert/templates/deployment.yaml
charts/jiralert/values.yaml

Added Add strategy, priorityClassName, capabilities.drop
- fixes #

[jiralert] Add strategy, priorityClassName, capabilities.drop

---

charts/alertmanager/Chart.yaml
charts/alertmanager/README.md
charts/alertmanager/templates/_helpers.tpl
charts/alertmanager/templates/ingress.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/unittests/__snapshot__/ingress_test.yaml.snap
charts/alertmanager/unittests/ingress_test.yaml
charts/alertmanager/values.yaml

- Switch to use a different config map reloader
- see: #3133
- prometheus now uses prometheus-operator/prometheus-config-reloader
- Remove old ingress version
- kubernetes 1.18 is old enough to deserve removal of support
- Simplify the chart
- required kubernetes 1.19 
- chore: add license identifer
- none.
- Need more additional notes?
- test with:
```
helm install traefik traefik/traefik --version 21.1.0 --set hostNetwork=true --set ports.traefik.expose=true -n kube-system
helm install prom oci://ghcr.io/prometheus-community/charts/alertmanager --version 0.33.1 -n kube-system --set configmapReload.enabled=true --set configmapReload.containerPort=9533 --set ingress.enabled=true --set ingress.className=traefik
helm upgrade prom ./ -n kube-system --set …
```

[alertmanager] Remove old ingress version, Switch config map reloader

---

charts/kube-prometheus-stack/Chart.yaml

Bumps the chart version in Charts.yaml to force the dependent charts to fetch updated version when the chart is published.
This specifically is to fetch the latest Grafana Helm chart grafana-6.58.4 (https://github.com/grafana/helm-charts/releases/tag/grafana-6.58.4) which correct a bug with pulling dashboards via the sidecar container.
Without a Chart.lock which was removed in a previous commit this seems like the best method for updating dependent chart versions.
N/A
Without a Chart.lock which was removed in a previous commit this seems like the best method for updating dependent chart versions. If there is another preferred method I'm happy to follow that process.

[kube-prometheus-stack] bumping chart version to allow updated dependent chart versions to be updated

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/values.yaml

Adds the option to add additional labels to the `Service` resources in the alertmanager chart. We need an additional label to enable [Linkerds multicluster](https://linkerd.io/2.13/tasks/multicluster/#exporting-the-services) support for our alertmanager setup.

[alertmanager] allow additional labels for services

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/deployment.yaml
charts/prometheus-adapter/values.yaml

Bump prometheus-adapter version to v0.11.0 and remove deprecated (and now unsupported) arg.
Fixes: #3642

[prometheus-adapter] Update prometheus adapter version and drop deprecated arg

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/networkpolicy.yaml
charts/kube-prometheus-stack/templates/prometheus/podDisruptionBudget.yaml
charts/kube-prometheus-stack/templates/prometheus/service.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecarExternal.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceperreplica.yaml

This PR fixes nonconformity/desync in pod selectors that is appeared after #3520 and #3587 were merged.
None, but related to #1519.
As was mentioned in earlier PRs (#3520 and #3587) a prometheus agent pod (that is deployed by operator) doesn't have `prometheus` label. Because of that we were forced to use another labels in pod selectors. But some resources selectors are left out of sync and another still need to be updated with introduced selectors.
Here is a description of the changes made:
- #3520 and #3587 introduced different selectors in `service.yaml` vs `networkpolicy.yaml`. They use `app.kubernetes.io/instance` vs `operator.prometheus.io/name` labels for the same pod selection. Usage of `operator.prometheus.io/name` label is taken as a basis here and in other changes of this PR.
- …

[kube-prometheus-stack] Unify usage of prometheus pods selectors

---

charts/prometheus/Chart.lock
charts/prometheus/Chart.yaml
charts/prometheus/templates/clusterrole.yaml
charts/prometheus/values.yaml

Releases bumped as follows:
- prometheus [2.46.0](https://github.com/prometheus/prometheus/releases/tag/v2.46.0)
- config-reloader [0.67.0](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.67.0)
- dependency kube-state-metrics 5.10.1
- dependency prometheus-node-exporter 4.21.0
A minor correction in clusterrole has been made: references to PSP resources should not be created without the required API being supported in the cluster as the resources being referred to are in fact not present.
None

[prometheus] Bump prometheus, config-reloader and chart deps

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

I want to clean up old replica sets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore I want to overwrite the Kubernetes default revision history limit.
See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).
-
-

[kube-prometheus-stack] Allow changing the default revisionHistoryLimit

---

charts/prometheus-statsd-exporter/Chart.yaml
charts/prometheus-statsd-exporter/templates/_helpers.tpl
charts/prometheus-statsd-exporter/templates/hpa.yaml

autoscaling/v2beta1 api for horizontalPodAutoscalers was [removed in k8s 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125)
This PR adds a conditional to use autoscaling/v2 API version if the k8s version of your cluster is 1.25 or greater.
- fixes #
@scDisorder - @-mentioning you per the instructions above. Please review when you have the time, thank you!

[prometheus-statsd-exporter] - add conditional for hpa apiVersion

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/values.yaml

Adds an option to configure the `command` on the `Deployment` created with `prometheus-redis-exporter`, similar to the option available in the [`prometheus-cloudwatch-exporter`](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-cloudwatch-exporter/values.yaml#L15-L27)

[prometheus-redis-exporter] Add option to change Deployment command

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml

Change the indentation for multiple imagePullSecrets and trim the whitespace to fix YAML parse error.
Error: YAML parse error on kube-prometheus-stack/templates/prometheus-operator/deployment.yaml: error converting YAML to JSON: yaml: line 36: did not find expected key

[kube-prometheus-stack] Fix indentation multiple imagePullSecrets

---

charts/prometheus-operator-admission-webhook/Chart.yaml
charts/prometheus-operator-admission-webhook/templates/deployment.yaml
charts/prometheus-operator-admission-webhook/values.yaml

The Prometheus Operator Admission Webhook Depoyment has been adapted to allow the user changing the default revisionHistoryLimit.
N/A
N/A

[prometheus-operator-admission-webhook] feat: allow changing the default revisionHistoryLimit

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

The Prometheus Node Exporter DaemonSet has been adapted to allow the user changing the default revisionHistoryLimit.
N/A
N/A

[prometheus-node-exporter] feat: allow changing the default revisionHistoryLimit

---

charts/prometheus-smartctl-exporter/Chart.yaml

Signed-off-by: yellowhat <yellowhat46@gmail.com>
This PR updates the image of smartctl-importer to v0.10.0.
* [https://github.com/prometheus-community/smartctl_exporter/releases/tag/v0.10.0](https://github.com/prometheus-community/smartctl_exporter/releases/tag/v0.10.0
)
*

[prometheus-smartctl-exporter]: update to smartctl exporter v0.10.0

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

When adding the sidecar container via helm values, our policies complain about the container not having security context set.
This sets the `securityContext` of the configmap reloader to the same values as the main container, to prevent it from running as root.

[alertmanager] Add securityContext to configmap reload

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/_helpers.tpl

The `prometheus.alertmanager.labels` and `prometheus.alertmanager.matchLabels` templates
were not removed when alertmanager was moved out of the Prometheus Helm chart: f41ec44757553db32c30dcdb896e80132599df28.
Edited: This PR removes several helper templates that were no longer used by the Prometheus Helm chart.

[prometheus] Remove unused helper tpl

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

A simple fix for the typo happened in kube-prometheus-stack values.yaml. I encountered an error while using the commented scrapeConfigNamespaceSelector field and tried to fix this in the official chart.

[kube-prometheus-stack] fix typo in scrapeConfigNamespaceSelector

---

charts/prometheus-conntrack-stats-exporter/Chart.yaml
charts/prometheus-conntrack-stats-exporter/templates/daemonset.yaml

Fixes the optional `podLabels` in the conntrack-stats-exporter. Currently, adding more than 1 key/value to `podLabels` results in this error:
```
Error: Failed to render chart: exit status 1: Error: YAML parse error on prometheus-conntrack-stats-exporter/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 27: mapping values are not allowed in this context
```
This update properly indents the pod labels.
- fixes #

[prometheus-conntrack-stats-exporter] fix podLabels

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

The kube-state-metrics deployment has been adapted to allow the user changing the default revisionHistoryLimit.
N/A
N/A

[kube-state-metrics] feat: allow changing the default revisionHistoryLimit

---

charts/alertmanager/Chart.yaml

- Updates Alertmanager image to [v0.26.0](https://quay.io/repository/prometheus/alertmanager?tab=tags&tag=v0.26.0) 
- maintenance. upstream: https://github.com/prometheus/alertmanager/releases/tag/v0.26.0
- none.
- The following tests were passed
```
helm install prom oci://ghcr.io/prometheus-community/charts/alertmanager --version 1.5.0 -n kube-system
helm upgrade prom ./ -n kube-system
```

[alertmanager] Updates Alertmanager image to v0.26.0 

---

charts/kube-prometheus-stack/Chart.yaml

- update helm release grafana to 6.59.* 
- maintainance.
- upstream: 
| Package | Update | Change |
|---|---|---|
| [grafana](https://grafana.net) ([source](https://github.com/grafana/helm-charts)) | minor | `6.58.*` -> `6.59.*` |
- none.
passed(kind 1.27.3)
```
helm install prom oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack --version 48.4.0 -n kube-system
helm upgrade prom ./ -n kube-system
```

[kube-prometheus-stack] update helm release grafana to 6.59.* 

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

- Updates [thanos image to v0.32.0](https://quay.io/repository/thanos/thanos?tab=tags&tag=v0.32.0)
- maintainance.
- upstream: https://github.com/thanos-io/thanos/compare/v0.31.0...v0.32.0
| Package | Update | Change |
|---|---|---|
| quay.io/thanos/thanos | minor | `v0.31.0` -> `v0.32.0` |
- none.
```
helm install prom oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack --version 48.5.0 -n kube-system
helm upgrade prom ./ -n kube-system
```

[kube-prometheus-stack] Updates thanos image to v0.32.0 

---

charts/prometheus/Chart.lock
charts/prometheus/Chart.yaml
charts/prometheus/README.md

- Bump chart dependencies
- Require Kubernetes 1.19+
| Package | Update | Change |
|---|---|---|
| [alertmanager](https://prometheus.io/) ([source](https://github.com/prometheus-community/helm-charts)) | major | `0.33.*` -> `1.6.*` |
| [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/) ([source](https://github.com/prometheus-community/helm-charts)) | minor | `5.10.*` -> `5.11.*` |
| [prometheus-node-exporter](https://github.com/prometheus/node_exporter/) ([source](https://github.com/prometheus-community/helm-charts)) | minor | `4.21.*` -> `4.22.*` |
- none.
- has major upgrade.
- kubernetes 1.18 is old enough to deserve removal of support
- add release notes

[prometheus] Bump chart dependencies, Bump minimum kubeVersion

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

- Updates [thanos image to v0.32.1](https://quay.io/repository/thanos/thanos?tab=tags&tag=v0.32.1)
- maintainance.
- upstream: https://github.com/thanos-io/thanos/compare/v0.32.0...v0.32.1
| Package | Update | Change |
|---|---|---|
| quay.io/thanos/thanos | patch | `v0.32.0` -> `v0.32.1` |
- none.
```
install prom oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack --version 49.0.0 -n kube-system --set prometheus.thanosService.enabled=true --set thanosRuler.enabled=true
helm upgrade prom ./ -n kube-system --set prometheus.thanosService.enabled=true --set thanosRuler.enabled=true
```

[kube-prometheus-stack] Updates thanos image to v0.32.1

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/rolebinding.yaml
charts/prometheus/values.yaml

Adds a `releaseNamespace` field that allows monitoring only the namespace in which Prometheus is deployed, without having to provide the namespace via the `namespaces` field explicitly. If both the `releaseNamespace` and `namespaces` fields are set, a joined list of namespaces will be monitored.
- fixes #3552 
This has been implemented in `kube-state-metrics` already; I took over most of this from the [releaseNamespace implementation](https://github.com/prometheus-community/helm-charts/blob/db2bd5d5f6a2af310b3b6a89c090bc9b9b5decf6/charts/kube-state-metrics/values.yaml#L287-L289) there.

[prometheus] Add a releaseNamespace option

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/templates/NOTES.txt
charts/kube-prometheus-stack/unittests/alertmanager/ingress_test.yaml
charts/kube-prometheus-stack/values.yaml

- Bump minimun kubeVersion to ">=1.19.0-0"
- Clarify that this chart does not work with kubernetes 1.18 anymore.
- Add Deprecation warning if using networking.k8s.io/v1betav1
- fixes #3605
- Note that already 1.18 does not work.
- see #3605
- `networking.k8s.io/v1beta1` not yet deleted here.
- kubernetes ~1.24 is already EOL.
- Will you be discontinuing support to ~1.21 or ~1.24 in the near future?
-  Warning note removed. I have decided that a warning to those still using kubernetes 1.21 is not necessary.

[kube-prometheus-stack] Bump minimun kubeVersion to ">=1.19.0-0"

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/service.yaml
charts/prometheus-node-exporter/values.yaml

Following https://github.com/prometheus-community/helm-charts/issues/2861 I would like to disable the node exporter service as we use pod monitor and we have large clusters (1K + nodes) and the k8s svc struggles with keeping up with nodes coming up and down and updating endpoints. this is optional and original behavior is preserved with a default value
- fixes #

[promethues-node-exporter] Add flag to disable service

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

Adds support for non key-value environment variables to the prometheus-kafka-exporter chart. This makes it possible mount keys Secrets/ConfigMaps into the container and use the values in the args.
This makes it possible to e.g. use `kafkaServers` from a ConfigMap:
```yaml
env:
- name: KAFKA_SERVER
valueFrom:
configMapKeyRef:
name: kafka-server
key: endpoint
kafkaServer:
- $(KAFKA_SERVER)
```
@gkarthiks @golgoth31 @zeritti

[prometheus-kafka-exporter] add support for valueFrom in env variables

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

This PR includes changes which will enable us to change the Deployment Strategy for kube-state-metrics when using the `Kind: Deployment`.
- fixes #3764
N/A

[kube-state-metrics] add option to set updateStrategy to Recreate

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/service.yaml
charts/kube-prometheus-stack/templates/prometheus/service.yaml

To integrate this port with applications such as istio the applicationProtocol should be set explicitly.
One solution to enable this integration is to add an `appProtocol` attribute to the port as explained in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol) and implemented in this PR. Another alternative is to prefix the port with `http-`.

[kube-prometheus-stack] fix reloader-web's app protocol

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

[prometheus-elasticsearch-exporter]  bump elastic-exporter to 1.6.0

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/ingress.yaml
charts/prometheus/templates/service.yaml
charts/prometheus/values.yaml

Similar to #2163 for the kube-prometheus-stack, this PR will make it possible to add an oauth proxy as a sidecar container, and change the ingress to point to an additional port in your service, that then goes to your oauth proxy. Nice and simple way of adding oauth to Prometheus. 
No issues opened for this chart, but this have been solved for the kube-prometheus-stack chart, so why not also make it possible in the prometheus chart. 
I have checked the helm chart with my changed, and it seems to work fine, but let me know if any changes is required.

[prometheus] Adding additionalPorts and servicePort

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/extra-manifests.yaml
charts/prometheus-node-exporter/values.yaml

@gianrubio @zanhsieh @zeritti 
Analogous to https://github.com/prometheus-community/helm-charts/pull/3287/ made for `prometheus` chart
Trying to add an extra manifest 
```
extraManifests:
- |
apiVersion: v1
kind: ConfigMap
metadata:
namespace: prometheus-node-exporter
name: configmap-prometheus-node-exporter-web-yaml
data:
prometheus-node-exporter-web.yaml: |
basic_auth_users:
admin: $aa$hashedpassword
```
getting `helm install` error:
```
Error: UPGRADE FAILED: YAML parse error on prometheus-node-exporter/templates/extra-manifests.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
```

[prometheus-node-exporter] Remove toYaml function in extraManifests template

---

charts/prometheus-fastly-exporter/Chart.yaml
charts/prometheus-fastly-exporter/templates/deployment.yaml

Add ability to pass in SecurityContext and PodSecurityContext
I don't think there is an issue.
Tested in my cluster with the following:
```yaml
prometheus-fastly-exporter:                                   
securityContext:                 
allowPrivilegeEscalation: false
capabilities:                  
drop: ["ALL"]                
podSecurityContext:              
seccompProfile:                
type: RuntimeDefault         
runAsNonRoot: true             
runAsUser: 10001               
runAsGroup: 10001              
```

[prometheus-fastly-exporter]: Add security context to fastly-exporter

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/cm.yaml

Adds template evaluation (via the `tpl` function) to the `remoteRead` & `remoteWrite` fields in the `ConfigMap`. This allows users of the chart to substitute values at templating time. This is especially useful if the services which a user wishes to write to are deployed as part of an adjacent sub-chart where their name includes the deployment name.
N/A

[prometheus] Apply templating to remote_read & remote_write config

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/deployment.yaml
charts/prometheus-redis-exporter/values.yaml

This pr adds support for (prometheus-redis-exporter)[./charts/prometheus-redis-exporter/] redis address environment variable to be configured from a secret.
It would unlock for redis address to be fetched though eg: [external-secrets](https://external-secrets.io/).
There is no issue linked to this change (that I know of).
I've performed some sanity checks locally to verify the chart configuration stays as is and the new configuration also works.
Since changes are all around deployment's configuration I'm using `helm` + `yq` to focus on that part of the rendered template.
This is the specific used command:
```bash
helm template . -f values.yaml |yq 'select(.kind == "Deployment").spec.template.spec.containers[0].env'
```
No diff, it's literally `values.yaml` by default, renders as:
```yaml …
```

[prometheus-redis-exporter] Allow `REDIS_ADDR` environment variable to be configured through a secret

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/service.yaml
charts/prometheus-kafka-exporter/values.yaml

I added support for the nodePort configuration for external use.
- fixes #

[prometheus-kafka-exporter] Add nodePort for external use

---

charts/prometheus-postgres-exporter/Chart.yaml

Upgrades postgres-exporter to v0.14.0. (see the [release notes](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.14.0)) This version includes new collectors, Postgres version compatibility fixes, and a fix for an issue caused by connection errors at startup.

[prometheus-postgres-exporter] Upgrade postgres-exporter version

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/service.yaml
charts/prometheus-kafka-exporter/values.yaml

I added an loadBalancerIP configuration to specify a static IP when using NodePort service type.
- This PR has a similar context with PR #3828 .

[prometheus-kafka-exporter] Add LoadBalancerIp

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml

This PR fixes the `preStop` command for the elasticsearch-exporter deployment. Right now, it's using `/bin/bash sleep 20`, but bash does not exist in the container image. Thusly, the fix is to use the existing `/bin/sleep` command to sleep 20 seconds.

[prometheus-elasticsearch-exporter]: Fix preStop command

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/README.md
charts/prometheus-node-exporter/templates/clusterrole.yaml

[prometheus-node-exporter] remove ns from clusterrole

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/servicemonitor.yaml

This (default) parameter is automatically added by k8s, causing the in-cluster object to differ from the manifest created by this chart. This discrepancy causes GitOps tooling to consider the resource out of date.
- fixes #3626

[prometheus-snmp-exporter] add action=replace to metricsRelabelings

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

Adds the option to add additional containers and initContainers to the kube-state-metrics helm chart.
This becomes handy when adding a sidecar to e.g. automatically update the crd configuration file.
Currently it requires patching the chart e.g. as done in: https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/observability/kube-state-metrics/kustomization.yaml (post `helm template`).
- fixes #

[kube-state-metrics] add option to add initContainers and additional sidecars

---

charts/kube-prometheus-stack/Chart.yaml

Lifts the Grafana helm-chart to use the latest minor version

[kube-prometheus-stack] lift to grafana helm-chart version 6.60

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/config-reloaders.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-state-metrics.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-resources.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-network.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

Adding keep_firing_for property to all rules. This avoids alert flapping.  https://github.com/prometheus/prometheus/pull/11827
- fixes #

[kube-prometheus-stack] Allow to configure keep_firing_for for all Prometheus rules

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/templates/ingress.yaml
charts/prometheus-json-exporter/templates/service.yaml
charts/prometheus-json-exporter/values.yaml

Fixes some default values from `[]` to `{}` and adds support for setting service labels and annotations.
@schmiddim @zanhsieh @xiu

[prometheus-json-exporter] defaults and service labels/annotations support

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/secret.yaml

Fixes ThanosRuler objectstore configs
fixes https://github.com/prometheus-community/helm-charts/issues/3912

[kube-prometheus-stack] fixes thanos ruler object store configs

---

.github/CODEOWNERS
charts/prometheus-memcached-exporter/.helmignore
charts/prometheus-memcached-exporter/Chart.yaml
charts/prometheus-memcached-exporter/README.md
charts/prometheus-memcached-exporter/templates/NOTES.txt
charts/prometheus-memcached-exporter/templates/_helpers.tpl
charts/prometheus-memcached-exporter/templates/deployment.yaml
charts/prometheus-memcached-exporter/templates/hpa.yaml
charts/prometheus-memcached-exporter/templates/prometheusrule.yaml
charts/prometheus-memcached-exporter/templates/service.yaml
charts/prometheus-memcached-exporter/templates/serviceaccount.yaml
charts/prometheus-memcached-exporter/templates/servicemonitor.yaml
charts/prometheus-memcached-exporter/templates/tests/test-connection.yaml
charts/prometheus-memcached-exporter/values.yaml

Adds a helm chart to deploy the official prometheus-memcached exporter.
- fixes #

[prometheus-memcached-exporter] Add chart

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/values.yaml

Cert-Manager converts simple duration values to their full format: `1h` ends up as `1h0m0s`
GitOps tools like Argo CD keep seeing this as a change and never reach a 'synced' state because they see this as a diff: `1h0m0s != 1h`. Using the full format fixes that.

[prometheus-adapter] Use full duration format for default certificate values

---

charts/prometheus-nginx-exporter/Chart.lock
charts/prometheus-nginx-exporter/Chart.yaml

[prometheus-nginx-exporter] bump nginx dep to 15.3.4

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

… alertmanager.spec
This is useful, if complex templating is required or properties are not exposed by the chart yet.
- fixes #

[kube-prometheus-stack] Allow to directly config prometheus.spec and  alertmanager.spec

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/README.md
charts/prometheus-json-exporter/templates/configmap.yaml
charts/prometheus-json-exporter/templates/deployment.yaml

Corrects ConfigMap name formula to be dependent on the configurable `prometheus-json-exporter.fullname` template like other resources in the chart. Without this, its not possible correctly maintain multiple instances of the exporter as part of single release.
- fixes #

[prometheus-json-exporter] fix: configmap name standard

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/cm.yaml
charts/prometheus/values.schema.json
charts/prometheus/values.yaml

Allows setting the `scrape_config_files` in the prometheus configuration which was introduced in 2.43.0 https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2430--2023-03-21 - this allows splitting up scrape_configs into multiple files (which can be mounted in via `extraConfigmapMounts` or `extraHostPathMounts`, etc) 
- fixes #
Thanks for reviewing!

[prometheus] Allow setting scrape_config_files in prometheus config

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/templates/prometheus/secret.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/secret.yaml
charts/kube-prometheus-stack/values.yaml

Updates thanos configs to allow the usage of existing secrets or the option of creating a new secret object
Full design discussion can be found in the issue 
fixes https://github.com/prometheus-community/helm-charts/issues/3869

[kube-prometheus-stack] fixes thanos configs

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Hello, 
I have faced an issue, when due to circumstances, cadvisor metric timestamp is from the past. Due to this, prometheus rejects metrics with reason "Error on ingesting out-of-order samples". 
I don't see any advantage in using exporters timestamp over prometheus timestamp, therefore I want to try to reject honor labels. 
Unfortunately, I found it is impossible within kube-prometheus-stack helm chart. 
This PR gives an opportunity to set honorLabels/Timestamps without creating separate ServiceMonitor.

Populating dynamic honorLabels and honorTimestamps in kubelet ServiceMonitor

---

charts/jiralert/Chart.yaml
charts/jiralert/ci/test-values.yaml
charts/jiralert/templates/ingress.yaml

[jiralert] Fix template error in ingress

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/_helpers.tpl
charts/prometheus/templates/deploy.yaml
charts/prometheus/templates/pvc.yaml
charts/prometheus/templates/sts.yaml
charts/prometheus/values.schema.json
charts/prometheus/values.yaml

This PR brings support for setting Prometheus' data retention size through field `server.retentionSize`.
Furthermore, a few fixes have also been included:
- An update to the values schema
- Field `commonMetaLabels` has been inserted in the values file
- Labels set in `server.persistentVolume.labels` to be attached also to the standalone PVC
- `resources` gets rendered only if set
- Comments corrected in values file
- Unused helper template `prometheus.daemonset.apiVersion` removed
- fixes #3871
- fixes #3806 
- fixes #3694
- fixes #3886
- fixes #3958

[prometheus] Support retention size, attach volume labels to PVC

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Bump grafana and kube-state-metrics version
- fixes #

[kube-prometheus-stack] Bump grafana and kube-state-metrics charts

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/psp.yaml
charts/prometheus-adapter/values.yaml

Prometheus adapter is missing pod security annotations, current workaround is to apply them as custom annotations but then they apply to all objects, copying the approach taken in kube-prometheus-stack and adding support for specific pod security policy annotations
Didn't bother raising one

[prometheus-adapter] - Added pod security policy specific annotations

---

charts/prometheus-operator-crds/Chart.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml

[prometheus-operator-crds] Bump crds to 0.70.0

---

.github/linters/ct.yaml

- Following https://github.com/prometheus-community/helm-charts/pull/3987#discussion_r1420446414
- Run shellcheck on custom lint file
- Causes https://github.com/prometheus-community/helm-charts/pull/4073
```sh
→ for DIR in ./charts/*; do
echo "==> Working on $DIR"
export DIR
sh -ec "if [ -f '${DIR}/ci/lint.sh' ]; then shellcheck '${DIR}/ci/lint.sh'; bash '${DIR}/ci/lint.sh'; fi"
done
```
<details>
<summary>Click to expand result.</summary>
```sh
==> Working on ./charts/alertmanager
==> Working on ./charts/alertmanager-snmp-notifier
==> Working on ./charts/jiralert
==> Working on ./charts/kube-prometheus-stack
In ./charts/kube-prometheus-stack/ci/lint.sh line 16:
source venv/bin/activate
^---------------^ SC1091 (info): Not following: venv/bin/activate was not specified as input (see …
```

[CI] Run shellcheck on custom lint file

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/lint.sh

- Required due to https://github.com/prometheus-community/helm-charts/pull/4072
- Shellcheck linter file

[kube-prometheus-stack] Shellcheck linter file

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

This rule was accidentally left out while migrating to the new layout for rules in #3883. This rule is currently referenced in the Grafana Dashboard [Kubernetes / Compute Resources / Node (Pods)](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml)

[kube-prometheus-stack]: re-enable memory working set rule

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Inhibit InfoInhibitor Alerts totally

[kube-prometheus-stack] inhibit InfoInhibitor alerts by default

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

Allow override command for the users that want to use a private container image.

[prometheus-kafka-exporter] Add option to change deployment command

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Fixing a small typo in the example comment in `value.yaml`
- fixes #3687

[kube-prometheus-stack] Fix example in value.yaml

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/serviceaccount.yaml

Allows to use default values and prevent an empty `imagePullSecrets` in the ServiceAccount generate resource.
- fixes #4059

fix(kube-state-metrics): skip imagePullSecrets when no override provided

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/ci/default-values.yaml
charts/prometheus-json-exporter/templates/deployment.yaml
charts/prometheus-json-exporter/values.yaml

This enables the user to specify annotations for the deployment.
@schmiddim, @zanhsieh, @xiu, mentioning you as per the PR template.
_No issue_
Annotations can't be set for the deployment
_None_

[prometheus-json-exporter] feat: add annotations for Deployment

---

charts/prometheus-opencost-exporter/Chart.yaml

https://github.com/opencost/opencost/releases/tag/v1.108.0

[prometheus-opencost-exporter] OpenCost 1.108.0 has been released

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

I made liveness and readiness probes customizable to make kube-state-metrics features like TLS and Basic-Auth fully available for chart users without requiring kube-rbac-proxy. When you enable those features in kube-state-metrics configuration then probes crash. To use TLS, we need to change httpGet.scheme to HTTPS and for Basic-Auth we need to add httpHeaders in httpGet.
I've also renamed `httpPort` to `servicePort` to bring it in-line with node-exporter.
This code was borrowed from #2053

[kube-state-metrics] Make liveness and readiness probes customizable

---

.github/CODEOWNERS
charts/prometheus-systemd-exporter/Chart.yaml

This PR adds @maxime1907 as a maintainer of the chart. I have been contributing to various [open source chart projects](https://github.com/maxime1907?tab=repositories&q=charts&type=&language=&sort=) and will be happy to support the community's work further as a chart maintainer.
- fixes #1656

[prometheus-systemd-exporter]: add maxime1907 as chart maintainer

---

charts/kube-prometheus-stack/Chart.yaml

Updates Grafana Chart version to 7.2.x version
-  Support Datasource sidecar having envValueFrom
-  fix secret datasources/notifiers rendering

[kube-prometheus-stack] Update grafana chart to 7.2.x

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

This PR allows tuning startupTime in operated prometheus. Should be valuable for the installations with big TSDB
@zeritti @gianrubio @zanhsieh

[kube-prometheus-stack] add maximumStartupDurationSeconds optional value

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

For our purposes of this chart, we would like to be able to customize the node-exporter daemonset with the following variables:
- For both the Node Exporter and KubeRBACProxy containers, variables have been added to configure `terminationMessagePath` and `terminationMessagePolicy`
- A variable was added to configure the `terminationGracePeriodSeconds`
- fixes #
@zeritti @gianrubio @zanhsieh

[prometheus-node-exporter] Add Termination Msg Params to Daemonset

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

Adds support for the minReadySeconds field on the Alertmanager StatefulSet. This feature has been marked stable as of Kubernetes 1.25. It is already supported for the [Alertmanager CRD](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml#L4294), but I would like to add it to this chart as well.
Being able to set this value may help alleviate https://github.com/prometheus/alertmanager/issues/2370.

[alertmanager] Add support for minReadySeconds

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/deployment.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/pdb.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/service.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/ciliumnetworkpolicy.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/clusterrolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/networkpolicy.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/psp-clusterrole.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/psp-clusterrolebinding.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/psp.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/service.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/verticalpodautoscaler.yaml

The prometheus-operator fullname is already defined and suffixed in
https://github.com/prometheus-community/helm-charts/blob/2f3dbddd3ed01e3b5044a9186f064b050dbe9a31/charts/kube-prometheus-stack/templates/_helpers.tpl#L27-L30
However, it's not used globally in the templates. With these changes there will be no inconsistencies between the `_helpers.tpl` and the templates themself.
- fixes #
There will be no actual changes in the generated files using `helm template` command after this contribution

[kube-prometheus-stack] Fixing template inconsistencies in prometheus-operator fullname

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/values.yaml

Prometheus-operator resources' names are suffixed with `-operator` by default which can lead to names like `prometheus-operator-operator(-...)`.
This will allow to override the fullname and remove the suffix if needed.
It will not change the previous default naming convention though.
- fixes #

[kube-prometheus-stack] Allow fullname override of prometheus-operator

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

- For both the `/proc` and `/sys` filesystems, a variable has been added to configure the `mountPropagation`
- Add option to define a volumes mount type
- fixes #

[prometheus-node-exporter] Add MountPropagation and VolumeMount Type to Daemonset

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

In the KubeRBACProxy container, there is a missing trim in the `toYaml` block, which makes for odd spacing in the daemonset. This removes the extra space.
Current:
```
resources:
requests:
cpu: 10m
memory: 32Mi
```
With this change:
```
resources:
requests:
cpu: 10m
memory: 32Mi
```
- fixes #

[prometheus-node-exporter] KubeRBACProxy Resources Syntax Bug Fix

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

Elasticsearch Exporter supports exposing metrics related to Index Lifecycle Management since 1.6.0.
While this is actually missing from the exporter README, [release notes](https://github.com/prometheus-community/elasticsearch_exporter/releases/tag/v1.6.0) and the [code](https://github.com/prometheus-community/elasticsearch_exporter/blob/master/main.go#L80) shows that it is actually available.
Lets allow chart users to configure it through the values.
No opened issues

[prometheus-elasticsearch-exporter] Support ILM metrics

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/templates/podmonitor.yaml
charts/prometheus-elasticsearch-exporter/templates/service.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

[prometheus-elasticsearch-exporter] add support for podmonitor

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml
charts/prometheus-blackbox-exporter/values.yaml

[prometheus-blackbox-exporter] define port field in selfservicemonitor

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/config-reloaders.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-state-metrics.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-resources.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-network.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

Attemp to address the issue with fixed values "for" and "severity" in the helm chart, to make it more flexible to use and allow to overload those values without forking and customzing the entire chart. 
- fixes #3384 
```
$ docker run -it --rm --network host --workdir=/data --volume ~/.kube/config:/root/.kube/config:ro --volume $(pwd):/data --volume ~/.config/helm:/root/.config/helm quay.io/helmpack/chart-testing:v3.10.1 ct lint --chart-dirs . --charts . --validate-maintainers=false                                                                                                                                   Linting charts...
Version increment checking disabled.
------------------------------------------------------------------------------------------------------------------------ …
```

[kube-prometheus-stack] allow override of for and severity rules

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/values.yaml

Currently the exporter allows using password from secret. This patch allows users to read username from secret as well. This is used in cases where automated username is created during install process of rabbitmq service.
Signed-off-by: Sulochan Acharya <sulochan@gmail.com>

[prometheus-rabbitmq-exporter] Allows reading User from secret

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

The conditional for including the custom resource state configmap is errantly included inside the conditional for kubeRBACProxy
n/a

[kube-state-metrics] Fix the customResourceState.enabled args conditional

---

charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/rules/rules.txt

It fixes a typo that i noticed while reviewing prometheusRules

[prometheus-smartctl-exporter] Fix typo in (prometheus)-rules.txt

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/deployment.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/serviceaccount.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceaccount.yaml
charts/kube-prometheus-stack/values.yaml

Add automountServiceAccountToken option to prometheus and prometheus-operator. It is needed as Azure's security recommendation suggests disabling automounting of API credentials.

[kube-prometheus-stack] Add automountServiceAccountToken option

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/README.md
charts/prometheus-snmp-exporter/templates/daemonset.yaml
charts/prometheus-snmp-exporter/templates/deployment.yaml
charts/prometheus-snmp-exporter/templates/servicemonitor.yaml
charts/prometheus-snmp-exporter/values.yaml

This PR upgrades snmp exporter to version 0.24.1 which supports submitting config as multiple files (see https://github.com/prometheus/snmp_exporter/issues/628). This provides the ability to move the auth part into a separate file and load it separately as a secret (from Vault for example).
This PR also introduces support for extraVolumes and extraVolumeMounts to support this feature.
My use case for this feature:
I have an init container that is responsible for getting the auth part of the config from the vault and needs to pass it to snmp-exporter, for this, I need to create an emptyDir volume and mount it to both containers. 
Also, it is quite a common feature to have for helm-charts with a lot of use cases in general.
Finally, this PR adds ability to specify auth query param to be …

[prometheus-snmp-exporter] Add extraVolumes support and passing auth param

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

[kube-prometheus-stack] Add extraVolumes and extraVolumeMounts to prometheus-operator deployment.
This is required to manually mount service account token, related to #4285.

[kube-prometheus-stack] extraVolumes and extraVolumeMounts

---

.github/linters/ct.yaml

Makes chart-testing logs easier to read. Feature createad on https://github.com/helm/chart-testing/pull/556.

[CI] Group chart-tester logs

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

This will make it easier to install the chart in environments where resources cannot be created in the kube-system namespace, such as a tightly scoped ArgoCD AppProject.
Without this change, to use the built-in ServiceMonitors with service.enabled=false, the cluster operator is expected to create services in the kube-system namespace that have labels that exactly match what the chart is expecting.
With this change, I can create these service resources with my own naming conventions and labels before installing the helm chart, and inform the ServiceMonitor on how to select them.
- fixes #

[kube-prometheus-stack] Allow setting selectors for built-in ServiceMonitors

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/service.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/endpoints.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/service.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Following on from #4312, I found while trying to use the built-in kube-dns service instead of just a custom externally-managed one for scraping metrics that the default configuration calls the metrics port `metrics`, not `http-metrics` like the chart expects.
This change allows overriding this value for all the built-in ServiceMonitors that create Services, and setting it will change the port name for the Helm managed services to ensure setting it without using custom Services continues to work.
- fixes #

[kube-prometheus-stack] Allow changing port name of built-in ServiceMonitors

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/service.yaml
charts/kube-prometheus-stack/values.yaml

This PR enables the configuration of the port value for the `reloader-web` port in the Prometheus Service Object. 
Port `8080` is a commonly used port, so it's possible that it's already taken.
Actually that's exactly what happened in our setup in MacStadium. We use a LoadBalancer Service to expose Prometheus to our clients. We reuse the same load balancer IP and unfortunately we already have a service listening on port 8080, so the Prometheus Service can't use it. 
With this change we are able to change the `reloader-web` Service Port to another value
- fixes #

[kube-prometheus-stack] Allow changing the reloader web port in the Prometheus Service

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

I find this comment on `serviceMonitor` a bit ambiguous, what should be true?
```yaml
##
interval: ""
selfMonitor: true
```
It should probably be moved on top of `selfMonitor`, which is the actual boolean flag that decides whether to create the `ServiceMonitor` or not [when alertmanager is enabled](https://github.com/prometheus-community/helm-charts/blob/2a7ea2f2f3d3b95b10981aad4c44e90de7aefe6c/charts/kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml#L1).
n/a

[kube-prometheus-stack] Update ambiguous doc comment for selfMonitor

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/values.yaml

- improve default containerSecurityContext for main container by adding `readOnlyRootFilesystem: true`
- copy-paste containerSecurityContext from main to rbac sidecar for better security out of the box

[kube-state-metrics] Tighten default security config for containers

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

This PR allows to update the prometheus-operator rollout `strategy`: `Recreate` or `RollingUpdate` (default)

[kube-prometheus-stack] add rollout strategy to prometheus-operator deployment

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/values.yaml

[alertmanager] allow configuration of ipFamilyPolicy

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/_helpers.tpl
charts/prometheus-pushgateway/values.yaml

This PR adds simple configuration for hard/soft podAntiAffinity for prometheus-pushgateway. The implementation is based on the existing pattern in [alertmanager](https://github.com/prometheus-community/helm-charts/blob/f00193179b8d083e8b609ef587c72d66c633072e/charts/alertmanager/templates/statefulset.yaml#L58)
It is already possible to configure podAntiAffinity using the `affinity` config field, however you need to provide the entire podAntiAffinity YAML object. Notably, this includes a selector which matches on Pod labels, therefore requires the developer writing this configuration to know how Pod labels will be rendered. Adding a simple hard/soft `podAntiAffinity` configuration option therefore simplifies a common configuration requirement and provides some extra backwards compatibility …

[prometheus-pushgateway] Add config for hard/soft podAntiAffinity

---

charts/prometheus/Chart.lock
charts/prometheus/Chart.yaml
charts/prometheus/templates/deploy.yaml
charts/prometheus/templates/sts.yaml
charts/prometheus/values.schema.json
charts/prometheus/values.yaml

Follows !4340
This PR adds simple configuration for hard/soft podAntiAffinity for prometheus. The implementation is based on the existing pattern in [alertmanager](https://github.com/prometheus-community/helm-charts/blob/f00193179b8d083e8b609ef587c72d66c633072e/charts/alertmanager/templates/statefulset.yaml#L58)
It is already possible to configure podAntiAffinity using the `server.affinity` config field, however you need to provide the entire podAntiAffinity YAML object. Notably, this includes a selector which matches on Pod labels, therefore requires the developer writing this configuration to know how Pod labels will be rendered. Adding a simple hard/soft `server.podAntiAffinity` configuration option therefore simplifies a common configuration requirement and provides some extra …

[prometheus] Add config for hard/soft podAntiAffinity and bump chart deps

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml

[kube-prometheus-stack] bump operator to 0.72.0

---

charts/kube-prometheus-stack/Chart.yaml

[kube-prometheus-stack]: upgrade prometheus-node-exporter to 4.31.0.

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/service.yaml

Fixes the KIA0601 error
is just the name of the service

[prometheus-adapter] Add a name to the Service object (KIA0601)

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml
charts/kube-prometheus-stack/templates/prometheus/clusterrole.yaml

This PR adds a rule required to scrap the `node-exporter` behind the RBAC proxy.
- fixes #3338

[kube-prometheus-stack] Add `node-exporter` RBAC Proxy rule to Prometheus ClusterRole

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

PodDisruptionBudget are mutable since kubernertes 1.15.
Remove the warning in the comments kube-prometheus-stack/values.yml to
avoid confusion.
Links: https://github.com/kubernetes/kubernetes/pull/69867
I didn't bump the chart version since this is a documentation only PR (comments, to be precise), but I can do so if that's still necessary in that case.

[kube-prometheus-stack] Remove outdated PDB warning

---

charts/prometheus/Chart.lock
charts/prometheus/Chart.yaml

[prometheus] bump to 2.51.1 + deps

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/templates/cluster-role-binding-auth-reader.yaml
charts/prometheus-adapter/values.yaml

When deploying the Prometheus Adapter in a Namespace the `auth-reader` role is still created in the `kube-system` namespace. Deploying into `kube-system` is not wanted for a lot of enterprise clusters.
This give the option to deploy the `auth-reader` role as a cluster role rather then a normal role. Now the User can easily deploy everything into one namespace
- fixes #

[prometheus-adapter] allow using cluster roles for auth reader

---

charts/kube-prometheus-stack/Chart.yaml

This PR just force a kube-prometheus-stack release to include the latest kube-state-metrics helm chart which includes a fix made available in https://github.com/prometheus-community/helm-charts/pull/4412.
See : https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.12.0
- fixes #4410

[kube-prometheus-stack] fix issue with kube-state-metrics 2.11.0

---

charts/prometheus-pgbouncer-exporter/Chart.yaml
charts/prometheus-pgbouncer-exporter/README.md

[prometheus-pgbouncer-exporter] bump to 0.8.0

---

charts/jiralert/Chart.yaml
charts/jiralert/templates/deployment.yaml
charts/jiralert/values.yaml

Trying to use `env` gives the following error:
`Error: template: jiralert/templates/deployment.yaml:70:43: executing "jiralert/templates/deployment.yaml" at <.Values.env>: nil pointer evaluating interface {}.env`
Also `values.yaml` doesn't show that `env:` is an option; one needs to check out the `deployment.yaml` to see that it's used

Fix env for jiralert chart

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml
charts/prometheus-blackbox-exporter/values.yaml

Add values to configure scheme and tlsConfig for self ServiceMonitor, which is required when enabling TLS for Blackbox-exporter

[prometheus-blackbox-exporter] Fix self ServiceMonitor to support HTTPS

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml

The fullname of the ThanosRuler custom resource instance is configured in the helpers, but it's not used anywhere in the templates.
Since ThanosRuler instances are managed by the prometheus-operator, like prometheus and alertmanager instances, we could use the same naming convention everywhere.
These changes will simplify ThanosRuler custom resource name in cases where `cleanPrometheusOperatorObjectName` is set to `true`.
- fixes #

[kube-promettheus-stack] ThanosRuler custom resource instance name

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/values.yaml

Implement alertDropLabels propertiery for thanosRuler + additionalConfig for more flexible situations
- fixes #

[kube-prometheus-stack] Thanos Ruler: Add alertDropLabels + additional config

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/daemonset.yaml
charts/prometheus-snmp-exporter/templates/deployment.yaml
charts/prometheus-snmp-exporter/values.yaml

- Add optional envFrom sections to DaemonSet and Deployment
@Miouge1 @xiu @walker-tom 
Allow setting an optional `envFrom` section in DaemonSet or Deployment in order to be able to inject secrets as environment variables to be expanded by the exporter.
- fixes #4438

[prometheus-snmp-exporter] Allow setting environment variables via envFrom

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/podDisruptionBudget.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/service.yaml

The ThanosRuler custom resource name is used as a label selector in thanos-ruler `Service` and `PodDisruptionBudget` templates.
These template field were missed in this [PR](https://github.com/prometheus-community/helm-charts/pull/4439) and can lead to broken deployments due to unmatched labels in cases where the CR names are simplified (`cleanPrometheusOperatorObjectNames: true`)
- fixes #

[kube-promettheus-stack] fix ThanosRuler custom resource name label selector

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/README.md
charts/prometheus-pushgateway/templates/_helpers.tpl
charts/prometheus-pushgateway/templates/secret.yaml
charts/prometheus-pushgateway/values.yaml

Since [pushgateway supports basic authentication](https://github.com/prometheus/pushgateway/tree/master?tab=readme-ov-file#tls-and-basic-authentication), this PR enables this functionality by introducing the `webConfiguration.basicAuthUsers` value. 
It also makes sure that credentials for basic authentication have to be specified only once in Values and can be utilised in the `httpHeaders` for the liveness and readiness probes as well as in the `web.config.file` provided from the mounted Secret. I think it is a neat feature, that you don't have to specify the same credentials twice in different forms. 
Maintainer's EDIT: The description of the breaking change removed as none has been introduced.

[prometheus-pushgateway] add support for basic authentication

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/service.yaml
charts/kube-state-metrics/values.yaml

add support for dual stack clusters

 [kube-state-metrics] add support for dual stack clusters

---

.github/workflows/check-codeowners.yaml

- remove yq install from codeowners lint
- snap install can take a while but yq should already be present on github runner. see: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#tools

remove yq install from codeowners lint

---

charts/prometheus-modbus-exporter/Chart.yaml
charts/prometheus-modbus-exporter/templates/deployment.yaml

Hi, I have discover that the current deployment template for the `prometheus-modbus-exporter` does not handle the overloading of the registry that can be found in the values.
In the values.yaml there is two references for that action:
```yaml
image:
registry: docker.io
...
configReloaderSidecar:
enabled: true
image:
registry: docker.io
```
But the actions in the deployment template are:
```yaml
containers:
- name: {{ include "prometheus-modbus-exporter.fullname" . }}
image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
...
- name: {{ include "prometheus-modbus-exporter.fullname" . }}-config-reloader-sidecar
image: "{{ .Values.configReloaderSidecar.image.repository }}:{{ .Values.configReloaderSidecar.image.tag }}"
```
The proposed change includes the …

[prometheus-modbus-exporter] fix deployment template

---

charts/prom-label-proxy/Chart.yaml
charts/prom-label-proxy/templates/ingress.yaml
charts/prom-label-proxy/values.yaml

It is useful for the case when we use one domain name for a bunch of prom-label-proxy deployments. In this case, we have to use different paths to route requests, but we need templating for paths to implement it.
It doesn't break backward capabilities for existing value files.

[prom-label-proxy] add path templating

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

Please refer to [prometheus-operator #5641](https://github.com/prometheus-operator/prometheus-operator/pull/5641)

[kube-prometheus-stack] support kubelet label selector

---

charts/prometheus/Chart.yaml
charts/prometheus/ci/01-automount-sa-token-values.yaml
charts/prometheus/ci/02-config-reloader-deployment-values.yaml
charts/prometheus/ci/03-config-reloader-sts-values.yaml
charts/prometheus/ci/04-extra-manifest-values.yaml
charts/prometheus/ci/05-server-deployment-values.yaml
charts/prometheus/ci/06-server-sts-values.yaml
charts/prometheus/ci/07-meta-labels-values.yaml
charts/prometheus/ci/08-sts-pvc-retention-policy-values.yaml
charts/prometheus/ci/09-standalone-deployment-values.yaml
charts/prometheus/ci/10-namespaced-sd-values.yaml
charts/prometheus/ci/11-default-values.yaml

The chart does not currently have any specific test cases to run in CI tasks and as a result, many fields and scenarios remain untested. This PR adds a few test cases setting fields that are otherwise unset or commented out.  
None

[prometheus] Add CI test cases

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/daemonset.yaml
charts/prometheus-snmp-exporter/templates/deployment.yaml
charts/prometheus-snmp-exporter/values.yaml

- Introduce optional revisionHistoryLimit for Deployment / DaemonSet
@Miouge1 @xiu @walker-tom 
Make the Deployment / DaemonSet `revisionHistoryLimit` configurable by introducing an optional Parameter to `values.yaml`.

[prometheus-snmp-exporter] Extend workload config

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/servicemonitor.yaml
charts/prometheus-snmp-exporter/values.yaml

- In addition to fixed '$key: $value' metric relabelings, allow arbitrary relabel configs in order to support e.g. common label prefixes
@walker-tom @xiu @Miouge1 
Metric relabeling is currently limited to fixed label replacements .
In order to support arbitrary [relabel configs](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.RelabelConfig), a new value `serviceMonitor.additionalMetricsRelabelConfigs` resp. `serviceMonitor.params.additionalMetricsRelabelConfigs` has been introduced.

[prometheus-snmp-exporter] Extend metric relabels

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/servicemonitor.yaml

This PR modifies the serviceMonitor template in the Prometheus MySQL Exporter Helm chart to prevent the default endpoint with the '/metrics' path from being scraped by Prometheus when the multi-target feature is enabled.
The need for this modification arises from the desire to have more control over which endpoints are scraped by Prometheus when using the multi-target feature. Before this, when the multi-target feature was enabled, all endpoints within the MySQL Exporter pod were be scraped, including the '/metrics' endpoint, which may not be desired in certain scenarios.
With this change, users can ensure that only the specific endpoints they want to scrape are included, providing greater flexibility and control over monitoring configurations. This can help optimize resource usage and …

[prometheus-mysql-exporter] remove base `metrics` endpoint from serviceMonitor when Multitarget is enabled

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/_helpers.tpl
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
charts/prometheus-elasticsearch-exporter/values.yaml

…lobally
This PR allows to override the image registry for the `prometheus-elasticsearch-exporter` using a `global.imageRegistry` flag, which is a common way to override the registry when this chart is bundled as a sub-chart.
The PR is made such that it is backwards compatible with the current version of the chart so that only a patch increment is needed according to semver. 
@svenmueller @desaintmartin @zeritti

[prometheus-elasticsearch-exporter] Allow to override imageRegistry globally

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/kube-prometheus-stack/values.yaml

Removes api check for `ttlSecondsAfterFinished` as the job resource is already `batch/v1` so the check for `batch/v1alpha1` is redundent.
It also allows overriding the existing value.
- fixes #4500

[kube-prometheus-stack] remove job ttl api check

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.schema.json
charts/alertmanager/values.yaml

While using `extraArgs` is possible, `baseURL` is consistent with the
Prometheus chart and is more discoverable.
The template modification is taken from the prometheus chart.

[alertmanager] add baseURL value

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

When kubelet obtains properly signed serving certificate (signed by the Kubernetes CA), read the related [docs](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubelet-serving-certs) then we do not want to skip TLS verification.
This PR makes TLS verification in kubelet servicemonitor configurable 
- fixes #4491

[kube-prometheus-stack]  Make TLS verification in kubelet servicemonitor configurable 

---

charts/prometheus/Chart.lock
charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

[prometheus] bump dependencies

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

This matches the indentation of everything else in the file. Existing template indents the final yaml by 2 spaces too many
Before:
```yaml
exemplars:
maxSize: 100000
```
After:
```yaml
exemplars:
maxSize: 100000
```

[kube-prometheus-stack] Fix exemplar indentation for consistency

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl

Prometheus operator creates a configMap for thanos-ruler rulerfiles using the following pattern:
`thanos-ruler-{.Values.kube-prometheus-stack.thanosRuler.crname}-thanos-ruler-rulefiles-0`
This can lead to a configMap name with more than the allowed 63 characters, if `cleanPrometheusOperatorObjectNames == false`.
When `cleanPrometheusOperatorObjectNames == true`, the limit is respected already, because `kube-prometheus-stack.thanosRuler.crname == kube-prometheus-stack.fullname` and `kube-prometheus-stack.fullname` is already truncated to 26 characters.
This PR is subtracting 1 from 26 truncation of `kube-prometheus-stack.fullname` for `kube-prometheus-stack.thanosRuler.crname` evaluation. This will ensure that the thanos-ruler created resources will have names compliant with the 63 char …

[kube-prometheus-stack] ThanosRuler limit resource names up to 63 characters

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
charts/kube-prometheus-stack/values.yaml

[kube-prometheus-stack] add the possibility to specify objectSelector for admissionWebhooks objects

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
charts/kube-prometheus-stack/values.yaml

This PR separates the ServiceAccount creation from rbac creation, It aligns the `admission-webhooks/job-patch` with the rest of the chart.
- fixes #4553

[kube-prometheus-stack] separate prometheus-operator/admission-webhooks/job-patch from the rbac creation

---

charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/rules/rules.txt

This PR adds a rule for device temperature, which can prevent physical damage to devices. I was only alerted about the temperature of my disks as they failed SMART entirely at their 80c threshold.
N/A

[prometheus-smartctl-exporter] add rule for device temperature

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/service.yaml
charts/prometheus-pushgateway/templates/servicemonitor.yaml
charts/prometheus-pushgateway/values.yaml

This PR introduces the ability to customize the hard-coded port name `http` for the pushgateway service. This enhancement is necessary for environments where a Prometheus ServiceMonitor already exists on Kubernetes to scrape metrics from the services, using port name different than `http` (e.g. `metrics`).
None

[prometheus-pushgateway] allow overriding service port name

---

charts/prometheus-ipmi-exporter/Chart.yaml
charts/prometheus-ipmi-exporter/templates/configmap.yaml
charts/prometheus-ipmi-exporter/templates/deployment.yaml
charts/prometheus-ipmi-exporter/values.yaml

The way this currently works is that it builds a config file from values inlined via Helm, and this may need to include some sensitive information such as usernames and passwords that should be otherwise kept out of a repo in the cases where you're managing all of your cluster configuration via git.
This PR update the Chart to add an option to be able to reference a Secret instead.

[prometheus-ipmi-exporter] Optionally pull config from a Secret

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/templates/servicemonitor.yaml

Add the default `action: replace` to ServiceAccount. 
Otherwise ArgoCD shows constant diff on the ServiceAccount resource. See image

[prometheus-json-exporter] Add default action to ServiceMonitor

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/service.yaml
charts/prometheus-node-exporter/values.yaml

It permits to disable clusterIP which is not required to fetch metrics. On cluster with very huge node number always moving, it create a loadbalancer on each node using much memory and CPU due to watches from the service proxy
Permit to customize node-exporter ClusterIP field, permitting people to disable this ClusterIP which is always updating its backend when nodes are added created, generating much work on each {service,kube}-proxy pod on the cluster

[prometheus-node-exporter] permit to customize service clusterIP

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

[kube-prometheus-stack] Add support for --enable-feature for alertmanager

---

charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/templates/service.yaml
charts/prometheus-smartctl-exporter/values.yaml

add support for dual stack clusters

[prometheus-smartctl-exporter] add support for dual stack clusters

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/sts.yaml

Add explicitly `persistentVolumeClaim` API version and kind  - they are added by API server which causes a drift in argo cd state - and having them do not make any charm.

[prometheus] fix: Add apiVersion and kind to STS persistent volume claim

---

charts/prometheus-redis-exporter/Chart.yaml
charts/prometheus-redis-exporter/templates/_helpers.tpl
charts/prometheus-redis-exporter/templates/deployment.yaml

- updates app version from v1.58.0 to v1.61.0
- fixes version label when image tag override is set
- fixes deployment annotation indentation

[prometheus-redis-exporter] Update Redis Exporter to 1.61.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Following https://github.com/grafana/helm-charts/pull/3066 @jkroepke

[kube-prometheus-stack] add support for dual stack clusters to grafana

---

.github/workflows/lint-test.yaml

Ref #4622 
- fixes #
tested in https://github.com/prometheus-community/helm-charts/actions/runs/9718384972/job/26826154436?pr=4646

[CI] install Gateway API CRDs for chart tests

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

This PR will add scapeClasses to the kube-prometheus-stack. It's already a feature of prometheus operator
- fixes #4685

[kube-prometheus-stack] Add scrapeClasses to prometheus resource (#4685)

---

.github/workflows/lint-test.yaml

In the last years, I've come across a lot of wrongly defined ServiceMonitors, PrometheusRules, etc, either from myself or other people.
In other Charts repositories like Kubernetes Dashboard, I install Prometheus Operator CRDs in order to have related values correctly tested before merging (usually with an additional `ci/` file).
Here, we are in deeper trouble: we do _not_ want to install CRDs if we are installing charts with... CRDs (otherwise, we will no longer properly test those important charts).
Here is a proposal to conditionally install CRDs.
Pros: easily test Prometheus Operator related resources and improve quality of charts (and ease reviews)
Cons: hardcoded list of charts to avoid.
What do you think?
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

chore(ci): install prometheus operator CRDs in order to be able to test ServiceMonitors / PrometheusRules / etc validity in charts.

---

charts/prometheus-mysql-exporter/Chart.yaml
charts/prometheus-mysql-exporter/templates/deployment.yaml

[prometheus-mysql-exporter] fix incorrect indentation in env variables

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

As in previous PRs, e.g. #3811 or #4696, I would like to enable users of the `kube-state-metrics` chart to optionally configure a `startupProbe` in the `Deployment`, if external circumstances require it.
As requested in the PR template, CC'ing @tariq1890 @mrueg @dotdc
The PRs I looked at as inspiration for this change had different approaches for making the `startupProbe` configurable, e.g. just passing on the entire value block, or configuring defaults for most fields vs a simple `startupProbe: {}`. I opted to keep it similar to the `readinessProbe` and `livenessProbe` already available in this chart, for consistency.
First PR here, happy about any feedback regarding the change itself or the PR process in general.

[kube-state-metrics] Allow configuration of startupProbe

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

Just after #4740 got merged, I realized a small mistake I made. `kube-state-metrics` actually recommends to use the `/healthz` endpoint for the `startupProbe`, not the `/livez` one (see [kube-state-metrics healthcheck endpoints docs](https://github.com/kubernetes/kube-state-metrics/?tab=readme-ov-file#healthcheck-endpoints)).
Me not reading the documentation properly.
Sorry for the extra work!

[kube-state-metrics] Align probing endpoints with recommendations

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/hack/update_mixins.sh
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/alertmanager-overview.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/apiserver.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/cluster-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/grafana-overview.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-multicluster.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/kubelet.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes-darwin.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/pod-total.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/proxy.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/scheduler.yaml
charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml

https://github.com/kubernetes/kube-state-metrics/pull/2388 introduced a syntax error. The syntax error has an effect to our pipeline.
I take a look closer into this, since we are using fixed shasums for dependencies but somewhere else, floating version are used.
It turns out that the lockfile for Jsonnet dependencies in [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnetfile.lock.json) is located in the repository root. To respect the lockfile, I had to change the update mixin configuration to run the generation from the repository root.
I also fixed the update script for macOS.
- fixes #

[kube-prometheus-stack] Fix mixins generation and fix update on mac

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

Adds newline to pod annotation indent, which fixes the chart rendering when supplying more than 1 pod annotation. When more than 1 annotation is supplied to indent, helm fails to render the chart with an error:
```
Error: YAML parse error on kube-state-metrics/templates/deployment.yaml: error converting YAML to JSON: yaml: line 54: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 54: did not find expected key
YAML parse error on kube-state-metrics/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources …
```

[kube-state-metrics] fix: nindent ksm pod annotations

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/sts.yaml

A simple change to remove a tab character at the end of the `apiVersion` property for `volumeClaimTemplates` for the StatefulSets template. I found this to be an issue when querying the Helm release manifest for Prometheus as it breaks YAML parsing to have an unexpected tab character.
- fixes #

[prometheus] Removing tab character on apiVersion of volumeClaimTemplates for StatefulSets

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
charts/kube-prometheus-stack/values.yaml

This parameter enables configuration of datasource pruning / auto deletion for Grafana through the Helm chart, functionality introduced in Grafana v11.1 (https://github.com/grafana/grafana/pull/83034)
- fixes #

[kube-prometheus-stack] feat: configure datasource auto-deletion

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

Add readiness and liveness probe for the prometheus-operator deployment for the kube-prometheus-stack helm chart.

[kube-prometheus-stack]: Add probes for prometheus-operator

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml

We're moving our infra charts from Terraform to ArgoCD/ApplicationSets and we need the ability to template
some values with an environment name. In this case, we need to asign some tolerations and nodeSelector for Karpernter.

[prometheus-elasticsearch-exporter] Add tpl to nodeSelector and tolerations

---

charts/prometheus-windows-exporter/Chart.yaml
charts/prometheus-windows-exporter/templates/daemonset.yaml
charts/prometheus-windows-exporter/values.yaml

This PR sets the HTTP path for the readiness and liveness probes for the Windows Exporter daemonset to `/health` and makes it configurable. It is currently set to `/` which returns 404 for many of my windows nodes on both AKS and EKS clusters. Likely because that path [was removed recently](https://github.com/prometheus-community/windows_exporter/commit/b977c8484b6341f706943cc1fc03247e5e836e99). When I manually edit the path to choose `/health` the probes start working again.
- fixes #4790

[prometheus-windows-exporter] Set the correct path for readiness and liveness probes

---

charts/prometheus-operator-crds/Chart.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml

upgrade the CRDs after https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-62.0.0

[prometheus-operator-crds] bump to 0.76.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
charts/kube-prometheus-stack/values.yaml

This PR introduces a new value which offers consumers to configure the fsTypes for all nodefs alerts.
The default values of fsTypeSelector is `fstype!=""`, however the default is overwritten in [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/8c0479c02d05f479fafdcce56ad09ea7a264998a/config.libsonnet#L97) to `fstype=~"ext[234]|btrfs|xfs|zfs"`, but not propagated to kube-prometheus. 
This distributed jsonnet concept with different repo is crazy.
- fixes #4800

[kube-state-metrics] Make fsType selector configurable

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
charts/kube-prometheus-stack/values.yaml

This PR adds functionality for operators to define a [ThanosRulerWebSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosrulerwebspec) to configure the builtin webserver of Thanos Rule. This functionality is the same as the existing Prometheus and Alertmanager `web` declarations.
It has been defined in the operator since the following PR in december: https://github.com/prometheus-operator/prometheus-operator/issues/6157

[kube-prometheus-stack] Adds web spec to `thanosRulerSpec`

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml

When using this chart as dependency, you may want to use alias. 
This alias may use camelCase as this is a common convention in values.yaml.  
This will result in an error as expected name must conform to RFC 1123.
```yaml
dependencies:
- name: prometheus-postgres-exporter
alias: postgresExporter
repository: "https://prometheus-community.github.io/helm-charts"
version: 5.3.0
condition: postgresExporter.enabled
```
```yaml
postgresExporter:
enabled: true
nameOverride: "prometheus-postgres-exporter"
image: ...
```
Results in
```yaml
metadata:
name: release-name-prometheus-postgres-exporter
labels:
chart: postgresExporter-5.3.0
app: prometheus-postgres-exporter
spec:
template:
spec:
containers:
- name: postgresExporter
```
None, this could be converted to an issue, but the fix seemed …

[prometheus-postgres-exporter] Allow override of container name

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Since release 4.38 of the prometheus-node-exporter chart, `podLabels` does not get attached to all the chart's resources. Instead, it gets attached to pods only. However, the default service monitor for node exporter expects label `jobLabel` at the node exporter service which it does not find any longer and therefore, `job` gets set to a default value instead of the expected `node-exporter`.
This PR upgrades the chart dependency to 4.39 which allows setting service labels and sets label `jobLabel=node-exporter` to the service. 
- fixes #4801
- fixes #4810

[kube-prometheus-stack] Bump node exporter dependency correcting service labels

---

charts/kube-prometheus-stack/Chart.yaml

PR will bump the Grafana deps to 8.5.* version, which is currently the latest version available in the [Grafana Helm Chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/Chart.yaml#L3)
- fixes #
This version fixes an interesting bug that lies in the 8.4.* version, where the grafana adds `Kind=server` as the filter to the traceql query when a trace is selected
refer: https://github.com/grafana/grafana/issues/88635

[kube-prometheus-stack] Bump grafana deps to 8.5.*

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.schema.json
charts/alertmanager/values.yaml

This PR lets users add additional Pod configs such as *dnsPolicy* and *hostNetwork*
- fixes #

[alertmanager] Variable to add extra Pod Configurations

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/serviceaccount.yaml

**What this PR does / why we need it**
We're moving our infra charts from Terraform to ArgoCD/ApplicationSets and we need the ability to template
some values with an environment name, accountID and etc ... 
In this case, we need the ability to template the service account and inject account id and environment name to the IAM role ARN

[kube-prometheus-stack] add tpl to prometheus service account

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

**What this PR does / why we need it**
We're moving our infra charts from Terraform to ArgoCD/ApplicationSets and we need the ability to template
`nodeSelector` and `tolerations`

[kube-state-metrics] add tpl to deployment template

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/ci/default-values.yaml
charts/prometheus-json-exporter/templates/deployment.yaml
charts/prometheus-json-exporter/values.yaml

json-exporter, make liveness and readiness probes fully configurable
This changes makes both probes fully configurable, e.g. you are now able to override timeoutSeconds and other settings.

[prometheus-json-exporter] make liveness and readiness probes fully configurable

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

- fixes #4897
Based one upstream https://github.com/prometheus-operator/prometheus-operator/pull/6882

[kube-prometheus-stack] support kubelet endpoint slices

---

charts/alertmanager-snmp-notifier/Chart.yaml
charts/alertmanager-snmp-notifier/README.md

It keeps the helm charts up to date with latest version of SNMP-notifier. It includes new options as well as security fixes.
No fix, just a version update.

[alertmanager-snmp-notifier] bump to 1.6.0

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/ci/networkpolicy-values.yaml
charts/prometheus-node-exporter/templates/networkpolicy.yaml
charts/prometheus-node-exporter/values.yaml

When enabled, the current NetworkPolicy blocks all egress traffic, and allows all ingress traffic destined for `.Values.service.port`. 
This PR allows for specifying a custom ingress NetworkPolicy for the prometheus-node-exporter. For example, we may want to restrict ingress traffic to only pods with a particular label.
```
networkPolicy:
enabled: true
ingress:
- from:
- podSelector:
matchLabels:
app.kubernetes.io/instance: foo
```
@gianrubio 
@zanhsieh
@zeritti

[prometheus-node-exporter] Allow for custom ingress NetworkPolicy

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/unittests/prometheus/scrape_config_namespace_selector_test.yaml
charts/kube-prometheus-stack/unittests/prometheus/scrape_config_selector_test.yaml
charts/kube-prometheus-stack/values.yaml

Running the latest prom-stack versions on legacy OpenShift clusters with no influence on the preinstalled CRDs results in errors such as this:
```
failed to create typed patch object (..): .spec.scrapeConfigNamespaceSelector: field not declared in schema
```
This PR provides a workaround using this values.yaml:
```
prometheus:
prometheusSpec:
scrapeConfigNamespaceSelector: null
scrapeConfigSelectorNilUsesHelmValues: null
scrapeConfigSelector: null
```
Yes, this is no ideal solution, but that seems to be what the enterprise-world  requires 😐️
At runtime, the operator yields some warnings about the missing fields, but apparently everything else works.
As discussed with @jkroepke I'm launching another try to include this feature :slightly_smiling_face: 
This is the same functionality as in …

[kube-prometheus-stack] Add downward compat for Prom CRD 

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
charts/prometheus-postgres-exporter/values.yaml

The following patch extends the serviceMonitor resource to allow users to apply a custom TLS configuration for TLS authentication and encryption between prometheus and the postgres-exporter. Furthermore, the protocol scheme can now be customized. The default is `http` but needs to be changed to `https`, when TLS authentication/encryption should be applied.
A user-specific TLS configuration can be applied as follows.
```yaml
enabled: true
scheme: https
tlsConfig:
caFile: /etc/prometheus/tls/ca/ca.crt
certFile: /etc/prometheus/tls/app2app/tls.crt
keyFile: /etc/prometheus/tls/app2app/tls.key
insecureSkipVerify: false
serverName: prometheus-postgres-exporter
```
Important Note: The `serverName` attribute must correspond to the CommonName or a Subject Alternative Name (SAN) of …

[prometheus-postgres-exporter] support custom TLS config

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

There is a discrepancy between the podAntiAffinity value and what is written in the comments of the chart.  
I think that "soft" as a podAntiAffinity is a reasonable vaule (and the comments say that is the default value).  
Unfortunately, looking at the values, it does not appear that is the actual default value.  
This PR adds it as a default
N/A

[kube-prometheus-stack] sets podAntiAffinity default to soft

---

charts/prometheus-sql-exporter/Chart.yaml
charts/prometheus-sql-exporter/templates/NOTES.txt
charts/prometheus-sql-exporter/templates/deployment.yaml
charts/prometheus-sql-exporter/templates/networkpolicy.yaml
charts/prometheus-sql-exporter/templates/pdb.yaml
charts/prometheus-sql-exporter/templates/prometheusrule.yaml
charts/prometheus-sql-exporter/templates/role.yaml
charts/prometheus-sql-exporter/templates/rolebinding.yaml
charts/prometheus-sql-exporter/templates/service.yaml
charts/prometheus-sql-exporter/templates/serviceaccount.yaml
charts/prometheus-sql-exporter/templates/servicemonitor.yaml

Instead of duplicating the labels & matchLabels in each file we are not relying on include.
N/A
None

[prometheus-sql-exporter] Fix labels/matchLabels by using include instead of duplicating declaration in each file

---

charts/prometheus/Chart.yaml
charts/prometheus/ci/12-ingress-values.yaml
charts/prometheus/templates/NOTES.txt
charts/prometheus/templates/ingress.yaml
charts/prometheus/values.yaml

following the same principle as in [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/ingress.yaml) i´ve added the possibility to use tpl within the ingress resource

[prometheus] add tpl to ingress

---

.github/workflows/lint-test.yaml
charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml
charts/kube-prometheus-stack/ci/05-alertmanager-ingress-host-with-wildcard-values.yaml
charts/kube-prometheus-stack/ci/05-ingress-and-gateway-routes-values.yaml
charts/kube-prometheus-stack/templates/prometheus/ingress.yaml
charts/kube-prometheus-stack/templates/prometheus/route.yaml
charts/kube-prometheus-stack/values.yaml

The current template is just an approach. Once finalized, we add it anywhere in the chart.
Ref: #4622 
- fixes #

[kube-prometheus-stack] Implement Gateway API

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/servicemonitor.yaml
charts/prometheus-node-exporter/values.yaml

This PR will add support of targetLabels in serviceMonitor to node-exporter.
- fixes #4966 for node-exporter

[prometheus-node-exporter] targetLabels support for node-exporter

---

charts/prometheus-smartctl-exporter/Chart.yaml
charts/prometheus-smartctl-exporter/templates/daemonset.yaml
charts/prometheus-smartctl-exporter/values.yaml

I can't see any reason that this exporter requires `hostNetwork: true`. It should only be looking at local devices. This also means that issues with port usage can occur when also using `node-exporter` which does need `hostNetwork`. I think it'd be best to just just remove the line as this PR does.
- fixes #4963

[prometheus-smartctl-exporter] Don't use `hostNetwork`

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/ci/03-non-defaults-values.yaml
charts/kube-prometheus-stack/templates/exporters/core-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-dns/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kube-scheduler/servicemonitor.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
charts/kube-prometheus-stack/values.yaml

This PR will add the support for targetLabels for all exporters in kube-prometheus-stack
- fixes #4966 kube-prometheus-stack exporters part

[kube-prometheus-stack] - targetLabels for all exporters

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
charts/kube-prometheus-stack/hack/sync_prometheus_rules.py

[kube-prometheus-stack] bump prometheus-operator to 0.78.1

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

Fix operator version in "From 65.x to 66.x"
Version was bumped in #4979, but wrong version was written in Readme.

[kube-prometheus-stack] Fix README.md

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml

[kube-prometheus-stack] bump to 0.78.2

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/values.yaml

Stop setting `livenessProbe.initialDelaySeconds` and `readinessProbe.initialDelaySeconds` to the Kubernetes defaults of `0` in `values.yaml`
Setting these values to the Kubernetes defaults causes permanent diffs in GitOps tooling, e.g. ArgoCD (see https://github.com/argoproj/argo-cd/issues/8833 for an example) as defaults are pruned when reading back the resource from the API.

[prometheus-postgres-exporter] Don't set initialDelaySeconds to the default values

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/pdb.yaml
charts/prometheus/values.yaml

- fixes:
- FIX to PDB template. Here we are seeing maxUnavailable defaulting to 1. If we try to only spec minAvailable, maxUnavailable is templating due to default value. K8s does not allow both of these specs. 
- This PR sees a change to allow specific values without issue.

[prometheus] pdb template values

---

charts/prometheus/Chart.yaml
charts/prometheus/README.md
charts/prometheus/values.yaml

[prometheus] bump prometheus to 3.0.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Declare the attachMetadata configuration in the `values.yaml` of kube-prometheus-stack, so that do not have to look for it in [node-exporter helm-chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L204).
- fixes #

[kube-prometheus-stack] Add node-exporter attachMetadata configuration

---

charts/jiralert/Chart.yaml
charts/jiralert/templates/servicemonitor.yaml

Up to now the field `serviceMonitor.additionalLabels` was present in the values.yaml but did not get used in the servicemonitor template.

[jiralert] Enable usage of serviceMonitor.additionalLabels

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml

fix bad rendering when serviceMonitor.enabled=true without serviceMonitor.multipleTarget.enabled
- fixes #

[prometheus-postgresql-exporter] fix template

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

This PR enables `trackTimestampsStaleness` for the cadvisor  path to avoid stale Metrics provided by the cadvisor. 
- fixes # 
@SuperQ  suggested this and might want to add comments. 
slack conversation: https://cloud-native.slack.com/archives/C167KFM6C/p1733917170837469

[kube-prometheus-stack] feature(kubelet): Add trackTimestampsStaleness

---

charts/prometheus-node-exporter/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/values.yaml

This PR prevents node-exporter from being scheduled on fargate
- fixes #4735
If my understanding is correct, then for people that have already added this nodeAffinity this would not be a breaking change, it would simply be redundant - but this I am not completely sure about.

[prometheus-node-exporter] prevent node exporter from being scheduled on fargate or virtual nodes

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
charts/prometheus-operator-crds/Chart.yaml

Signed-off-by: AvivGuiser <avivguiser@gmail.com>
- fixes #

[kube-prometheus-stack]: bump to 0.79.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml

Refactor the Kubelet ServiceMonitor with a helper template for handling http/https schema. This will reduce the chance of copy-pasta mistakes when updating the different kubelet monitoring endpoints.
* Define `kube-prometheus-stack.kubelet.scheme` for the port/schema.
* Define `kube-prometheus-stack.kubelet.authConfig` for TLS access controls.
- none

[kube-prometheus-stack] Chore: Improve kubelet ServiceMonitor

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/values.yaml

operator v0.79.0 default prom version is not 3.0.1
- fixes #

[kube-prometheus-stack] bump prom to 3.0.1 to align with upstream default

---

charts/kube-prometheus-stack/Chart.yaml

Fixes [#3487 "Error: Failed to launch the browser process!\nchrome_crashpad_handler: --database is required" with "image-renderer"`](https://github.com/grafana/helm-charts/pull/3487)

[kube-prometheus-stack] Upgrade Grafana to 8.8.*

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
charts/kube-prometheus-stack/values.yaml

Improve the collection of cAdvisor metrics by adjusting the scrape interval to match the kubelet hardcoded minimum housekeeping interval.
* Set the cAdvisor, and resource, interval to 10s by default.
* Use the user configured a kubelet metrics interval if not default.
* Enforce honorTimestamps for cAdvisor and resource if timetamp staleness is enabled.
- fixes #

[kube-prometheus-stack] Feat: Improve cAdvisor metrics scrape

---

charts/prometheus-operator-crds/Chart.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml

Updates to the latest prometheus operator CRDs (0.79.1).
N/A
CRDs copied in from prometheus-operator, straightforward changes.

[prometheus-operator-crds] bump to 0.79.1

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml

Updates to the latest prometheus operator CRDs (0.79.1) for kube-prometheus-stack.
N/A
CRDs copied in from prometheus-operator, straightforward changes.

[kube-prometheus-stack]: bump to 0.79.1

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml

Updates to the latest prometheus operator (0.79.2) for kube-prometheus-stack.
N/A
None.

[kube-prometheus-stack]: bump to 0.79.2

---

charts/prometheus-operator-crds/Chart.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml

Updates to the latest prometheus operator (0.79.2).
N/A
None

[prometheus-operator-crds] bump to 0.79.2

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
charts/prometheus-postgres-exporter/values.yaml

This PR introduces the ability to **select the database to connect to in a multi-target configuration** and have the servicemonitor correctly scrape databases that do not match username.
The multi-target configuration section is completed with the new optional parameter `databaseName` as follows:
```yaml
enabled: true
multipleTarget:
enabled: true
targets:
- endpoint: pg01.local
name: pg01
- endpoint: pg02.local
name: pg02
databaseName: mydb     # <== New optional parameter for selecting database
```
This configuration produces the following servicemonitor resource:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
endpoints:
- metricRelabelings:
params:
auth_module:
- client.pg01
target:
- pg01.local:5432
path: /probe
port: http
- metricRelabelings: …
```

[prometheus-postgres-exporter] Use non default database in multi-targets

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/values.yaml

This PR exposes persistentVolumeClaimRetentionPolicy field of Alertmanager CRD resource. PersistentVolumeClaimRetentionPolicy is a feature introduced for StatefulSets (by default in K8s 1.27.0+), this feature lets us decide whether the StatefulSet should delete or retain it's corresponding PVC's it is deleted or scaled. It is particularly useful in environments where stale volumes can grow in amount, causing additional costs or clutter in general. The CRD field itself was added to Prometheus operator with https://github.com/prometheus-operator/prometheus-operator/pull/7183 and released with https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.79.0, however not yet exposed in kube-prometheus-stack.

[kube-prometheus-stack] Add alertmanager persistentVolumeClaimRetentionPolicy

---

.github/workflows/lint-test.yaml

Trying python 3.11 to fix error in lint-test workflow:
```
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
- fixes #5082

[ci] fix python version for lint-test

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/NOTES.txt

By default, `kubectl port-forward` command in PostgreSQL exporter Helm chart doesn't include the namespace, which doesn't provide consistent experience for default and non-default namespaces installation

[prometheus-postgres-exporter] add namespace by default to the kubectl port-forward command 

---

charts/prometheus-mongodb-exporter/Chart.yaml
charts/prometheus-mongodb-exporter/ci/podsecuritycontext-values.yaml
charts/prometheus-mongodb-exporter/templates/deployment.yaml
charts/prometheus-mongodb-exporter/values.yaml

Allow to configure pod security context
Add value _**podSecurityContext**_ as it's present on most of other chart as _prometheus-postgres-exporter_ and _prometheus-elasticsearch-exporter_
Don't set default value to avoid breaking change.
@steven-sheehy
@zeritti

[prometheus-mongodb-exporter] Allow to configure pod security context

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/templates/secret.yaml

Connection credentials should be stored securely using secrets. Right now, the chart allows to provide your own secret, but if the credentials are given as values to the chart, they are exposed in the deployment env variables.
This PR adds a new secret, that will be created only if the user or password is provided and if the existing user/password secret is not given.

[prometheus-rabbitmq-exporter] Create secret to store credentials when provided

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml
charts/kube-state-metrics/values.yaml

KSM support additional environment, in my case, i want to enable some client-go features with environment.
tested:
set env with normal
```
helm upgrade ksm .  --set "env[0].name=KUBE_FEATURE_ClientsAllowCBOR"  --set "env[1].name=KUBE_FEATURE_ClientsPreferCBOR" --set "env[0].value='true'" --set "env[1].value='true'" -i
```
and got the environment:
```yaml
Environment:
KUBE_FEATURE_ClientsAllowCBOR:   'true'
KUBE_FEATURE_ClientsPreferCBOR:  'true'
```
set env with autosharding.
```
helm upgrade ksm . --set "autosharding.enabled='true'" --set "env[0].name=KUBE_FEATURE_ClientsAllowCBOR"  --set "env[1].name=KUBE_FEATURE_ClientsPreferCBOR" --set "env[0].value='true'" --set "env[1].value='true'" -i
```
and got the environment:
```yaml
Environment:
POD_NAME: …
```

[kube-state-metrics] add additional environment variables support.

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/servicemonitors.yaml
charts/kube-prometheus-stack/values.yaml

The current kube-prometheus-stack does not allow relabeling and metricRelabeling for additional service monitors. The issue is that, these values are not placed under endpoint and we get the following error.
```bash
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec): unknown field "relabelings" in com.coreos.monitoring.v1.ServiceMonitor.spec
```
The MR moves metricRelabeling and relabeling under endpoint. To test the helm chart one can use the following values.
```yaml
prometheus:
additionalServiceMonitors:
- name: test                          
selector:
matchLabels:
app.kubernetes.io/name: test 
namespaceSelector:
matchNames:
- test
endpoints:
- path: /metrics
port: http …
```

[prometheus-kube-stack] Fix relabeling and metricRelabeling for additional serviceMonitor

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/values.yaml

Update API metric relablings for Prometheus 3.0
Prometheus 3.0 normalizes bucket float values to include `.0` for
integers. Update the
* Add additional noisy apiserver metrics to the bucket filter.
* `apiserver_request_sli_duration_seconds_bucket`
* `apiserver_request_slo_duration_seconds_bucket`
* `etcd_request_duration_seconds_bucket`
* Improve regex match to explicitly match `.`.
Improve cAdvisor metric filtering
Add new metricRelablings to the cAdvisor filter to reduce
default cardinality by eliminating noisy metrics.
* Drop container_memory_failures_total{scope="hierarchy"} metrics, we only need the container scope.
* Drop container_network_... metrics that match various interfaces that correspond to CNI and similar interfaces.
Add kubelet default metricRelabings
Reduce bucket …

[kube-prometheus-stack] Improve various metric relabelings

---

charts/prometheus-windows-exporter/Chart.yaml
charts/prometheus-windows-exporter/templates/service.yaml
charts/prometheus-windows-exporter/values.yaml

This change moves the `prometheus.io/scrape` service annotation into the values.yaml file where it can be disabled if not desired. 
Also add comments in the values.yaml file for the service section.
All of these changes make this match how things look and work in the Node Exporter helm chart.
- fixes #5129 
My testing to ensure that things behave correctly:
```bash
helm template test . | yq 'select(.kind == "Service") | .metadata.annotations'
helm template test . --set 'service.annotations.extra=1234' | yq 'select(.kind == "Service") | .metadata.annotations'
helm template test . --set 'service.annotations.prometheus\.io/scrape=null' | yq 'select(.kind == "Service") | .metadata.annotations'
helm template test . --set 'prometheus.monitor.enabled=true' | yq 'select(.kind == "Service") | …
```

[prometheus-windows-exporter] Extract the prometheus.io/scrape service annotation

---

charts/prometheus-yet-another-cloudwatch-exporter/Chart.yaml
charts/prometheus-yet-another-cloudwatch-exporter/README.md

- fixes error
```
Error: chart "prometheus-yet-another-cloudwatch-exporter" matching 0.39.0 not found in prometheus-community index. (try 'helm repo update'): no chart name found
```
read me was incorrect

[prometheus-yet-another-cloudwatch-exporter] fix yace chart name in readme

---

charts/prometheus-yet-another-cloudwatch-exporter/Chart.yaml
charts/prometheus-yet-another-cloudwatch-exporter/README.md

see: https://github.com/prometheus-community/helm-charts/pull/5165#issuecomment-2590325789

[prometheus-yet-another-cloudwatch-exporter] consistent naming of chart (make it match directory)

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

I was confused on initial install of  `kube-prometheus-stack` why I was not successfully getting a Prometheus Adapter set up, and saw there was an open issue https://github.com/prometheus-community/helm-charts/issues/4741 that shared my confusion. This PR just clarifies that going to [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) and seeing the component list will not be _exactly_ the same behavior as a fresh install of this chart. @jkroepke I saw you on the initial issue thread, so I figured I should ping you!
- fixes #4741

[kube-prometheus-stack] Add comment about excluded components from kube-prometheus

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

In kube-prometheus-stack we can't add `tsdb.outOfOrderTimeWindows` spec for a PrometheusAgent CR.
According to the API specs : `tsdb.outOfOrderTimeWindows` is available for PrometheusAgent >= 2.54.0
- fixes #

[kube-prometheus-stack]  fix: tsdb.outOfOrderTimeWindows is also available for PrometheusAgent

---

.github/workflows/renovate-bump-chart-version.yaml
renovate.json

xref: #4292 
This PR continues the integration of Renovate into this repository. Unfortunately, Renovate cannot automatically bump the Helm chart version for changes made in the values files.
To address this, a support workflow has been added, which uses GitHub Actions to bump the version.
Additionally, the renovate.json file is configured to group version bumps by chart directory. Custom managers have been added from our internal company repository. These custom managers allow developers to enable automated dependency updates by adding Renovate annotations, using code comments. The regex patterns include common use cases, such as the following example:
https://github.com/prometheus-community/helm-charts/blob/7c7bc2e63639ff9cfb8ebae1903efeb4037b3923/charts/kube-prometheus-stack/values.yaml …

[ci] add github workflow to the bump version of an Chart version

---

.github/workflows/release.yaml

Should solve the following error https://github.com/prometheus-community/helm-charts/actions/runs/12834237724/job/35791102326 mention by https://github.com/prometheus-community/helm-charts/pull/5190#issuecomment-2599073566
The fix is documented here: https://github.com/helm/chart-releaser/blob/cb3ed7107e0adfb5eae170bfc01bf61ee811e87a/README.md#common-error-messages
- fixes #

[ci] add skip_existing to chart-releaser

---

.editorconfig
.github/CODEOWNERS
.github/workflows/check-codeowners.yaml
scripts/check-codeowners.sh

* Fixup issue link to point to correct location.
* Remove `@jkroepke` from manual listing now that they are a member of `helm-chart-admins`.
* Refactor `scripts/check-codeowners.sh` to simplify it.
- fixes #

[ci] Update codeowners script

---

.github/linters/ct.yaml

In https://github.com/prometheus-community/helm-charts/pull/5190, we decided that the maintainer's name can be freely defined. The maintainer's URL contains a link to the corresponding GitHub account. By default, helm-chart-testing checks if the maintainer's name matches a GitHub handle. This validation conflicts with the new process and should be deactivated.
Ref: https://github.com/prometheus-community/helm-charts/actions/runs/12877122925/job/35901109795?pr=5221#step:7:43
- fixes #
An upstream issue has been created: https://github.com/helm/chart-testing/issues/708
I also re-order and sort the yaml keys.

[ci] disable validate-maintainers in helm-chart-testing

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

The current image have security vulnerabilities.
- fixes #4550
Take from https://github.com/kubernetes/ingress-nginx/pull/12693/files
Note: it seems the version is equal, however this just a coincidence. The current image is years old while the 1.5.1 seems update to date.

[kube-prometheus-stack] Update ingress-nginx/kube-webhook-certgen to v1.5.1

---

renovate.json

Detect images dependencies like this in values.yaml:
https://github.com/prometheus-community/helm-charts/blob/3a15cac83487322f76ed07061fe1254e5f457e5c/charts/kube-prometheus-stack/values.yaml#L2625-L2628
- fixes #
Tested: https://regex101.com/r/9R46tF/1

[ci] Extend image detection for values.yaml

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/README.md
charts/prometheus-rabbitmq-exporter/ci/default-values.yaml
charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
charts/prometheus-rabbitmq-exporter/values.yaml

[prometheus-rabbitmq-exporter] upgrade to 1.0.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md

It makes the link between kube-prometheus-stack's appVersion, CRDs, and prometheus-operator's version explicit.
In the context of [[kube-prometheus-stack] CRDs version issue for 67.9.0](https://github.com/prometheus-community/helm-charts/issues/5127), this would have made clear that a semver hiccup occured (appVersion was bumped).
- fixes #5127 
Thanks to @jkroepke for the inputs.
I assumed that the version bump rules also cover documentation.

[kube-prometheus-stack] (docs) link between appVersion CRDs Prometheus-Operator

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

syntax error, causing warning "exemplars is a table" when you set exemplars
none
feel like this is too small to bump the chart version, so I skip that step

[kube-prometheus-stack] fix: exemplars should be obj

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Comment should be right next to the value
NA

[kube-prometheus-stack] fix: incorrect comment value mapping

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

Chart is set up to install the service monitor for kube-state-metrics so it's easy to duplicate metrics if scraping is not disabled.
- fixes #2181
@andrewgkew, @gianrubio, @gkarthiks, @GMartinez-Sisti, @jkroepke, @scottrigby, @Xtigyro, @QuentinBisson
Not sure about what level of version bump this should be, just went with patch release, happy to take advisement on this though. I know it's fixing a closed issue, but it takes a bit of knowledge and experience to track down why this happens and fix it so felt it was worth a PR.

[kube-prometheus-stack] Disable kube-state-metrics service scraping  by default

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

This PR adds a configurable value of revisionHistoryLimit to the blackbox-exporter and initializes it at the default value of 10.
This will enable users of this helm chart to easily decrease the number of retained replicaSets to fit into smaller clusters or environments or just to get a better overview. 
- fixes #5227

[prometheus-blackbox-exporter] feat: add revisionHistoryLimit as a value to blackbox-exporter helmchart

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/service.yaml
charts/prometheus/values.yaml

This PR adds support to the Prometheus chart to set "externalTrafficPolicy" option to server's service.
- fixes #

 [prometheus] Add "externalTrafficPolicy" to server's service

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/NOTES.txt
charts/kube-prometheus-stack/values.yaml

- fixes #5267 
- Enhances the chart with additional Grafana connection details

[kube-prometheus-stack] update chart information about how to use newly installed chart

---

charts/prometheus-operator-admission-webhook/Chart.yaml
charts/prometheus-operator-admission-webhook/values.schema.json
charts/prometheus-operator-admission-webhook/values.yaml

issuerRef was failing schema validation . It was expecting a string instead of an object
changes the type from string to object in the values.schema.json
```yaml
certManager:
enabled: true
issuerRef:
name: rootca-for-sandbox-issuer
kind: ClusterIssuer
rootCert: {}
webhookCert: {}
```
```bash
shivansh.singla@NRHN958E MSYS ~/Desktop/terraform-req/prometheus (main)
$ helm upgrade --install prometheus-operator-admission-webhook prometheus-community/prometheus-operator-admission-webhook --values webhook-values.yaml
coalesce.go:289: warning: destination for prometheus-operator-admission-webhook.certManager.issuerRef is a table. Ignoring non-table value ()
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s): …
```

[prometheus-operator-admission-webhook] issuerRef needs to be an object

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/charts/crds/templates/upgrade/job.yaml

Many custom Kubernetes distros add +<custom-distro-name> to the end of the Kubernetes version. This removes the + so we get the correct version of the kubectl container.
- fixes #5291

[kube-prometheus-stack] Remove Plus Character From Upgrade Job for Custom Distros

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/charts/crds/templates/upgrade/job.yaml

Fixes issue where custom Kubernetes distros append special versions to the upgrade job. Distros are not consistent with their naming conventions. Some add a +<distro-name> while others add a -<distro-name>. This PR extracts the Kubernetes version from the custom distro name using a Regex expression. According to Kubernetes versioning docs, released versions are always x.y.z. See
https://kubernetes.io/releases/version-skew-policy/
- fixes #5291

[kube-prometheus-stack] Fix Kubectl Version #2

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/route.yaml
charts/kube-prometheus-stack/templates/prometheus/route.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/route.yaml
charts/kube-prometheus-stack/values.yaml

Bugfixing an issue by creating multiple routes for alertmanager, prometheus and thanosruler. In this case the linebreak does not work and the outcome is not a valid resource.
Adding new feature to create a route for https redirect see also https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#http-to-https-redirects
No open issue found that points to this bug and feature
@andrewgkew  @gianrubio @gkarthiks @GMartinez-Sisti @jkroepke @scottrigby @Xtigyro @QuentinBisson

kube-prometheus-stack bugfix wrong line break and add https redirect route

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/charts/crds/unittests/rendering_test.yaml
charts/kube-prometheus-stack/charts/crds/values.yaml

The kube-prometheus-stack CRD subchart fails to render on the current version with
```
Error: template: crds/templates/upgrade/serviceaccount.yaml:1:18: executing "crds/templates/upgrade/serviceaccount.yaml" at <.Values.upgradeJob.enabled>: nil pointer evaluating interface {}.enabled
```
This is because of the preview upgradejob feature that was added:
> This feature is in preview, off by default and may change in the future.
The CRD subchart has no default `values.yaml` and sets no defaults itself for statements like
```
{{- if .Values.upgradeJob.enabled }}
```
Which produces the error above.
This PR adds a default values.yaml ensuring rendering and a unittest to prevent regression.
I understand the intent might not be for people to install this CRD chart directly, but instead render it …

[kube-prometheus-stack] Fix: Add default values to subchart to allow rendering

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/templates/deployment.yaml

- Remove templating code which was adding `commonLabels` twice to the deployment 
- fixes #5328

[prometheus-elasticsearch-exporter] Fix duplicate commonLabels in deployment.yaml

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml

Fixes the scope of the `.Values.prometheusOperator.tls.enabled` condition introduced in #206. The current scoping prevents the use of `extraArgs` and `lifecycle` when not enabling TLS.
While this is a bug fix/patch, this will change the behavior of the deployment for any users who may have been setting the `extraArgs` and `lifecycle` values without enabling TLS. Let me know if I should bump the minor version instead of the patch version.

[kube-prometheus-stack] Fix TLS condition scope

---

charts/prometheus-rabbitmq-exporter/Chart.yaml
charts/prometheus-rabbitmq-exporter/templates/configmap.yaml

using `additionalLabels` value causes the rendered `ConfigMap` manifest to be invalid YAML as the rendered labels YAML block is not prepended by a new line (`indent` is used instead of `nindent`)
```console
helm template rmq-test \
oci://ghcr.io/prometheus-community/charts/prometheus-rabbitmq-exporter \
--version 2.1.0 \
--set-json 'additionalLabels={"test":"test"}' \
--debug
Error: YAML parse error on prometheus-rabbitmq-exporter/templates/configmap.yaml: 
error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context
```

[prometheus-rabbitmq-exporter] fix ConfigMap when additional labels are used

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/networkpolicy.yaml
charts/kube-prometheus-stack/unittests/alertmanager/networkpolicy_test.yaml
charts/kube-prometheus-stack/values.yaml

- Added NetworkPolicy template for Alertmanager
- Added NetworkPolicy configuration options in values.yaml
- Added comprehensive unit tests
- Updated documentation
The NetworkPolicy configuration allows:
- Ingress from configured ingress controller
- Ingress from Prometheus pods
- Inter-pod communication for clustering
- Egress for DNS resolution
- Egress for SMTP notifications (ports 25, 587, 465)
- Egress for webhook notifications (ports 80, 443)
- Added unit tests for NetworkPolicy configuration
- Verified template rendering
- Tested with both default and custom configurations
Fixes #5247

[kube-prometheus-stack] Add NetworkPolicy support for Alertmanager

---

.github/CODEOWNERS
MAINTAINERS.md
charts/prometheus-snmp-exporter/Chart.yaml

Remove unresponsive maintainer @miouge1.
Closes: https://github.com/prometheus-community/helm-charts/issues/5155

[prometheus-snmp-exporter] Remove unresponsive maintainer

---

charts/prometheus-snmp-exporter/Chart.yaml
charts/prometheus-snmp-exporter/templates/daemonset.yaml
charts/prometheus-snmp-exporter/templates/deployment.yaml
charts/prometheus-snmp-exporter/values.yaml

Add security context support for Configmap-reload container at snmp-exporter daemonset and deployment and set a containerSecurityContext: {} at values.yaml
- fixes #4996
Follow the PR @walker-tom

`[prometheus-snmp-exporter]` - add security context support for Configmap-reload container at snmp-exporter daemonset and deployment

---

charts/prometheus-opencost-exporter/Chart.yaml
charts/prometheus-opencost-exporter/README.md

As the upstream now supports this directly we can deprecate and remove this unmaintained chart.
Related: https://github.com/prometheus-community/helm-charts/issues/5152

[prometheus-opencost-exporter] Mark prometheus-opencost-exporter deprecated

---

charts/prometheus-operator-admission-webhook/Chart.yaml
charts/prometheus-operator-admission-webhook/templates/certmanager.yaml
charts/prometheus-operator-admission-webhook/values.yaml

Seeing lots of rotations on the certificate for the webhook. So want to mitigate the problem first by providing a revisionHistoryLimit on the cert according to https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
- replaces https://github.com/prometheus-community/helm-charts/pull/5379

[prometheus-operator-admission-webhook] feat(chart): add support for revisionHistoryLimit on the cert

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/networkpolicy.yaml
charts/kube-prometheus-stack/values.yaml

Set gateway/ingress namespace and podLabel selector to an empty string/object in order to not accidentally expose something unexpected. Move the Loki rule to the additionalIngress examples as Loki is not part of the stack. The 'alertmanager.service.clusterPort' was added as it was not declared in the values and now needs to be enabled explicitly.
Issue: #5318
- fixes #

[kube-prometheus-stack] Fix NetworkPolicy for Alertmanager

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

This PR adds support for configuring `nameValidationScheme` in Prometheus CR.
Setting this parameter to `Legacy` should result in prometheus-operator rendering `metric_name_validation_scheme: legacy` in config, thus configuring prometheus to request metrics/labels in the legacy way.

[kube-prometheus-stack] Add nameValidationScheme field to Prometheus CR

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml

Fix indentation for the nameValidationScheme field in Prometheus CR.
This time I rendered it locally :/

[kube-prometheus-stack] Fix indentation for the nameValidationScheme field in Prometheus CR

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/certmanager.yaml
charts/kube-prometheus-stack/values.yaml

Seeing lots of rotations on the certificate for the webhook. So want to mitigate the problem first by providing a revisionHistoryLimit on the cert according to https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
- replaces https://github.com/prometheus-community/helm-charts/pull/5379

kube-prometheus-stack - feat(chart): add support for revisionHistoryLimit on the cert

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/_helpers.tpl
charts/prometheus-postgres-exporter/templates/configmap.yaml
charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/templates/networkpolicy.yaml
charts/prometheus-postgres-exporter/templates/pdb.yaml
charts/prometheus-postgres-exporter/templates/prometheusrule.yaml
charts/prometheus-postgres-exporter/templates/role.yaml
charts/prometheus-postgres-exporter/templates/rolebinding.yaml
charts/prometheus-postgres-exporter/templates/secrets.yaml
charts/prometheus-postgres-exporter/templates/service.yaml
charts/prometheus-postgres-exporter/templates/serviceaccount.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
charts/prometheus-postgres-exporter/values.yaml

this is done in accordance with other charts in this repo, e.g. prometheus
The change allows to override the Namespace of namespaced resources using values, like is common practice in [other charts in this repo](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L1242).
This also prevents faulty helm implementations ([ref](https://github.com/helm/helm/issues/9256)) from installing resources in the wrong namespace.

[prometheus-postgres-exporter] Allow namespace override

---

charts/prometheus-yet-another-cloudwatch-exporter/Chart.yaml
charts/prometheus-yet-another-cloudwatch-exporter/templates/prometheusrule.yaml
charts/prometheus-yet-another-cloudwatch-exporter/templates/servicemonitor.yaml

These capabilities come from CRDs which makes impossible to get `ServiceMonitor`definition  with `helm template` command without `--validate` flag.
```
$ helm template . --kube-version 1.31.0 | grep ServiceMonitor
$ helm template . --validate | grep ServiceMonitor
kind: ServiceMonitor
```
As in the `values.yaml`, there's already the possibility to enable/disable `serviceMonitor` and `prometheusRule`, I think we can simply remove these checks.

[prometheus-yet-another-cloudwatch-exporter] remove capabilities checks

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

This Pull Request updates the `securityContext` to `podSecurityContext` in the `charts/kube-prometheus-stack/values.yaml` file. This change is necessary to align with the configuration in `kube-prometheus-stack/charts/crds/templates/upgrade/job.yaml`, which uses `podSecurityContext`.
The change is required because the upgrade/job.yaml template references .Values.upgradeJob.podSecurityContext, which was previously inconsistent with the values.yaml configuration.

[kube-prometheus-stack] Update securityContext to podSecurityContext for upgradeJob

---

charts/prometheus-yet-another-cloudwatch-exporter/Chart.yaml
charts/prometheus-yet-another-cloudwatch-exporter/templates/deployment.yaml
charts/prometheus-yet-another-cloudwatch-exporter/values.yaml

Possibility to add extra lables to deployment metadata

[prometheus-yet-another-cloudwatch-exporter] Add labels to deployment

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/templates/pdb.yaml
charts/prometheus-cloudwatch-exporter/values.yaml

This PR adds PodDisruptionBudget support for prometheus-cloudwatch-exporter.
- N/A
By default, PDB is not created (podDisruptionBudget.enabled: false) for backward compatibility.

[prometheus-cloudwatch-exporter] Add PodDisruptionBudget

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml

Currently it is not possible to pass templated values as serviceName, fixing alertmanager, prometheus and thanosruler templates to allow to pass helm templates

[kube-prometheus-stack] make servicename as tpl

---

charts/prometheus-systemd-exporter/Chart.yaml
charts/prometheus-systemd-exporter/README.md
charts/prometheus-systemd-exporter/templates/daemonset.yaml
charts/prometheus-systemd-exporter/values.yaml

Allows setting `systemd.collector.unit-include` argument, which was hardcoded.
This allows the user to select the systemd units he is interested into.
- fixes #4879 
~I have leveraged existing `extraArgs` for this. The exporter itself has a default value of `.+` for included units, but I have kept current behaviour not to do a breaking change.~
I have also:
~- Bumped exporter version to [v0.7.0](https://github.com/prometheus-community/systemd_exporter/releases/tag/v0.7.0) which has been recently released~ -> will do under separate PR
- Bumped the Chart version to ~`1.0.0`~ `0.4.0`
~- This is not a breaking change, so might be confusing. But according to https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md?plain=1#L51 charts should start at `1.0.0`~
I can undo any …

[prometheus-systemd-exporter]  Allow set unit include and bump to v0.7.0

---

charts/prometheus-operator-admission-webhook/Chart.yaml
charts/prometheus-operator-admission-webhook/ci/affinity-tpl-values.yaml
charts/prometheus-operator-admission-webhook/ci/affinity-values.yaml
charts/prometheus-operator-admission-webhook/ci/default-values.yaml
charts/prometheus-operator-admission-webhook/ci/deployment-labels-values.yaml
charts/prometheus-operator-admission-webhook/ci/env-values.yaml
charts/prometheus-operator-admission-webhook/ci/extra-args-values.yaml
charts/prometheus-operator-admission-webhook/ci/liveness-probe-values.yaml
charts/prometheus-operator-admission-webhook/ci/pdb-values.yaml
charts/prometheus-operator-admission-webhook/ci/pod-labels-values.yaml
charts/prometheus-operator-admission-webhook/ci/resources-values.yaml
charts/prometheus-operator-admission-webhook/ci/service-labels-values.yaml
charts/prometheus-operator-admission-webhook/ci/serviceaccount-values.yaml
charts/prometheus-operator-admission-webhook/ci/servicemonitor-values.yaml
charts/prometheus-operator-admission-webhook/templates/deployment.yaml
charts/prometheus-operator-admission-webhook/templates/hooks/job-createSecret.yaml
charts/prometheus-operator-admission-webhook/templates/hooks/job-patchWebhook.yaml
charts/prometheus-operator-admission-webhook/values.schema.json
charts/prometheus-operator-admission-webhook/values.yaml

`tpl` affinity field.  Less hardcoding of values specific to a single release.
None

[prometheus-operator-admission-webhook] tpl affinity

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

This PR allows setting the `scrapeProtocols` field on the `Prometheus` objects so a default fallback can be specified. 
Non has been opened.
This field is part of the CRD, see https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml#L8625, but wasn't configurable until now.

[kube-prometheus-stack] feat: allow setting scrapeProtocols for Prometheus

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml

This PR will add the provision to apply the `ImagePullSecret` into the Prometheus-Operator Admission Webhook Patch and Create Jobs. This will allow private container registry authentication by providing the `ImagePullSecret`.
- fixes #5487 - kube-prometheus-stack-70.3.0 - prometheus-operator/admission-webhooks Jobs doesn't include ImagePullSecrets.

kube-prometheus-stack - Adding imagePullSecret to Admission webhook Jobs

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/deploy.yaml
charts/prometheus/templates/sts.yaml
charts/prometheus/values.schema.json
charts/prometheus/values.yaml

this PR add `pod.spec.runtimeClassName` field support for prometheus chart
- fixes #

[prometheus] add support for runtimeClassName field in pod.spec

---

charts/prometheus-pushgateway/.helmignore
charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/ci/basic-auth-values.yaml
charts/prometheus-pushgateway/ci/servicemonitor-basicauth-secret-values.yaml
charts/prometheus-pushgateway/ci/servicemonitor-basicauth-values.yaml
charts/prometheus-pushgateway/templates/_helpers.tpl
charts/prometheus-pushgateway/templates/secret.yaml
charts/prometheus-pushgateway/templates/servicemonitor.yaml
charts/prometheus-pushgateway/values.yaml

Add support for basicAuth in ServiceMonitor.
- fixes #4821

[prometheus-pushgateway] add support for basicAuth in ServiceMonitor

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/values.yaml

The 30s bucket is used by the kubernetes mixin rules to compute official SLO availability rules. Remove this bucket from the excessive bucket drop fiter.
- fixes https://github.com/prometheus-community/helm-charts/issues/5514

[kube-prometheus-stack] fix: Add 30s bucket to apiserver latency metrics

---

charts/prometheus-adapter/Chart.yaml
charts/prometheus-adapter/README.md

When the sum over average values is reported by Metrics API, the result for query consumers is a number of bytes with a decimal point and some precision after it. That's really not good for a number in bytes.
Headlamp UI somehow receives that number re-formatted as millibytes, which its parseRam function does not correctly balk and crash at, so the UI occasionally reports 1000x the actual memory usage, and sometimes flaps back to displaying correctly.
When I add these round wrappers the metric gets reported as a whole number of bytes and that doesn't happen anymore!
No need for a chart rev, I don't know where this query definition comes from and I can find no references to it in any prometheus-adapter docs other than this one README, so I'm fixing it right at the source. (If anyone knows …

[prometheus-adapter] fix metrics api in README

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/_helpers.tpl
charts/kube-state-metrics/templates/scrapeconfig.yaml
charts/kube-state-metrics/values.yaml

This PR enables scrapeConfig to be used as alternative to serviceMonitor for kube-state-metrics.
We want to have a way to configure the kube-state-metrics in High Availiability. The simple way to do it is increasing the number of `replicas` to 2. However, it duplicates the kube-state-metrics metrics. 
With the use of scrapeConfig resource instead of serviceMonitor, you can scrape the kube-state-metrics as a traditional kubernetes services where each replica will expose its endpoint port giving high availability 
- https://github.com/kubernetes/kube-state-metrics/issues/611

[kube-state-metrics] Use scrapeConfig to have HA

---

charts/prometheus/Chart.yaml
charts/prometheus/templates/deploy.yaml
charts/prometheus/templates/sts.yaml

This PR updates the Prometheus chart to use the tpl function for dynamic image repository, tag, and digest values. This enhancement is critical when using multiple subcharts, like Prometheus, and wanting to configure the image repository only once in the parent chart, without duplication.
- Replaced static values with tpl for image repository, tag, and digest to allow the parent chart’s values to be passed dynamically to subchart.
- This change eliminates the need for duplication when using multiple instances of Prometheus (or other subcharts) and ensures consistent image configuration across all instances.

[prometheus] Support dynamic image config via tpl

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/_helpers.tpl
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/templates/alertmanager/extrasecret.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml
charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
charts/kube-prometheus-stack/templates/alertmanager/networkpolicy.yaml
charts/kube-prometheus-stack/templates/alertmanager/podDisruptionBudget.yaml
charts/kube-prometheus-stack/templates/alertmanager/psp-role.yaml
charts/kube-prometheus-stack/templates/alertmanager/psp-rolebinding.yaml
charts/kube-prometheus-stack/templates/alertmanager/route.yaml
charts/kube-prometheus-stack/templates/alertmanager/secret.yaml
charts/kube-prometheus-stack/templates/alertmanager/service.yaml
charts/kube-prometheus-stack/templates/alertmanager/serviceaccount.yaml
charts/kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
charts/kube-prometheus-stack/templates/alertmanager/serviceperreplica.yaml
charts/kube-prometheus-stack/values.yaml

This PR introduces support for deploying Alertmanager in a custom namespace by allowing the user to set alertmanager.namespaceOverride. This improves flexibility, especially for multi-namespace or more security-conscious setups, where isolating Alertmanager from other monitoring components is preferred.
- fixes #

[kube-prometheus-stack] Add support for deploying Alertmanager in a custom namespace

---

charts/prometheus-operator-admission-webhook/Chart.yaml
charts/prometheus-operator-admission-webhook/templates/mutatingWebhookConfiguration.yaml
charts/prometheus-operator-admission-webhook/templates/validatingWebhookConfiguration.yaml
charts/prometheus-operator-admission-webhook/values.yaml

A [pull request](https://github.com/prometheus-community/helm-charts/issues/3860) to chart/prometheus-operator-crds allowed the ability to selectively disable CRD objects.  In response to that, it's now also necessary to support selective disabling of webhooks.
None

[prometheus-operator-admission-webhook] selectively disable webhooks

---

charts/prometheus-operator-admission-webhook/Chart.yaml

Operator released v0.82.0
https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.82.0

[prometheus-operator-admission-webhook] bump  admission webhook to v0.82.0

---

charts/prometheus-operator-admission-webhook/Chart.yaml
charts/prometheus-operator-admission-webhook/values.schema.json
charts/prometheus-operator-admission-webhook/values.yaml

Fixes coalesce warning when setting type to string (from default map)
```
coalesce.go:220: warning: cannot overwrite table with non table for affinity (map[])
```

[prometheus-operator-admissions-controller] affinity=null

---

charts/prometheus-pushgateway/Chart.yaml
charts/prometheus-pushgateway/templates/_helpers.tpl
charts/prometheus-pushgateway/values.yaml

allow for global.imageRegistry and global.imagePullSecrets overrides with the local chart settings taking precedence over the global settings.
This is needed to allow users that must host their own registry easily override where the chart pulls from.
@gianrubio @cstaud @zeritti

[prometheus-pushgateway] allow for global.image.registry and global.imagePullSecrets overrides

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/UPGRADE.md
charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/pdb.yaml
charts/kube-prometheus-stack/templates/prometheus-operator/pdb.yaml
charts/kube-prometheus-stack/values.yaml

When setting up the availability of your cluster the operator-webhook has a definable PDB, but not the operator itself.
This adds an optional `PodDisruptionBudget` for the operator container itself.
- fixes #

[kube-prometheus-stack] Add optional PDB for operator

---

charts/prometheus-json-exporter/Chart.yaml
charts/prometheus-json-exporter/values.yaml

Fixes the default scrapeTimeout to be a valid value
Commit [c50b12e526e5fd2769b52cc6d7438163e8d5da10](https://github.com/prometheus-community/helm-charts/commit/c50b12e526e5fd2769b52cc6d7438163e8d5da10) changed the behavior so that the scrapeTimeout is always set. However, [the current defaults](https://github.com/prometheus-community/helm-charts/blob/3171fe0905a4e3125fd33cc1b12a572834cb7c06/charts/prometheus-json-exporter/values.yaml#L72-L77) are invalid, since the timeout is larger than the interval.
Due to that, at least alloy rejects to scrape the ServiceMonitor with the error
> scrape timeout greater than scrape interval for scrape config with job name \"serviceMonitor/namespace/service-monitor-name/0\"
This is a breaking change for any users that have set an interval higher than 30s …

[prometheus-json-exporter]: scrape timeout must be lower than interval

---

MAINTAINERS.md
charts/alertmanager/Chart.yaml
charts/alertmanager/templates/serviceperreplica.yaml
charts/alertmanager/templates/services.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.schema.json
charts/alertmanager/values.yaml

It can be useful to customize the name of Alertmanager's container port in situations where another K8s object is observing new deployments (e.g. Prometheus collector that watches for ports named "metrics"). This PR enables this use case with a new top-level `containerPortName` value, which defaults to the current, hard-coded "http" value.
I left the name of the Service as-is just to keep the PR small.

[alertmanager] Allow customizing the name of the container port

---

charts/alertmanager/Chart.yaml
charts/alertmanager/ci/config-reload-values.yaml
charts/alertmanager/templates/statefulset.yaml
charts/alertmanager/values.yaml

The alertmanager chart misses the probes for the optional sidecar.
The reloader sidecar is present in multiple charts already and there it includes the probes. E.g.:
- blackbox exporter
https://github.com/prometheus-community/helm-charts/blob/c12280491748258ffd573a5af53bda6d811f6bed/charts/prometheus-blackbox-exporter/values.yaml#L463-L472
- kube-prometheus-stack (via Operator):
https://github.com/prometheus-operator/prometheus-operator/blob/b2f9aacee4c8812928626210572e2e998425f492/pkg/operator/config_reloader.go#L321-L339
- prometheus:
https://github.com/prometheus-community/helm-charts/blob/c12280491748258ffd573a5af53bda6d811f6bed/charts/prometheus/values.yaml#L101-L114
maybe also other charts (didn't check all)
FYI @PatMis16
`---`
I noticed that there was a discussion about defining …

[alertmanager] Ability to add probes for reloader sidercar

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml

Corrects the indentation of the rendered `servicemonitor.scrapeLimits` template for `kube-etcd`, as the rendered properties should be at the same indentation level as the `targetLabels` property per the API for `ServiceMonitor`. Prior to Helm 3.18.0 this appears to have been ignored, but now results in the following error:
```
Error: INSTALLATION FAILED: YAML parse error on kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context
```
- fixes #5648

[kube-prometheus-stack] Fix indendation of rendered servicemonitor.scrapeLimits for kube-etcd

---

charts/kube-prometheus-stack/Chart.yaml

Bump Helm dependency Grafana to the latest [9.2.1](https://github.com/grafana/helm-charts/releases/tag/grafana-9.2.1) to include Grafana `12.0.0-security-01`, which addresses high-severity CVE `CVE-2025-4123`.
- [Grafana blog post](https://grafana.com/blog/2025/05/21/grafana-security-release-high-severity-security-fix-for-cve-2025-4123/)
- [Diff for Grafana Helm chart from `9.0.0` to `9.2.1`](https://github.com/grafana/helm-charts/compare/grafana-9.0.0...grafana-9.2.1)
- Security: Fix [CVE-2025-4123](https://grafana.com/security/security-advisories/cve-2025-4123/) (HIGH)

[kube-prometheus-stack]: Bump dependency Grafana to 9.2.1

---

charts/alertmanager/Chart.yaml
charts/alertmanager/templates/statefulset.yaml

This PR fixes a regression introduced by me in PR
- #5635
In this PR my intent was to add the probes as an optional piece. Sadly Kubernetes does not accept `{}` for the probes fields like it does for `resources: {}`.
- fixes #5687
`---`

[alertmanager] Make configmapReload probes really optional

---

charts/prom-label-proxy/Chart.yaml
charts/prom-label-proxy/templates/deployment.yaml

When using the HPA resource for the prom-label-proxy chart, the `.spec.replicas` is still being set on the deployment. During upgrade the desiredCount is ignored and being reset to the `.spec.replicas` value by default. My change is to not set `.spec.replicas` on the deployment when using the HPA object.
* `.spec.replicas` being set on the deployment of `prom-label-proxy` when using the HPA object.f

[prom-label-proxy] When enabling HPA, do not set .spec.replicas on the deployment

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/service.yaml

The nodeport field on a service is only valid on Services of type NodePort.
Other charts in this repo handle this correctly, so adding the same if statement in kube-state-metrics chart.
Thanks in advance :)

[kube-state-metrics] Only set NodePort on valid service type

---

charts/prometheus-nginx-exporter/Chart.yaml
charts/prometheus-nginx-exporter/templates/servicemonitor.yaml

Ensure Custom Namespace Is Used in ServiceMonitor
I have installed prometheus-nginx-exporter in the nginx namespace but I want the service monitor to be installed in the monitoring namespace (different namespace).
And I see there is that option in values.yaml but it doesn't work well.
https://github.com/prometheus-community/helm-charts/blob/5c1972cbc0fcef75802d36d1f9b489f3555d107a/charts/prometheus-nginx-exporter/values.yaml#L77-L81
- fixes #

[prometheus-nginx-exporter] Fix custom namespace handling in service monitor

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
charts/kube-prometheus-stack/values.yaml

To provide supported otlp configuration in the prometheus.yaml configuration file, as described at https://prometheus.io/docs/prometheus/latest/configuration/configuration and https://prometheus.io/docs/guides/opentelemetry.
Addapted to kube-prometheus-stack following the CustomResourceDefinition file helm-charts\charts\kube-prometheus-stack\charts\crds\crds\crd-prometheuses.yaml
- fixes #5080

[kube-prometheus-stack] add otlp configuration to prometheus.yaml

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
charts/kube-prometheus-stack/unittests/alertmanager/alertmanager_test.yaml

This PR fixes an issue where the `alertmanagerConfigNamespaceSelector` field was intended to be `null` when unspecified, but the chart rendered it as an empty map instead. This caused `Alertmanager` to select resources from all namespaces, rather than restricting discovery to its own namespace.
- fixes #4704

[kube-prometheus-stack] Allow null value in alertmanagerConfigNamespaceSelector

---

charts/prometheus-to-sd/Chart.yaml
charts/prometheus-to-sd/templates/deployment.yaml
charts/prometheus-to-sd/values.yaml

[prometheus-to-sd] bump prometheus-to-sd  exporter to 0.9.2

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/README.md
charts/prometheus-postgres-exporter/templates/_helpers.tpl

CC: @gianrubio @zanhsieh @zeritti 
The benefit of using those labels, suggested by the https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ , is that many applications are able to work with them nativeli, generally making thinks easier.
This brings this helm-chart close to the other in this repository.
No open issue

[prometheus-postgres-exporter] use labels suggested by K8s best practices

---

charts/prom-label-proxy/Chart.yaml
charts/prom-label-proxy/README.md

[prom-label-proxy] Document OCI artiacts in README

---

charts/alertmanager-snmp-notifier/Chart.yaml
charts/alertmanager-snmp-notifier/README.md

[alertmanager-snmp-notifier] Document OCI artifacts in README

---

charts/alertmanager/Chart.yaml
charts/alertmanager/README.md

[alertmanager] Document OCI artifacts in README

---

charts/prometheus-blackbox-exporter/Chart.yaml
charts/prometheus-blackbox-exporter/README.md

[prometheus-blackbox-exporter] Document OCI artiacts in README

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/README.md

[prometheus-kafka-exporter] Document OCI artiacts in README

---

charts/prometheus-cloudwatch-exporter/Chart.yaml
charts/prometheus-cloudwatch-exporter/README.md

[prometheus-cloudwatch-exporter] Document OCI artiacts in README

---

charts/prometheus-conntrack-stats-exporter/Chart.yaml
charts/prometheus-conntrack-stats-exporter/README.md

[prometheus-conntrack-stats-exporter] Document OCI artiacts in README

---

charts/prometheus-consul-exporter/Chart.yaml
charts/prometheus-consul-exporter/README.md

[prometheus-consul-exporter] Document OCI artiacts in README

---

charts/prometheus-couchdb-exporter/Chart.yaml
charts/prometheus-couchdb-exporter/README.md

[prometheus-couchdb-exporter] Document OCI artiacts in README

---

charts/prometheus-druid-exporter/Chart.yaml
charts/prometheus-druid-exporter/README.md

[prometheus-druid-exporter] Document OCI artiacts in README

---

charts/prometheus-elasticsearch-exporter/Chart.yaml
charts/prometheus-elasticsearch-exporter/README.md

[prometheus-elasticsearch-exporter] Document OCI artiacts in README

---

charts/prometheus-fastly-exporter/Chart.yaml
charts/prometheus-fastly-exporter/README.md

[prometheus-fastly-exporter] Document OCI artiacts in README

---

charts/prometheus-systemd-exporter/Chart.yaml
charts/prometheus-systemd-exporter/README.md

[prometheus-systemd-exporter] Document OCI artiacts in README

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/README.md

[prometheus-postgres-exporter] Document OCI artiacts in README

---

charts/prometheus-pingdom-exporter/Chart.yaml
charts/prometheus-pingdom-exporter/README.md

[prometheus-pingdom-exporter] Document OCI artiacts in README

---

charts/prometheus-ipmi-exporter/Chart.yaml
charts/prometheus-ipmi-exporter/README.md

The *prometheus-ipmi-exporter* chart did not have a proper README.
This PR adds one which has the same structure as the other charts READMEs.

[prometheus-ipmi-exporter] Add README

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

This PR introduces support for defining Kubernetes hostAliases via values.yaml in the prometheus-kafka-exporter Helm chart.
hostAliases allow mapping custom hostnames to IP addresses inside the Pod’s /etc/hosts file, which can be useful in environments without DNS records or when static hostname resolution is required.
**charts/prometheus-kafka-exporter/templates/deployment.yaml**
Added a conditional block to render hostAliases if provided in values.yaml.
**charts/prometheus-kafka-exporter/values.yaml**
Added a new hostAliases key with an example configuration (commented out by default).
Enables optional static hostname resolution for the exporter Pod without requiring external DNS changes.
Fully backwards-compatible: if hostAliases is empty or not set, no changes are applied to the …

[prometheus-kafka-exporter] feat: added hostAliases capabilities

---

charts/kube-state-metrics/Chart.yaml
charts/kube-state-metrics/templates/deployment.yaml

Consistently use `/` for the probes path
- fixes #

[kube-state-metrics]: consistently use / in probes path

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

Added startup probe for prometheus-kafka-exporter chart which was missing.
#5884

[prometheus-kafka-exporter] Add Startup Probe

---

.github/workflows/ci.yaml
.github/workflows/renovate-custom-hooks.yaml

See:
* https://github.com/renovatebot/renovate/discussions/37842
- fixes #

[CI] Allow mend[bot] to run Renovate post job

---

charts/prometheus-kafka-exporter/Chart.yaml
charts/prometheus-kafka-exporter/templates/deployment.yaml
charts/prometheus-kafka-exporter/values.yaml

This PR updates the **prometheus-kafka-exporter** Helm chart to allow users to specify custom TLS file names via new values:  
```yaml
tls:
...
caFile: ca.crt
certFile: tls.crt
keyFile: tls.key
server:
tls:
...
caFile: ca.crt
certFile: tls.crt
keyFile: tls.key
```
The deployment template has been updated to use these values for both the main and server TLS configuration, replacing previously hardcoded file names.  
Default values are set to:
- `ca.crt`
- `tls.crt`
- `tls.key`
This change makes the chart more flexible when working with secrets created by tools like the [Strimzi Kafka Operator](https://strimzi.io/), which names secret keys differently.
- The change is backward compatible, since defaults align with existing behavior.  
- No changes are required for existing users unless they …

[prometheus-kafka-exporter] Add new values to set TLS file names

---

charts/prometheus-postgres-exporter/Chart.yaml
charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
charts/prometheus-postgres-exporter/values.yaml

This commit adds support for adding `metricRelabelings` support per target when using Multi Target in `postgres-exporter`. In a Multi Target environment this can be useful for example for adding labels to a specific target.
For example in my project we have a `postgres-exporter` deployment with several targets using Multi Target support. Each target is owned to a different team, and we plan to use this feature to route alerts to the corresponding team notification channel.
n/a
Thanks for your work!!

[prometheus-postgres-exporter] Add metricRelabelings per target

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
charts/kube-prometheus-stack/values.yaml

This PR allows users to supply arbitrary datasource `jsonData`. Currently, a user cannot change the default datasource's `jsonData` to anything they want (say for example, `prometheusType` which supports [any of these values](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/types.ts#L31-L36))
This change is opt-in; there is no impact to existing configurations.

[kube-prometheus-stack] Support supplying jsonData on the default datasource
