- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/extra-manifests.yaml
- charts/kube-state-metrics/values.yaml
It is common now that helm charts offer the ability to deploy custom resources along the application. It is especially useful for managing Secrets (eg. via external-secrets.io / Secrets Store CSI Driver) or deploying more granular NetworkPolicy (eg. CiliumNetworkPolicy).
Charts in the community that supports this:
- all Argoproj charts (Argo CD, Argo workflows, ...)
- grafana charts (Grafana, Promtail, Loki, etc.)
- most Bitnami charts
- VictoriaMetrics charts
none
Same implementation as:
- https://github.com/prometheus-community/helm-charts/pull/3167
- https://github.com/prometheus-community/helm-charts/pull/2798
- https://github.com/prometheus-community/helm-charts/pull/2294
/cc: @tariq1890 @mrueg  @dotdc
> [kube-state-metrics] Add ability do deploy extra manifests

- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/templates/deployment.yaml
Postgres-exporter [0.13.0](https://github.com/prometheus-community/postgres_exporter/commit/db08eee988e8e59095d780b620d4c9b8e8cc8ba8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) renamed the parameter from `bgwriter` to  `stat_bgwriter`
Fix the parameter name
> [prometheus-postgres-exporter] Fix the parameter to disable `stat_bgwriter` collecting

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/extra-manifests.yaml
- charts/prometheus-node-exporter/values.yaml
It is common now that helm charts offer the ability to deploy custom resources along the application. It is especially useful for managing Secrets (eg. via external-secrets.io / Secrets Store CSI Driver) or deploying more granular NetworkPolicy (eg. CiliumNetworkPolicy).
Charts in the community that supports this:
- all Argoproj charts (Argo CD, Argo workflows, ...)
- grafana charts (Grafana, Promtail, Loki, etc.)
- most Bitnami charts
- VictoriaMetrics charts
none
Same implementation as:
- https://github.com/prometheus-community/helm-charts/pull/3167
- https://github.com/prometheus-community/helm-charts/pull/2798
- https://github.com/prometheus-community/helm-charts/pull/2294
- https://github.com/prometheus-community/helm-charts/pull/3593
/cc: @gianrubio @zanhsieh @zeritti
> [prometheus-node-exporter] Add ability do deploy extra manifests

- charts/prometheus-statsd-exporter/Chart.yaml
- charts/prometheus-statsd-exporter/templates/deployment.yaml
Add checksum of configmap to pod's annotation that lead to recreate the pod when configmap is updated.
- fixes #
> [prometheus-statsd-exporter] add checksum of configmap to deployment

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/rbac-configmap.yaml
fix kubeRBACProxy rbac-configmap namespace missing
- fixes #
> [prometheus-node-exporter] fix rbac-configmap namespace missing

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/templates/extra-manifests.yaml
- charts/prometheus-snmp-exporter/values.yaml
Adds a value to the `prometheus-snmp-exporter` chart to allow you to deploy additional Kubernetes resources, such as OpenShift Routes, as part of this Helm Chart. This is the same as what has been done for the `prometheus` chart among others.
> [prometheus-snmp-exporter] Add extra manifests template to snmp-exporter chart

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/service.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] allow configuration of ipFamilyPolicy

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/rbac-configmap.yaml
fix kubeRBACProxy rbac-configmap namespace missing
- fixes #
> [kube-state-metrics] fix rbac-configmap namespace missing

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/hack/minikube/cmd.sh
Removes an extraneous closing brace from the minikube script
Unreferenced
n/a
> [kube-prometheus-stack] remove extraneous brace from minikube script

- charts/prometheus-operator-admission-webhook/Chart.yaml
- charts/prometheus-operator-admission-webhook/README.md
- charts/prometheus-operator-admission-webhook/values.schema.json
- charts/prometheus-operator-admission-webhook/values.yaml
Signed-off-by: Yongseon Lee <yongseonlee0@gmail.com>
This replaces the type of `prometheus-operator-admission-webhook.jobs.tolerations` from `object` to `array` as it should be.
> [prometheus-operator-admission-webhook] replace the type of jobs.tolerations to array

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/hack/requirements.txt
Bump requests library to 2.31.0.
Addresses:
- CVE-2021-33503 (urlib3) - dos
- CVE-2023-32681 - Proxy-Authorization headers leaking
Unreferenced
N/A
> [kube-prometheus-stack] bump requests lib

- charts/prometheus-adapter/Chart.yaml
- charts/prometheus-adapter/templates/deployment.yaml
Templating error on `dnsConfig` for the `prometheus-adapter` chart:
```
YAML parse error on prometheus-adapter/templates/deployment.yaml: error converting YAML to JSON: yaml: line 70: did not find expected key
```
> [prometheus-adapter] fix templating for dnsConfig 

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/templates/crd-thanosrulers.yaml
Need features added by prometheus crds 0.67.0
None
> [prometheus-operator-crds] Upgrade crds to 0.67.0

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/statefulset.yaml
- charts/alertmanager/values.yaml
The Alertmanager StatefulSet has been adapted to allow the user changing the default revisionHistoryLimit.
N/A
N/A
> [alertmanager] feat: allow changing the default revisionHistoryLimit

- charts/prometheus/Chart.yaml
- charts/prometheus/templates/deploy.yaml
- charts/prometheus/templates/sts.yaml
- charts/prometheus/values.yaml
The Prometheus Depoyment and StatefulSet have been adapted to allow the user changing the default revisionHistoryLimit.
N/A
N/A
> [prometheus] feat: allow changing the default revisionHistoryLimit

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/templates/service.yaml
- charts/prometheus-blackbox-exporter/values.yaml
> [prometheus-blackbox-exporter] allow configuration of ipFamilyPolicy

- .github/CODEOWNERS
- charts/prometheus-modbus-exporter/Chart.yaml
- charts/prometheus-modbus-exporter/README.md
- charts/prometheus-modbus-exporter/templates/NOTES.txt
- charts/prometheus-modbus-exporter/templates/_helpers.tpl
- charts/prometheus-modbus-exporter/templates/configmap.yaml
- charts/prometheus-modbus-exporter/templates/deployment.yaml
- charts/prometheus-modbus-exporter/templates/service.yaml
- charts/prometheus-modbus-exporter/templates/serviceaccount.yaml
- charts/prometheus-modbus-exporter/templates/servicemonitor.yaml
- charts/prometheus-modbus-exporter/templates/tests/test-connection.yaml
- charts/prometheus-modbus-exporter/values.yaml
> [prometheus-modbus-exporter] full

- charts/prometheus-adapter/Chart.yaml
- charts/prometheus-adapter/templates/service.yaml
- charts/prometheus-adapter/values.yaml
> [prometheus-adapter] Allow configuration of ipFamilyPolicy

- charts/prometheus-windows-exporter/Chart.yaml
- charts/prometheus-windows-exporter/README.md
- charts/prometheus-windows-exporter/values.yaml
Removes references to `node_exporter` in the `windows_exporter` chart, likely left accidentally from a copy & paste.
N/A
> [prometheus-windows-exporter] Set correct name for windows_exporter

- charts/prometheus-druid-exporter/Chart.yaml
- charts/prometheus-druid-exporter/templates/deployment.yaml
- charts/prometheus-druid-exporter/values.yaml
Add `imagePullSecrets` configure
- fixes #
> [prometheus-druid-exporter] add PullSecrets configure

- charts/prometheus-statsd-exporter/Chart.yaml
> [statd exporter] update version

- charts/jiralert/Chart.yaml
- charts/jiralert/templates/_helpers.tpl
This PR adds commonLabels to jiralert. I didn't use customLabels to not change current functionality, but could change it to customLabels as well if desired.
> [jiralert] Added commonLabels to jiralert

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Fixed wrong comment in (default) values.yaml
> [kube-prometheus-stack] Corrected operator service account comment

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/ciliumnetworkpolicy-createSecret.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/ciliumnetworkpolicy-patchWebhook.yaml
- fixes [this PR](https://github.com/prometheus-community/helm-charts/pull/3671)
> kube-prometheus-stack : change ciliumnetworkpolicy hooks from post to pre in prometheus-operator

- charts/prometheus-mongodb-exporter/Chart.yaml
- charts/prometheus-mongodb-exporter/templates/deployment.yaml
- charts/prometheus-mongodb-exporter/values.yaml
Adds dnsConfig to mongodb-exporter
N/A
> [prometheus-mongodb-exporter] add dnsConfig

- charts/prometheus-node-exporter/Chart.yaml
> [prometheus-node-exporter] bump version

- charts/prometheus-smartctl-exporter/Chart.yaml
This PR updates the image of smartctl-importer to v0.11.0.
* https://github.com/prometheus-community/smartctl_exporter/releases/tag/v0.10.0
- fixes #
>  [prometheus-smartctl-exporter]: update to smartctl exporter v0.11.0

- charts/kube-state-metrics/Chart.yaml
Bumps ksm to https://github.com/kubernetes/kube-state-metrics/releases/v2.10.0
- fixes #
> [kube-state-metrics] Bump to v2.10.0

- charts/kube-prometheus-stack/Chart.yaml
Following #3749, bump kube-prometheus-stack dependencies
- fixes #
> [kube-prometheus-stack] bump kube-state-metrics and prometheus-node-exporter

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml
> [kube-prometheus-stack] Generate latest alerts

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
Signed-off-by: drfaust92 <ilia.lazebnik@gmail.com>
- fixes #3650
> [kube-prometheus-stack] fix thanos sidecar ingress

- charts/prometheus-mongodb-exporter/Chart.yaml
- charts/prometheus-mongodb-exporter/values.yaml
Comment was misguiding for users when they are checking the comments in values.yaml. 
- fixes #
> [prometheus-mongodb-exporter] Fix comments on podAnnotations

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] update prometheus to 2.47.0 + deps

- charts/prom-label-proxy/Chart.yaml
> [prom-label-proxy] bump to 0.7.0

- charts/prometheus-kafka-exporter/Chart.yaml
> [prometheus-kafka-exporter] bump kafka exporter to 1.7.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/ciliumnetworkpolicy.yaml
The current `cilliumNetworkPolicy` for prometheus-operator does not work over TLS.
This PR fixes this by removing L7 rules when using TLS.
> [kube-prometheus-stack] fix prometheus-operator cilium netpol when using TLS

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] bump pushgateway to 1.6.1

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] bump redis exporter to 1.54.0

- charts/prometheus-adapter/Chart.yaml
- charts/prometheus-adapter/templates/deployment.yaml
- charts/prometheus-adapter/values.yaml
> [prometheus-adapter] bump adapter to v0.11.1

- charts/prometheus-mongodb-exporter/Chart.yaml
> [prometheus-mongodb-exporter] bump mongo exporter to 0.39.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
- charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes-darwin.yaml
- charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes.yaml
- charts/kube-prometheus-stack/values.yaml
This PR adds new values - .Values.nodeExporter.operatingSystems.[linux|darwin].enabled.
It's used for controlling creation of Node Exporter Mac OS Grafana dashboard.
https://github.com/prometheus-community/helm-charts/issues/3763
This is related to previous PR: https://github.com/prometheus-community/helm-charts/pull/3385
- [ X ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ X ] Chart Version bumped
- [ X ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
> [kube-prometheus-stack] Adding operating systems values for node exporter

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml
- charts/kube-prometheus-stack/values.yaml
This PR adds support for attaching node's metadata to discovered kubelet's targets. Prometheus has supported this feature for the (specific) endpoints created by the operator since release 2.45.0. Set to `false` by default.
- fixes #3227
> [kube-prometheus-stack] Add support for attaching node metadata

- charts/prometheus/Chart.yaml
- charts/prometheus/templates/clusterrole.yaml
The cluster role for cluster-wide service discovery does not grant a permission on _EndpointSlices_ (stable since 1.21, supported as a role type by Prometheus since 2.21). This PR adds that permission.
- fixes #3839
> [prometheus] Add permission on endpointslices in cluster role

- charts/kube-prometheus-stack/Chart.yaml
Updated kube-prometheus-stack chart to include the latest kube-state-metrics changes by default.
> [kube-prometheus-stack] updated kube-state-metrics to 5.14.x

- charts/kube-prometheus-stack/Chart.yaml
51.4.0 contains grafana chart 6.60.3. The fix https://github.com/grafana/helm-charts/pull/2696 is included in 6.60.4
Bumping the chart version is sufficient here, since we have 6.60.* defined as dependency which should use the latest grafana chart version.
- fixes #3866
> [kube-prometheus-stack] Bump dependencies

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] - bump thanos to 0.32.4

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] bump redis exporter to 1.55

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [conntrack stats exporter] Update to v0.4.16

- charts/prometheus/Chart.yaml
- charts/prometheus/templates/serviceaccount.yaml
- charts/prometheus/values.schema.json
- charts/prometheus/values.yaml
> [prometheus] Allow setting automountServiceAccountToken

- charts/prometheus/Chart.yaml
- charts/prometheus/values.schema.json
> [prometheus] Loosen typing for pdb.maxUnavailable

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] Upgrade Prometheus, update deps

- .github/workflows/lint-test.yaml
Fixes lint error `Unable to validate cosign version: 'v2.0.0'`
ref: 
- https://github.com/helm/chart-testing-action/issues/132
- https://github.com/prometheus-community/helm-charts/actions/runs/6724133147/job/18346741991?pr=3936
- fixes #
> [CI] Fix linter job: Unable to validate cosign version: 'v2.0.0'

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] Bump to 0.69.1

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] Bump to 0.69.1

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] Bump to 1.6.2

- charts/kube-state-metrics/Chart.yaml
> [kube-state-metrics] Bump to 2.10.1

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] Bump helm deps

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml
0.69 requires new RBAC permissions
Ref: https://github.com/prometheus-operator/prometheus-operator/commit/7f9bdca5d3717083541b213f2d5a2d3357eb8074
- fixes #
> [kube-prometheus-stack] Add missing RABC permission for Prometheus Operator

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] Bump to 1.7.0 + rbac proxy to 0.15.0

- charts/prometheus-adapter/Chart.yaml
> [prometheus-adapter] Bump prom adapter to 0.11.2

- charts/prometheus-adapter/Chart.yaml
- charts/prometheus-adapter/templates/deployment.yaml
Argo CD rejects the deployment when the priorityClassName key is present without a value.
> [prometheus-adapter] Only set priorityClassName if non-empty

- charts/prometheus-windows-exporter/Chart.yaml
- charts/prometheus-windows-exporter/values.yaml
add memory to the default collectors
> [prometheus-windows-exporter] add memory collector to windows-exporter values.yaml

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] Bump prom to 2.48.0

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] Bump to 0.70.0

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
> [prometheus-operator-crds] Fix accidental space

- charts/prometheus-statsd-exporter/Chart.yaml
> [prometheus-statsd-exporter] Bump to 0.26.0

- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/templates/deployment.yaml
- charts/prometheus-postgres-exporter/values.yaml
With this PR you are able to set priorityClassName
> [prometheus-postgres-exporter] - introduced priorityClassName

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/ci/lint.sh
- charts/kube-prometheus-stack/hack/requirements.txt
- charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
Valides, if hack scripts matches source
- fixes #3941
> [kube-prometheus-stack] Add custom CI actions

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Updates Prometheus image to 2.48.1 which includes fixes for the Agent mode:
https://github.com/prometheus/prometheus/pull/13251
> [kube-prometheus-stack] bump prometheus image tag to 2.48.1

- charts/prometheus/Chart.yaml
> [prometheus] Bump to 2.48.1

- charts/prometheus-mongodb-exporter/Chart.yaml
> [prometheus-mongodb-exporter] bump to 0.40

- charts/prometheus-fastly-exporter/Chart.yaml
- charts/prometheus-fastly-exporter/templates/deployment.yaml
- charts/prometheus-fastly-exporter/values.yaml
> [prometheus-fastly-exporter] Bump to 7.6.1

- charts/prometheus-nats-exporter/Chart.yaml
New version of prometheus-nats-exporter
- fixes #
> [prometheus-nats-exporter] feat: bump prometheus-nats-exporter to 0.13.0

- charts/alertmanager-snmp-notifier/Chart.yaml
> [alertmanager-snmp-notifier] Bump to 1.5.0

- charts/prometheus-pushgateway/Chart.yaml
- charts/prometheus-pushgateway/templates/_helpers.tpl
- charts/prometheus-pushgateway/values.yaml
> [prometheus-pushgateway] add host aliases

- charts/prometheus-elasticsearch-exporter/Chart.yaml
- charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
> [prometheus-elasticsearch-exporter] bump elastic exporter to 1.7.0

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
- charts/prometheus-node-exporter/values.yaml
Adds a new value `.Values.version` to override reading version from `.Values.image.tag` or `.Chart.AppVersion` in case of custom repositories.
- fixes #4104
- fixes #3821 
N/A
> [prometheus-node-exporter] add version value to override image.tag

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] bump redis exporter to 1.56.0

- charts/alertmanager-snmp-notifier/Chart.yaml
- charts/alertmanager-snmp-notifier/templates/service.yaml
- charts/alertmanager-snmp-notifier/values.yaml
> [alertmanager-snmp-notifier] Allow configuration of ipFamilyPolicy

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump Thanos to 0.33.0

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] bump to 0.4.17

- charts/prometheus-mysql-exporter/Chart.yaml
> [prometheus-mysql-exporter] bump to 0.15.1

- charts/prometheus-json-exporter/Chart.yaml
- charts/prometheus-json-exporter/templates/configmap.yaml
- charts/prometheus-json-exporter/values.yaml
With this PR it is possible to store a structured config via `configuration.structuredConfig`.
This means that individual values of the configuration can be overwritten, e.g. via Helm `--set configuration.structuredConfig.modules.test_module.http_client_config.basic_auth.username=foo`. This is currently not possible.
*No issues*
*None*
> [prometheus-json-exporter] feat: add support for structuredConfig

- charts/prom-label-proxy/Chart.yaml
> [prom-label-proxy] bump to 0.8.0

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.24.0

- charts/prometheus-mysql-exporter/Chart.yaml
- charts/prometheus-mysql-exporter/templates/prometheusrule.yaml
- charts/prometheus-mysql-exporter/values.yaml
Adds `PrometheusRule` to mysql-exporter chart
Was mainly done like it is achieved in the redis-exporter chart.
> [proemtheus-mysql-exporter] add promethesrules

- charts/prometheus-memcached-exporter/Chart.yaml
> [prometheus-memcached-exporter] bump to 0.14.2

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
`{{- if .Values.prometheus.prometheusSpec.thanos.objectStorageConfig.existingSecret }}` is causing nil pointer errors due to `prometheus.prometheusSpec.thanos` config defaulting to `{}` in values
https://github.com/prometheus-community/helm-charts/blob/29eb6a1954a10aa2e4423c0d70aab0c78373cee3/charts/kube-prometheus-stack/values.yaml#L3698
- fixes #
> [kube-prometheus-stack] Avoid nil pointer error with empty thanos config

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] bump operator to 0.71.0

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] bump pgw to 1.7.0

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] bump pgw dep

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml
> [kube-prometheus-stack] add missing rbac permissions for 0.71.0

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] bump operator to 0.71.2

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.25.1

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump operator to 0.71.2

- charts/kube-prometheus-stack/Chart.yaml
> [kube-prometheus-stack] bump win and node exporter deps

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/values.yaml
> [prometheus-blackbox-exporter] bump reloader to 0.71.2

- charts/prometheus-nats-exporter/Chart.yaml
> [prometheus-nats-exporter] bump to 0.14.0

- charts/prometheus-statsd-exporter/Chart.yaml
- charts/prometheus-statsd-exporter/templates/deployment.yaml
- charts/prometheus-statsd-exporter/templates/hpa.yaml
- charts/prometheus-statsd-exporter/values.yaml
Want to set preStop to make sure that Prometheus collects all metric samples before it stops.
- fixes #
> [prometheus-statsd-exporter] allow to set lifecycle to deployment

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/templates/daemonset.yaml
- charts/prometheus-blackbox-exporter/templates/deployment.yaml
Currently, the chart version is part of the pod labels. If the version is increased, the pod will be restarted which is not always necessary.
- fixes #
> [prometheus-blackbox-exporter] Use selectorLabel for pod

- charts/prometheus-systemd-exporter/Chart.yaml
- charts/prometheus-systemd-exporter/templates/daemonset.yaml
- charts/prometheus-systemd-exporter/values.yaml
Hello,
I have an idea for an improvement of the chart.
This PR add the possibility to mount extraVolumes on DaemonSet. 
It is useful for some distros like flatcar because ```/var/run/dbus/system_bus_socket``` must be mounted on the container.
Thanks for reviewing !
> [prometheus-systemd-exporter] allow mount extraVolumes

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Updates Thanos Ruler to v0.34.0 with support of `keep_firing_for` and other improvements, changelog available here: https://github.com/thanos-io/thanos/blob/main/CHANGELOG.md#v0340---260124
> [kube-prometheus-stack] Update Thanos Ruler to v0.34.0

- charts/kube-prometheus-stack/Chart.yaml
Updates Grafana helm chart version to 7.3.x
- fixes #
> [kube-prometheus-stack] Update Grafana chart to 7.3.x

- charts/prometheus-ipmi-exporter/Chart.yaml
> [prometheus-ipmi-exporter] bump to 1.8.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
In PR https://github.com/prometheus-community/helm-charts/pull/4209 I update Thanos Sidecar to v0.34.0, but missed update Ruler, this PR is created to fix this
> [kube-prometheus-stack] Update Thanos to v0.34.0

- charts/prom-label-proxy/Chart.yaml
> [prom-label-proxy] bump to 0.8.1

- charts/prometheus-statsd-exporter/Chart.yaml
- charts/prometheus-statsd-exporter/templates/deployment.yaml
- charts/prometheus-statsd-exporter/values.yaml
support topologySpreadConstraints settings.
NONE
@scDisorder
> [prometheus-statsd-exporter] support topologySpreadConstraints settings.

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
- charts/prometheus-node-exporter/values.yaml
- A variable was also added to configure env variable for the KubeRBACProxy container
- fixes #
> [prometheus-node-exporter] Add Support for Environment Variables for KubeRBACProxy Container

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
- charts/prometheus-node-exporter/values.yaml
- Specify container `restartPolicy` for Node Exporter container
- fixes #
> [prometheus-node-exporter] Add Support to Configure Restart Policy for Node Exporter Daemonset

- .github/CODEOWNERS
- charts/prometheus-snmp-exporter/Chart.yaml
Adds myself as a maintainer of the promtheus-snmp-exporter Chart as agreed in #4158.
- fixes #4158
> [prometheus-snmp-exporter] Add Tom as maintainer

- charts/prometheus/Chart.yaml
- charts/prometheus/templates/cm.yaml
- charts/prometheus/values.schema.json
- charts/prometheus/values.yaml
We want to make ConfigMap Annotations configurable
- fixes #4243 
mentioning @zanhsieh
> [prometheus]: introduce configMapAnnotations

- charts/prometheus-windows-exporter/Chart.yaml
- charts/prometheus-windows-exporter/templates/daemonset.yaml
> [prometheus-windows-exporter] fix windows exporter deprecated flag

- charts/prometheus-pushgateway/Chart.yaml
- charts/prometheus-pushgateway/templates/_helpers.tpl
- charts/prometheus-pushgateway/templates/serviceaccount.yaml
- charts/prometheus-pushgateway/values.yaml
By default, Kubernetes automatically mounts a serviceaccount token that can be used to authenticate against the Kubernetes API. This PR enables disabling automatic mounting of API tokens in order to reduce attack surface.
- fixes #
> [prometheus-pushgateway] Allow disabling automount of service account token

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
A version number with a dash following the <MAJOR>.<MINOR>.<PATCH> version fields is marked as a pre-release. Pre-releases are excluded from general semantic version lookups unless the constraint includes a pre-release identifier to the constraint.
Changing the constraint to include pre-release versions as described in the helm  documentation:  
in this case >= 1.4.0-0 So that chart users would be able to use tags of the form1.7.0-custom-tag and semverCompare will be able t0 function properly. Reference: https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions
- fixes #3821
- fixes #4104 
Although #4105 provides a way to fix this problem …
> [prometheus-node-exporter] Fix tag used in semverCompare to be able to use  custom tagged versions of node-exporter image

- charts/kube-prometheus-stack/Chart.yaml
> [kube-prometheus-stack] bump deps

- charts/prometheus-pingmesh-exporter/Chart.yaml
> [prometheus-pingmesh-exporter] bump to 1.2.1

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] bump deps

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/alertmanager/ingress.yaml
- charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
- charts/kube-prometheus-stack/templates/prometheus/ingress.yaml
- charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
- charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
- charts/kube-prometheus-stack/templates/thanos-ruler/ingress.yaml
Use the Helm tpl function for ingress annotations to avoid setting already defined values again. 
e.g.
```yaml
annotations:
nginx.ingress.kubernetes.io/auth-tls-secret: "{{ $.Release.Namespace }}/secret-name"
```
ref: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-certificate-authentication
This change is backwards compatible and will not break anything.
- fixes #
@jkroepke @gianrubio @gkarthiks @GMartinez-Sisti @scottrigby
> [kube-prometheus-stack] use of helm tpl for ingress annotations

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] bump to 0.4.18

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
> [kube-prometheus-stack] fix helm error in ingressperreplica.yaml

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
https://github.com/prometheus-community/helm-charts/pull/4236#issuecomment-1955089668
I forgot the Alertmanager one here, that makes me sad.
- fixes #
> [kube-prometheus-stack] fix helm error in am/ingressperreplica.yaml

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/templates/deployment.yaml
- charts/prometheus-snmp-exporter/values.yaml
> [prometheus-snmp-exporter] make strategy configurable

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
Helm binaries built with older Go releases, e.g. 1.15, fail with an unclosed action when rendering the daemonset template due to new line characters within an action. This PR removes the new line characters making the template compatible with older releases. 
- fixes #4206
> [prometheus-node-exporter] Fix unclosed action in daemonset template

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] bump to 1.58.0

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] bump to 2.50.0

- charts/prometheus-kafka-exporter/Chart.yaml
- charts/prometheus-kafka-exporter/README.md
- charts/prometheus-kafka-exporter/templates/deployment.yaml
- charts/prometheus-kafka-exporter/templates/service.yaml
- charts/prometheus-kafka-exporter/values.yaml
Allow users of the chart to add custom labels to the deployment and/or pod.
- fixes: https://github.com/prometheus-community/helm-charts/issues/3986
> [prometheus-kafka-exporter] Support additional labels on pod and deployment

- .github/CODEOWNERS
- scripts/check-codeowners.sh
> Update CODEOWNERS for renovate.json

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
- charts/kube-prometheus-stack/templates/prometheus/servicemonitor.yaml
> [kube-prometheus-stack] allow setting reloader scheme for svc monitor

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/templates/deployment.yaml
- charts/prometheus-blackbox-exporter/values.yaml
This enables setting annotations for the Deployment.
@desaintmartin, @gianrubio, @rsotnychenko, @monotek, mentioning you as owners as instructed in the PR template.
Not being able to set annotations for the Deployment.
_no open issue_
> [prometheus-blackbox-exporter] Enable annotations for Deployment

- charts/prometheus-mysql-exporter/Chart.yaml
- charts/prometheus-mysql-exporter/templates/deployment.yaml
- charts/prometheus-mysql-exporter/values.yaml
The PR add the priority class to the mysql exporter deployment. This helps for adding weight for the scheduler and eviction of pods.
- fixes #4310
> [prometheus-mysql-exporter] Set priorityclass

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prom 2.50.1 and thanos to 0.34.1

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/templates/servicemonitor.yaml
Fixes #4315 and resolves issue introduced in #4020.
- fixes #
> [prometheus-snmp-exporter] Fix optional auth section

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump alertmanager to 0.27.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/deployment.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] add strategy to admission webhook deployment

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/deployment.yaml
Fix probe check when kubeRbacProxy is enabled.
- fixes #
> [kube-state-metrics] Fix probe check when kubeRbacProxy is enabled

- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/README.md
- charts/prometheus-postgres-exporter/templates/deployment.yaml
- charts/prometheus-postgres-exporter/values.yaml
This PR allows overriding the registry from which to fetch the Prometheus Postgres exporter, independently from the repository. This is useful in cases such as when using AWS ECR pull through cache where the registry must be changed but not the repository.
> [prometheus-postgres-exporter] allow overriding image registry

- charts/prometheus-mysql-exporter/Chart.yaml
- charts/prometheus-mysql-exporter/templates/servicemonitor.yaml
Add `metrics` when multipleTarget enable. Both metrics and probes collect.
- fixes https://github.com/prometheus/mysqld_exporter/issues/812
> [prometheus-mysql-exporter]: Add `metrics` when multipleTarget enable

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prometheus to 2.51.0

- charts/prometheus-stackdriver-exporter/Chart.yaml
> [prometheus-stackdriver-exporter] bump to 0.15.0

- charts/kube-state-metrics/Chart.yaml
> [kube-state-metrics] bump to 2.11.0

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.72.0

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/values.yaml
> [prometheus] bump to 2.51.0 + deps

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/values.yaml
> [kube-state-metrics] bump kube-rbac-proxy to support K8s 1.28

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] bump kube-rbac-proxy to support K8s 1.28

- charts/kube-prometheus-stack/Chart.yaml
Bump the kube-state-metrics chart to 5.18.*.
changes :
- ksm : https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.11.0
- chart : https://github.com/prometheus-community/helm-charts/pull/4371 
- chart : https://github.com/prometheus-community/helm-charts/pull/4384
- N/A
> [kube-prometheus-stack] bump kube-state-metrics to 5.18.*

- charts/prometheus-kafka-exporter/Chart.yaml
- charts/prometheus-kafka-exporter/templates/servicemonitor.yaml
- charts/prometheus-kafka-exporter/values.yaml
Adding support for customizing api version for pod/service monitor as it is useful for support with Azure managed prometheus that looks for pod/service monitors in its own api group
> [prometheus-kafka-exporter]add ability to customize apiversion for pod/service monitor

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/templates/configmap.yaml
- charts/prometheus-blackbox-exporter/values.yaml
This PR introduces a new ability to set **annotations** for the **Secret**.
@desaintmartin, @gianrubio, @rsotnychenko, @monotek, mentioning you as owners as instructed in the PR template.
> [prometheus-blackbox-exporter] Enable annotations for Secret

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.73.0

- charts/prometheus-pushgateway/Chart.yaml
- charts/prometheus-pushgateway/templates/service.yaml
- charts/prometheus-pushgateway/values.yaml
add support for dual stack clusters
- fixes #4423
> [prometheus-pushgateway] Support dual stack clusters

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] bump to 0.73.0

- charts/prometheus-smartctl-exporter/Chart.yaml
> [prometheus-smartctl-exporter] bump to 0.12.0

- charts/prometheus-statsd-exporter/Chart.yaml
> [prometheus-statsd-exporter] bump to 0.26.1

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] bump to 1.8.0

- charts/prometheus-blackbox-exporter/Chart.yaml
> [prometheus-blackbox-exporter] bump to 0.25.0

- charts/prometheus-pushgateway/Chart.yaml
- charts/prometheus-pushgateway/templates/extra-list.yaml
- charts/prometheus-pushgateway/templates/extra-manifests.yaml
- charts/prometheus-pushgateway/values.yaml
Add functionality to deploy auxiliary K8s objects together with the release
> [prometheus-pushgateway] add extraManifests value for auxiliary K8s objects

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
> [kube-prometheus-stack] bump to 0.73.1

- charts/prometheus-memcached-exporter/Chart.yaml
> [prometheus-memcached-exporter] bump to 0.14.3

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prom to 2.51.2

- charts/prometheus-systemd-exporter/Chart.yaml
- charts/prometheus-systemd-exporter/templates/daemonset.yaml
- charts/prometheus-systemd-exporter/values.yaml
… and document it in values.
- fixes #
> [prometheus-systemd-exporter]: fix extraArgs indentation

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/alertmanager/service.yaml
- charts/kube-prometheus-stack/templates/exporters/core-dns/service.yaml
- charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/service.yaml
- charts/kube-prometheus-stack/templates/exporters/kube-dns/service.yaml
- charts/kube-prometheus-stack/templates/exporters/kube-etcd/service.yaml
- charts/kube-prometheus-stack/templates/exporters/kube-proxy/service.yaml
- charts/kube-prometheus-stack/templates/exporters/kube-scheduler/service.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/service.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/service.yaml
- charts/kube-prometheus-stack/templates/prometheus/service.yaml
- charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml
- charts/kube-prometheus-stack/templates/prometheus/serviceperreplica.yaml
- charts/kube-prometheus-stack/templates/thanos-ruler/service.yaml
- charts/kube-prometheus-stack/values.yaml
add support for dual stack clusters on exporters
- fixes #4429
> [kube-prometheus-stack]add support for dual stack clusters

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
> [kube-prometheus-stack] bump operator to 0.73.2

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] bump to 2.51.2 + dependencies

- charts/prometheus-nats-exporter/Chart.yaml
New version of prometheus-nats-exporter has been released
- fixes #
> [prometheus-nats-exporter] feat: bump prometheus-nats-exporter to 0.15.0

- charts/prometheus-modbus-exporter/Chart.yaml
> [prometheus-modbus-exporter] update to 0.4.1

- charts/prometheus-systemd-exporter/Chart.yaml
- charts/prometheus-systemd-exporter/templates/daemonset.yaml
> [prometheus-systemd-exporter]: add missing dbus volume, fix systemd volume mount point, remove unused proc volume

- charts/prometheus-node-exporter/Chart.yaml
Update Node Exporter to https://github.com/prometheus/node_exporter/releases/tag/v1.8.0.
cc maintainers @gianrubio @zanhsieh @zeritti
N/A
> [prometheus-node-exporter] bump to 1.8.0

- charts/kube-prometheus-stack/Chart.yaml
> [kube-prometheus-stack ] bump deps

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/pdb.yaml
Reduce redundant check and align to to helpers pdb check
- fixes #
> [kube-prometheus-stack] align pdb to single check

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] set ttlSecondsAfterFinished relevant for argocd

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/service.yaml
- charts/prometheus-node-exporter/values.yaml
Add externalTrafficPolicy config option to node exporter service.
When the service type set to nodeport, we can have this externalTrafficPolicy config set to local so service only forward request to the local node exporter pod.
@gianrubio @zanhsieh @zeritti 
- fixes #
> [prometheus-node-exporter] Add externalTrafficPolicy to prometheus node exporter service spec

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prom to 2.52.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] make default datasources name configurable

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/README.md
Updates Grafana helm chart version to 8.0.x
- fixes #
Not 100% about the versioning. Bumped major as it's a major version of the Grafana chart and it has some breaking changes listed in the Grafana changelog: https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/. However, none of these will directly impact `kube-prometheus-stack` as I see it.
> [kube-prometheus-stack] Update Grafana chart to 8.0.x

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/values.yaml
> [kube-state-metrics] bump kube-rbac-proxy to 0.18.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump thanos to 0.35.1

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.74.0

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] bump exporter to 1.8.1 + kube-rbac-proxy to 0.18.0

- charts/prometheus-elasticsearch-exporter/Chart.yaml
- charts/prometheus-elasticsearch-exporter/templates/_helpers.tpl
- charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
- charts/prometheus-elasticsearch-exporter/values.yaml
Fixes the imagePullSecrets for elasticsearch exporter 
- fixes #4580
> [prometheus-elasticsearch-exporter] Correct imagepullsecrets for elasticsearch exporter

- charts/kube-prometheus-stack/Chart.yaml
> [kube-prometheus-stack] bump chart deps

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prom to 2.53.0

- charts/prom-label-proxy/Chart.yaml
> [prom-label-proxy] bump to 0.10.0

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/values.yaml
> [prometheus] bump to 2.53.0 + deps

- charts/prometheus-fastly-exporter/Chart.yaml
> [prometheus-fastly-exporter] bump to 8.0.0

- charts/prometheus-rabbitmq-exporter/Chart.yaml
- charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
- charts/prometheus-rabbitmq-exporter/values.yaml
add additional environment variables support. Use case: setting GOMAXPROCS.
Also re-indent correctly the `env` section.
- fixes #
> [prometheus-rabbitmq-exporter] add additional environment variables support

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
Bump to `prometheus-operator@0.75.0`
> [prometheus-operator-crds] Bump prometheus-operator v0.75.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/README.md
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
Bump to `prometheus-operator@0.75.0`
> [kube-prometheus-stack] Bump prometheus-operator v0.75.0

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/serviceaccount.yaml
Option to set automountServiceAccountToken on service account resource.
- fixes #4628
> [prometheus-node-exporter] add automountServiceAccountToken for serviceaccount resource

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/templates/daemonset.yaml
- charts/prometheus-snmp-exporter/templates/deployment.yaml
- charts/prometheus-snmp-exporter/values.yaml
This PR adds the option to set  priorityClassName in pods in helm chart prometheus-snmp-exporter
> [prometheus-snmp-exporter] Add  option to set priorityClassName

- charts/prometheus-elasticsearch-exporter/Chart.yaml
- charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
- charts/prometheus-elasticsearch-exporter/values.yaml
> [prometheus-elasticsearch-exporter] add support for revisionhistorylimit

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/deployment.yaml
- charts/kube-state-metrics/templates/serviceaccount.yaml
- charts/kube-state-metrics/values.yaml
> [kube-state-metrics] Add automountServiceAccountToken flags

- charts/kube-prometheus-stack/Chart.yaml
Bump chart dependencies to latest available
- fixes #
> [kube-prometheus-stack] bump chart dep version

- charts/prometheus-json-exporter/Chart.yaml
- charts/prometheus-json-exporter/templates/extra-manifests.yaml
- charts/prometheus-json-exporter/values.yaml
- This PR add the `extraManifests` field in the `values.yaml`.
- If we use an API which requires a refresh token, we need to deploy a CronJob outside of the chart. It would be more convenient to add this manifest as extra manifest within the `values.yaml`. 
- This kind of approach is already implemented in other charts in this repo. 
@schmiddim
@zanhsieh
@xiu
> [prometheus-json-exporter] Add extra manifests field

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump admission webhook to 0.75.1

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] bump pushgateway to 1.9.0

- charts/prom-label-proxy/Chart.yaml
- charts/prom-label-proxy/README.md
- charts/prom-label-proxy/ci/kube-rbac-proxy-values.yaml
- charts/prom-label-proxy/templates/_helpers.tpl
- charts/prom-label-proxy/templates/clusterrole.yaml
- charts/prom-label-proxy/templates/clusterrolebinding.yaml
- charts/prom-label-proxy/templates/deployment.yaml
- charts/prom-label-proxy/templates/rbac-configmap.yaml
- charts/prom-label-proxy/templates/service.yaml
- charts/prom-label-proxy/values.yaml
Add kube-rbac-proxy support to prom-label-proxy.
- fixes #
> [prom-label-proxy] kube-rbac-proxy support

- charts/prometheus/Chart.yaml
- charts/prometheus/ci/02-config-reloader-deployment-values.yaml
- charts/prometheus/ci/03-config-reloader-sts-values.yaml
- charts/prometheus/templates/deploy.yaml
- charts/prometheus/templates/sts.yaml
- charts/prometheus/values.yaml
Readiness, liveness and startup probes were added to "configmapReload" container in Prometheus pod.
- fixes #4623
> [prometheus] Add readiness/liveness/startup probes to config-reloader container

- charts/prometheus-systemd-exporter/Chart.yaml
- charts/prometheus-systemd-exporter/ci/prometheus-operator-values.yaml
- charts/prometheus-systemd-exporter/templates/prometheusrule.yaml
- charts/prometheus-systemd-exporter/values.yaml
> [prometheus-systemd-exporter]: add support for prometheus rules.

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] bump prom deps

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump operator to 0.75.1 and prom to 2.53.1

- charts/prometheus-memcached-exporter/Chart.yaml
> [prometheus-memcached-exporter] bump memcached exporter to 0.14.4

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/clusterrole.yaml
> [kube-prometheus-stack] fix rbac for kube-state-metrics when using kube-rbac-proxy

- charts/prometheus-node-exporter/Chart.yaml
> [prometheus-node-exporter] bump node exporter to 1.8.2

- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/templates/deployment.yaml
- charts/prometheus-postgres-exporter/values.yaml
This PR adds support for the `DATA_SOURCE_USER_FILE` variable for the postgres-exporter helm charts.
- fixes #4719
> [prometheus-postgres-exporter] Add support for DATA_SOURCE_USER_FILE

- charts/prometheus-memcached-exporter/Chart.yaml
- charts/prometheus-memcached-exporter/ci/01-default-values.yaml
- charts/prometheus-memcached-exporter/ci/02-security-context-values.yaml
- charts/prometheus-memcached-exporter/ci/03-resources-values.yaml
- charts/prometheus-memcached-exporter/templates/deployment.yaml
Allow to specify securityContext in container specs
- fixes https://github.com/prometheus-community/helm-charts/issues/4728
> [prometheus-memcached-exporter] Fixing problem when enabling security context

- charts/prometheus-stackdriver-exporter/Chart.yaml
> [prometheus-stackdriver-exporter] bump to 0.16.0

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/deployment.yaml
> [kube-state-metrics] bump to 2.13.0

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/vpa.yaml
- charts/alertmanager/values.schema.json
- charts/alertmanager/values.yaml
> [alertmanager] VPA capability for AlertManager

- charts/prometheus-rabbitmq-exporter/Chart.yaml
- charts/prometheus-rabbitmq-exporter/values.yaml
Should be an empty list instead of an empty dict.
- fixes #
> [prometheus-rabbitmq-exporter] additional environment variables support: correct default empty value

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] bump to 0.75.2

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.75.2

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/ci/04-prometheus-operator-webhook-values.yaml
- charts/kube-prometheus-stack/ci/06-prometheus-operator-webhook-annotations-values.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/_prometheus-operator-webhook.tpl
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] allow setting annotations for admission webhooks

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/deployment.yaml
- charts/kube-state-metrics/values.yaml
> [kube-state-metrics] add pod labels for ksm

- charts/kube-prometheus-stack/Chart.yaml
> [kube-prometheus-stack] bump kube-state-metrics to 5.25.x

- charts/prometheus-elasticsearch-exporter/Chart.yaml
- charts/prometheus-elasticsearch-exporter/ci/create-serviceaccount-values.yaml
- charts/prometheus-elasticsearch-exporter/ci/create-serviceaccount.yaml
- charts/prometheus-elasticsearch-exporter/templates/_helpers.tpl
- charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
- charts/prometheus-elasticsearch-exporter/templates/serviceaccount.yaml
values.serviceAccount.name does not have an effect when `create: true`.  It should customize the created serviceAccount name.
> [prometheus-elasticsearch-exporter] Add ability to customize created serviceaccount name

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.26.1

- charts/kube-prometheus-stack/Chart.yaml
This will create a kube-prometheus-stack release to include the kube-state-metrics fix from https://github.com/prometheus-community/helm-charts/pull/4759.
Bug was introduced in https://github.com/prometheus-community/helm-charts/pull/4752 (61.6.0).
- N/A
> [kube-prometheus-stack] release to fix ksm podAnnotations

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Update thanos sidecar and thanos ruler to `0.36.0`:
https://github.com/thanos-io/thanos/releases/tag/v0.36.0
- fixes #
> [kube-prometheus-stack] bump thanos to 0.36.0

- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/ci/default-values.yaml
- charts/prometheus-postgres-exporter/ci/extramanifests-values.yaml
- charts/prometheus-postgres-exporter/templates/extra-manifests.yaml
- charts/prometheus-postgres-exporter/values.yaml
Introduce extraManifest for prometheus postgres exporter
- fixes #
> [prometheus-postgres-exporter] Introduce extraManifests value

- charts/prometheus-redis-exporter/Chart.yaml
- charts/prometheus-redis-exporter/ci/extramanifests-values.yaml
- charts/prometheus-redis-exporter/templates/extra-manifests.yaml
- charts/prometheus-redis-exporter/values.yaml
Introduce extraManifest for prometheus redis exporter
- fixes #
> [prometheus-redis-exporter] Introduce extraManifests value

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
- charts/prometheus-node-exporter/values.yaml
Support hostIPC setting
- fixes #
> [prometheus-node-exporter] Support hostIPC setting

- charts/prometheus-redis-exporter/Chart.yaml
- charts/prometheus-redis-exporter/templates/deployment.yaml
- charts/prometheus-redis-exporter/values.yaml
Introduce the possibility to specify priorityClassName
- fixes #
> [prometheus-redis-exporter] introduce priorityClassName

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prom to 2.54.0

- charts/prometheus/Chart.yaml
> [prometheus] bump prometheus to 2.54.0

- charts/prometheus-adapter/Chart.yaml
> [prometheus-adapter] bump adapter to 0.12.0

- charts/kube-prometheus-stack/Chart.yaml
> [kube-prometheus-stack] bump grafana deps to 8.4.*

- charts/prometheus-mongodb-exporter/Chart.yaml
- charts/prometheus-mongodb-exporter/templates/deployment.yaml
We're moving our infra charts from Terraform to ArgoCD/ApplicationSets and we need the ability to template
some values with an environment name. In this case, we need to asign some tolerations and nodeSelector for Karpernter.
> [prometheus-mongodb-exporter] add tpl to nodeSelector and tolerations

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.27.1

- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/templates/deployment.yaml
Hey folks :wave:
I made that little PR to allow the deployment to rollout restart (through the labels update) when the password in the secret is updated.
Don't hesitate to ping if you any question 😉 
Cheers ☀️ 
- None
> [prometheus-postgres-exporter] rollout deployment from secret update

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/README.md
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
- charts/kube-prometheus-stack/templates/prometheus/clusterrole.yaml
- charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump operator to 0.76.0 + deps

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] update deps

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/ci/service-labels-values.yaml
- charts/prometheus-node-exporter/ci/serviceport-values.yaml
- charts/prometheus-node-exporter/templates/service.yaml
- charts/prometheus-node-exporter/values.yaml
This PR adds support for additional service labels.
Furthermore, 
- comments on service fields have been inserted
- CI test cases added
The change is related to issue #4801.
None
None
> [prometheus-node-exporter] Add support for custom service labels

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.76.0

- charts/prom-label-proxy/Chart.yaml
> [prom-label-proxy] bump to 0.11.0

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.27.2

- charts/prometheus-statsd-exporter/Chart.yaml
> [prometheus-statsd-exporter] bump to 0.27.1

- charts/prometheus-elasticsearch-exporter/Chart.yaml
- charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
- charts/prometheus-elasticsearch-exporter/values.yaml
Add `topologySpreadConstraints` for the deployment
> [prometheus-elasticsearch-exporter] Add topologySpreadConstraints

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/values.yaml
> [prometheus] bump prometheus release and node-exporter dependency

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
This PR updates Prometheus in the kube-prometheus-stack helm chart to version 2.54.1
- fixes #
> [kube-prometheus-stack] Bump Prometheus to 2.54.1

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.28.1

- charts/prometheus-kafka-exporter/Chart.yaml
> [prometheus-kafka-exporter] bump to 1.8.0

- charts/prometheus-pgbouncer-exporter/Chart.yaml
> [prometheus-pgbouncer-exporter] bump to 0.9.0

- charts/kube-prometheus-stack/Chart.yaml
> [kube-prometheus-stack] Bump windows exporter to 0.6.0

- charts/prometheus-nginx-exporter/Chart.yaml
- charts/prometheus-nginx-exporter/README.md
- charts/prometheus-nginx-exporter/templates/NOTES.txt
- charts/prometheus-nginx-exporter/values.yaml
Removing the ingress value declaration in the `prometheus-nginx-exporter` as it is misleading, there is no ingress there.
> [prometheus-nginx-exporter] Remove redundant ingress values

- charts/prometheus-mongodb-exporter/Chart.yaml
> [prometheus-mongodb-exporter] bump to 0.41.0

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] bump to 1.63.0

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] bump to 0.4.19

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
- charts/kube-prometheus-stack/values.yaml
This exposes the `cluster.label` option for alertmanager. This allows us to resolve https://github.com/prometheus/alertmanager/issues/2250 (added in https://github.com/prometheus/alertmanager/pull/3354).
The `clusterLabel` is supported by the CRD here: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml#L2094
None
> [kube-prometheus-stack] Add support for alertmanager cluster.label

- charts/prometheus-elasticsearch-exporter/Chart.yaml
> [prometheus-elasticsearch-exporter] bump to 1.8.0

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] bump to 1.10.0

- charts/prometheus-fastly-exporter/Chart.yaml
> [prometheus-fastly-exporter] bump to 9.0.0

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
upgrade the CRDs after https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-65.0.0
- fixes #4892
> [prometheus-operator-crds] bump to 0.77.1

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] bump to 0.4.20

- charts/prometheus-sql-exporter/Chart.yaml
> [prometheus-sql-exporter] bump sql exporter to 0.5.5

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.29.1

- charts/prometheus-stackdriver-exporter/Chart.yaml
- charts/prometheus-stackdriver-exporter/ci/annotations-values.yaml
- charts/prometheus-stackdriver-exporter/templates/deployment.yaml
This PR corrects issues related to deployment annotations partly introduced in PR #4767. Furthermore, a CI test case has been added for testing the annotations. 
None
> [prometheus-stackdriver-exporter] Correct deployment annotations

- charts/prometheus-mongodb-exporter/Chart.yaml
> [prometheus-mongodb-exporter] bump to 0.41.2

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] fix Provision Grafana comment example

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/hack/sync_grafana_dashboards.py
- charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/nodes-aix.yaml
- charts/kube-prometheus-stack/values.yaml
With chart release 65.0.0 (#4889) the nodes-aix dashboard has been added and I'd like to let the user decide to disable it as it is already possible for Linux and for Darwin. 
n/a
> [kube-prometheus-stack] Allow disabling the nodes-aix dashboard

- charts/prometheus-mongodb-exporter/Chart.yaml
> [prometheus-mongodb-exporter] bump to 0.42.0

- charts/prometheus-sql-exporter/Chart.yaml
> [prometheus-sql-exporter] bump to 0.5.8

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/values.yaml
> [prometheus] bump to 2.55.0 + deps

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.29.2

- charts/prometheus-pgbouncer-exporter/Chart.yaml
> [prometheus-pgbouncer-exporter ]bump to 0.10.2

- charts/prometheus-statsd-exporter/Chart.yaml
> [prometheus-statsd-exporter] bump to 0.28.0

- charts/prometheus-ipmi-exporter/Chart.yaml
> [prometheus-ipmi-exporter] bump to 1.9.0

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] bump to 1.66

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/ci/05-ingress-and-gateway-routes-values.yaml
- charts/kube-prometheus-stack/templates/alertmanager/route.yaml
- charts/kube-prometheus-stack/templates/thanos-ruler/ingress.yaml
- charts/kube-prometheus-stack/templates/thanos-ruler/route.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] Implement Gateway API for AM/Thanos Ruler

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
The selector of  additionalPodMonitors and additionalServiceMonitors is simple. I am confused by it when I first use it . 
- [ X ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ X ] Chart Version bumped
- [ X ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
> [kube-prometheus-stack] Add more informations to selector of additionalPodMonitors and additionalServiceMonitors

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.78.1

- charts/prometheus-mysql-exporter/Chart.yaml
- charts/prometheus-mysql-exporter/values.yaml
> [prometheus-mysql-exporter] bump to 0.16.0 + cloudsql proxy image bump

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] bump to 0.4.21

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/deployment.yaml
> [kube-state-metrics] bump to 2.14.0

- charts/prometheus-memcached-exporter/Chart.yaml
> [prometheus-memcached-exporter] bump to 0.15.0

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/values.yaml
> [prometheus] bump to 2.55.1

- charts/prometheus-mysql-exporter/Chart.yaml
- charts/prometheus-mysql-exporter/templates/deployment.yaml
- charts/prometheus-mysql-exporter/values.yaml
It implements an extra value "config.extraArgs" which takes arbitrary arguments as a list of strings allowing more flexible configuration of the exporter.
- fixes #
> [prometheus-mysql-exporter] Implement config.extraArgs to be able to define any cmdline argument

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
bump CRDs to 0.78.2
- [  x ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x  ] Chart Version bumped
- [ x ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)
> [prometheus-operator-crds] bump to 0.78.2

- charts/prometheus-postgres-exporter/Chart.yaml
> [prometheus-postgres-exporter] bump to 0.16.0

- charts/prometheus-elasticsearch-exporter/Chart.yaml
- charts/prometheus-elasticsearch-exporter/templates/NOTES.txt
New line character is causing issues while deploying the chart.
- fixes #
> [prometheus-elasticsearch-exporter] Bugfix for NOTES.txt

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Update thanos sidecar and thanos ruler to 0.37.0:
https://github.com/thanos-io/thanos/releases/tag/v0.37.0
- fixes #
> [kube-prometheus-stack] bump thanos to 0.37.0

- charts/prometheus-stackdriver-exporter/Chart.yaml
- charts/prometheus-stackdriver-exporter/templates/deployment.yaml
> [prometheus-stackdriver-exporter] bump to 0.17.0

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] bump to 0.4.23

- charts/prometheus-mongodb-exporter/Chart.yaml
> [prometheus-mongodb-exporter] bump to 0.43.1

- charts/prometheus/Chart.yaml
> [prometheus] bump to 3.0.1

- charts/prometheus-nats-exporter/Chart.yaml
> [prometheus-nats-exporter] bump to 0.16.0

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] bump to 0.79.0

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.79.0

- charts/prometheus-operator-admission-webhook/Chart.yaml
> [prometheus-operator-admission-webhook] bump to 0.79.2

- charts/prometheus-smartctl-exporter/Chart.yaml
> [prometheus-smartctl-exporter] bump to 0.13.0

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/values.yaml
> [kube-state-metrics] bump kube-rbac-proxy to 0.18.2

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] bump redis 1.67.0

- charts/prometheus-pingmesh-exporter/Chart.yaml
> [prometheus-pingmesh-exporter] bump to 1.2.2

- charts/prom-label-proxy/Chart.yaml
- charts/prom-label-proxy/values.yaml
> [prom-label-proxy] bump kube-rbac-proxy to 0.18.2

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] bump kube-rbac-proxy to 0.18.2

- charts/prometheus-nginx-exporter/Chart.lock
- charts/prometheus-nginx-exporter/Chart.yaml
- charts/prometheus-nginx-exporter/README.md
- charts/prometheus-nginx-exporter/ci/ci-values.yaml
- charts/prometheus-nginx-exporter/templates/_helpers.tpl
- charts/prometheus-nginx-exporter/templates/deployment.yaml
- charts/prometheus-nginx-exporter/values.yaml
> [prometheus-nginx-exporter] bump to 1.4.0

- charts/prometheus-json-exporter/Chart.yaml
> [prometheus-json-exporter] add home link in chart.yaml

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prom to 3.1.0 + deps

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/ci/13-pdb-values.yaml
> [prometheus] bump prom to 3.1.0 + deps

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/README.md
- charts/prometheus-snmp-exporter/values.yaml
> [prometheus-snmp-exporter] bump to 0.27.0

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] bump to 1.11.0

- charts/prometheus-yet-another-cloudwatch-exporter/Chart.yaml
- charts/prometheus-yet-another-cloudwatch-exporter/README.md
Add a migration guide
- fixes #
> [prometheus-yet-another-cloudwatch-exporter] add migration guide

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump alertmanager to 0.28.0

- charts/prometheus/Chart.yaml
- charts/prometheus/README.md
- charts/prometheus/values.yaml
This PR restores certificate verification in the default scrape configs by commenting out the corresponding line keeping thus the Prometheus' default. 
The chart's default values should not lower security settings of the application. If certificate verification is not wanted for any reason, users themselves should take the decision to skip it.
- fixes #3002
Since the change might be breaking for some users, I am considering it major.
> [prometheus] Do not skip certificate verification in scrape configs

- renovate.json
Of course, it's very hard to test the renovate.json from a branch other than main.
- fixes #5198
> [ci] fix issue in renovate.json

- .github/workflows/renovate-bump-chart-version.yaml
action failure: https://github.com/prometheus-community/helm-charts/actions/runs/12844028753/job/35816613817?pr=5201
- fixes #
> [ci] Strip quotes from list of changed charts

- .github/workflows/renovate-bump-chart-version.yaml
it seem that github.ref_name contains the name of the temporary PR branch while github.head_ref takes the name of the source branch
- fixes #
> [ci] renovate-bump-chart-version.yaml use github.head_ref instead github.ref_name

- .github/workflows/check-codeowners.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- .github/workflows/superlinter.yml
- .github/workflows/sync-readme.yaml
Mandatory for https://github.com/prometheus-community/helm-charts/pull/5208
- fixes #
> [ci] migrate super-linter to action

- .github/workflows/check-codeowners.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- .github/workflows/superlinter.yml
- .github/workflows/sync-readme.yaml
Github will do it anyways soon. I also pin the version, renovate may take care in 2 years. 
- fixes #
> [ci] update runners to 24.04

- README.md
The status badge _Release Charts_ in the main README file is currently showing `no status`, i.e. it cannot retrieve the real status of the worflow. This PR brings a corection in the  URL.
None
> [docs] Correct workflow status badge

- charts/alertmanager/Chart.yaml
> [alertmanager] bump to 0.28.0

- .github/workflows/superlinter.yml
It turn out that super-linter invoke yamllint over helm templates. That wont work, since helm template are no yaml files.
The values.yaml for helm charts are covered by helm-chart-test anyways.
- fixes #
> [ci] disable yaml linter

- charts/prometheus-stackdriver-exporter/Chart.yaml
- charts/prometheus-stackdriver-exporter/templates/deployment.yaml
- charts/prometheus-stackdriver-exporter/values.yaml
Bumps to [v0.18.0](https://github.com/prometheus-community/stackdriver_exporter/releases/tag/v0.18.0)
- Adds `extraEnv` to allow users to set golang tunables, for example: `GOMAXPROCS`, `GOMEMLIMIT` or `GOGC`
> [prometheus-stackdriver-exporter] bump to 0.18.0 and extraEnv support

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter ]bump to 0.4.24

- charts/prometheus-pingdom-exporter/Chart.yaml
- charts/prometheus-pingdom-exporter/README.md
- charts/prometheus-pingdom-exporter/values.yaml
> [pingdom-exporter] fix port & readme

- charts/prometheus-sql-exporter/Chart.yaml
bump prometheus-sql-exporter version to 0.5.9
- fixes #
> [prometheus-sql-exporter] bump to 0.5.9

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] docs: api url update

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] bump to 0.4.25

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/values.yaml
> [prometheus] bump to dependencies

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/charts/crds/templates/upgrade/job.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] set `--force-conflicts` on CRD job

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] bump prometheus-operator to 'v0.80.0'

- .github/workflows/check-codeowners-maintainers.yaml
- MAINTAINERS.md
- scripts/check-maintainers.sh
Requested in https://github.com/prometheus-community/helm-charts/issues/5026
- fixes #5026
- fixes #5083
> [all] Add MAINTAINERS.md

- charts/kube-state-metrics/Chart.yaml
> [kube-state-metrics] Bump to v2.15.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/additionalAlertRelabelConfigs.yaml
- charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
There is a need to dynamically templating prometheus config depending on the `.Release.Name`.
- alertmanager relabel config 
- secret names attached to Prometheus pod 
- configmap names attached to Prometheus pod 
- fixes #
@jkroepke
> [kube-prometheus-stack] Add support for `tpl` in various prometheus spec fields 

- charts/kube-prometheus-stack/Chart.yaml
Remove `README.md` file from `.helmignore` so that it is available in [ArtifactHub](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) as before.
- fixes #5302
> [kube-prometheus-stack] remove readme file from helmignore

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
related to #1900
Omits the secretProviderClass stanza that populates the csi-secret.yaml resource, from the .spec.Thanos section of the Prometheus resource.
@andrewgkew
@gianrubio
@gkarthiks 
@GMartinez-Sisti
@jkroepke
@scottrigby 
@Xtigyro 
@QuentinBisson
- fixes #
https://github.com/prometheus-community/helm-charts/issues/1900
> [kube-prometheus-stack]omitting secretProviderClass stanza from spec.Thanos

- charts/prometheus/.helmignore
- charts/prometheus/Chart.yaml
- charts/prometheus/templates/pvc.yaml
- charts/prometheus/values.yaml
Field `server.persistentVolume.volumeBindingMode` is not applicable to a persistent volume. This PR removes it from the templates. Furthermore, `ci` is to be excluded from the released artefact. 
- fixes #5040
> [prometheus] Remove field volumeBindingMode

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/ingress.yaml
- charts/alertmanager/values.yaml
> [alertmanager] Add support for extra labels in Alertmanager ingress

- charts/prometheus-json-exporter/Chart.yaml
Update prometheus-json-exporter to [0.7.0](https://github.com/prometheus-community/json_exporter/releases/tag/v0.7.0)
N/A
Latest version of `prometheus-json-exporter` updates bunch of dependencies resolving a lot of reported vulnerabilities
- v0.7.0
- v0.6.0
> [prometheus-json-exporter] update appVersion to 0.7.0

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/README.md
Updates the version of snmp-exporter to v0.28.0.
- fixes #
Release notes https://github.com/prometheus/snmp_exporter/releases/tag/v0.28.0
> [prometheus-snmp-exporter] bump to 0.28.0

- charts/prometheus-node-exporter/.helmignore
- charts/prometheus-node-exporter/Chart.yaml
Due to the latest upgrade of the upstream image, this will update the image tag of the node exporter.
<https://quay.io/repository/prometheus/node-exporter?tab=tags&tag=latest>
> [prometheus-node-exporter] chore(deps): upgrade node-exporter app version to v1.9.0

- charts/prometheus-rabbitmq-exporter/Chart.yaml
- charts/prometheus-rabbitmq-exporter/README.md
- charts/prometheus-rabbitmq-exporter/templates/deployment.yaml
- charts/prometheus-rabbitmq-exporter/templates/secret.yaml
- charts/prometheus-rabbitmq-exporter/values.yaml
This PR is to support specific annotations on the deployment resource.
> [prometheus-rabbitmq-exporter] support deployment annotations

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
To dynamically reference secrets depending on the `.Release.Name`. Follow up on https://github.com/prometheus-community/helm-charts/pull/5286.
- fixes #
@jkroepke
> [kube-prometheus-stack] Add `tpl` support for additional secret names

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
- charts/kube-prometheus-stack/values.yaml
This adds the urlDisplayLabel to the exemplar config section for the prometheus datasource in Grafana. It allows to customize the text on the button used to navigate to traces from exemplars.
- fixes #
> [kube-prometheus-stack]Add urlDisplayLabel to exemplar config

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
> [prometheus] bump dependencies

- charts/prometheus-mongodb-exporter/.helmignore
- charts/prometheus-mongodb-exporter/Chart.yaml
- charts/prometheus-mongodb-exporter/ci/default-values.yaml
- charts/prometheus-mongodb-exporter/ci/servicemonitor-multi-target-anon-values.yaml
- charts/prometheus-mongodb-exporter/templates/deployment.yaml
- charts/prometheus-mongodb-exporter/values.yaml
Removes arbitrary restriction of requiring auth in mongodb_exporter when doing multi-target.
- fixes #5337
> [prometheus-mongodb-exporter] Fix unnecessary required auth when doing multi-target

- charts/prometheus-fastly-exporter/Chart.yaml
> [prometheus-fastly-exporter] bump to v9.0.1

- charts/prometheus-kafka-exporter/.helmignore
- charts/prometheus-kafka-exporter/Chart.yaml
- charts/prometheus-kafka-exporter/templates/NOTES.txt
> [prometheus-kafka-exporter] bump to v1.9.0

- charts/prometheus-operator-admission-webhook/.helmignore
- charts/prometheus-operator-admission-webhook/Chart.yaml
- charts/prometheus-operator-admission-webhook/values.yaml
> [prometheus-operator-admission-webhook] bump to v0.80.1

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [prometheus-operator-crds] bump to v0.80.1

- charts/prometheus-postgres-exporter/.helmignore
- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/README.md
- charts/prometheus-postgres-exporter/ci/config-values.yaml
- charts/prometheus-postgres-exporter/ci/deployment-labels-values.yaml
- charts/prometheus-postgres-exporter/ci/disable-metrics-values.yaml
- charts/prometheus-postgres-exporter/ci/exporter-config-values.yaml
- charts/prometheus-postgres-exporter/ci/extraenv-values.yaml
- charts/prometheus-postgres-exporter/ci/pdb-values.yaml
- charts/prometheus-postgres-exporter/ci/podlabels-values.yaml
- charts/prometheus-postgres-exporter/ci/serviceaccount-values.yaml
- charts/prometheus-postgres-exporter/ci/servicelabels-values.yaml
- charts/prometheus-postgres-exporter/ci/servicemonitor-values.yaml
> [prometheus-postgres-exporter] bump to v0.17.0

- charts/prom-label-proxy/Chart.yaml
- charts/prom-label-proxy/values.yaml
> [prom-label-proxy]fix - prom op doc

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/README.md
- charts/kube-prometheus-stack/templates/prometheus-operator/aggregate-clusterroles.yaml
- charts/kube-prometheus-stack/values.yaml
From an issue opened in [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/issues/7367), since the documentation was moved, fix the urls
> [kube-prometheus-stack] - prom op docs

- charts/prometheus-windows-exporter/Chart.yaml
- charts/prometheus-windows-exporter/values.yaml
> [prometheus-windows-exporter] fix - prom op doc

- charts/prometheus-operator-admission-webhook/Chart.yaml
- charts/prometheus-operator-admission-webhook/values.yaml
> [prometheus-operator-admission-webhook] fix - prom op doc

- charts/prometheus-kafka-exporter/Chart.lock
- charts/prometheus-kafka-exporter/Chart.yaml
- charts/prometheus-kafka-exporter/values.yaml
> [prometheus-kafka-exporter] fix - prom op doc

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/README.md
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] fix - prom op doc

- charts/prometheus-stackdriver-exporter/Chart.yaml
- charts/prometheus-stackdriver-exporter/README.md
> [prometheus-stackdriver-exporter] fix - prom op doc

- charts/prometheus-mysql-exporter/Chart.yaml
> [prometheus-mysql-exporter] bump to v0.17.1

- charts/alertmanager/Chart.yaml
- charts/alertmanager/values.yaml
> [alertmanager] bump prometheus-config-reloader to 0.80.1

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.30.0

- .github/CODEOWNERS
- MAINTAINERS.md
- charts/prometheus-druid-exporter/Chart.yaml
Remove unresponsive maintainer @sandy724.
Closes: https://github.com/prometheus-community/helm-charts/issues/5159
> [prometheus-druid-exporter] Remove unresponsive maintainer

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump prom to 3.2.1 + windows chart dep

- charts/prometheus-modbus-exporter/Chart.yaml
- charts/prometheus-modbus-exporter/values.yaml
> [prometheus-modbus-exporter] fix - prom op doc

- charts/prometheus-mysql-exporter/Chart.yaml
> [prometheus-mysql-exporter] bump to 0.17.2

- charts/prometheus-blackbox-exporter/Chart.yaml
> [prometheus-blackbox-exporter] bump to 0.26.0

- charts/prometheus/Chart.yaml
> [prometheus] bump prom to 3.2.1

- .github/CODEOWNERS
- MAINTAINERS.md
- charts/prometheus-stackdriver-exporter/Chart.yaml
Remove Remove unresponsive maintainer @apenney
Closes: https://github.com/prometheus-community/helm-charts/issues/5143
> [prometheus-stackdriver-exporter] Remove unresponsive maintainer

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/values.yaml
> [prometheus-snmp-exporter] fix - prom op doc

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/role.yaml
- charts/kube-state-metrics/values.yaml
Closes https://github.com/prometheus-community/helm-charts/issues/5336 
Aligned with https://github.com/kubernetes/kube-state-metrics/blob/c853e41feeed7771b3bc2d462e05aef5ee16812f/examples/standard/cluster-role.yaml 
- fixes #
> [kube-state-metrics] add missing role grants from upstream

- charts/prometheus-pingdom-exporter/Chart.yaml
> [pingdom-exporter] update to 0.2.1

- PROCESSES.md
Add some administrative docs in context of helm-chart admin here. I'm happy for feedback.
CC @scottrigby @monotek @torstenwalter @SuperQ 
By mistake, I also added myself to the artifacthub-repo.yaml, which I plan to submit as a PR. ref: https://github.com/prometheus-community/helm-charts/commit/26ce93a3cd3cd2b84c08de24b4cbfce29d2f0d4e
> [admin] docs for admin responsibilities

- charts/alertmanager/Chart.yaml
> [alertmanager] bump to 0.28.1

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] bump Alertmanager to 0.28.1

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
upgrade the CRDs after https://github.com/prometheus-community/helm-charts/commit/af41821c712c3d79789eec8af31cadc5b9740576
> [prometheus-operator-crds] bump to 0.81.0

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] bump to 0.30.5

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/hack/renovate-post-upgrade-hook.sh
Add dashboard and rules generation via renovate. xref: #5425 
- fixes #
> [kube-prometheus-stack] add renovate-post-upgrade-hook.sh

- charts/prometheus-elasticsearch-exporter/Chart.yaml
- charts/prometheus-elasticsearch-exporter/templates/deployment.yaml
> [prometheus-elasticsearch-exporter] bump to 1.9.0

- .github/workflows/renovate-bump-chart-version.yaml
It gives chart developers the opportunity to run post hook through the renovate helper. Only files under the specific charts directory will be commit.
- fixes #
> [ci] added post-upgrade hooks for renovate

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/hack/renovate-post-upgrade-hook.sh
I miss to install the jb command for renovate hook.
- fixes #5201
> [kube-prometheus-stack] install jb command inside renovate-post-upgrade-hook.sh

- charts/prometheus-pingdom-exporter/Chart.yaml
- charts/prometheus-pingdom-exporter/README.md
- charts/prometheus-pingdom-exporter/templates/deployment.yaml
- charts/prometheus-pingdom-exporter/values.yaml
Adds the ability to set arguments to the service.
- fixes #
> [prometheus-pingdom-exporter] add support for set arguments

- .github/dependabot.yml
- renovate.json
> [CI] Enable renovate for all charts

- renovate.json
The blackbox exporter helm chart has a reference to an image that contains helm values.
https://github.com/prometheus-community/helm-charts/blob/68f0c98c98b23d3b164b0d9c463e2d68f9ec419e/charts/prometheus-blackbox-exporter/values.yaml#L94
in that case, renovate tries to lookup the registry `{{ .Values.global.imageRegistry }}` which fails.
- fixes #
> [renovate] Exclude images references with values.

- renovate.json
This should be the last one. This put renovate in a auto mode and requests PR bumps once per week.
They can still manually triggered via #4298 
- fixes #
> [ci] Set automatic schedule and remove manually approve

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Some reference URLs are no longer accessible. This PR updates them with their most recent versions.
- fixes #
> [kube-prometheus-stack] Update reference URL and fix typo

- charts/alertmanager/Chart.yaml
Configures auto monitoring of application updates using [RenovateBot](https://docs.renovatebot.com/)
@jkroepke
> [alertmanager] dependency monitoring for alertmanager

- charts/prometheus/Chart.yaml
This PR adds an hint for renovate to link the appVersion as https://github.com/prometheus/prometheus version.
- fixes #
> [prometheus] add renovate version hint

- charts/prometheus-snmp-exporter/Chart.yaml
- charts/prometheus-snmp-exporter/ci/01-default-values.yaml
- charts/prometheus-snmp-exporter/ci/02-extra-manifest-values.yaml
- charts/prometheus-snmp-exporter/ci/03-daemonset-values.yaml
- charts/prometheus-snmp-exporter/ci/04-config-without-reloader-values.yaml
- charts/prometheus-snmp-exporter/ci/05-config-with-reloader-values.yaml
- charts/prometheus-snmp-exporter/ci/06-multiple-configs-values.yaml
- charts/prometheus-snmp-exporter/ci/07-extra-configs-values.yaml
- charts/prometheus-snmp-exporter/values.yaml
Implementing base set of test cases for `prometheus-snmp-exporter` Chart to reduce reviewer burden and improve CI.
- fixes #
> [prometheus-snmp-exporter] Added ci test cases in prometheus-snmp-exporter

- charts/prometheus-nginx-exporter/Chart.yaml
- charts/prometheus-nginx-exporter/templates/service.yaml
- charts/prometheus-nginx-exporter/values.yaml
add externalTrafficPolicy option for nginx-exporter service
- fixes #
> [prometheus-nginx-exporter] add externalTrafficPolicy option 

- charts/prometheus-pingdom-exporter/Chart.yaml
- charts/prometheus-pingdom-exporter/templates/deployment.yaml
- charts/prometheus-pingdom-exporter/values.yaml
Added new arguments to be passed to the service in version 0.4.0
- fixes #
> [prometheus-pingdom-exporter] Updating version and adding new arguments

- charts/prometheus-windows-exporter/Chart.yaml
> [prometheus-windows-exporter] Add renovate hint

- .github/workflows/renovate-custom-hooks.yaml
> [ci] renovate post upgrade hooks: use local files instead shell variables

- charts/prometheus-mongodb-exporter/Chart.yaml
> [prometheus-mongodb-exporter] add renovate for mongodb

- charts/prometheus-node-exporter/Chart.yaml
> [prometheus-node-exporter] add renovate for node exporter

- charts/prometheus-node-exporter/Chart.yaml
This PR updates the node-exporter version to 1.9.1
> [prometheus-node-exporter] Bump node-exporter version to 1.9.1

- charts/prometheus-adapter/Chart.yaml
- charts/prometheus-adapter/templates/extra-objects.yaml
- charts/prometheus-adapter/values.yaml
My current use-case is implementing cert-manager `CertificateRequestPolicy`. In order to make this more generic, I copy pasted the extraManifests from kube-prometheus-stack.
- fixes #
> [prometheus-adapter] add extra objects template

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/deployment.yaml
- charts/kube-state-metrics/values.yaml
Adds ability for operators to define specific DNS configuration for the KSM pod. Some people have interesting DNS setups and this allows them to configure that without modifying the chart templates. Otherwise, uses defaults as defined per the kubernetes documentation.
> [kube-state-metrics] Allow configuration of DNS for deployments

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
- charts/prometheus-operator-crds/hack/update_crds.sh
- charts/prometheus-operator-crds/values.yaml
This change adds an opt-out mechanism for CRDs so only the CRDs needed for the cluster are installed (e.g. only pod- and servicemonitors for setups using Mimir).
- fixes #3860
> [prometheus-operator-crds] add opt-out for CRDs

- charts/prometheus-pushgateway/Chart.yaml
> [prometheus-pushgateway] add renovate hint for prometheus-pushgateway

- charts/prometheus-conntrack-stats-exporter/Chart.yaml
> [prometheus-conntrack-stats-exporter] add renovate hint for conntrack-stats-exporter

- charts/prometheus-smartctl-exporter/Chart.yaml
- charts/prometheus-smartctl-exporter/templates/daemonset.yaml
- charts/prometheus-smartctl-exporter/templates/servicemonitor.yaml
- charts/prometheus-smartctl-exporter/values.yaml
- fixes #5317
- Also allows configuration of prometheus MetricRabelings
> [prometheus-smartctl-exporter] allow configuration of updateStrategy and prom metricRelabelings

- charts/prometheus-pushgateway/Chart.yaml
- charts/prometheus-pushgateway/templates/secret.yaml
Web config secret is missing `metadata.namespace` field.
`metadata.namespace` was added, matching deployment namespace.
- fixes #5560
> [prometheus-pushgateway]: add namespace to web-config secret

- charts/prometheus-smartctl-exporter/Chart.yaml
In https://github.com/prometheus-community/helm-charts/pull/5342 we mistakenly bumped the app version along with the chart version, which rendered the new chart broken as it cannot pull a non-existant image.
> [prometheus-smartctl-exporter] Fix app version

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
- charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
> [rometheus-operator-crds] bump operator v0.82

- charts/prometheus-nginx-exporter/Chart.yaml
> [prometheus-nginx-exporter] add renovate hint to nginx

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/service.yaml
- charts/prometheus-node-exporter/values.yaml
Similar to #4512.
Usecase: Using a custom scraper running as a DaemonSet. Setting `internalTrafficPolicy: Local` ensures each custom scraper will reach the Node exporter on the same node.
N/A
> [prometheus-node-exporter] Add internalTrafficPolicy to Prometheus Node exporter service spec

- charts/alertmanager-snmp-notifier/Chart.yaml
- charts/alertmanager-snmp-notifier/README.md
- charts/alertmanager-snmp-notifier/ci/templates-values.yaml
- charts/alertmanager-snmp-notifier/templates/configmap.yaml
- charts/alertmanager-snmp-notifier/templates/deployment.yaml
- charts/alertmanager-snmp-notifier/templates/hpa.yaml
- charts/alertmanager-snmp-notifier/values.schema.json
- charts/alertmanager-snmp-notifier/values.yaml
It updates the chart with the latest release of SNMP notifier, with updated options
> [alertmanager-snmp-notifier] bump snmp-notifier to v2.0.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/pdb.yaml
> [kube-prometheus-stack] fix broken pdb due to missing line break

- charts/prometheus-snmp-exporter/Chart.yaml
> [prometheus-snmp-exporter] add renovate config

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Replace non-uff-8 characters like ’ or ”
- fixes #5659
> [kube-prometheus-stack] replace non utf-8 characters

- charts/prometheus-nats-exporter/Chart.yaml
> [prometheus-nats-exporter] add renovate config

- charts/prom-label-proxy/Chart.yaml
- charts/prom-label-proxy/values.yaml
replace non ascii characters ’ by '
> [prom-label-proxy] remove non ascii characters

- charts/prometheus-windows-exporter/Chart.yaml
- charts/prometheus-windows-exporter/values.yaml
replace non ascii characters ’ by '
> [prometheus-windows-exporter] remove non ascii characters

- charts/prometheus-redis-exporter/Chart.yaml
> [prometheus-redis-exporter] add renovate config

- charts/prom-label-proxy/Chart.yaml
> [prom-label-proxy] add renovate config

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/values.yaml
replace non ascii character ’ by '
> [prometheus-node-exporter] replace non ascii characters

- charts/prometheus-fastly-exporter/Chart.yaml
> [prometheus-fastly-exporter] add renovate

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/hack/renovate-post-upgrade-hook.sh
> [prometheus-operator-crds] automate CRDs bumps

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/templates/pdb.yaml
> [kube-state-metrics] remove support for deprecated pdb version

- charts/prometheus/Chart.yaml
- charts/prometheus/templates/_helpers.tpl
- charts/prometheus/templates/ingress.yaml
- charts/prometheus/values.yaml
> [prometheus] drop support for deprecated ingress version

- charts/prometheus-nats-exporter/Chart.yaml
- charts/prometheus-nats-exporter/templates/deployment.yaml
- charts/prometheus-nats-exporter/values.yaml
New version of nats exporter
- fixes #
> [prometheus-nats-exporter] feat: bump prometheus-nats-exporter

- charts/prom-label-proxy/Chart.yaml
- charts/prom-label-proxy/templates/_helpers.tpl
- charts/prom-label-proxy/templates/ingress.yaml
> [prom-label-proxy] remove support for deprecated APIs

- renovate.json
> [ci] remove hour restriction from renovate schedule

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] fix alertmanager.spec.storage.volumeClaimTemplate.spec.selector

- renovate.json
> [CI] For prometheus-operator-crds, bump major version

- renovate.json
> [CI] For prometheus-operator-crds, bump major version else patch

- .github/workflows/renovate-custom-hooks.yaml
Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>
- fixes #
> [CI] fix renovate post-hook action with larger files

- .github/workflows/ci.yaml
> [CI] fix renovate auto merge

- renovate.json
> [ci] add rebaseWhen option in renovate.json

- renovate.json
> [ci] bump Chart.yaml if changes are only in sub-directories.

- charts/prometheus-nginx-exporter/Chart.yaml
- charts/prometheus-nginx-exporter/templates/_helpers.tpl
- charts/prometheus-nginx-exporter/templates/deployment.yaml
- charts/prometheus-nginx-exporter/values.yaml
Allow custom labels and annotations options for deployment only
I need to add these only for deployment  :
```
labels:
component-deployment=nginx-exporter
annotations:
cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
```
But that feature is not available yet.
- fixes #
> [prometheus-nginx-exporter] Add support for additional labels and annotations in Deployment

- renovate.json
Enable Renovate automerging for the chart helps to improve releases efficiency
- fixes #
> [prometheus-nats-exporter] chore: enable automerging prometheus-nats-epxorter updates

- charts/prometheus-cloudwatch-exporter/Chart.yaml
- charts/prometheus-cloudwatch-exporter/templates/_helpers.tpl
- charts/prometheus-cloudwatch-exporter/templates/clusterrole.yaml
- charts/prometheus-cloudwatch-exporter/templates/clusterrolebinding.yaml
- charts/prometheus-cloudwatch-exporter/templates/deployment.yaml
- charts/prometheus-cloudwatch-exporter/templates/ingress.yaml
- charts/prometheus-cloudwatch-exporter/values.yaml
Signed-off-by: AvivGuiser <avivguiser@gmail.com>
remove support for depreactes k8a api in various resources
- relates #5671
> [prometheus-cloudwatch-exporter]: remove support for depreacted apis

- renovate.json
See https://github.com/prometheus-community/helm-charts/pull/5824 for an example
- fixes #
> [ci] Exclude major version bumps from auto merge

- renovate.json
Ref: https://cloud-native.slack.com/archives/C088K18PKL3/p1751066603453239
Chart maintainer are inactive for over a year.
cc @monotek 
- fixes #
> [ci] renovate auto-merge: enable auto-merge for prometheus-to-sd and prometheus-consul-exporter

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
Kubernetes best practices suggest use of port names rather than numbers where possible.  This patch shifts the `liveness` and `readiness` probes to use port names.
- fixes #5589
> [prometheus-node-exporter] use port names for probes

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/clusterrole.yaml
This adds more explicit reasoning for the difference in the cluster role template.
- fixes #3306 (sorta)
This more detailed comment should repeats of #3306.  There should be no functional changes.
> [kube-prometheus-stack] Update inline doc on template

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/statefulset.yaml
- charts/alertmanager/values.yaml
Making emptyDir volume work with proper configuration, reference : https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
- fixes #
> [alertmanager] Add option emptyDir volume on persistence

- charts/prometheus-nginx-exporter/Chart.yaml
- charts/prometheus-nginx-exporter/templates/servicemonitor.yaml
- charts/prometheus-nginx-exporter/values.yaml
The ability to customize the API version for pod and service monitors is useful for compatibility with Azure managed Prometheus, which searches for pod and service monitors within its own API group.
> [prometheus-nginx-exporter] Add ability to customize API version for service monitor

- charts/alertmanager-snmp-notifier/Chart.yaml
- charts/alertmanager-snmp-notifier/templates/ingress.yaml
Signed-off-by: AvivGuiser <avivguiser@gmail.com>
Removed support for deprecated k8s apis
- relates #5671
> [alertmanager-snmp-notifier]: remove support for depreacted apis

- renovate.json
> [admin] Enable Auto Merge for renovate dependency bumps by default

- charts/prometheus-nginx-exporter/Chart.yaml
- charts/prometheus-nginx-exporter/templates/deployment.yaml
- charts/prometheus-nginx-exporter/values.yaml
Allow users to configure the deployment `strategy` for prometheus-nginx-exporter instead of leaving it _hardcode_.
In the deployment template there is _hardcode_ value for the `strategy`.
- fixes #
> [prometheus-nginx-exporter] Add option to configure update Strategy

- charts/prometheus-operator-crds/Chart.yaml
- charts/prometheus-operator-crds/README.md
> [prometheus-operator-crds] Document OCI artiacts in README

- charts/prometheus-to-sd/Chart.yaml
- charts/prometheus-to-sd/README.md
> [prometheus-to-sd] Document OCI artiacts in README

- charts/prometheus-sql-exporter/Chart.yaml
- charts/prometheus-sql-exporter/README.md
> [prometheus-sql-exporter] Document OCI artiacts in README

- charts/prometheus-smartctl-exporter/Chart.yaml
- charts/prometheus-smartctl-exporter/README.md
> [prometheus-smartctl-exporter] Document OCI artiacts in README

- charts/prometheus-pushgateway/Chart.yaml
- charts/prometheus-pushgateway/README.md
> [prometheus-pushgateway] Document OCI artiacts in README

- charts/prometheus-windows-exporter/Chart.yaml
- charts/prometheus-windows-exporter/templates/daemonset.yaml
- charts/prometheus-windows-exporter/values.yaml
This PR allows setting resources for the init container `configure-firewall`. Due to active policies in some environments, defining resources for init containers is required.
None
> [prometheus-windows-exporter] Allow setting resources for initContainer configure-firewall

- charts/prometheus-kafka-exporter/Chart.yaml
- charts/prometheus-kafka-exporter/templates/_helpers.tpl
- charts/prometheus-kafka-exporter/templates/deployment.yaml
- charts/prometheus-kafka-exporter/values.yaml
To be certain when crawling for multiple Kafka Clusters metrics feeding one prometheus.
This way we can distinguish them with the custom cluster label
```
prometheus_metric_name{cluster="customLabel",...}
```
- fixes #
This is a feature request, currently this can be worked-around by passing string with proper flag via extraArgs
> [prometheus-kafka-exporter] add kafka labels to prometheus metrics

- charts/prometheus-postgres-exporter/Chart.yaml
- charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
- charts/prometheus-postgres-exporter/values.yaml
The ability to customize the API version for pod and service monitors is useful for compatibility with Azure managed Prometheus, which searches for pod and service monitors within its own API group.
> [prometheus-postgres-exporter] Add ability to customize API version for service monitor 

- charts/prometheus-redis-exporter/Chart.yaml
- charts/prometheus-redis-exporter/templates/servicemonitor.yaml
- charts/prometheus-redis-exporter/values.yaml
The ability to customize the API version for pod and service monitors is useful for compatibility with Azure managed Prometheus, which searches for pod and service monitors within its own API group.
> [prometheus-redis-exporter] Add ability to customize API version for service monitor

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
- charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
- charts/kube-prometheus-stack/values.yaml
Adding possibility to set a custom dnsConfig for the Alertmanager and Prometheus pods.
`N/A`
> [kube-prometheus-stack] Allow custom dnsConfig for alertmanager and prometheus

- charts/prometheus-sql-exporter/Chart.yaml
> [prometheus-sql-exporter] bump to 0.8

- charts/prometheus-blackbox-exporter/Chart.yaml
Signed-off-by: AvivGuiser <avivguiser@gmail.com>
- fixes #
> [prometheus-blackbox-exporter]: add renovate hint for blackbox exporter

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Fixes typo from`specifiy` to `specify` in values.yaml
> [kube-prometheus-stack]: fix typo in values.yaml

- charts/prometheus-ipmi-exporter/Chart.yaml
- charts/prometheus-ipmi-exporter/templates/deployment.yaml
Restart pod when configuration change
N/A
> [prometheus-ipmi-exporter] Restart pod when config change

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/podmonitors.yaml
- charts/kube-prometheus-stack/templates/prometheus/servicemonitors.yaml
- charts/kube-prometheus-stack/values.yaml
To drop additional metrics during _relabelings_ based on Node labels, the scrapping must collect nodes metadata.
Allows `attachMetadata` option to `additionalServiceMonitors` and `additionalPodMonitors`.
> [kube-prometheus-stack] Added attachMetadata option to additionalServiceMonitors and additionalPodMonitors

- charts/prometheus/Chart.yaml
- charts/prometheus/templates/NOTES.txt
- charts/prometheus/templates/_helpers.tpl
- charts/prometheus/templates/deploy.yaml
- charts/prometheus/templates/headless-svc.yaml
- charts/prometheus/templates/network-policy.yaml
- charts/prometheus/templates/service.yaml
- fixes #
I didnt cover grpc port as its not present in the pod spec. can be added as part of different PR with other relevant flags
> [prometheus] use named targetport

- charts/prometheus-stackdriver-exporter/Chart.yaml
- charts/prometheus-stackdriver-exporter/templates/deployment.yaml
- charts/prometheus-stackdriver-exporter/templates/servicemonitor.yaml
- charts/prometheus-stackdriver-exporter/values.yaml
* Add possibility to separate endpoints for internal metrics and metrics for stackdriver
* Add possibility to set scrape class for service monitor
> [prometheus-stackdriver-exporter] ServiceMonitor scrapeClass and separated endpoints

- .github/workflows/ci.yaml
- .github/workflows/renovate-custom-hooks.yaml
Reverts prometheus-community/helm-charts#6195
> Revert "[CI] Update dependency python to 3.14"
